### PR TITLE
Update platform default splash to remove NB10 reference

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Updated the default platform splash that has been stuck saying NetBeans 10 for a long time!

I copied the IDE splash for consistency and just added the word "platform".

Unfortunately, this doesn't work without changing a few of the default bundle values.  This shouldn't be an issue in practice as anyone adding their own splash has almost certainly overridden these already.

To test use -

```
ant -Dcluster.config=platform build
ant -Dcluster.config=platform tryme
```

### CODE REVIEW

**Review by eirikbakke — APPROVED** [review]
Yes, good to update the template splash screen, to avoid confusion. Also good as the new one illustrates the ability to provide a double resolution for retina/HiDPI screens.

**Comment by neilcsmith-net** [comment]
Thanks @eirikbakke Am I right in thinking you made the original of this?  Was there an svg somewhere?

**Comment by eirikbakke** [comment]
Yes! It was made in Adobe Illustrator, but the following SVG is probably better to keep as an "original" going forward:

NetBeans HiDPI Splash Screen Template

The splash screen contains a slightly cleaned-up version of the NetBeans logo, which I have also put in a separate file here:

Apache NetBeans Logo with Product Name

The cleanup was just tiny changes of the vertex positions so that adjacent edges don't have microscopic gaps in them (which sometimes cause artifacts when the SVG is rasterized to PNG).

**Review by ebarboni — APPROVED** [review]
LGTM, nice catch :p

**Comment by neilcsmith-net** [comment]
Thanks, and thanks for sharing SVG @eirikbakke Have taken local copy, but perhaps could PR to include in the repo for future changes?

**Comment by eirikbakke** [comment]
@neilcsmith-net Sure, I can do that. What folder in the netbeans repo should files like this go in? (Another file I can put there is the Adobe Illustrator file for SVG icons drawn so far.)

**Pull request merged**
