### PR TITLE
[NETBEANS-3730] Use NewProject JavaFX archetypes tailored for NetBeans

### PR DESCRIPTION
**Pull request by errael**
See [archetypes project](https://github.com/errael/javafx-maven-archetypes) for documentation and details. The maven artifact referenced from this PR is in maven central (stating the obvious?).

### CODE REVIEW

**Comment by errael** [comment]
Updated PR to include latest javafx-version features.

**Comment by ebarboni** [comment]
Hi, I see that the PR https://github.com/openjfx/javafx-maven-archetypes/pull/8 is merged
Not sure how the plugin com.raelity.jfx follow the openjfx one

**Comment by geertjanw** [comment]
com.reality.jfx is a fork of openjfx and so it does not follow the openjfx one

**Comment by ebarboni** [comment]
https://github.com/errael/javafx-maven-archetypes say it's even with openjfx

**Comment by errael** [comment]
@ebarboni , @geertjanw Take a look at https://github.com/errael/javafx-maven-archetypes-netbeans. This PR is based on that. It incorporates all the latest changes including https://github.com/openjfx/javafx-maven-archetypes/pull/8 and .test.sh passes. Take a look at a dev email  from March 8 for a brief note on how to use this archetype via "Project from Archetype": http://mail-archives.apache.org/mod_mbox/netbeans-dev/202003.mbox/%3Cd44a8b47-39c4-0f82-05c6-b21aa15f75d1%40raelity.com%3E

**Comment by ebarboni** [comment]
ok merging

**Comment by jtulach** [comment]
I think it is a mistake to not use the official [javafx-maven-archetypes](https://github.com/openjfx/javafx-maven-archetypes/). The Gluon guys (@jperedadnr, @abhinayagarwal, @johanvos)  were very friendly to accept our [contribution to make sure the archetypes work with JDK8](https://github.com/openjfx/javafx-maven-archetypes/pull/8). 

I am the one to blame, I don't have much time to play with this at all, but: Have @errael tried to provide a patch to the [original archetypes](https://github.com/openjfx/javafx-maven-archetypes/) and got refused at least? 

Forking a (JavaFX) community should be the last resort, not the 1st (e.g. simplest) solution!

**Comment by errael** [comment]
@jtulach, in my mind this is the last resort. I first put this together because @geertjanw's PR6/PR8 had been around for several months. It's a backup so that NetBeans could ship with working archetypes in NewProject list just in case.  The archetype I put together has basically two changes from the **current** openjfx archetypes:

1. pom executions for run and debug which came from @jperedadnr [at StackOveflow](https://stackoverflow.com/questions/56197372/i-cant-debug-an-application-using-netbeans-11-with-javafx-12) slightly modified so that NetBeans could provide the jpda.address. It also appeared in an [openjfx-docs issue](https://github.com/openjfx/openjfx-docs/issues/100)
2. nbactions.xml which also comes from @jperedadnr comments

It's true I did not issue a PR to [original archetypes](https://github.com/openjfx/javafx-maven-archetypes/) for them to accept nbactions.xml; I believed what I read in other comments that they would not accept NetBeans specific stuff. And since both the pom executions and nbactions.xml came from the openjfx team, I figured (perhaps mistakenly) that they simply didn't choose to incorporate them.

I'll give them 2 PR's for these changes. As you can see from this PR it is trivial to change to a different archetype when it works.

**Comment by geertjanw** [comment]
Did this make it into 12.0-beta 1, if so, can you try 12.0-beta 1 and report here whether everything is as it should be, @errael?

**Comment by ebarboni** [comment]
Yep this is in beta1. As last ressort.
In the future it would be better to rely on openjfx archetype and to modify NetBeans side if something is specific to NetBeans. An archetype should be agnostic if possible.

**Comment by geertjanw** [comment]
Can you also try to see if these work in 12.0-beta 1, @ebarboni?

**Comment by neilcsmith-net** [comment]
> An archetype should be agnostic if possible.

+1. But that also requires agnostic ways of specifying common IDE actions, like run, debug, etc. This is not just a NetBeans problem, and is surely better solved in collaboration with Maven, OpenJFX and other IDEs?

As and until, can we detect JavaFX plugin and change default run actions when it's there?

**Comment by ebarboni** [comment]
sorry I hava low profile internet (need to have confereence with student) :/ was stuck for 2h dl will try later

maybe it's a way to adapt our mapping to the rest of the world.
for maven 
by default 
https://github.com/apache/netbeans/blob/accdbada0a9c5105bd3f06e435024230c1618316/java/maven/src/org/netbeans/modules/maven/execute/DefaultActionGoalProvider.java
will use the following
https://github.com/apache/netbeans/blob/3993bff721a4e34006494ebe970cd5650a70692c/java/maven/src/org/netbeans/modules/maven/execute/defaultActionMappings.xml

so maybe a more precise provider for javafx may help

this is prospective, did look very deep.

**Comment by errael** [comment]
I've [created PR](https://github.com/openjfx/javafx-maven-archetypes/pull/10) about adding debug execution to the openjfx archetypes. I've decided not to create a PR for nbactions.xml, I did mention @neilcsmith-net comments about a group to tackle the generic problem of specifying common IDE actions.

**Pull request merged**
