### PR TITLE
Update FlatLaf from 3.5 to 3.5.1

### PR DESCRIPTION
**Pull request by mbien**
bugfix release, see
https://github.com/JFormDesigner/FlatLaf/releases/tag/3.5.1

### CODE REVIEW

**Review by eirikbakke — APPROVED** [review]
Looks straightforward.

Is there a MacOS notarization script somewhere that must be updated whenever the FlatLAF native library paths change? (Just curious.)

**Comment by neilcsmith-net** [comment]
> Is there a MacOS notarization script somewhere that must be updated whenever the FlatLAF native library paths change?

@eirikbakke no, all separate dylib files are signed, as well as the ones in the jar itself as long as it matches the pattern at https://github.com/apache/netbeans-nbpackage/blob/master/src/main/java/org/apache/netbeans/nbpackage/macos/MacOS.java#L32

**Review by DevCharly — APPROVED** [review]
Great. Thank you.

**Comment by eirikbakke** [comment]
> no, all separate dylib files are signed, as well as the ones in the jar itself as long as it matches the pattern

Perfect!

**Pull request merged**
