### PR TITLE
Indexing of inner classes/interfaces

### PR DESCRIPTION
**Pull request by sdedic**
* Abstract methods were not indexed at all, since [they have no code](https://github.com/apache/netbeans/compare/delivery...sdedic:groovy/completion-inner-classes3?expand=1#diff-6ee817fd5ae2474a0c13faafb5907287e443661413bb3a5adef6c6a250280e12L303). 
* Indexer did not dive [into inner types](https://github.com/apache/netbeans/compare/delivery...sdedic:groovy/completion-inner-classes3?expand=1#diff-a15c71a9d9bb85f1b65d31becc69c263b500c5c1fc6cea716b1629d4f531e08fR278), 
* Navigator works bad with inner types, displayed `OuterType$InnerType`
* Variable type was obscured by assignments later than caret position.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
Having a test would increase my confidence in the change.

**Comment by ebarboni** [comment]
It's mergeable because it's green but I cannot test function. Need some squashing ?

**Comment by sdedic** [comment]
> Need some squashing ?

Hm, each of the commits fixes/addresses a separate thing, it could be better to have them separate (for the history).

**Comment by ebarboni** [comment]
feel free to merge maybe one more technical reviewer agree.

**Comment by sdedic** [comment]
Sorry for the recommit; I've split tests for the two separate  issues into individual commits. Now we have some unit tests for the fixes, too!

**Pull request merged**
