### PR TITLE
[NETBEANS-4443] PHP 8.0 Support

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-4443

- Rebased https://github.com/apache/netbeans/tree/php80-support with the master branch
- Fix the spec versions (see :https://github.com/apache/netbeans/commit/f2725d78318e38f1c138f3feae84eb71c54291e8 )

NOTE: Some new syntaxes are not supported yet.

### CODE REVIEW

**Review by tmysik — APPROVED** [review]

**Comment by tmysik** [comment]
@junichi11 

Approved. Please, let me know if I can merge it now (or feel free to do it).

Thank you.

**Comment by junichi11** [comment]
@tmysik Let's leave that to @lkishalmi (Release manager of NB12.2) Thank you :)

@lkishalmi Could you please merge this if there is no problem?

**Comment by tmysik** [comment]
@junichi11 There are some CI failures. Could you please check them? Thank you.

**Comment by junichi11** [comment]
@tmysik They are tests for the Java area. So, try rerunning the jobs.

**Comment by neilcsmith-net** [comment]
Yes, the main work of any release manager these days is to continually retrigger those tasks until they turn green - go @lkishalmi! :wink: In general, don't worry too much if those tests fail at times, particularly if not touching anything related.

**Comment by lkishalmi** [comment]
Yeah, I'm chasing Travis all day long. It seems this one got through, so let it be merged.

**Pull request merged**
