### PR TITLE
Warmup Maven Embedder to improve first-project-creation UX

### PR DESCRIPTION
**Pull request by mbien**
performance (`EmbedderFactory`):

 - first embedder initialization can take a while, async-profiler showed that a big chunk of it is spent within google guice
 - this starts the warmup task early, which solves the problem, since this will happen while the user is looking at the wizard
 - the warmup task is a no-op if it was already initialized

cleanup:

 - small jdk 17 renovation

the purple bits are `com.google.inject.*` code:

image

### CODE REVIEW

**Comment by mbien** [comment]
this is offtopic but this was unexpected: `new Properties(other)` is apparently no copy constructor since [it stores a reference to other](https://github.com/openjdk/jdk/blob/7ec55df34af98e9a80381dba7f7f2127f2248f73/src/java.base/share/classes/java/util/Properties.java#L206-L211)! reverted that change.

**Review by neilcsmith-net — APPROVED** [review]
Makes sense to me.

Possibly consider two commits in future - code update and behaviour change.  Makes it easier to see the actual proposed change.

The fun of legacy collections! :laughing:

**Comment by mbien** [comment]
I have to work on improving my stash management

**Comment by sdedic** [comment]
Hm, I guess originally the warmup was postponed to first project open so that it does not slow down startup of the application, but it could be possibly prior ergonomics was introduced which inhibits the whole module.

**Comment by mbien** [comment]
> Hm, I guess originally the warmup was postponed to first project open so that it does not slow down startup of the application, but it could be possibly prior ergonomics was introduced which inhibits the whole module.

it is still the case. It just triggers the initialization a little bit earlier now. One wizard panel earlier to be exact.

When a project is already open, there should be no difference. With no project open there won't be any initialization still.

Technically I wouldn't call it warmup, since it is about lazy/eager initialization and less of running things to throw them away again.

one day I plan to revisit this again  https://github.com/apache/netbeans/pull/5638 and check what is still needed and what can be optimized for new hardware/software realities.


quick way to debug the embedder initialization (I should have added proper logging there):
```diff
diff --git a/java/maven.embedder/src/org/netbeans/modules/maven/embedder/EmbedderFactory.java b/java/maven.embedder/src/org/netbeans/modules/maven/embedder/EmbedderFactory.java
index 752f59f..7482909 100644
--- a/java/maven.embedder/src/org/netbeans/modules/maven/embedder/EmbedderFactory.java
+++ b/java/maven.embedder/src/org/netbeans/modules/maven/embedder/EmbedderFactory.java
@@ -385,8 +385,10 @@
     }
 
     public static @NonNull MavenEmbedder getProjectEmbedder() {
+        System.out.println("<<<<<<<<<<<<<<<<get>>>>>>>>>>>>>>>>>>>");
         synchronized (PROJECT_LOCK) {
             if (project == null) {
+                System.out.println("<<<<<<<<<<<<<<<<init>>>>>>>>>>>>>>>>>>>");
                 try {
                     project = createProjectLikeEmbedder();
                 } catch (PlexusContainerException ex) {
@@ -394,6 +396,7 @@
                     throw new IllegalStateException(ex);
                 }
                 projectLoaded.set(true);
+                System.out.println("<<<<<<<<<<<<<<<<done>>>>>>>>>>>>>>>>>>>");
             }
             return project;
         }

```

**Pull request merged**
