### PR TITLE
[NETBEANS-2875] Fix for Enterprise Catalog references broken

### PR DESCRIPTION
**Pull request by peedeeboy**
*What this Pull Request does in a nutshell*
As reported on the Dev mailing list by Thomas Kellerer, the Enterprise Catalog cannot locate its schema files in Netbeans 11.1, as they no longer exist in the location specified (I suspect they were removed from this location during Oracle donation).  This results in XML validation errors when opening/validating a web.xml file in the Editor.

This PR fixes that by changing the base resource path in EnterpriseCatalog.java to `nbres:/org/netbeans/modules/j2ee/dd/impl/resources/` where the schema files do exist.  The DD Loaders module is already dependent on this module, so it seems a fairly safe change to me...?  It also seemed sensible to only have one place to maintain them.

This PR also adds a simple Unit Test that will iterate through every schema in the Enterprise Catalog and check that the URL can be opened by Netbeans.

*Files changed/added*
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/catalog/EnterpriseCatalog.java
Changed:
`private static final String RESOURCE_PATH = "nbres:/org/netbeans/modules/j2ee/ddloaders/catalog/resources/"; //NO18N`
to:
`private static final String RESOURCE_PATH = "nbres:/org/netbeans/modules/j2ee/dd/impl/resources/"; //NO18N`
Where these schema files do exist.

enterprise/j2ee.ddloaders/test/unit/src/org/netbeans/modules/j2ee/ddloaders/catalog/EnterpriseCatalogTest.java
Added this file including a Unit Test that will iterate through Enterprise Catalog entries and check the URL can be opened.

*Testing*
1) Create a new Maven Web Application project.  Choose JavaEE7
2) Create a Standard Deployment Descriptor file (web.xml)
Before this PR:
3) Netbeans will show a red X next to the web.xml node in Project explorer
4) Right clicking in the Editor for the web.xml file and choosing "Validate XML" will result in an XML validation error
After this PR:
3) Netbeans will not show the red X next to the web.xml node
4) Right clicking in the Editor for the web.xml and choosing "Validate XML" will validate the file successfully

*Things I'm not 100% happy with*
The Unit Test will output the following warning:
'org.netbeans.modules.settings.RecognizeInstanceObjects$OverObjects <init>
WARNING: Not listening on module system'
I believe because the URL Factory is being used without the entire NB Module System being loaded.  I'm not sure this is actually a problem for the Unit Test (trying to load the entire Module System seems like overkill for such a simple test), but there also doesn't seem to be any way to suppress this particular warning with a '@SurpressWarnings' annotation.  Suggestions?

### CODE REVIEW

**Comment by peedeeboy** [comment]
@juneau001 Would you be kind enough to check that this PR won't cause any issues with your excellent work on Java EE 8 implementation?  Many thanks! :)

**Comment by matthiasblaesing** [comment]
The unittest fails currently - it tries to load `nbres:/org/netbeans/modules/j2ee/dd/impl/resources/jobXML_1_0.xsd`, which is not present. The file is referenced in `EnterpriseCatalog.java`, line 126. My google-foo was good and I found a source for `jobXML_1_0.xsd`.

https://github.com/WASdev/standards.jsr352.jbatch/blob/master/com.ibm.jbatch.container/src/main/resources/xsd/jobXML_1_0.xsd

That file can be directly included (ASL2 licenses). I would add a new comment after line 10, where the file was from and that the notice file:

https://github.com/WASdev/standards.jsr352.jbatch/blob/master/NOTICE.txt

did not contain information, that applies to the referenced file.

**Comment by peedeeboy** [comment]
Hi @matthiasblaesing .  Many thanks for your feedback.

This PR is to replace my previous PR, https://github.com/apache/netbeans/pull/1266, which was (at least partially) regressed.

In that PR, you asked my to remove the reference tojobXML_1_0.xsd from EnterpriseCatalog.java as the licensing wasn't clear for that file.

Please clarify if you want to me to add the file, or I can again remove the reference from EnterpriseCatalog.java, whichever you think best.

**Comment by juneau001** [comment]
I haven't had an opportunity to review this pull request yet, but I will do so tonight...along with the included change from @matthiasblaesing ...Thanks for working on this issue!

**Comment by matthiasblaesing** [comment]
If I remember correctly I was not aware of a correctly licensed variant of jobXML_1_0.xsd. That has changed and thus I would include this compatible file.

Am 23. Juli 2019 22:19:15 MESZ schrieb Pete Whelpton <notifications@github.com>:
>Hi @matthiasblaesing .  Many thanks for your feedback.
>
>This PR is to replace my previous PR,
>https://github.com/apache/netbeans/pull/1266, which was (at least
>partially) regressed.
>
>In that PR, you asked my to remove the reference tojobXML_1_0.xsd from
>EnterpriseCatalog.java as the licensing wasn't clear for that file.
>
>Please clarify if you want to me to add the file, or I can again remove
>the reference from EnterpriseCatalog.java, whichever you think best.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/apache/netbeans/pull/1388#issuecomment-514367985

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by peedeeboy** [comment]
I've added `jobXML_1_0.xsd` to `enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/`.  

I ran `ant -Dcluster.config=enterprise rat` locally, and it seems to recognize `jobXML_1_0.xsd` as Apache Licensed, so I haven't added it to the `licenseinfo.xml` file

Hope that is the right thing to do....

**Comment by juneau001** [comment]
I have reviewed the code and built successfully.  Everything looks good.  Thanks for making the requested updates for jobXML_1_0.xsd.

**Comment by peedeeboy** [comment]
Thanks @juneau001 !  Appreciate your input :)

**Comment by matthiasblaesing** [comment]
Merged via https://github.com/apache/netbeans/commit/f1603f06ea1033bec08e90c2a45585d8e1412c6f

Thank you.

**Pull request closed without merging**
