### PR TITLE
Increment spec versions for 12.6 development

### PR DESCRIPTION
**Pull request by ebarboni**
I'm not sure of the schedule for that. Should be done before freeze :D

### CODE REVIEW

**Review by neilcsmith-net — APPROVED** [review]
Yes, should go in as soon as last delivery to master merge is complete and sigtests done. #3059 for 12.5 being so late was an oversight.

**Review by JaroslavTulach — APPROVED** [review]

**Comment by ebarboni** [comment]
should we merge this and do another spec incr on master once delivery for 12.6 is created ?

**Comment by neilcsmith-net** [comment]
@ebarboni well, either way this needs to merge.  I think @matthiasblaesing is right about timing the next increment though.

**Comment by ebarboni** [comment]
closing my eyes and merging only version bump

**Comment by matthiasblaesing** [comment]
@ebarboni Neils interpretation was correct. The spec version bump here is necessary, my mail was intended for the future, not the left overs for 12.5.

**Pull request merged**
