### PR TITLE
lower the OS level memory consumption of NB LSP

### PR DESCRIPTION
**Pull request by thurka**
Cherry-picked https://github.com/apache/netbeans/pull/5909 from master to delivery.

(cherry picked from commit 879061efcae9c68081feae717c0517c975057237)

### CODE REVIEW

**Review by sdedic — APPROVED** [review]

**Comment by neilcsmith-net** [comment]
@thurka we don't generally cherry pick from master to delivery.  If this change was meant for NB18 it should have been opened and reviewed against delivery in the first place.  It's doable, but will require extra work to sync delivery back into master.  cc/ @MartinBalin for a call on that.  Should merge as late as we can or it will break other CI testing against master in #5908

**Comment by MartinBalin** [comment]
@neilcsmith-net I forgot to mention to Tomas it has to go to delivery, forgot thing which is obvious for me. How does the cherry picked commit from master to delivery requires syncing delivery back to master? Sorry, I don't understand.

**Comment by MartinBalin** [comment]
Thank you very much Neil

**Comment by mbien** [comment]
not sure if this will help, but we could add a few notes to the reviewer guide:
https://cwiki.apache.org/confluence/display/NETBEANS/PRs+and+You+-+A+reviewer+Guide

**Comment by neilcsmith-net** [comment]
> not sure if this will help, but we could add a few notes to the reviewer guide: https://cwiki.apache.org/confluence/display/NETBEANS/PRs+and+You+-+A+reviewer+Guide

@mbien yes. Going slightly off-topic, but consolidating / linking the text from the [NOTICE] emails and the page on PRs to delivery would be good.

https://lists.apache.org/thread/2c0nlt35xo01p4k8r6gtktqmt9tjcvtx
https://cwiki.apache.org/confluence/display/NETBEANS/Pull+requests+for+delivery

And that tracking [NOTICE] emails is a prerequisite for any committer (that was why we started using the tag in the first place).

**Comment by neilcsmith-net** [comment]
@MartinBalin OK, sync will merge cleanly as I hoped, so only downside is the commit will be in master history twice.

**Comment by MartinBalin** [comment]
@neilcsmith-net  thank's for merging. Re where to document how to target PR when there is a release branch already and you want to merge to both should not this be mentioned here? https://cwiki.apache.org/confluence/display/NETBEANS/Submitting+Pull+Requests I can update it.

**Comment by neilcsmith-net** [comment]
@MartinBalin it's mentioned in every [NOTICE] email, as in the one linked above, and there's additional information on the other wiki page I linked too.  We could add information from both the links to the Submitting Pull Requests page.  Assuming that gets read! :smile:

The key thing is that paying attention to [NOTICE] emails on dev@ (even if nothing else) should be a pre-requisite for committing.

**Comment by mbien** [comment]
I linked the delivery wiki page now from here too:
https://cwiki.apache.org/confluence/display/NETBEANS/PRs+and+You+-+A+reviewer+Guide

and I added screenshots which hopefully increases the probability of someone reading it :)

**Pull request merged**
