### PR TITLE
Feature: Added all enterprise modules with non failing unit tests

### PR DESCRIPTION
**Pull request by asbachb**

### CODE REVIEW

**Comment by mbien** [comment]
I checked the log for the typical junit test summary and `gradle.javaee`, `j2ee.ant`, `web.kit`, `web.primefaces` and `websvc.core` don't seem to run any tests?

If there is nothing to run, lets not add it to CI until there is.

I ran the workflow two more times and all green on the enterprise job which is a good sign regarding reliability. Thanks for doing this!

**Comment by asbachb** [comment]
Double checked the modules. Removed some stuff from the `test` folder which seemed to be quite dead code.

**Comment by matthiasblaesing** [comment]
Would it make sense to go directly to Java 11, instead of reinstating tests, that run on a JDK we don't target? I assume, that after the 8->11 transition the next step up will not be painless, but less painful, that that.

**Comment by mbien** [comment]
@matthiasblaesing yeah would be great, I started the work a while ago #5166 but got stuck at some point and other higher priority tasks showed up.

What we could do though is to run all compatible tests on JDK 11 and the rest on JDK 8 within the same job.

From the old tests, only `enterprise/websvc.editor.hints` was failing on JDK 11 - haven't checked any modules which were added here in this PR.

**Review by mbien — APPROVED** [review]
all green, going to merge this.

will move as many enterprise tests to JDK 11 as possible in a followup PR.

**Pull request merged**
