### PR TITLE
Java Hints SPI module renovation

### PR DESCRIPTION
**Pull request by mbien**
3 commits: first (large) is cleanup, second improves hint metrics logging, third has some performance tweaks

Java Hints SPI module cleanup:

 - records, switch, instanceof
 - removed unused fields and code
 - collections
 - code simplifications
 - java 17 lang level
 

HintsInvoker logging improvements:

 - print metrics to regular logger ([`-Dorg.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.level=FINE`](https://github.com/apache/netbeans/pull/7563#issuecomment-2229562394))
 - add invocation count and cancelled state
 - sort by time spent before dump
 

Performance Improvements:

in CopyFinderBasedBulkSearch:

 - implemented matches method
 - extracted matcher from loop

in JavaFixUtilities:

 - fast path for JavaFixUtilities can-safely-remove scanners

### CODE REVIEW

**Comment by mbien** [comment]
@jlahoda curious what you think about the last commit https://github.com/apache/netbeans/pull/7563/commits/d5a5ee0c2099925e14586b519a6f280f486755c2. It is fairly simple in concept and attempts to stop as soon the result is known.

**Review by lahodaj — APPROVED** [review]
I think it looks good. One general comment is that factories list `List.of()` are very `null`-averse - it is not even permitted to ask the resulting instance if it contains `null`. But if tests are fine with the change, it is OK, I think (and we can fix/revert spots which would turn out to be problematic).

On a process side, I note there will be a conflict between this patch and https://github.com/apache/netbeans/pull/7548, as both adjust the `@SuppressWarnings` fix (cc @Achal1607).

**Comment by mbien** [comment]
> it is not even permitted to ask the resulting instance if it contains null

interesting! I didn't consider this scenario. But it does make sense that null-averse collections would consider calls like `contains(null)` as possible bug in client code. I will take another look through the usages before merge.

**Comment by mbien** [comment]
@Achal1607 are you ok with resolving the conflicts if this makes it in first?

**Comment by Achal1607** [comment]
Yes i will resolve the conflicts no problem

**Comment by mbien** [comment]
I took a look through all changes which involved the collection factories and it should be all fine. The most common case is that a map or list ends up in a loop which doesn't expects null elements. 

So if something is calling `contains(null)` or `get(null)` somewhere (which I also checked), it would likely be a sleeping bug.

While looking through it I found a few more trivial record candidates which I implemented. Enabling all tests and will run a local smoke test, going to merge if everything is ok.

**Comment by mbien** [comment]
btw, output for `-Dorg.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.level=FINE` looks like:
```
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=46.61ms, invocations=81, cancelled=false}: error-in-javadoc
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=16.73ms, invocations=2, cancelled=false}: o.n.m.j2ee.ejbverification.UseInjectionInsteadOfInstantionRule
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=11.13ms, invocations=3, cancelled=false}: org.netbeans.modules.java.hints.jdk.ConvertToARM
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=10.15ms, invocations=1075, cancelled=false}: MissingJavaEEForUnitTestExecutionHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=9.52ms, invocations=916, cancelled=false}: org.netbeans.modules.java.hints.bugs.NPECheck
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=4.84ms, invocations=74, cancelled=false}: org.netbeans.modules.java.hints.threading.Tiny.canBeFinal
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=3.70ms, invocations=1149, cancelled=false}: org.netbeans.modules.java.hints.bugs.Unbalanced$Collection
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=2.94ms, invocations=21, cancelled=false}: org.netbeans.modules.java.hints.jdk.ConvertToStringSwitch
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=1.91ms, invocations=12, cancelled=false}: org.netbeans.modules.java.hints.jdk.UseSpecificCatch
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=1.73ms, invocations=90, cancelled=false}: org.netbeans.modules.java.hints.bugs.UnusedAssignmentOrBranch.unusedAssignment
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=1.49ms, invocations=263, cancelled=false}: org.netbeans.modules.java.hints.bugs.ThrowableNotThrown.methodInvocation
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=1.36ms, invocations=1075, cancelled=false}: OptionalEE7APIsHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=1.14ms, invocations=514, cancelled=false}: org.netbeans.modules.java.hints.StaticAccess
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=1.05ms, invocations=74, cancelled=false}: org.netbeans.modules.java.hints.HideFieldByVar
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=1.05ms, invocations=1, cancelled=false}: org.netbeans.modules.java.openjdk.jtreg.MissingRefOutputHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.97ms, invocations=1, cancelled=false}: org.netbeans.modules.java.openjdk.jtreg.TagOrderHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.95ms, invocations=1, cancelled=false}: org.netbeans.modules.java.openjdk.jtreg.WrongSourceVersion
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.94ms, invocations=1, cancelled=false}: org.netbeans.modules.java.openjdk.jtreg.ModulesHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.90ms, invocations=2, cancelled=false}: Javac_canUseDiamond
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.89ms, invocations=605, cancelled=false}: org.netbeans.modules.java.hints.LeakingThisInConstructor
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.84ms, invocations=1076, cancelled=false}: org.netbeans.modules.java.hints.bugs.Unbalanced$Array
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.71ms, invocations=68, cancelled=false}: org.netbeans.modules.java.hints.bugs.UnusedAssignmentOrBranch.deadBranch
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.61ms, invocations=47, cancelled=false}: Imports_EXCLUDED
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.58ms, invocations=81, cancelled=false}: org.netbeans.modules.java.hints.ExportNonAccessibleElement
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.47ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.AnnotationPostContruct
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.40ms, invocations=2, cancelled=false}: org.netbeans.modules.java.hints.WrongPackageSuggestion
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.40ms, invocations=6, cancelled=false}: org.netbeans.modules.java.hints.bugs.InfiniteRecursion.run
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.39ms, invocations=263, cancelled=false}: org.netbeans.modules.java.hints.OverridableMethodCallInConstructor
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.39ms, invocations=5, cancelled=false}: org.netbeans.modules.java.hints.suggestions.ConvertIfToSwitch
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.38ms, invocations=86, cancelled=false}: org.netbeans.modules.java.hints.bugs.CheckReturnValueHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.36ms, invocations=68, cancelled=false}: org.netbeans.modules.java.hints.bugs.Tiny.indentation
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.32ms, invocations=6, cancelled=false}: org.netbeans.modules.java.hints.AddOverrideAnnotation
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.31ms, invocations=561, cancelled=false}: org.netbeans.modules.java.hints.StaticNonFinalUsedInInitialization
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.28ms, invocations=74, cancelled=false}: org.netbeans.modules.java.hints.suggestions.ConstantNameHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.27ms, invocations=74, cancelled=false}: org.netbeans.modules.java.hints.HideField
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.25ms, invocations=110, cancelled=false}: org.netbeans.modules.java.hints.InitializerCanBeStatic
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.24ms, invocations=35, cancelled=false}: org.netbeans.modules.java.hints.jdk.ConvertToTextBlock
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.23ms, invocations=263, cancelled=false}: EmbeddableEJBContainer
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.20ms, invocations=1, cancelled=false}: obsoleteAnnotationSupportedSource
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.19ms, invocations=1, cancelled=false}: Imports_SAME_PACKAGE
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.16ms, invocations=1, cancelled=false}: o.n.m.j2ee.jpa.verification.QueriesProperlyDefined
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.15ms, invocations=23, cancelled=false}: Wrong_String_Comparison
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.13ms, invocations=1, cancelled=false}: o.n.m.j2ee.jpa.verification.OnlyEntityOrMappedSuperclassCanUseIdClass
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.12ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.jdk.Regexp
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.12ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.perf.ReplaceBufferByString
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.11ms, invocations=1, cancelled=false}: Imports_DEFAULT_PACKAGE
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.10ms, invocations=18, cancelled=false}: org.netbeans.modules.java.hints.RemoveUnnecessaryReturn
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.08ms, invocations=6, cancelled=false}: org.netbeans.modules.editor.htmlui.JSNI2JavaScriptBody
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.05ms, invocations=2, cancelled=false}: org.netbeans.modules.java.hints.bugs.Tiny.varTypeDiamondOperator
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.05ms, invocations=3, cancelled=false}: org.netbeans.modules.java.hints.EqualsHint
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.04ms, invocations=6, cancelled=false}: org.netbeans.modules.java.hints.ClassStructure.finalPrivateMethod
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.04ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.MissingHashCode
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.03ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.MultipleLoggers
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.02ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.WSisSLSB
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.02ms, invocations=2, cancelled=false}: StringBuilderAppend
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.02ms, invocations=6, cancelled=false}: org.netbeans.modules.java.hints.finalize.FinalizeDoesNotCallSuper
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.02ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.jdk.AnnotationProcessors.oGSA
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: o.n.m.web.jsf.hints.FlowScopedBeanWithoutCdi
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.threading.Tiny.volatileArray
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.BeanHasDifferentLBIandRBI
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=2, cancelled=false}: org.netbeans.modules.java.hints.bugs.ConfusingVarargsParameter.primitiveArray
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.bugs.ThrowableNotThrown.newThrowable
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: Imports_UNUSED
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.BeanImplementsBI
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: org.netbeans.modules.java.hints.bugs.Unused
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.SessionSynchImplementedBySFSBOnly
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=6, cancelled=false}: org.netbeans.modules.java.hints.finalize.FinalizeDeclared
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.01ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.LegalModifiers
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.LocalAnnotatedBeanHasLBI
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.RemoteAnnotatedBeanHasRBI
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.SBSuperClassNotSB
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.BusinessMethodExposed
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.HasNoArgContructor
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: AnnotationAsSuperInterface
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.PersistentTimerInEjbLite
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.web.jsf.hints.JakartaFacesBeanIsGonnaBeDeprecated
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.BMnotPartOfRBIandLBI
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.j2ee.ejbverification.AsynchronousMethodInvocation
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: {time=0.00ms, invocations=1, cancelled=false}: o.n.m.web.jsf.hints.JavaxFacesBeanIsGonnaBeDeprecated
FINE [org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker]: hint processing complete
```
(~800 LOC java class)

**Pull request merged**
