### PR TITLE
Parameterise NetBeans version number for installer builds

### PR DESCRIPTION
**Pull request by rtaneja1**

### CODE REVIEW

**Comment by geertjanw** [comment]
Is there any reason not to merge this, what part of this needs to be especially reviewed?

**Comment by geertjanw** [comment]
Any reason not to merge this? Feel free to merge, @rtaneja.

**Comment by rtaneja1** [comment]
There seems to be some infra issue with travis, build failing in bin/install-jdk.sh for another PRs as well with same errors
Expected feature release number in range of 9 to 13, but got: 8
[31;1mThe command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .[0m

**Comment by rtaneja1** [comment]
Build passes here
https://builds.apache.org/view/M-R/view/NetBeans/job/netbeans-installers/

**Pull request merged**
