### PR TITLE
Change maven 384 dependencies to codehaus groupID

### PR DESCRIPTION
**Pull request by ebarboni**
During testing of org.netbeans.api:org-netbeans-api-maven:jar:RELEASE130 it appears that the pom is using dependencies that should come from codehaus groupId instead of sonatype.

### CODE REVIEW

**Review by neilcsmith-net — APPROVED** [review]

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me - thanks for catching this. There is a test tool in the build tool to check the hash, but not the artifact.

**Comment by ebarboni** [comment]
@neilcsmith-net would it be possible to have that in the release130 branch for being able to regenerate all the artefacts.

**Comment by neilcsmith-net** [comment]
@ebarboni planning to sync for rc2 later today.

**Comment by neilcsmith-net** [comment]
OK, it's in release130 now.

**Pull request merged**
