### PR TITLE
Merge pull request #2866 from apache/master

### PR DESCRIPTION
**Pull request by geertjanw**
Sync master to release124 for beta 2

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@geertjanw not sure this should still be open?!

**Comment by geertjanw** [comment]
After success of rc2, we'll merge the master/release124 pr.

**Comment by neilcsmith-net** [comment]
@geertjanw nothing should be merged from release124 to master. I think this is an old PR that should just be closed!

After rc2 will be #2926

**Comment by geertjanw** [comment]
Maybe we made a mistake and it should be delivery/master -- i.e., we don't have a sync for that.

**Comment by geertjanw** [comment]
Yes, we do have this:

https://github.com/apache/netbeans/pull/2926

**Comment by geertjanw** [comment]
Should we simply close this, looks like it was a mistake.

**Pull request closed without merging**
