### PR TITLE
Fixed test cases to run/pass on JDK17

### PR DESCRIPTION
**Pull request by singh-akhilesh**
https://issues.apache.org/jira/browse/NETBEANS-5679
Fixed below test cases:
editor.java.GoToSupportTest.java
java.editor.codegen.DelegateMethodGeneratorTest
java.editor.base.semantic.UnusedDetectorTest
java.editor.base.javadoc.JavadocImportsTest

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
Can we start running the tests on JDK17? I don't see [any tests on JDK17](https://github.com/apache/netbeans/pull/2954/checks?check_run_id=2576175595) here.

**Comment by singh-akhilesh** [comment]
> Can we start running the tests on JDK17? I don't see [any tests on JDK17](https://github.com/apache/netbeans/pull/2954/checks?check_run_id=2576175595) here.

We have to update the travis pipeline for JDK17. However there are more test cases in java.editor and java.editor.base that's also has to be address. We are working on this. So lets wait some more time. Thanks

**Review by BradWalker — APPROVED** [review]
thanks..

**Comment by JaroslavTulach** [comment]
Btw. we aren't [testing on JDK16 either](https://github.com/apache/netbeans/pull/2954/checks?check_run_id=2576175595)! Can I somehow stop further _unverified bugfixes_ until we start testing on target platforms? I don't mind if we disable some tests on JDK16 or JDK17, but we have to be testing in our Travis CI!

**Comment by singh-akhilesh** [comment]
> Btw. we aren't [testing on JDK16 either](https://github.com/apache/netbeans/pull/2954/checks?check_run_id=2576175595)! Can I somehow stop further _unverified bugfixes_ until we start testing on target platforms? I don't mind if we disable some tests on JDK16 or JDK17, but we have to be testing in our Travis CI!



> Btw. we aren't [testing on JDK16 either](https://github.com/apache/netbeans/pull/2954/checks?check_run_id=2576175595)! Can I somehow stop further _unverified bugfixes_ until we start testing on target platforms? I don't mind if we disable some tests on JDK16 or JDK17, but we have to be testing in our Travis CI!

**Comment by singh-akhilesh** [comment]
> Btw. we aren't [testing on JDK16 either](https://github.com/apache/netbeans/pull/2954/checks?check_run_id=2576175595)! Can I somehow stop further _unverified bugfixes_ until we start testing on target platforms? I don't mind if we disable some tests on JDK16 or JDK17, but we have to be testing in our Travis CI!

Yes, you can stop unverified bugfixes.

**Review by jlahoda — APPROVED** [review]
Overall looks fine. A few improvements here:
https://github.com/singh-akhilesh/netbeans/pull/1

These are:
-the completion tests disable parameter names for all, trying to avoid by re-organizing code, so the DelegateMethodGeneratorTest can pass
-the `brokenMethod` in `UnusedDetectorTest` is really broken - better to disable that piece of test.

**Pull request merged**
