### PR TITLE
[NETBEANS-2888] - Project Context Path problem for Java Maven Web Application

### PR DESCRIPTION
**Pull request by juneau001**
- Modified 7 files and added a glassfish-web.xml template
- File modifications change support for Java EE applications to create and/or modify glassfish-web.xml if deploying to Eclipse GlassFish

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@juneau001 thanks!  Can you run RAT locally?  Seems to be failing that on the Travis tests, although possible that's not the actual cause of failure there due to some build changes going on.

**Comment by neilcsmith-net** [comment]
@juneau001 thanks, but re-run RAT test on Travis after build merging still shows a failure, which I think is actually a valid issue.

```
BUILD FAILED
/home/travis/build/apache/netbeans/scratch/nbbuild/build.xml:2250: Failed Rat test(s):
Unapproved license in 1 file(s) 
https://github.com/apache/netbeans/tree/master/enterprise/glassfish.eecommon/src/org/netbeans/modules/glassfish/eecommon/api/ddtemplates/javaee/glassfish-web.xml
```

**Comment by juneau001** [comment]
Thanks @neilcsmith-net I will add a license header to the file.

**Comment by neilcsmith-net** [comment]
@juneau001 not sure!  Only reference I kind find to EPL is in `java/junit.ui/licenseinfo.xml`

Pinging @matthiasblaesing for review / help on what needs to be done here.

**Comment by matthiasblaesing** [comment]
I'm only commenting on the license issue:

- Is the new `glassfish-web.xml` a copy from somewhere? If not, add the ALv2 license and you are done.
- If the file is copied and the source is verified to place it under Eclipse Public License 2.0, you just use the `EPL-v20` for the ref:

```xml
<license ref="EPL-v20" />
```

The ref points to a file inside the `nbbuild/licenses` folder.

**Comment by neilcsmith-net** [comment]
@juneau001 my previous comment on this appears to have gone walkabout! :confused: 

I think the license info line

```
<comment type="COMMENT_UNSUPPORTED" />
```

needs to be `TEMPLATE_MINIMAL_IP` or `CATEGORY_B`.  Probably the former - check descriptions at https://github.com/apache/netbeans/blob/master/nbbuild/antsrc/org/netbeans/nbbuild/extlibs/licenseinfo/CommentType.java#L22  `COMMENT_UNSUPPORTED` is for file types (png, json, etc.) that can't have license headers.

**Comment by neilcsmith-net** [comment]
@juneau001 thanks!  Just retriggered the one failing test (pretty sure nothing relevant as it's failing spuriously on everything at the moment).  Assuming green I'll merge.

**Pull request merged**
