### PR TITLE
nbbuild dir: removed unessesary old forms of Integer type

### PR DESCRIPTION
**Pull request by tbw777**
Changed boxing/autoboxing with Integer()/valueOf()/intValue() to raw int values or parseInt(some string)

### CODE REVIEW

**Comment by mbien** [comment]
@tbw777 thats enough PRs for now. lets wait a bit till we can merge a few.

**Comment by tbw777** [comment]
@mbien 
OK!

**Comment by tbw777** [comment]
@mbien 
I'l try some small PR, write me is it good.
A reason: blocking PR queue is low my motivation to do anything.

**Comment by mbien** [comment]
@tbw777 doing larger PRs is fine. Just not crazy large. Someone has to review the PR somehow.

So it depends how complex a PR is. If it does something simple in 200 files.. it might be ok. You can also put multiple commits into a single PR which makes reviewing also easier. 

This one for example is too big #5203 since merging this will cause too many conflicts at once to other PRs. This is better #5189.
Also keep in mind that PRs uses apache resources since CI has to build and test a lot - too many PRs is also bad if they can be combined into medium-sized PRs.

So please don't open too many PRs since we have to merge some first. You can work with your clone of netbeans without creating PRs, and once we can merge more you simply open more if you want. It can take some time.

**Comment by tbw777** [comment]
@mbien ok

**Comment by tbw777** [comment]
@mbien can i post now one new PR or continue wait? )

**Comment by matthiasblaesing** [comment]
> @mbien can i post now one new PR or continue wait? )

Flooding the project with mass change PRs is a good way to be ignored. Let the current PRs be drained and then go on. Remember: we are not paid to do this and I'm more inclined to look at PRs fixing actual problems and not just mechanical cleanups.

**Comment by tbw777** [comment]
ok

**Review by lkishalmi — APPROVED** [review]
Seems reasonable to me.

**Comment by BradWalker** [comment]
> > @mbien can i post now one new PR or continue wait? )
> 
> Flooding the project with mass change PRs is a good way to be ignored. Let the current PRs be drained and then go on. Remember: we are not paid to do this and I'm more inclined to look at PRs fixing actual problems and not just mechanical cleanups.

Hey @tbw777, let provide some context here.. I started out by cleaning up a lot of source code "low hanging" fruit. Stuff that was really easy to review. So I understand the excitement.

But, remember people have to review this. And what might seem trivial or straight-forward to you is work for others. That's not to say your work doesn't have meaning or value. It does have value and people want to include it. So just be aware there is work on our end to get this into the system.

So, pace yourself. We want you involved for the long term. Don't burn yourself out. Let us catch up to your enthusiasm.

**Review by BradWalker — APPROVED** [review]

**Review by mbien — APPROVED** [review]

**Pull request merged**
