### PR TITLE
Upgrade bundled maven to 3.9.3.

### PR DESCRIPTION
**Pull request by mbien**
minor dependency update from 3.9.2 to 3.9.3 of bundled maven

beside the usual bugfixes, the most notable change is that there won't be any plugin validation warnings for default plugins as seen in typical hello world projects, since the default plugins are now set to a recent enough version of the box.

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by ebarboni** [comment]
+1 3.9.3 is out now :p

**Comment by mbien** [comment]
awesome. gonna refresh this PR soon. Had a little unplanned "situation" at home and was offline.

**Comment by mbien** [comment]
rabased to resolve conflict, switched dependency from staging to central

**Comment by mbien** [comment]
@ebarboni want to review? :)

**Comment by ebarboni** [comment]
@mbien LGTM get some stress because I forget to clean former maven version from external.

**Comment by mbien** [comment]
@ebarboni awesome, thanks. Lets get this in so that it gets some testing in before freeze.

**Comment by ebarboni** [comment]
@mbien,  not sure but with 3.9.3 got some install issue on Windows (using clean install) with access denied on local repo folder.
removing localrepo seems to solve the issue.

**Pull request merged**
