### PR TITLE
Fix an 'illegal reflective access' warning on startup

### PR DESCRIPTION
**Pull request by eirikbakke**
This commit removes the warning below, which was observed when starting a NetBeans Platform application:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openide.util.RequestProcessor$TopLevelThreadGroup (file:/C:/Users/ebakke/.m2/repository/org/netbeans/api/org-openide-util/RELEASE180ULT7/org-openide-util-RELEASE180ULT7.jar) to method sun.awt.AppContext.getAppContext()
WARNING: Please consider reporting this to the maintainers of org.openide.util.RequestProcessor$TopLevelThreadGroup
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### CODE REVIEW

**Review by matthiasblaesing — COMMENTED** [review]
Wouldn't it make sense to remove the code completely? Even when considering developments like OpenWebStart, I assume, that the developers from OWS do the sane thing and don't try to share the same java process for multiple executions. Thus this indeed is mood.

**Comment by eirikbakke** [comment]
Yeah, I can remove it. I have a habit of keeping old code around until it actually gets in the way, but this one is unlikely to ever be needed again.

**Comment by eirikbakke** [comment]
Thanks for reviewing! Merging...

**Comment by mbien** [comment]
forgot to squash :)

**Comment by eirikbakke** [comment]
D'oh, sorry about that!

**Pull request merged**
