### PR TITLE
[NETBEANS-4997] use edge chromium syntax for opening URLs in Edge

### PR DESCRIPTION
**Pull request by sworisbreathing**
https://issues.apache.org/jira/browse/NETBEANS-4997

Solution is taken from https://stackoverflow.com/a/62452956

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@junichi11 valid question. The question that was asked in the past: What is the worst that could happen if the author claims ownership and requires removal of the change?

For this change it is trivial and I doubt copyright could be claimed on this change (it is trivial to start a command line and pass an URL there). So I think it is fine.

**Comment by sworisbreathing** [comment]
@junichi11 @matthiasblaesing yeah copyright of course belongs to ASF. I've committed to other apache projects in the past and have a JIRA account under the same handle, so I just assumed I had already signed the CLA at some point. I'm happy to follow up on that if this isn't sufficient :-)

**Comment by junichi11** [comment]
> I try to run it in windows tomorrow although I'm not sure about this area

Maybe, I can't verify this today, sorry. I'm going to do it ASAP.

**Comment by mbien** [comment]
so what shall we do with this PR?

@sworisbreathing to resurrect this please update the commit so that the real email address is in it and force push into this PR.

**Comment by BradWalker** [comment]
> so what shall we do with this PR?
> 
> @mbien said "so what shall we do with this PR?"

I looked over this and agree it's a correct improvement.

Basically what is happening is the change is to move away from using MS protocol handlers to calling msedge directly and passing it the URL on the command line. A good improvement as this is how things are done now. The reference in the original comments are correct.

If you want I can update/push it?

**Comment by mbien** [comment]
> If you want I can update/push it?

@BradWalker lets wait a bit for @sworisbreathing, maybe he heard the ping this time and is willing to fix the commit header so he gets credit. If not then simply close this PR and reopen a new one.

**Comment by BradWalker** [comment]
> > If you want I can update/push it?
> 
> @BradWalker lets wait a bit for @sworisbreathing, maybe he heard the ping this time and is willing to fix the commit header so he gets credit. If not then simply close this PR and reopen a new one.

Sounds good to me..

**Comment by sworisbreathing** [comment]
I'll try and get this fixed up over the weekend.

P.S. I really appreciate how much you care about giving contributors credit for their contributions:-)

**Comment by BradWalker** [comment]
> I'll try and get this fixed up over the weekend.
> 
> P.S. I really appreciate how much you care about giving contributors credit for their contributions:-)

Hey @sworisbreathing , the team really wants contributions ! In that regard, you deserve to be recognized. So, if it hasn't been said yet.

Thanks for your help!

**Comment by sworisbreathing** [comment]
ok I've updated it to use my apache.org email. also I've emailed the pmc which I hadn't realized I needed to do 2 years ago when I signed the ICLA. so fingers crossed this is good to go!

**Review by mbien — APPROVED** [review]

**Review by BradWalker — APPROVED** [review]

**Comment by mbien** [comment]
thanks for sticking around -> merging

(just to clarify: I was mostly trying to get a valid email address in the commit header, but ICLA is a bonus and useful if you are planing more contributions to apache projects)

**Pull request merged**
