### PR TITLE
Snapshot of APIS as of NetBeans 23

### PR DESCRIPTION
**Pull request by ebarboni**
Snapshot of APIs as of NetBeans 23

```bash
# checkout branch (or release tag)
git checkout release230
git clean -dxf
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb240a1
git stash pop
git add -A
git commit -m "Snapshot of APIS as of NetBeans 23"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

Filtered diff created using -

```bash
curl -L https://github.com/apache/netbeans/pull/<PR_ID>.diff | filterdiff -#2- > filtered-apis-nb230.txt
```
</details>

[filtered-apis-nb230.txt](https://github.com/user-attachments/files/17059758/filtered-apis-nb230.txt)

### CODE REVIEW

**Review by matthiasblaesing — APPROVED** [review]
I saw nothing obviously wrong here.

**Review by neilcsmith-net — APPROVED** [review]
Agreed, looks fine at a glance.

This needs to be done initially around rc1 as @jtulach has pointed out - reviewing after release can't catch unintended API changes.

**Comment by ebarboni** [comment]
wiki edited to make it better next time :D

**Comment by neilcsmith-net** [comment]
Thanks @ebarboni Need to possibly review if anything else is missing from that page that got added to the schedule (plugin redirect update with rc3 comes to mind) - let's follow up on that elsewhere.

**Comment by ebarboni** [comment]
will merge later today

**Pull request merged**
