### PR TITLE
Continuous build in Windows

### PR DESCRIPTION
**Pull request by hectorespert**
Use GitHub actions to build and run tests in Windows.

https://lists.apache.org/thread.html/rc3a7ad290b004557c69d8cac7f5bd4825ca3d230b626641a8565164b%40%3Cdev.netbeans.apache.org%3E

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
Great work!

**Comment by geertjanw** [comment]
Pretty cool. GitHub actions uses Zulu, at least by default, so speaking as an Azul guy, this is cool. :-)

**Comment by ebarboni** [comment]
do we have limit on workload / usage for githubactions?

**Comment by hectorespert** [comment]
> do we have limit on workload / usage for githubactions?

These are the usage limits: https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits. Seems that there isn't any limitation in build minutes for open projects.

**Comment by KacerCZ** [comment]
@hectorespert Do you plan to run all tests on Windows?
It would be useful because some tests (i.e. php/php.atoum) pass on Linux but fail no Windows.

**Pull request merged**
