### PR TITLE
Add markup tag completion hints for inline snippets

### PR DESCRIPTION
**Pull request by MegJayan**
Provide hints for markup tags in inline snippets. Below is the screenshot for the feature
markupHint

multipleMarkupTag

### CODE REVIEW

**Review by singh-akhilesh — APPROVED** [review]
LGTM

**Comment by matthiasblaesing** [comment]
@singh-akhilesh any reason not to merge this? As @MegJayan is not a committer, she needs someone to merge this, are you willing to? If not what needs to happen before?

**Comment by singh-akhilesh** [comment]
> @singh-akhilesh any reason not to merge this? As @MegJayan is not a committer, she needs someone to merge this, are you willing to? If not what needs to happen before?

I was waiting for the approval by arvindaprameya , i'll ask him to approve asap. Meanwhile i'll rerun the failed jobs.

**Comment by matthiasblaesing** [comment]
@singh-akhilesh thank you for the information - I was just wondering ;-). For the failing commit validation job, this might not be a real problem, see #4211.

**Comment by arvindaprameya** [comment]
Approved, thanks for making this change Meghna !

**Comment by singh-akhilesh** [comment]
> @singh-akhilesh thank you for the information - I was just wondering ;-). For the failing commit validation job, this might not be a real problem, see #4211.

Merged the PR, thanks.

**Comment by mbien** [comment]
@MegJayan cool feature, thanks!

**Review by lahodaj — COMMENTED** [review]
FWIW, looks reasonable to me.

**Pull request merged**
