### PR TITLE
Updates discoclient library (which adds more downloadable distributions)

### PR DESCRIPTION
**Pull request by emilianbold**

### CODE REVIEW

**Comment by emilianbold** [comment]
Since test seems to have failed due to a timeout?

**Comment by matthiasblaesing** [comment]
@emilianbold I restarted the failing test, you can do this yourself, if you log into travis com with your github account.

**Comment by emilianbold** [comment]
@matthiasblaesing thank you. I was wondering how to redo the builds without pushing new changes...

I see all checks pass now.

**Review by matthiasblaesing — APPROVED** [review]
Change looks sane to me.

**Comment by neilcsmith-net** [comment]
Either the base branch needs changing to `delivery` and retesting, or the milestone needs moving to 12.5.  cc @geertjanw

**Comment by geertjanw** [comment]
I would change to 'delivery', don't know how for sure, can you do it?

**Comment by neilcsmith-net** [comment]
Has that just added a bunch of extra commits from master?  Think needs @emilianbold to take a look and rebase the branch against delivery.

**Comment by neilcsmith-net** [comment]
Thanks @emilianbold - that looks better! :smile:

**Review by geertjanw — APPROVED** [review]

**Comment by emilianbold** [comment]
All checks passed, 2 approvals.

**Pull request merged**
