### PR TITLE
Upgrade Gradle Tooling API to 7.5 with Java 18 Support

### PR DESCRIPTION
**Pull request by lkishalmi**
It seems we are lucky. After a short lived Gradle 7.5-rc5 the final 7.5 is here today.

### CODE REVIEW

**Comment by lkishalmi** [comment]
I have no idea why the Java 11 commit validation fails. though it failed 4 times in a row.
I've checked the ```ant commit-validation`` locally and that went well for me.

**Comment by mbien** [comment]
however, i just noticed that travis didn't start here. It can be usually fixed by force pushing again into the PR.

**Comment by lkishalmi** [comment]
@mbien Thanks. Just rebased the branch on master and force pushed back. It seems Travis kicked off this time. Another round of whack a mole is coming...

**Comment by mbien** [comment]
hmm travis is failing with:
```
[downloadbinaries] File /home/travis/build/apache/netbeans/extide/gradle/external/gradle-7.4-bin.zip
 requested by /home/travis/build/apache/netbeans/extide/gradle/external/binaries-list
 to have hash 483F39DCC23C3FB098C00E6A14E0AEBE3D10F00C actually had hash 96BA80A0BCD8D09FBFD209679E1D021AD090F6E8
```
did they upload a new zip? I saw that in other runs too, e.g https://app.travis-ci.com/github/apache/netbeans/builds/253255878 which in master.

**Comment by lkishalmi** [comment]
Saw that too. And this one as well:
```
/home/travis/build/apache/netbeans/webcommon/javascript2.jade/external/jflex-1.4.3.jar requested by /home/travis/build/apache/netbeans/webcommon/javascript2.jade/external/binaries-list to have hash 88516325EF6816C047027DD87D00493CF6C31E7E actually had hash 6C14D94FC47046CC850F5E08A3D2A11122155B24
```

I've again downloaded the gradle-7.4-bin.zip, checked the sha1sum,it matches with the one in our repository. So I guess Travis has some network issues.

**Review by neilcsmith-net — APPROVED** [review]

**Review by matthiasblaesing — APPROVED** [review]
Only eyeballed this, but looks ok.

**Comment by mbien** [comment]
fyi: travis kept restoring the same bad file from cache which caused the hash mismatch. I cleared all caches via travis admin UI. Which forced it to download everything again on next build. -> master is greed

**Comment by lkishalmi** [comment]
@mbien Thanks for get this thing sorted!

**Pull request merged**
