### PR TITLE
[NETBEANS-2612] WIP apidoc frameless and branding agnostic

### PR DESCRIPTION
**Pull request by ebarboni**
apidoc new look and using branding from json . Recovery of my mistake in #1270

This PR encompass several changes (currently putting effort on layout of web page)
As build.xml provide information this PR focus only on apidoc.

### Remove branding properties
remove of properties in *nbbuild/build.properties*:
*config.javadoc.all,previous.release.year,previous.release.month,previous.release.day*
### Setup build from new parameter **build.branch**
it also transorm in an xml file to have all history.
json file hosted here https://gitbox.apache.org/repos/asf?p=netbeans-jenkins-lib.git;a=blob;f=meta/netbeansrelease.json;
(this json file will also help @vieiro for building website)
### rework of the apidoc html
use l&f of Apache NetBeans website, scrollabe menu to have all history
embedd arch + apichanges to have jdk like menu (try to help navigability)
all classes display, jquery or script addition to ease searching filtering

Live demo:
http://bits.netbeans.org/apidoctest/branding.html

### CODE REVIEW

**Comment by ebarboni** [comment]
@neilcsmith-net this post beta2 maybe to have apidoc branding gone

**Comment by neilcsmith-net** [comment]
@ebarboni I wasn't sure how ready it is - says WIP! :wink: Can merge in immediately after beta2 if you're ready and reviews complete.

**Comment by neilcsmith-net** [comment]
Retriggered the (getting very annoying!) breaking test.

If we can get positive review by @JaroslavTulach and @vieiro by Tue 8th I can merge for final beta build.  Or shall we hold for 11.3?

**Comment by ebarboni** [comment]
It will not hurt not having it in release package. It's more to have nice apidoc website. And will try to port it to the previous release later.

**Comment by ebarboni** [comment]
Hi @neilcsmith-net @vieiro @JaroslavTulach , I wonder if I can put that change on master, I may have to adjust build system so branding is good.

**Comment by neilcsmith-net** [comment]
@ebarboni fine with me!  There's still an open question on who (you?) is RM'ing 11.3.  If not you, their review may be more appropriate than mine?

**Comment by ebarboni** [comment]
trying to squash and merge, and see what happen

**Comment by ebarboni** [comment]
Hi @neilcsmith-net , I'm not sure of the terminology, but I can put the commit to release112 (and previous 9.0 to 11.1 for consistency) via cherry pick ?

**Comment by neilcsmith-net** [comment]
Hi @ebarboni suggest cherry-pick locally and then pull-requests for each required branch.  Do you really need all, or just active releases?

**Comment by ebarboni** [comment]
Thks, Will follow your advice, will do for all previous Apache (TLP and incubator) era just for consistency. We may need to fix some link later (wiki still on netbeans.org, and some subproject.netbeans.org).  
frame based apidoc is very hard to navigate with all the security now.

**Pull request merged**
