### PR TITLE
JEDDICT-322 org.netbeans.modules.db.core convert friend to public packages

### PR DESCRIPTION
**Pull request by jGauravGupta**
Github issue: https://github.com/jeddict/jeddict/issues/322

Friend API of the Apache NetBeans Platform used by Jeddict modules:

| NetBeans Module name | NetBeans Module location | APIs | Used by Jeddict modules | Requirement |  Why access needed? |
| --- | --- | --- | --- | --- | --------- |
| org.netbeans.modules:org-netbeans-modules-db-core | netbeans\ide\db.core | org.netbeans.modules.db.api.sql.execute | io.github.jeddict.jpa.modeler | public-packages |  SQL Editor integration in JPA Modeler |

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
This module doesn't seem to be listed in `nbbuild/build.properties` in list of modules for  the `config.javadoc.stable` configuration. As such it wouldn't be visible at http://bits.netbeans.org/dev/javadoc list - please fix that. Otherwise OK.

**Comment by jGauravGupta** [comment]
I will create another PR to add Jeddict modules as friend.

**Comment by JaroslavTulach** [comment]
Why you want another PR to increase the list of friends? I gave you go and Matthias wanted few more trivial fixes. Increasing list of 3rd party friends is contra-productive.

**Comment by lkishalmi** [comment]
Well, the question is? Is this intended to go into 12.2? or just in master.
I'm a bit confused. The version change in manifest.mf would indicate that this would meant to be in 12.2 with an API change.
Yet the milestone has not been set and the base branch is master.
If this is meant to be on master, then the version shall reflect that (fix the conflict)

**Comment by jGauravGupta** [comment]
Hi @lkishalmi , 

It can be part of the next release 12.3, so merge in the master will be ok.

**Comment by jGauravGupta** [comment]
`org.netbeans.modules.db.api.sql.execute.SQLExecution` API is used by the Jeddict module. Do you want me to move the `org.netbeans.modules.db.api.sql.execute.LogFileLogger` & `org.netbeans.modules.db.api.sql.execute.SQLExecuteOptions` classes to `org.netbeans.modules.db.impl.sql.execute.*`?

**Comment by matthiasblaesing** [comment]
@lkishalmi why was this rushed in? There are open comments and @jGauravGupta asked what to do about that. Given that nobody really ensured db api is sane I'm already icky, that this is solved without a fried dependency, at least the changes I commented should have been done.

And yes - I should have marked this as changes requested.

**Comment by matthiasblaesing** [comment]
I'll propose an update for this shortly.

**Comment by matthiasblaesing** [comment]
Ok - I reread, reevaluated - lets keep as is.

**Comment by lkishalmi** [comment]
Thanks!

**Pull request merged**
