### PR TITLE
Assignments to parameters to record compact constructors should not be marked as unused.

### PR DESCRIPTION
**Pull request by lahodaj**
The parameters (and hence the assigned values) are implicitly used at the end of the compact constructors.

Please see:
https://github.com/oracle/javavscode/issues/53

---
**^Add meaningful description above**

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

If you're a committer, please label the PR before pressing "Create pull request" so that the right test jobs can run.

### CODE REVIEW

**Comment by mbien** [comment]
since this is isolated to hints, we could get this in for rc3 if you want. This would have to be rebased and retargeted to delivery.

regarding records: there are multiple issues coming from the fact that the IDE does not associate the record parameters from the constructor with the final fields of the record. E.g this does also break the rename refactoring, and mark occurrences etc. 

I was looking at the unused-hint already before, but was not sure if simply ignoring the params would be the right way to fix it in context of the other problems.

**Comment by mbien** [comment]
interesting test failure:
```
java.lang.AssertionError: 3:8 cannot access Record
class file for java.lang.Record not found
at org.netbeans.modules.java.hints.test.api.HintTest.ensureCompilable(HintTest.java:380)
at org.netbeans.modules.java.hints.test.api.HintTest.run(HintTest.java:459)
at org.netbeans.modules.java.hints.test.api.HintTest.run(HintTest.java:444)
at org.netbeans.modules.java.hints.bugs.UnusedAssignmentOrBranchTest.testRecordCompactConstructor(UnusedAssignmentOrBranchTest.java:226)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at org.netbeans.junit.NbTestCase.access$200(NbTestCase.java:79)
at org.netbeans.junit.NbTestCase$2.doSomething(NbTestCase.java:484)
at org.netbeans.junit.NbTestCase$1Guard.run(NbTestCase.java:405)
at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lahodaj** [comment]
Right, the test must be disabled when j.l.Record is not present in the platform (that is what we typically do for other tests like this).

The exception in the log seems unrelated to this patch, so something to investigate independently.

Rebased to delivery.

**Comment by lahodaj** [comment]
> regarding records: there are multiple issues coming from the fact that the IDE does not associate the record parameters from the constructor with the final fields of the record. E.g this does also break the rename refactoring, and mark occurrences etc.
> 
> I was looking at the unused-hint already before, but was not sure if simply ignoring the params would be the right way to fix it in context of the other problems.

I am afraid that overall, we may need to tweak the feature to understand the records properly - there's probably no simple solution that would solve everything in one go.

**Comment by mbien** [comment]
> Right, the test must be disabled when j.l.Record is not present in the platform (that is what we typically do for other tests like this).

true! If there are many tests with JDK 17+ runtime requirements, we should consider a `[11, 21]` matrix. If its just a few, we could isolate them and run them separately on a JDK 17 or 21 step. (NB 22 will bump the testing baseline to JDK 17).

**Review by mbien — APPROVED** [review]
changes make sense to me. Tests are green, tested it manually too and the compact constructor params are no longer seen as unused.

**Comment by neilcsmith-net** [comment]
Thanks, merging.  I've edited the title as this shows in our release notes.  Linking to third-party issues is fine, but as with Payara FISH labels, let's leave them out of titles or open a related issue here to reference.

**Pull request merged**
