### PR TITLE
[NETBEANS-97] Don't add braces around try/synchronized blocks when reformatting

### PR DESCRIPTION
**Pull request by bondolo**
Extraneous braces will also be removed according to user preference

See previous PR which I was unable to update for context:

https://github.com/apache/netbeans/pull/173

### CODE REVIEW

**Comment by bondolo** [comment]
ping. Now includes requested unit tests

**Comment by matthiasblaesing** [comment]
@lbruun @sdedic could you please have a look at this and see if the concerns raised on the original PR are fixed?

**Comment by geertjanw** [comment]
There doesn't seem to be a reason not to merge this, though maybe you can provide some screenshots here to show everything that this adds on the user interface level and what this looks like in the editor?

**Comment by geertjanw** [comment]
The reason I ask this is that I don't know right now exactly what to put in the New & Noteworthy for this one. My understanding is that if a certain new option is set in netbeans.conf, then a specific kind of formatting will take place.

**Comment by geertjanw** [comment]
OK, we really need documentation here, but clearly everything that has been asked for has been provided and it's time to merge this now.

**Pull request merged**
