### PR TITLE
Java Code Templates for List.of(), Map.of(), and Set.of()

### PR DESCRIPTION
**Pull request by lkishalmi**
Some cheap new tricks for Java Wizards!

### CODE REVIEW

**Review by mbien — APPROVED** [review]
lof mof sof, I like it!

**Comment by mbien** [comment]
(not sure about using var for collections by default, since types often matter but it is just a template)

**Comment by mbien** [comment]
@lkishalmi what would you think about also adding `ilof` `imof` and `isof`?

**Comment by lkishalmi** [comment]
> (not sure about using var for collections by default, since types often matter but it is just a template)

Well, since the resulted collection is immutable, I do not think the type would really matter.

Personally I would mainly use them in education space, creating sort code for demonstration purposes, and yes they are just templates.

**Comment by lkishalmi** [comment]
> @lkishalmi what would you think about also adding `ilof` `imof` and `isof`?

Where `i` would stand for?

**Comment by mbien** [comment]
`i` for the interface on the left hand side.

`ilof` would be `List<|> list = List.of()`

it might have to put the cursor between `<>` first, since I am not quite sure how to automatically set the there.

**Comment by lkishalmi** [comment]
Could be done, I'd probably use `llof`, `mmof, and `ssof` for abbrevs. `isof` is pretty close to the commonly used `iof`.

Also popped in my mind, that the `List.copyOf()`, etc would be more common with records, and then records with compact constructor...

**Pull request merged**
