### PR TITLE
[NETBEANS-5499] Felix removed in favour of Netbinox, fixes URLStreamHandlerFactory. add-opens added for jdk.compiler.

### PR DESCRIPTION
**Pull request by sdedic**
I wonder whether we need `netigso` and `felix` at all...
Otherwise: Felix breaks `URLStreamHandlerFactory` on JDK16. See [NETBEANS-5499](https://issues.apache.org/jira/browse/NETBEANS-5499).

I've also encountered some messages like
```
Caused by: java.lang.IllegalAccessError: superclass access check failed: class org.netbeans.lib.nbjavac.services.CancelAbort (in unnamed module @0x2d7c3092) cannot access class com.sun.tools.javac.util.Abort (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x2d7c3092
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
```
on NBJLS console when running under JDK16. The Language Server's config lacks a lot of `--add-open` compared to NetBeans' one, related to `jdk.compiler`, so I've added them.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
Felix is an Apache project. Can you make sure the bug is properly communicated with Richard Hall & co.?

**Comment by sdedic** [comment]
Last change: I've left a commented-out template options in the file. Sorry; commit rewritten.

**Comment by sdedic** [comment]
I've screwed up something. When I was testing locally, removing netigso seemed to work (?) but maybe I didn't clean up everything, because Travis fails with:
```
     [exec] java.lang.IllegalStateException: No NetigsoFramework found, is org.netbeans.core.netigso module enabled?
     [exec] 
     [exec] 	at org.netbeans.NetigsoHandle.getDefault(NetigsoHandle.java:63)
     [exec] 	at org.netbeans.NetigsoHandle.turnOn(NetigsoHandle.java:115)
     [exec] 	at org.netbeans.ModuleManager.enable(ModuleManager.java:1441)
     [exec] 	at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
     [exec] 	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
     [exec] 	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
     [exec] 	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
     [exec] 	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
     [exec] 	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
     [exec] 	at org.netbeans.core.startup.Main.start(Main.java:282)
     [exec] 	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
     [exec] 	at java.lang.Thread.run(Thread.java:748)
     [exec] 
```
that's not good.

**Review by JaroslavTulach — APPROVED** [review]
I'd like to know what Felix guys say about the failure.

**Pull request merged**
