### PR TITLE
use maven central search service for class name search.

### PR DESCRIPTION
**Pull request by mbien**
wip prototype to play around with.

how to test:
open/create maven project, type some class name, use the hint to do a maven search. Results should contain both central and local entries.

The maven central index does not contain class information anymore. As workaround we make a http request and merge the results with the local index.

augmented-central-search

performance is pretty bad compared to the local index, but this is to be expected from a web service which wasn't really made for this purpose:
```
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: passed on 1,024 clauses processing classnames:logger with 234 hits
INFO [org.netbeans.modules.maven.centralsearch.MavenCentralClassesQuery]: Response{numFound=223981, numDocs=200, start=0}
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: findVersionsByClass time = 4101
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: passed on 1,024 clauses processing classnames:jfr with 50 hits
INFO [org.netbeans.modules.maven.centralsearch.MavenCentralClassesQuery]: Response{numFound=47, numDocs=47, start=0}
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: findVersionsByClass time = 339
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: passed on 1,024 clauses processing classnames:jfrlogger with 2 hits
INFO [org.netbeans.modules.maven.centralsearch.MavenCentralClassesQuery]: Response{numFound=6, numDocs=6, start=0}
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: findVersionsByClass time = 1247
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: passed on 1,024 clauses processing classnames:jfr with 50 hits
INFO [org.netbeans.modules.maven.centralsearch.MavenCentralClassesQuery]: Response{numFound=47, numDocs=47, start=0}
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: findVersionsByClass time = 217
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: passed on 1,024 clauses processing classnames:jfrlogger with 2 hits
INFO [org.netbeans.modules.maven.centralsearch.MavenCentralClassesQuery]: Response{numFound=6, numDocs=6, start=0}
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: findVersionsByClass time = 463
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: passed on 1,024 clauses processing classnames:util with 1,203 hits
INFO [org.netbeans.modules.maven.centralsearch.MavenCentralClassesQuery]: Response{numFound=329503, numDocs=200, start=0}
INFO [org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl]: findVersionsByClass time = 2320
```
It does some caching though, so repeated requests are quite fast.

### CODE REVIEW

**Comment by ebarboni** [comment]
@mbien we got informal slack discussion but do you have pointer why/when the removal of classname from central indexer ?

**Comment by neilcsmith-net** [comment]
Nice! :smile: I've been wanting to look at using central search service for ages (for NB and a platform app).  I assume you've seen the search plugin?  https://github.com/emilianbold/maven.search.remote

Using JDK HTTP is great, but I wonder if requirement for JDK 11 will cause any concern?  This module is not excluded from VSCode I think?  Perhaps can be in a separate module?

Could this use pre-existing JSON libs in the IDE (like the plugin does)?

**Comment by mbien** [comment]
> we got informal slack discussion but do you have pointer why/when the removal of classname from central indexer ?

@ebarboni I don't know. However it was a long time ago. I would say its years not months. I actually completely forgot about it and debugged deep into lucene code to figure out why we don't get any results :). Then I remembered reading [this](https://github.com/apache/maven-indexer/blob/6a0c6017794dca6ee1af151f7914ab3cd0e4aa25/indexer-examples/indexer-examples-basic/src/main/java/org/apache/maven/index/examples/BasicUsageExample.java#L274).


> Nice! smile I've been wanting to look at using central search service for ages (for NB and a platform app). I assume you've seen the search plugin? https://github.com/emilianbold/maven.search.remote

@neilcsmith-net I remember you mentioning it before but only looked at it now. My first attempt was similar, I did try to implement all queries of `RepositoryIndexQueryProvider` and put it into a module, but it showed that the search service is purely for artifacts and fairly limited. A prefix group ID search wouldn't be easily possible for example. The search is unfortunately not very well documented. I looked through source code to see what it is actually returning.

(btw the search can be also really slow. I sometimes got 10s response time in tests - it does cache though, so repeating the search is faster)

> 
> Using JDK HTTP is great, but I wonder if requirement for JDK 11 will cause any concern? This module is not excluded from VSCode I think? Perhaps can be in a separate module?

Well yes. This is the remainder of the first attempt to implement it, it was a separate optional module. We can borrow a bit time to use a different jdk 8 compatible client. But keep in mind that maven-indexer and lucene requires now JDK 11 too (maven-indexer has now a [nice multi threaded extraction implementation](https://github.com/apache/maven-indexer/pull/255)). So its not a if, its a when at this point. (we already backported a [whole class](https://github.com/apache/netbeans/blob/4a697ab128d7df8885a8479b5cc4212e6a56835e/java/maven.indexer/src/org/apache/lucene/search/MultiTermQuery.java#L334) due to a bugfix, this already is a fragile hack. If something would load lucene before we do, this will break)

So when will the VSCode extension switch to JDK 11?

> 
> Could this use pre-existing JSON libs in the IDE (like the plugin does)?

sure. Jackson (or any jaxb json equivalent) is just really convenient in this case and produces maintainable code. Anyone who looks at the POJOs knows what is going on there - if the service changes it can be quickly fixed. Streaming APIs require a few more brain cycles for maintainers :)

This is just an unfinished experiment to start a conversation. The method `find(final List<QueryField> fields, List<RepositoryInfo> repos)` is going to need a special case too if a class name appears.

`NexusRepositoryIndexerImpl` does too much right now IMO. I think we should check if we can split it into indexer and query provider, this might make it easier to work with.

**Comment by matthiasblaesing** [comment]
> So when will the VSCode extension switch to JDK 11?

Why is VSCode tied to JDK 11? I can understand some of the concerns about the platform modules, but for the IDE I don't seen an argument. At least I would not think twice about creating a new JDK11 only module.

**Comment by mbien** [comment]
> > So when will the VSCode extension switch to JDK 11?
> 
> Why is VSCode tied to JDK 11? I can understand some of the concerns about the platform modules, but for the IDE I don't seen an argument. At least I would not think twice about creating a new JDK11 only module.

This is in `java/maven.indexer` right now and only substitutes the class name query maven-indexer can't provide anymore. VSCode Extension is probably using this modules for maven support I suppose. As long the extension wants to run on 8, we can't bump the language level on this module. However, as previously mentioned, we can't delay that forever for reasons other than HTTPClient (there are enough JDK 8 replacements for it, even though its yet another extra step, is is really no big deal to swap this out).

Since this is a prototype to test things out, I didn't bother to add another dependency, I simply used JDK 11 HTTPClient.

**Comment by mbien** [comment]
only a sync with minor changes

**Comment by mbien** [comment]
closing in favor of #5984

**Pull request closed without merging**
