### PR TITLE
[NETBEANS-5031] - remove use of deprecated APIs in MiniEdit.java

### PR DESCRIPTION
**Pull request by BradWalker**
I'm trying to remove the use of a deprecated API that hinders updating the Java version.

MiniEdit.java uses a really old deprecated API. This API prevents us from upgrade the Java
source version in the project properties file.

So step #1 is to remove the use of the old deprecated API.

### CODE REVIEW

**Comment by BradWalker** [comment]
I would like to ask if @JaroslavTulach could have a look at this as it's his code that I'm changing.. That would be helpful if possible..

**Review by JaroslavTulach — APPROVED** [review]
Consider also removing dependency on `org.openide.util.enum` from the `project.xml` file.

**Comment by BradWalker** [comment]
> Consider also removing dependency on `org.openide.util.enum` from the `project.xml` file.

Hey @JaroslavTulach , I can't seem to find this.. Can you point to where I should look so that I'm more familiar in the futures. Thanks..

**Comment by jtulach** [comment]
I cannot find it.

Btw. is this file even compiled? If I make an error in the file, rebuilding the `java/performance` module still succeeds. Doing `java/performance$ grep -r actionsframework .` yields no results...

**Comment by BradWalker** [comment]
> I cannot find it.
> 
> Btw. is this file even compiled? If I make an error in the file, rebuilding the `java/performance` module still succeeds. Doing `java/performance$ grep -r actionsframework .` yields no results...

Hey @JaroslavTulach, I don't think this file is even compiled. So I would be willing to even remove it from the tree? My change is simply to try and keep things "neat & complete" as I clean up the old rust..

What do you think I should do?

**Pull request merged**
