### PR TITLE
Disable flaky ValidateLayerConsistencyTest

### PR DESCRIPTION
**Pull request by matthiasblaesing**
See https://github.com/apache/netbeans/issues/4211 for details

### CODE REVIEW

**Comment by sdedic** [comment]
I invested several hours into experimenting with the test, on 2 different local machines, very similar environment (kernel version, JDK version). I am still unable to reproduce this locally. I found out that on JDK 8/11, the consistency test fails with this error on Github CI:
```
2022-06-24T19:36:52.4908198Z     [junit] Testcase: org.netbeans.core.validation.ValidateLayerConsistencyTest:testActionInstancesOnlyInActionsFolder:	Caused an ERROR
2022-06-24T19:36:52.4908858Z     [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
2022-06-24T19:36:52.4909459Z     [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
2022-06-24T19:36:52.4910056Z     [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-06-24T19:36:52.4910660Z     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-24T19:36:52.4911206Z     [junit] 	at java.base/java.util.Vector.forEach(Vector.java:1388)
2022-06-24T19:36:52.4911716Z     [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-06-24T19:36:52.4912366Z     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-24T19:36:52.4912984Z     [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-06-24T19:36:52.4913634Z     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-24T19:36:52.4914270Z     [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-06-24T19:36:52.4914927Z     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-24T19:36:52.4916082Z     [junit] 	at java.base/java.util.Vector.forEach(Vector.java:1388)
2022-06-24T19:36:52.4916699Z     [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-06-24T19:36:52.4917293Z     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-24T19:36:52.4917891Z     [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-06-24T19:36:52.4918462Z     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-06-24T19:36:52.4919023Z     [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-06-24T19:36:52.4920176Z     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
I am not sure if this is a result of `assert`ing in `Main` on `NbRepository` or the real error.

**Comment by mbien** [comment]
hi @sdedic, sorry for the delay I didn't watch this PR, just saw your post now.

> Anyway, if the VM _crashed_ a `hs_err_*.log` could be useful, but it's not archived in the logs archive. Any idea on how to get my hands hs_err.log would be useful. Currently I am thinking about including it (in a test PR) as an uploaded artifact ... and get it through GH API.

if you take this and put it after the test fails in a PR, you would get the full workspace. Change the artifact name, change the if into `if: always()`, done. But don't do that in a matrix please since I don't know the storage limit of apache. Consider manually removing the artifacts if you experiment.

https://github.com/apache/netbeans/blob/6bf270e71b5950783ed2038060863dc5f28271fb/.github/workflows/main.yml#L64-L75


> 
> There's other interesting option -- https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys .... an interesting idea: have ssh opened into the GH action's VM. But potentially a dangerous one.

this won't work since apache projects don't have access to all github actions, all official actions are supported and there is a white list for some hand picked third party actions. There are tricks how to make this work but the next barrier would be permissions, and adding personal access tokens to the project is only possible via infra as far as I know - we can't simply edit project setting like in regular gh projects (all workflows run with minimal permissions).

**Comment by mbien** [comment]
@sdedic 
actually Matthias already added an upload step to the CV job
https://github.com/apache/netbeans/blob/6bf270e71b5950783ed2038060863dc5f28271fb/.github/workflows/main.yml#L111-L120

you can simply modify the file filter in a PR to make it upload crash logs

**Review by mbien — APPROVED** [review]
lets merge this PR. This will be a pain otherwise during the RC phase. We can enable it later again or find another solution if there is one.

**Comment by mbien** [comment]
fyi, there is no jvm crash log generated in that particular crash. I tried uploading it and there was none, then i set the path explicitly to /tmp and there still was no crash file at that place.

**Comment by matthiasblaesing** [comment]
> fyi, there is no jvm crash log generated in that particular crash. I tried uploading it and there was none, then i set the path explicitly to /tmp and there still was no crash file at that place.

My reading of this is, that we hit an AssertionError in java code. That won't trigger a `hs_err_*.log`, this hits the normal uncaught exception code path (i.e. prints stack trace and exits the VM). I would expect a `hs_err_*.log` if the VM breaks (failing to allocate memory or getting a segfault).

**Comment by neilcsmith-net** [comment]
> lets merge this PR. This will be a pain otherwise during the RC phase. We can enable it later again or find another solution if there is one.

+1

> I would expect a hs_err_*.log if the VM breaks

Well, there are circumstances you won't get one then, but I think you're right here - don't think the "exited abnormally" means a VM crash.

**Comment by matthiasblaesing** [comment]
Given that we get into release phase, lets get this in. It does not mean, that we should not try to fix this, but just acknowledges, that it happens and has now lead to irritation multiple times, basicly training people to just ignore errors from commit validation.

**Pull request merged**
