### PR TITLE
Remove textArea border in MultiLineComboBoxEditor

### PR DESCRIPTION
**Pull request by DJ-Raven**
This PR update the UI. by removed textArea border in `MultiLineComboBoxEditor` class
This `MultiLineComboBoxEditor` use in:
- Find in Projects by pressed `Ctrl+F`
- Replace in Projects by pressed `Ctrl+H`

### After changed

Preview with flatlaf light laf

Preview with flatlaf light cupertino (multi line search)

Please review, Thank you

### CODE REVIEW

**Comment by mbien** [comment]
awesome, thanks for the fix!

@DJ-Raven could you update the commit author to your full name like in your last PR?
for comparison:
 - this PR: https://github.com/apache/netbeans/pull/7799.patch
 - last PR: https://github.com/apache/netbeans/pull/7332.patch

```
 git commit --amend --author="Author Name <email@address.com>" --no-edit
```
and simply force push

**Comment by DJ-Raven** [comment]
@mbien already push

**Review by eirikbakke — APPROVED** [review]
Thanks for this fix; looks good!

Perhaps quickly check that it also works on the Windows LAF as well (though any problems would be purely cosmetic).

**Review by mbien — APPROVED** [review]
checked some of the older LAFs and it looked good except on GTK. But GTK LAF is a lost cause i think, NB doesn't render well on it and nothing aligns (not only in this dialog toolbars etc look also bad).
image



Metal
image

Nimbus
image

**Comment by eirikbakke** [comment]
Yeah, I don't think the alignment problems in older LAFs are due to this patch; I saw them when trying Nimbus without the patch, for instance. (In any case I don't think much effort needs to be spent on the older LAFs at this point; they just served as a useful "test case" for the patch.)

**Comment by eirikbakke** [comment]
Merged it--thanks again for the patch!

**Comment by DJ-Raven** [comment]
Thank @mbien @eirikbakke for review.

**Comment by mbien** [comment]
>  I don't think the alignment problems in older LAFs are due to this patch;

yes, this is not what I meant. This dialog is somewhat special since it uses the old grid bag layout which doesn't implement text baseline alignment for neighboring components if i remember correctly. Two combo boxes are also multi line fields with dynamic height - so this is to be expected that it won't look nice on all LAFs. (I remember starring at the dialog a while while doing https://github.com/apache/netbeans/pull/3393)

What i meant was that the GTK laf specifically looks inconsistent everywhere else too. Toolbar icons have the wrong size and every combo box looks different. I set `-J-Djdk.gtk.version=2` for VisualVM to make it somewhat useable (fixes the toolbars at least).

I am wondering if we should filter it out from the LAF list? I guess users could still use the flag to force it.

**Comment by eirikbakke** [comment]
> I am wondering if we should filter it out from the LAF list? I guess users could still use the flag to force it.

Perhaps? Or otherwise advertise that we really recommend FlatLAF over the other ones.

The main reason to keep the older LAFs around is that it's useful to have each of the basic Java LAFs available in the list for people who are developing Swing apps and would like to see what each one of them looks like in the context of the full IDE. It's also useful during NetBeans IDE development, to test Swing code changes with different LAFs to make sure the code does not make accidental assumptions about specific LAF implementation details.

> I set -J-Djdk.gtk.version=2 for VisualVM to make it somewhat useable (fixes the toolbars at least).

I think we used to have that setting as default in NetBeans, until https://issues.apache.org/jira/browse/NETBEANS-5862 removed it. Maybe certain issues appeared to have been fixed in the JDK, but others were not.

**Comment by neilcsmith-net** [comment]
> > I am wondering if we should filter it out from the LAF list? I guess users could still use the flag to force it.
> 
> Perhaps? Or otherwise advertise that we really recommend FlatLAF over the other ones.

I've opened a PR to filter the LAF list, starting with all the JDK LAFs.  Could just filter the most problematic if necessary.

**Pull request merged**
