### PR TITLE
[NETBEANS-2722] Upload button text and def. window size

### PR DESCRIPTION
**Pull request by riksoft**
https://issues.apache.org/jira/browse/NETBEANS-2722

The text "Take over local changes" it's unclear. Changed into "Upload local changes"

The default diff window size is too small. Changed to 1024x768 (Just to be conservative... but it's still too small for me).
The diff window size should be improved implementing the persistance of the resized window size to let any user set whatever he wants.

### CODE REVIEW

**Comment by geertjanw** [comment]
Great job!

**Comment by junichi11** [comment]
Please apply this patch if needed to your `patch-1` branch: 
```
git pull https://github.com/junichi11/netbeans netbeans-2722
```
or
```
curl -L https://github.com/junichi11/netbeans/commit/d6cf197097b82c9a6848088bef59b809472a7920.patch | git am
```
netbeans-2722

**Comment by junichi11** [comment]
@riksoft 
Please read this: https://netbeans.apache.org/participate/submit-pr.html
As Geertjan changed the title, we have to add issue number to the commit message and the PR title.

**Comment by riksoft** [comment]
@junichi11 
OK. Actually Geertjan told me to do that but using the word "description" I didn't realize I have to put the bug code in the title. Next time! :-)

**Comment by junichi11** [comment]
@riksoft If you apply my patch(keep the last diff window size) to your `patch-1` branch, please push it.
```
$ cd netbeans
$ git pull https://github.com/junichi11/netbeans netbeans-2722
$ git push origin patch-1
```
 Otherwise, please let me know.

**Comment by riksoft** [comment]
@junichi11 
I don't have a local evironment for Java/Netbeans development (I did the editing directly on github, not locally), so I can't apply your pach, test, or push back. I could set a VM for such purpose but it takes time and I can't do it now.

**Comment by junichi11** [comment]
@riksoft please add me(junichi11) to your repo as a collaborators if possible. I can add the commit.

**Comment by junichi11** [comment]
BTW, Maybe, you should have a local repository because you can't pull new changes from the remote repository and can't test changes.

**Comment by riksoft** [comment]
@junichi11 
The problem is that I'm not a java developer, that's why I've never bother to install Netbeans source code locally.
BTW you've been added to my repo.

**Comment by junichi11** [comment]
> The problem is that I'm not a java developer, that's why I've never bother to install Netbeans source code locally.

I see. Personally, I don't think that it is good way...

> BTW you've been added to my repo.

Thanks! I'll push my change.

**Comment by junichi11** [comment]
@tmysik Thank you! Will merge.

**Pull request merged**
