### PR TITLE
[NETBEANS-5367] Changed PHP Annotation API to public

### PR DESCRIPTION
**Pull request by KacerCZ**
https://issues.apache.org/jira/browse/NETBEANS-5367

First step to be able to implement annotations in module not listed in friend packages.

### CODE REVIEW

**Comment by geertjanw** [comment]
Is there any objection to this, @junichi11?

**Comment by junichi11** [comment]
@tmysik Is this OK?

**Comment by tmysik** [comment]
IMHO, one should be *really* sure that the API is good (usable and stable, at least) before making it public. Also, it seems to me quite unexpected to make the first public PHP API from this module exactly... But I won't be blocking this PR, of course; however, I will not approve it either.

@jtulach 
It would be definitely good to know what Jarda thinks about this. Thanks!

**Comment by KacerCZ** [comment]
My goal is to implement PHPStan annotations in "php.code.analysis" module (because this module implements PHPStan support).
PHP Annotations API can be made public (as I understand it is prefered for Java APIs) or "php.code.analysis" module will need to become friend.
I'd like to know what NetBeans veterans think is better.

**Comment by matthiasblaesing** [comment]
I know that everyone says friend modules are evil, but I see only two options:

- accept that fact or
- be willing to break API

I think both options should be considered (yes, there are reasons API should be broken) - in this case we are late in the cycle, so why not add a friend and plan for publication of the API in the next cycle?

**Comment by tmysik** [comment]
Definitely a friend, IMHO. Exactly the same as for all the other PHP modules. Making any API public really needs to be planned and reviewed properly, it is a big commitment.

**Comment by neilcsmith-net** [comment]
They're not evil, just should never have been used to mark unstable APIs IMO.  (JDK has right approach on opt-in).

However, agree with adding a friend on a one release basis.  Push this to 12.5 for review.

**Comment by KacerCZ** [comment]
OK, I'll make it friend module.
Thanks for your time.

**Comment by KacerCZ** [comment]
@mvorisek Support for PHPStan annotations is in progress and is separate from array format.
Relevant issue is https://issues.apache.org/jira/browse/NETBEANS-4983

**Pull request closed without merging**
