### PR TITLE
Improvements for LSP Client

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Please see individual commits for details.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@jlahoda @vieiro could you please have a look at this and see if this looks sane to you? The intention is to fix the issue reported in #4034 without changing the API.

**Comment by ebarboni** [comment]
Tested and seems to solve the issue, build check are green. Merging.  Will build the rc2.

**Comment by vieiro** [comment]
@matthiasblaesing , sorry for the delay (busy week). 

This looks sane to me. I love the `notifyFuture ... thenApply`. Pretty cool!

**Comment by matthiasblaesing** [comment]
> @matthiasblaesing , sorry for the delay (busy week).

No problem - thank you that you had a look at this!

> This looks sane to me. I love the `notifyFuture ... thenApply`. Pretty cool!

Yeah it matched perfectly - if I remember correctly @sdedic added it and turns out it is a very nice addition.

**Pull request merged**
