### PR TITLE
[NETBEANS-1159] Using UPL licensed graal-js-parser.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
I've took the [first UPL version](https://github.com/JaroslavTulach/graaljs/commit/b73460ebc4f768bfb6fcfa8832969dd34705da32) of the graal.js parser and [modified it](https://github.com/JaroslavTulach/graaljs/commits/NB82Parser) to work with current NetBeans JavaScript editing infrastructure. Then I created Graal.js JAR using folling steps:
```bash
$ git clone https://github.com/JaroslavTulach/graaljs.git
$ cd graaljs/
graaljs$ git checkout e20fe15
graaljs$ ant
graaljs$ ls -l graal-js/mxbuild/dists/graal-js-parser.jar
```
Since [e20fe15](https://github.com/JaroslavTulach/graaljs/commit/e20fe15dc14a42b5246901cefc524235e7b77505) there is an Ant script to perform the build. I compiled with JDK8.

The graal-js-parser has been uploaded as `F500B932961B227F74352474D23F905EC52F112E-graal-js-parser-e20fe15.jar` to our binaries set and this pull request is using it.

### CODE REVIEW

**Comment by sdedic** [comment]
We probably do not need customizations in `webcommon/libs.nashorn/build.xml` neither, since JS parser lib can be part of the regular build (?)

**Comment by junichi11** [comment]
@JaroslavTulach Maybe, `php.editor` also needs the fix? 
https://github.com/apache/netbeans/blob/39e97b900a8d604f3968e07605ee0d7709f37977/php/php.editor/nbproject/project.properties#L81-L82

**Comment by geertjanw** [comment]
This is great, no more need for the user to install the parser themselves.

**Comment by matthiasblaesing** [comment]
Thank you - a build worked and starting with a clean userdir, all JS features were directly accessible (nice!). I had a first look at the sources and this is what I noticed:

**Build from source fails**

mx still feels alien to me and I failed to build graal.js from source:
- cloned https://github.com/graalvm/mx.git
- checked out 5.229.5
- added path to mx checkout to path
- cloned https://github.com/JaroslavTulach/graaljs.git
- changed into graaljs/graal-js and ran `mx build --project GRAAL_JS_PARSER` 
```
matthias@athena:~/src/graaljs/graal-js$ mx build --project GRAAL_JS_PARSER
Traceback (most recent call last):
  File "/home/matthias/src/mx/mx.py", line 19726, in <module>
    main()
  File "/home/matthias/src/mx/mx.py", line 19613, in main
    primary = _discover_suites(primarySuiteMxDir, load=should_load_suites)
  File "/home/matthias/src/mx/mx.py", line 3364, in _discover_suites
    _register_visit(primary)
  File "/home/matthias/src/mx/mx.py", line 3362, in _register_visit
    s._load()
  File "/home/matthias/src/mx/mx.py", line 1506, in _load
    self._load_extensions()
  File "/home/matthias/src/mx/mx.py", line 1931, in _load_extensions
    mod = __import__(extensionsName)
  File "/home/matthias/src/graaljs/graal-js/mx.graal-js/mx_graal_js.py", line 338, in <module>
    build_args=['--language:js']
TypeError: __init__() takes at least 6 arguments (5 given)
matthias@athena:~/src/graaljs/graal-js$ 
```
Am I missing something?

**License information**

A _quick_ check of the licenses (aka `grep -lr "GNU General " *`) gave me:

GPL license header:
graal-js/mx.graal-js/mx_graal_js.py
graal-js/mx.graal-js/mx_graal_js_benchmark.py
graal-js/src/com.oracle.js.parser/src/com/oracle/js/parser/package-info.java
graal-js/src/com.oracle.js.parser/src/com/oracle/js/parser/resources/Messages.properties

GPL license file:
graal-js/mx.graal-js/LICENSE

GPL+UPL header, without indication that the file is dual licensed:
graal-js/src/com.oracle.truffle.js.runtime/src/com/oracle/truffle/js/runtime/builtins/JSURLEncoder.java
graal-js/src/com.oracle.truffle.js.runtime/src/com/oracle/truffle/js/runtime/builtins/JSURLDecoder.java

GPL+UPL+BSD license:
graal-js/src/com.oracle.truffle.js.runtime.doubleconv/src/com/oracle/truffle/js/runtime/doubleconv/DiyFp.java
graal-js/src/com.oracle.truffle.js.runtime.doubleconv/src/com/oracle/truffle/js/runtime/doubleconv/DoubleConversion.java

There are other licenses on graal-nodejs, I hope, that no code outside graal-js is used for graal-js.

**Comment by JaroslavTulach** [comment]
Thanks for the detailed review, @matthiasblaesing. The `TypeError: __init__() takes at least 6 arguments (5 given)` problem has something to do with old/new version of `mx`. I have seen it as well before (but not when writing the above steps). The workaround was:
```diff
graal-js$ git diff
diff --git a/graal-js/mx.graal-js/mx_graal_js.py b/graal-js/mx.graal-js/mx_graal_js.py
index bb59b035d7..ae60755801 100644
--- a/graal-js/mx.graal-js/mx_graal_js.py
+++ b/graal-js/mx.graal-js/mx_graal_js.py
@@ -331,12 +331,6 @@ mx_sdk.register_graalvm_component(mx_sdk.GraalVmLanguage(
         'graal-js:ICU4J-DIST'
     ],
     launcher_configs=[
-        mx_sdk.LanguageLauncherConfig(
-            destination='bin/<exe:js>',
-            jar_distributions=['graal-js:GRAALJS_LAUNCHER'],
-            main_class='com.oracle.truffle.js.shell.JSLauncher',
-            build_args=['--language:js']
-        )
     ],
     boot_jars=['graal-js:GRAALJS_SCRIPTENGINE']
 ))
``` 

Thanks for the license check. Yes, the `graal-js/src/com.oracle.js.parser/src/com/oracle/js/parser/package-info.java` and `graal-js/src/com.oracle.js.parser/src/com/oracle/js/parser/resources/Messages.properties` are an oversight that I will fix. The other files are unrelated and I'd rather leave them without any modification. They aren't used in the parser anyway. When I run:
```
graaljs/graal-js$ mx clean
graaljs/graal-js$ mx -v build --project GRAAL_JS_PARSER
javac -g -d mxbuild/src/com.oracle.js.parser/bin -classpath  
-parameters -proc:none -target 1.8 -source 1.8 
@mxbuild/src/com.oracle.js.parser/javafilelist.txt 
-Xlint:none -XDignore.symbol.file -encoding UTF-8 -Xmaxerrs 10000
```
e.g. it should be enough to run just the `javac` and then package the source and resource files somehow:
```
$ /jdk1.8.0/bin/javac -g -d mxbuild/src/com.oracle.js.parser/bin 
-classpath  -parameters -proc:none -target 1.8 -source 1.8 
@mxbuild/src/com.oracle.js.parser/javafilelist.txt 
-Xlint:none -XDignore.symbol.file -encoding UTF-8 -Xmaxerrs 10000
```
The `javafilelist.txt` contains only files under the `src/com.oracle.js.parser/src` directory, so licenses of other files shall not matter.

**Pull request merged**
