### PR TITLE
[NETBEANS-4478] Fixed tests for PHP Code analysis on Windows

### PR DESCRIPTION
**Pull request by KacerCZ**
https://issues.apache.org/jira/browse/NETBEANS-4478

Paths in log file have to be system-dependent for tests to work as
expected.

### CODE REVIEW

**Comment by KacerCZ** [comment]
@tmysik @junichi11 Please review.

**Comment by junichi11** [comment]
Maybe, it is a problem of an absolute path?
I would add a file for windows(e.g. phpstan-log-netbeans-3022-without-workdir-win.xml) since this case needs not a correct path although I'm not sure whether it works fine.

e.g.
```xml
<checkstyle>
<file name="C:\test\phpstan\app\Test1.php">
  <error line="13" column="1" severity="error" message="Binary operation &quot;+&quot; between string and 2 results in an error." />
</file>
<file name="C:\test\phpstan\app\Test2.php">
  <error line="9" column="1" severity="error" message="Anonymous function should return string but returns void." />
  <error line="9" column="1" severity="error" message="Result of closure (void) is used." />
</file>
</checkstyle>
```
```java
        String logFileName = Utilities.isWindows()
                ? "phpstan-log-netbeans-3022-without-workdir-win.xml"
                : "phpstan-log-netbeans-3022-without-workdir.xml";
        List<Result> results = PHPStanReportParser.parse(getLogFile(logFileName), root, workDir);
workDir);
```

BTW, you should attach a log related to the failure to the issue page if it exists. Thanks.

**Comment by KacerCZ** [comment]
I was trying to minimize differences between Windows as other systems.
So I didn't want to duplicate whole file because there is no guarantee that both files will keep same structure.

**Comment by junichi11** [comment]
As I wrote above, I don't have a strong opinion  (because it is not overwrite.)

Please attach logs to issue pages. Thanks.

**Comment by KacerCZ** [comment]
I added relevant part of log to issue.

**Comment by KacerCZ** [comment]
`PHPStanReportParserTest` now uses simple string replacement.

**Pull request merged**
