### PR TITLE
Update Gradle Tooling API wrapper to 8.5

### PR DESCRIPTION
**Pull request by mbien**
- bump from 8.4 to 8.5
 - gradle 8.5 now supports running on JDK 21 [release notes](https://docs.gradle.org/8.5/release-notes.html)

targets delivery

### CODE REVIEW

**Review by lkishalmi — APPROVED** [review]
Looks good! Thanks!

**Comment by sdedic** [comment]
Does not need  `manifest.mf` module version bumping ?

**Comment by mbien** [comment]
> Does not `manifest.mf` module version need bumping ?

@sdedic AFAIK no, since this is done once per release anyway via https://github.com/apache/netbeans/pull/6576, https://github.com/apache/netbeans/pull/6959

**Comment by neilcsmith-net** [comment]
I won't be able to test until next week, but on principle I'm -0.5 on this one.

Why? What issues are fixed with this? The  tooling API is meant to be forward compatible, and afaik does not suffer from the same max JDK concerns. So what problems with it or our use of it require an update just as we're about to finalise the release? And are there other ways to address those now or in future so that doesn't happen again?

**Comment by lkishalmi** [comment]
Well, there is one painful shortcoming in NB Gradle support. The Boot Classpath of a project is actually taken from the Runtime Classpath: https://github.com/apache/netbeans/blob/681aa7656757ed9ddc7c2f19af8360f85dcfdf66/java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/BootClassPathImpl.java#L72

That would make the use of the new Java 21 API-s uncomfortable (would not be appear, marked red, but would compile after all)

**Comment by mbien** [comment]
> I won't be able to test until next week, but on principle I'm -0.5 on this one.
> 
> Why? What issues are fixed with this? The tooling API is meant to be forward compatible, 

I actually don't have any race horses in the race here or whatever the correct sentence is :)

NB 21rc2 on JDK 21:
image
image

With this PR applied I didn't get the "resolve problems dialog". I simply assumed that we forgot to update the lib wrapper to 8.5, so I quickly opened this PR. The gradle tests can also currently not run on JDK 21 which I was re minded of while doing #7019.

**Comment by mbien** [comment]
closing in favor of #6926 since 8.6 was just released. To make neil's decision easier to figure out what to merge ;)

**Pull request closed without merging**
