### PR TITLE
Backporting profiler related changes into Apache NetBeans.

### PR DESCRIPTION
**Pull request by JaroslavTulach**
VisualVM project decided to pursue its own development of `profiler.lib` and `profiler.oql` since [affe1eb1308554](https://github.com/oracle/visualvm/commit/affe1eb1308554d4df8fcdd6308e9fa4e3f3787). Understandable given the complicated situation NetBeans project was in at that time. However since then the Apache NetBeans project has proven its maturity, ability to deliver and produce regular quarterly releases, as well as upload all the NetBeans libraries to Maven central. Maven central is the default way of distributing and consuming the libraries and I am reusing `profiler.lib` in [Insight project](https://github.com/oracle/graal/blob/master/tools/docs/Insight.md). While doing so, I noticed slight differences in behavior and in order to mimize them I am proposing applying them to Apache NetBeans `profiler.lib` and `profiler.oql` libraries.

First of all I took the [changes](https://github.com/oracle/visualvm/compare/affe1eb1308554...e88fe0edbb) from 

 $ git diff [affe1eb1308554](https://github.com/oracle/visualvm/commit/affe1eb1308554d4df8fcdd6308e9fa4e3f3787)...[e88fe0edbb](https://github.com/oracle/visualvm/commit/e88fe0edbb)

and filtered them out to contain only the changes in above two libraries:
```bash
filterdiff -i '*/visualvm/libs.profiler/lib.profiler/**' | \
  sed s#visualvm/libs.profiler/lib.profiler#profiler/lib.profiler#g | \
  sed s#org/graalvm/visualvm/lib/jfluid#org/netbeans/lib/profiler#g`
```
then I applied the changes as a07981a and resolved remaining clashes manually. Now I am creating a pull request to let the integration tests run and notify me of remaining issues that need to be polished.

### CODE REVIEW

**Comment by korenevskiy** [comment]
@JaroslavTulach 
Welcome.
I do not know where to write. But please read it.
Please add the option to deactivate the project or disable the project. Just like it works in Visual Studio. There is an option to turn off the project.
I have a lot of projects in NetBeans. Periodically, I conduct work with 6 work projects. Each project has open files.
Add the ability to disable and enable projects, so that after enabling them, the working files of each project are automatically opened for editing.

**Comment by vitaly-los** [comment]
> @JaroslavTulach
> Welcome.
> I do not know where to write. But please read it.
> Please add the option to deactivate the project or disable the project. Just like it works in Visual Studio. There is an option to turn off the project...

You  should report it here https://issues.apache.org/jira/projects/NETBEANS/issues/ 
Write a good explanation what you mean

**Comment by korenevskiy** [comment]
@vitaly-los 
Hello. This is my first time doing this.
Did I do the right thing?
https://issues.apache.org/jira/browse/NETBEANS-5674

**Comment by matthiasblaesing** [comment]
@korenevskiy this is not the right place to discuss things - the mailing list is the right location for this. See here: http://netbeans.apache.org/help/index.html. Please remove the comments here, you are messing up reviews.

**Comment by matthiasblaesing** [comment]
The big question is: Who is the author of the code and in who owns copyright/can relicense the code. Options I can speculate about:

- @JaroslavTulach is the author himself, then everything is fine, he is a committer, has therefore an ICLA on file
- all authors are committers/have an ICLA on file or only provided minimal changes, then I still think we can merge
- the work was done under the Oracle OCLA umbrella, then contribution could be covered by an CCLA (not sure whether OCLA and CCLA are transitive) or a Software License Grant
- something other

In any case I like the intention to get this all merged again so in general a +1 for the intention and a -1 for the unclear license question.

**Comment by JaroslavTulach** [comment]
No, the code wasn't written by me. I tried to admit that by making myself a committer, but not author of a07981a. Deeper investigation of all the commits shows:
```bash
visualvm$ git log affe1eb1308554...e88fe0edbb | grep ^Author: | sort -u
Author: Brandon Fish <brandon.j.fish@oracle.com>
Author: Jiri Sedlacek <jiri.sedlacek@oracle.com>
Author: Tomas Hurka <tomas.hurka@gmail.com>
visualvm$ git log affe1eb1308554...e88fe0edbb | grep ^Author.*Hurka | wc -l
552
visualvm$ git log affe1eb1308554...e88fe0edbb | grep ^Author.*Sedlacek | wc -l
446
visualvm$ git log affe1eb1308554...e88fe0edbb | grep ^Author.*Fish | wc -l
1
```
E.g except https://github.com/oracle/visualvm/commit/9efce02560871140feda1d3e9ca528714e932cff all the code is written by either @thurka or @jisedlac. Now, let's try to select just the commits related to `visualvm/libs.profiler/lib.profiler`. I have written following `filter.sh` script:
```bash
git log affe1eb1308554...e88fe0edbb | grep commit | cut -d " " -f2 | while read X; do 
  D=`git show $X | filterdiff -i '*/visualvm/libs.profiler/lib.profiler/**'`
  if [ "x$D" == "x" ]; then 
     # echo None $D
     IGNORE=$D
   else 
     git show $X | grep ^Author: 
   fi 
done
```
Running `filter.sh | wc -l` yields `87`. 78 commits by @thurka and 9 by @jisedlac. The https://github.com/oracle/visualvm/commit/9efce02560871140feda1d3e9ca528714e932cff  commit isn't included in a07981a at all.

**Comment by matthiasblaesing** [comment]
Thank you for the analysis. So could the two main authors get an ICLA on file? I looked through the ICLA signee list and did not find either.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing well, we don't strictly _need_ an ICLA for contributions even if useful - only committers _require_ one.  But either way, we surely need the clear intention of the authors (and/or employer if necessary) to re-license and contribute these particular changes here?

**Comment by matthiasblaesing** [comment]
@neilcsmith-net ah yes - you are right. To have some permanent record, a tracking issue in JIRA would then be helpful.

**Comment by JaroslavTulach** [comment]
Yes, having consents from both authors is a pre-requisitte to integrate. I haven't obtained the permission so far. Closing. Whether there is a way to avoid doing the same work twice remains to be seen.

**Pull request closed without merging**
