### PR TITLE
[NETBEANS-3268] Add hints for variables and method return parameters

### PR DESCRIPTION
**Pull request by graben**
Waiting for #1559 getting merged.

### CODE REVIEW

**Comment by graben** [comment]
@jlahoda : Could you plz have a look on this.

**Comment by jlahoda** [comment]
Two questions:
-why not member selects? (Like Math.PI.)
-I wonder if we are getting to a place where we need a customization for this, so that users can choose if they want to see the names only in some specific cases.

**Comment by graben** [comment]
Never thought about member selects but let me have a look it should be easy with the code separated in its own method. I think customization will be a thing to think about once this feature is confirmed to be activated by default maybe for 12.0.

**Comment by graben** [comment]
@jlahoda : Add member select to highlighter and test.

**Comment by graben** [comment]
@jlahoda : Ready to merge?

**Comment by graben** [comment]
@jlahoda : Can we get this into 11.3?

**Pull request merged**
