### PR TITLE
[Netbeans-5734] Quick fix to make NB 12.4+ run Glassfish 6.1 on JDK 11+

### PR DESCRIPTION
**Pull request by matthiasblaesing**
This PR is a cleaned up and enhanced version of #3056. It was also rebased onto the release125 branch.

This is primary a bug fix, so should be considered for 12.5.

Closes: #3056

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@juneau001 

For a discussion please see the referenced original PR. This is the consolidated version, I'd appreciate opinions as I currently don't use glassfish myself and so working from past experiences.

**Comment by neilcsmith-net** [comment]
👍 Should be based on delivery branch though (which I guess won't make a difference yet).

**Comment by matthiasblaesing** [comment]
@neilcsmith-net thanks for the check - something felt wrong, but I could not pin-point it. At this point it is indeed uncritical as the base commit is the same for all candidates, so I switched target branch in the PR settings.

**Review by juneau001 — COMMENTED** [review]
Loaded PR into local development environment.  Compiled and built without issues.  Configured GlassFish 6.1 with JDK 11 and successfully deployed Jakarta EE application using JDK 11.

**Comment by ebarboni** [comment]
green light I will merge, and resync (I hope to success in this step) to make a "beta" with all 12.5 intended content :D

**Pull request merged**
