### PR TITLE
[NETBEANS-4652] Change the max level of PHPStan to 8

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-4562

- https://phpstan.org/user-guide/rule-levels

netbeans-4652-phpstan-level8

### CODE REVIEW

**Comment by tmysik** [comment]
@junichi11 

Just thinking whether it would make sense to make it configurable... :thinking: Probably not necessary :)

BTW can I merge it, right? The test failure seems unrelated to me. Or am I wrong?

Thanks!

**Comment by junichi11** [comment]
@tmysik 
> Just thinking whether it would make sense to make it configurable...  Probably not necessary :)

Let's think that after the new level is added in the future again :) e.g. We can add the max level combobox. or change to the text field.

> BTW can I merge it, right? The test failure seems unrelated to me. Or am I wrong?

It should be OK. Maybe this: https://lists.apache.org/thread.html/r680b5a50fc7c8d07c91c0750df6cafa1e49732cbfdfbc2aa15c3c012%40%3Cdev.netbeans.apache.org%3E

Thank you!

**Comment by tmysik** [comment]
@junichi11 

> We can add the max level combobox. or change to the text field.

I was thinking more about a simple configuration (properties) file with a max level. Anyone could update it manually without a code change. And yes, if someone puts there `1000` then it is his/her fault :)

**Comment by junichi11** [comment]
@tmysik 
> I was thinking more about a simple configuration (properties) file with a max level. Anyone could update it manually without a code change. And yes, if someone puts there `1000` then it is his/her fault :)

Makes sense. Good idea!

**Pull request merged**
