### PR TITLE
[NETBEANS-3108] PHP: Some features(e.g. Go to declaration) do not work after "new"

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-3108

- Just check `StaticFieldAccess` and `FieldAccess` in the `ModelVisitor`

### CODE REVIEW

**Comment by tmysik** [comment]
Thanks a lot, @junichi11 !

**Comment by neilcsmith-net** [comment]
@tmysik please await the review in future - that was a slightly badly timed merge! Thanks.

**Comment by tmysik** [comment]
@neilcsmith-net No idea what you mean, sorry. Could you be more specific, please? Thanks.

**Comment by neilcsmith-net** [comment]
@tmysik I did not want this in master yet. I merged what was ready, but this was waiting for your review.

We're in release freeze. The point of the release manager being asked to review is so that they can OK and/or merge when suitable.  After merging what was ready I merged the build branding / infra changes as mentioned on dev@ and want to get that fixed up and working ASAP to get the release branch and beta out.

**Comment by tmysik** [comment]
@neilcsmith-net @junichi11 

> I did not want this in master yet

Then you must tell me. Or the author of PR. I don't read such information here - am I missing something? No tag, no message, nothing.

Sorry, I am doing this in my leisure time so I really cannot follow any other mailing lists, etc. I am afraid that this can result only in one thing - I will stop doing reviews (which is not what I want, believe me).

**Comment by neilcsmith-net** [comment]
@tmysik I'm not trying to discourage you from reviewing.  If there's not a green tick by all reviewers at top right, please don't assume it's OK to merge.  And if you do want to merge, please follow dev@ for announcements - such overarching notices are not made on individual PRs.

You're not the only one doing this in their leisure time! :wink:

**Comment by junichi11** [comment]
@tmysik  I'm bad. I should have written something for merging. So sorry... I always appreciate your review.

**Comment by tmysik** [comment]
@junichi11 My bad, I overlooked that @neilcsmith-net is as a reviewer too - that is information I know I need to look for the next time! Sorry guys!

@neilcsmith-net 

> If there's not a green tick by all reviewers at top right, please don't assume it's OK to merge

Now I will know. Sorry for missing it. No idea whether it is possible but - can we allow PR to be merged only when all the reviewers agree? In such a case, I won't be able to merge this PR (and probably force you to approve it so I can merge ;)

**Comment by neilcsmith-net** [comment]
@tmysik no problem! :smile:  Looking at the PR I just opened, it should also tell you about pending reviews above the test info on the merge section.

It's possible we could consider protected branches so reviews and tests have to pass, but not sure if we want to do that everywhere?  An extra warning would be nice though!  Bit on required reviews at https://help.github.com/en/articles/about-pull-request-reviews

**Comment by tmysik** [comment]
@neilcsmith-net 

> https://help.github.com/en/articles/about-pull-request-reviews

I would expect something like `Allow merge only if all reviewers approved` checkbox in the repository settings. But that is not the case if I understand it correctly. Using a fixed number of reviewers does not seem to me to be much useful (maybe for companies it can work well?).

**Pull request merged**
