### PR TITLE
Defensive guards against invalid code points in preferences.

### LINKED ISSUE #5147: Since some weeks tasks in my NB development environment do not end any more.
### Apache NetBeans version

Apache NetBeans 16

### What happened

Since some weeks tasks in my NB development environment do not end any more.
Instead the status line shows e.g. '12 more'. If i click that message the tasks (debugger, clean build, etc) are shown with the indeterminate progress bar. A click in the 'cancel' button doesnt help. Instead closing NB that list of tasks is presented to the user to be finished. After confirm, NB shuts down and the tasklist is shown again for confirmation

This was observed in NB 12.5 which I used for years and never had such problem.
I update the NB16 (and took over the configuration) - Same problem

I was checking the IDE Log and found a message
java.lang.IllegalArgumentException: Key contains code point U+0000

Notification says, there is an unexpected Exception (each time  clean build or debugger or run was finished
[messages.log](https://github.com/apache/netbeans/files/10301078/messages.log)

### How to reproduce

I guess this is a 'broken' configuration issue - No way to reproduce ... 
I have a lot of projects, which I am working on frequently.
The option to remove the 'Roaming/Netbeans' folder would be most annoying, because I would need to setup the configuration full again (will be a pain)

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Windows 10

### JDK

OpenJDK 15

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Happens for each task done in the netbeans 

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

### LINKED ISSUE #5633: Unexpected java.lang.IllegalArgumentException: Key contains code point U+0000
### Apache NetBeans version

Apache NetBeans 17

### What happened

[messages.log](https://github.com/apache/netbeans/files/10924329/messages.log)

### How to reproduce

_No response_

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

Windows 10 Pro, version 21H2, build 19044-2694, Intel i7 x64 16.0 GB

### JDK

openjdk-19.0.1_windows-x64_bin.zip

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time when run, but not when run in debug.

### Are you willing to submit a pull request?

No

### LINKED ISSUE #5634: NetBeans IDE processes do not terminate, and cannot be cancelled.
### Apache NetBeans version

Apache NetBeans 17

### What happened

On any execution of a project (run, debug, javadoc) the process does not end. The only way to end the processes is to close the IDE.
Screenshot 2023-03-08 123855
Screenshot 2023-03-08 123855
Screenshot 2023-03-08 123628

### How to reproduce

Compile and run anything.

This problem was not present in NetBeans 15 but was/is present in NetBeans 16 and 17

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

Windows 10 Pro, version 21H2, build 19044-2694, Intel i7 x64 16.0 GB

### JDK

openjdk-19.0.1_windows-x64_bin.zip

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Every time.

### Are you willing to submit a pull request?

No

### LINKED ISSUE #6076: java.lang.IllegalArgumentException: Key contains code point U+0000
### Apache NetBeans version

Apache NetBeans 18

### What happened

When I build the  java project, the process bar keeps ongoing and does not finish. There is an error message beside it. 
[messages.log](https://github.com/apache/netbeans/files/11746271/messages.log)

### How to reproduce

_No response_

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

since yesterday it occurs every time I build the project 

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
The code point '\u0000' breaks the Preferences storage as demonstrated in https://bugs.openjdk.org/browse/JDK-8068373, as preventive measure it can't be used in keys since https://bugs.openjdk.org/browse/JDK-8084823.

There are many reports of windows users running into seemingly unrelated issues, but closer investigation showed that they all had at some point "invalid code point" exceptions in the log.

this usually happens in a code pattern like this:
```java
for (String k : pref.keys()) { // contains an invalid key
    ... = pref.get(key, null);  // throws IAE
}
```
It is not clear what causes the corruption (and why it seems to only occur on windows), this PR adds some defensive code to cover some common cases, logs it and makes sure no corrupted properties files are imported from old configs on first launch.

the jackpot rule:
```java
$pref.keys() :: $pref instanceof java.util.prefs.Preferences;;
```
had 70 hits - this PR covers only common cases + adds the import filter.

```
org.apache.tools.ant.module.bridge.impl.BridgeImpl$PostRun
java.lang.IllegalArgumentException: Key contains code point U+0000
	at java.prefs/java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:296)
	at org.apache.tools.ant.module.api.IntrospectedInfo$3.load(IntrospectedInfo.java:681)
	at org.apache.tools.ant.module.AntSettings.getCustomDefs(AntSettings.java:119)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl$PostRun.run(BridgeImpl.java:443)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
```
```
java.lang.IllegalArgumentException: Key contains code point U+0000
       at java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:296)
       at java.util.prefs.AbstractPreferences.getBoolean(AbstractPreferences.java:531)
       at org.netbeans.core.windows.TopComponentTracker.load(TopComponentTracker.java:99)
       at org.netbeans.core.windows.PersistenceHandler.load(PersistenceHandler.java:126)
       at org.netbeans.core.windows.WindowSystemImpl.load(WindowSystemImpl.java:81)
       at org.netbeans.core.GuiRunLevel$InitWinSys.run(GuiRunLevel.java:229)
```
```
java.lang.IllegalArgumentException: Key contains code point U+0000
      at java.prefs/java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:296)
      at org.netbeans.modules.maven.queries.MavenFileOwnerQueryImpl.registerCoordinates(MavenFileOwnerQueryImpl.java:153)
      at org.netbeans.modules.maven.ProjectOpenedHookImpl.registerWithSubmodules(ProjectOpenedHookImpl.java:431)
      at org.netbeans.modules.maven.ProjectOpenedHookImpl.projectOpened(ProjectOpenedHookImpl.java:138)
      at org.netbeans.spi.project.ui.ProjectOpenedHook$1.projectOpened(ProjectOpenedHook.java:60)
  [catch] at org.netbeans.modules.project.ui.OpenProjectList.notifyOpened(OpenProjectList.java:1273)
      at org.netbeans.modules.project.ui.OpenProjectList.doOpenProject(OpenProjectList.java:1354)
      at org.netbeans.modules.project.ui.OpenProjectList.open(OpenProjectList.java:798)
      at org.netbeans.modules.project.ui.OpenProjectList$6.run(OpenProjectList.java:650)
      at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
      at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
      at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
      at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

closes #6076
closes #5147
closes #5633
closes #5634
https://bz.apache.org/netbeans/show_bug.cgi?id=271652
https://issues.apache.org/jira/browse/NETBEANS-3284

### CODE REVIEW

**Review by neilcsmith-net — APPROVED** [review]
Generally a good move. Thanks for picking up!

On the protecting on import side -

- there are `.properties` files outside of `config/Preferences`. Are we 100% sure there is no valid reason for `\u0000` in them? Or need to filter by preferences root?
- does the import protection also need to be considered in - https://github.com/apache/netbeans/blob/master/platform/options.api/src/org/netbeans/modules/options/export/OptionsExportModel.java#L293 ? (yes, I love we have two code paths with somewhat different implementations of similar things!)

**Comment by mbien** [comment]
@neilcsmith-net good that you pointed me to `OptionsExportModel`, since it left several streams open, and all `ZipFile`s.

I never used that feature before. Lets test this a bit before merging.

**Review by matthiasblaesing — APPROVED** [review]
Not sure about the \0 in properties, but the changes look sane.

**Comment by mbien** [comment]
thanks for the reviews and sorry for the delay.

I am also not sure about the null code point as property *value*, but https://bugs.openjdk.org/browse/JDK-8068373 for example describes it being illegal in XML files. Given that a) there was no such value in any property in my config backups and b) properties could end up in xml at some point which makes it probably safer to filter them out during config migration.

-> merging

**Pull request merged**
