### PR TITLE
Add a README for the bitmap-to-SVG icon process, plus Illustrator file and icon scripts

### PR DESCRIPTION
**Pull request by eirikbakke**
This PR documents the process for drawing and installing scalable SVG versions of NetBeans icons, and commits the Illustrator File and script that was used to assemble icons in the separate PRs https://github.com/apache/netbeans/pull/7463.

Details:
* Add a README file which documents the process for drawing and installing scalable SVG versions of the many old bitmap icons that are present in the NetBeans UI.
* Add the Adobe Illustrator file with the around 70 icons that have been drawn to date. This Illustrator file also contains template artboards for icons that should be prioritized in the future. There's a PDF version of the Illustrator file for those who wish to have a look at it without installing Illustrator.
* Add the IconTasks script, which is used to find, organize, and install icons in the NetBeans repo.
* Add a HTML page summary of the icons and mappings to old bitmaps, generated by the IconTasks script. (The HTML page summary icons.html includes image references to SVG files that are committed in a [separate PR](https://github.com/apache/netbeans/pull/7463), so it will have broken image links until that PR is merged as well. I have put a hosted version with working images here: https://people.csail.mit.edu/ebakke/misc/netbeans-icons-240612.html )

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for looking at this.  The other PR looks great from a glance.  This part I wonder whether should be added to https://github.com/apache/netbeans-tools instead?

**Comment by neilcsmith-net** [comment]
> Happy to open a PR against netbeans-tools instead if you think that's the best place for these files.

It think it might be, but let's see what others think - cc/ @mbien @ebarboni @matthiasblaesing 

> Perhaps we revisit the idea of generating PNGs of different resolutions ... from the SVGs at build time instead of relying on the rather heavyweight NetBeans SVG loader.

Possibly.  Another option might be to switch to a lighter-weight loader.  Something for discussion elsewhere, perhaps mailing list, but interesting to see FlatLaf change to JSVG (as has IntelliJ) https://github.com/JFormDesigner/FlatLaf/issues/664 https://github.com/weisJ/jsvg

**Comment by matthiasblaesing** [comment]
> > Happy to open a PR against netbeans-tools instead if you think that's the best place for these files.
> 
> It think it might be, but let's see what others think - cc/ @mbien @ebarboni @matthiasblaesing

If this not tied into the build process, I would keep outside the main project and indeed that was my first though when seeing this PR.

**Comment by mbien** [comment]
> > Happy to open a PR against netbeans-tools instead if you think that's the best place for these files.
> 
> It think it might be, but let's see what others think - cc/ @mbien @ebarboni @matthiasblaesing

+1 for the tools repo. If possible without the PDF for two reasons: pdfs can do too much to be in code repos IMO and secondly: it would have to be kept in sync with the illustrator file, no?

**Comment by mbien** [comment]
btw I could open the `.ai` file with inkscape and everything seemed to show up, "New Vector" and "Old Bitpmaps" layers etc

**Comment by eirikbakke** [comment]
Thanks for your comments; I have now revised the script to work from the netbeans-tools repo instead, and opened a PR there: https://github.com/apache/netbeans-tools/pull/67

**Pull request closed without merging**
