### PR TITLE
[NETBEANS-4443] PHP 8.0 Support: Nullsafe operator

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-4443

- https://wiki.php.net/rfc/nullsafe_operator
- Fix the parser and lexers
- Add the `isNullsafe()` method to `Dispatch`
- Add/Fix unit tests for the parser and the lexers
- Fix the `PHP80UnhandledError`
- Fix the `PHP5ErrorHandlerImpl` (also add "fn", "match", "??=" because they are missing)
- Fix the formatting feature
- Fix the code completion feature
- Fix the IndentationCounter
- Add unit tests for GotoDeclaration and MarkOccurrences

#### PHP 8.0 (Project Properties)

nb-php80-nullsafe-operator

#### PHP 7.4 (Project Properties)

nb-php80-nullsafe-operator-php74

### CODE REVIEW

**Comment by tmysik** [comment]
@junichi11 There are some failures on JDK 14, could you please check them? Thanks.

**Review by tmysik — APPROVED** [review]

**Comment by tmysik** [comment]
@junichi11  BTW, again, plenty of files, really not possible to review it :)

**Comment by junichi11** [comment]
> There are some failures on JDK 14, could you please check them? Thanks.

Will try restarting the job. (Maybe, no problem because it's the test of java.hints)

> BTW, again, plenty of files, really not possible to review it :)

Yes :)

Thank you!

**Comment by junichi11** [comment]
I just rebased. (No changes. Checks were passed once.)
nb-pr2446

**Pull request merged**
