### PR TITLE
[cnd] lsp client

### PR DESCRIPTION
**Pull request by vieiro**
Introducing `cnd/cnd.lsp` a LSP client for [clangd](https://clangd.llvm.org/).

- We drop `cpplite` DataObjects and Options.
- We add some extra colors for C/C++ semantic tokens (variables, members, functions, macros), both in light and dark versions.
- We expand `pkg-config` macros and add a `PkgConfigManager` for cnd (to find libraries, etc.)
- We enhance `ide/lsp-client` to use one thread for language server kind (TypeScript, C/C++, etc.)
    - So one slow language server does not affect others.
    - So requests to the same language server are properly sequenced.
- We make `ide/lsp-client` honor the fonts-colors registered for the mime-type (and fall back to default ones otherwise).

### CODE REVIEW

**Comment by vieiro** [comment]
An screenshot with FlatLaf light theme, sporting:

- The LSP server running.
- A debugging session (with variables, call-stack, threads) supported by gdb.
- Semantic syntax coloring (different colors for members/variables, etc.)
- LSP autocompletion from clangd.

imagen

**Review by matthiasblaesing — APPROVED** [review]
I did not really go through all changes, I notice to potential problems:

- is it a good idea to expose the state of the LSP Server? In the TypeScript bindings the complexity is hidden from the user. I'm not sure if that could also apply to the C language servers.
- there are changes to the common lsp code. This might create conflicts if change go into master in the meantime. Should it be split out?

**Comment by vieiro** [comment]
Hi @matthiasblaesing , thanks for the review.
1.- I think it's ok to expose the state of the LSP server. I think developers want to know if things are running or not (in the cpplite era one could not see if the lsp server was running or not).
2.- Regarding the changes, we can split them out and send them to master. I thought it would be a good idea to make a test in cnd first, with two LSP servers running at the time. Anyway making all different capabilities go though a single RequestProcessor solves issue https://github.com/apache/netbeans/issues/3812 .

Best we can do, I think, is to test here in this branch (without merging) with two LSP servers running (say clangd and typescript), see if things run well, and then remove the commit from this PR and send it to master instead. What say?

**Comment by matthiasblaesing** [comment]
Sounds sane - a single request processor still allows unserialized insertion of new tasks on the java side. They are executed in order, but the order might already be wrong.

**Comment by vieiro** [comment]
Ok. Thanks, @matthiasblaesing . So I'll test this for some time, see how well it behaves with different LSP servers and then remove the commit from this PR and send it to master instead.

**Comment by vieiro** [comment]
So I did some testing and yes, each LSP server (TypeScript and C/C++) is handled in its own thread as intended, so if a LSP server is slow or something the rest won't we affected. I couldn't detect any problems with LSP stuff.

Here is the first one...
```
"pool-5-thread-1" #76 prio=5 os_prio=0 cpu=105,90ms elapsed=263,25s tid=0x00007f7a9409b800 nid=0xe0cd runnable  [0x00007f7a6c098000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@11.0.14.1/Native Method)
	at java.io.FileInputStream.read(java.base@11.0.14.1/FileInputStream.java:279)
	at java.io.BufferedInputStream.fill(java.base@11.0.14.1/BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read(java.base@11.0.14.1/BufferedInputStream.java:271)
	- locked <0x000000008ce139d0> (a java.lang.ProcessImpl$ProcessPipeInputStream)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.14.1/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.14.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.14.1/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.14.1/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.14.1/Thread.java:829)
```

... and the second one.
```
"pool-1-thread-1" #52 prio=5 os_prio=0 cpu=60,85ms elapsed=320,74s tid=0x00007f7a900ad800 nid=0xe062 runnable  [0x00007f7a6c699000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@11.0.14.1/Native Method)
	at java.io.FileInputStream.read(java.base@11.0.14.1/FileInputStream.java:279)
	at java.io.BufferedInputStream.fill(java.base@11.0.14.1/BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read(java.base@11.0.14.1/BufferedInputStream.java:271)
	- locked <0x0000000088a86c90> (a java.lang.ProcessImpl$ProcessPipeInputStream)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.14.1/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.14.1/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.14.1/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.14.1/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.14.1/Thread.java:829)
```

Next step is to extract the commit for `ide/lsp.client`and push it to master, and remove it from here.

[netbeans-ts-cpp-threads.txt](https://github.com/apache/netbeans/files/8597461/netbeans-ts-cpp-threads.txt)

**Comment by vieiro** [comment]
Also coloring works as expected: The C/C++ coloring on the left is registered in under the C/C++ mimetype, the Typescript coloring on the right is `ide/lsp.client` default.

imagen

So the commit for `ide/lsp.client` that honors fonts/colors registered in the mime-type works well too.

**Comment by vieiro** [comment]
Commits in `ide/lsp.client` have been moved to https://github.com/apache/netbeans/pull/4057, merging to master instead.

**Pull request merged**
