### PR TITLE
[TRAVIS] Add missing license to correct failing verification

### PR DESCRIPTION
**Pull request by graben**
@ebarboni : Should be merge to avoid actual travis build to fail.

### CODE REVIEW

**Comment by graben** [comment]
Hi @lkishalmi, your latest Freemarker update from #2067 seems to break Travis build at all. Hopefully I fixed the right thing on the fly ;)

**Comment by graben** [comment]
Well, there also unit test seems to fail.

**Comment by graben** [comment]
Ignore failing tests for now. Must be completely rewritten since freemarker has changed it error handling. Much more chatty :)

**Comment by lkishalmi** [comment]
Thanks for fixing my bad. I do not know how could I push that incomplete PR in the first place. I'm sorry.

**Comment by jlahoda** [comment]
Looks good to me. Eric, unless there are objections, or unless you want to do it yourself, I'll merge in a few hours. (The only alternative I see would be to revert #2067 - but I think fixing it is better!)

Thanks @graben for fixing this!

**Comment by graben** [comment]
Just fixed another minor file returning 2.3.19 instead of 2.3.30.

**Pull request merged**
