### PR TITLE
PHP: Corrected a typo in the php parser tests

### PR DESCRIPTION
**Pull request by troizet**
Corrected a typo in the php parser tests.

### CODE REVIEW

**Comment by KacerCZ** [comment]
Change looks sane.
Let's see result of CI.

**Review by KacerCZ — APPROVED** [review]

**Comment by junichi11** [comment]
@mbien Doesn't work tests of php.editor?

**Comment by mbien** [comment]
> @mbien Doesn't CI run tests of php.editor?

hi @junichi11, the label was added *after* the workflow request was built. Starting a fresh workflow will take new labels into account (restarting will not unfortunately).

This is the main reason we have the "secret" workaround of PR locking/unlocking which is used a trigger for a fresh workflow run (instead of restarting an old run which does not update its label information).

going to do this now and start a fresh workflow run here

**Comment by junichi11** [comment]
@mbien OK. Thanks!

**Comment by mbien** [comment]
@junichi11 thanks for checking that the correct tests run during review!

**Review by junichi11 — APPROVED** [review]

**Pull request merged**
