### PR TITLE
Snapshot of APIs as of 12.4

### PR DESCRIPTION
**Pull request by geertjanw**
Followed these instructions: https://github.com/apache/netbeans/pull/2788 (except the getPeer search command didn't work for me, hope that having them included is not a big issue).

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@geertjanw looks like my `sed` command might be Linux specific - https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux 😬 

The other option is to remove manually - that's what was done before - I got fed up of doing it.  Ideally it wouldn't be generated, but @jtulach might have a view on an approach here.

**Comment by geertjanw** [comment]
Can we go ahead with this PR without that, i.e., is it OK as it is right now?

**Comment by JaroslavTulach** [comment]
Since #2881 the removal of `getPeer()` shall not be necessary. Even if one is running on JDK9+, we compare against APIs of JDK8 thanks to the `release` attribute of `Sigtest` task.

**Review by JaroslavTulach — APPROVED** [review]

**Comment by geertjanw** [comment]
Can this be merged now?

**Comment by neilcsmith-net** [comment]
@geertjanw I would normally regenerate on the basis of the release, in case there were any late additions.  Although as this ended up being close to vote I think it might be fine (ideally we'd do first iteration for review before freeze).  If you're confident it's picked up everything then should be merged, and I think spec version increment is still pending following on from merging this?

**Comment by ebarboni** [comment]
redone in #3024

**Pull request closed without merging**
