### PR TITLE
Revert "[NETBEANS-819] partial fix for cursor. Text selection does't work"

### PR DESCRIPTION
**Pull request by lkishalmi**
Reverts apache/netbeans#2509

Dear @hlavki,

Please respond and/or fix the text selection issue on #2509. I'm about to merge this revert PR about three days from now.

### CODE REVIEW

**Comment by hlavki** [comment]
Hi @lkishalmi,

sorry for not responding.... really heavy to find time for this, but I'll try to fix this in 3 days thanks

**Review by matthiasblaesing — APPROVED** [review]
@lkishalmi The revert looks identical to the one I use locally to get usable nightlies. As @hlavki indicated he is working on this we should give him enough time.
@hlavki please do not take this approval as a disapproval of your work. As indicated above, I'd like to see a real fixed getting in, but if needed, this PR is a valid revert.

**Comment by hlavki** [comment]
@matthiasblaesing thanks, I am ok with Laszlo's pushing ;)
I am working on it and I hope it will be fixed soon. But I have to say that it will be more than 3 days.

**Comment by lkishalmi** [comment]
The issue selection issue has been fixed.

**Pull request closed without merging**
