### PR TITLE
binaries-list dependency checker needs to set up the env for maven

### PR DESCRIPTION
**Pull request by mbien**
overlooked something for https://github.com/apache/netbeans/pull/7644. I wished I could run workflows locally.

### CODE REVIEW

**Review by neilcsmith-net — APPROVED** [review]
> I wished I could run workflows locally.

You should be able to run them on your own repo branch though.

**Comment by mbien** [comment]
> You should be able to run them on your own repo branch though.

yeah true, I have also a dummy PR for similar reasons here https://github.com/mbien/netbeans/pull/1. It still is not quite the same that I have to push first.

I could have done it in this case I believe if i would have pushed this PR branch to mbien/master, then trigger it manually via actions.

I have to give this a try one day https://github.com/nektos/act

**Comment by mbien** [comment]
works. thanks for reviewing!

**Comment by neilcsmith-net** [comment]
> I could have done it in this case I believe if i would have pushed this PR branch to mbien/master, then trigger it manually via actions.

It doesn't have to be in master.  You can choose the PR branch in the trigger UI.  Although possibly this should also run on push to itself like the native workflows do anyway?

**Comment by mbien** [comment]
the reason I wrote this was to discover dependencies which would need updates. For this I typically run it locally. I don't quite see the value of triggering it automatically during PRs which modify binaries-list files - since at this point the dev already figured out what to update.

You can see on the history that i run this one a month or so. Nobody else ran it so far. 

It could be run automatically weekly or something like that. But will anyone look at this?

**Comment by mbien** [comment]
> I didn't mean running it when any PRs are opened - I just mean adding something like https://github.com/apache/netbeans/blob/master/.github/workflows/native-binary-build-launcher.yml#L38 so it runs every time you push a change to the workflow in your personal repo.

oh, thats a cool trick! Going to add this next time I update it.

**Comment by neilcsmith-net** [comment]
Believe me, if that wasn't in those I'd still be writing the PRs to get them in! :smile:

**Pull request merged**
