### PR TITLE
Support port offset for wildfly server

### PR DESCRIPTION
**Pull request by akronenw**
This solves the same issue as mentioned in #5453, but cleaner.
The problem: Wildfly servers are configured with XML files like `standalone.xml`. Those contain socket binding groups that comprise a bunch of ports and can have a port offset defined. One such group is the `standard-sockets` group in which for example the management port is defined. All variables in the config file can (must?) be written like `${jboss.socket.binding.port-offset:10000}`, that is, a variable and the fallback (or default) value separated by a `:`.
NetBeans does not set the port-offset variable, hence the default from the config file is used, but NetBeans does not parse it either so the Wildfly server runs on a different port as known by NetBeans. That leads to a correctly started server that can't be restarted, stopped or refreshed from the NetBeans server context view (but it is possible to start it regularly).

I fixed this by parsing the config and extracting the default port offset from the standard socket group. The offset is then added to the admin port value (which can be set in the add server wizard) in the deployment manager.

I did not add the offset to the regular port, because I have not yet found an issue with that (most likely I will, sooner or later) and that would mean touching a lot more files.

### CODE REVIEW

**Comment by mbien** [comment]
@ehsavoie want to take a look at this?

would be good to check if this closes any issues, e.g description of #3936 sounds potentially related.

**Comment by ehsavoie** [comment]
The issue is that this doesn't fix the problem: if the offset is set when starting WildFly using -Djboss.socket.binding.port-offset=100 then you are back on it since you would need to connect to the running server management API to get the effective value.
I'm a bit surprised because I thought that you could pass the management port in the plugin which is (in my opinion) the only viable solution:
"The offset is then added to the admin port value (which can be set in the add server wizard)"

I don't understand why you don't set the proper port value per server instance.

**Comment by akronenw** [comment]
Hello @ehsavoie, 
thanks for checking this.

> if the offset is set when starting WildFly using -Djboss.socket.binding.port-offset=100 then you are back on it since you would need to connect to the running server management API to get the effective value

I don't understand that. Do you mean, starting Wildfly manually and passing the port-offset as parameter? If so, that would not make sense, as the whole point is that NetBeans starts the server and passes everything in.

> I don't understand why you don't set the proper port value per server instance.

Yes, I could do that. But the port offset in the `standalone.xml` applies to more ports than admin and HTTP. As NetBeans only allows to set admin and HTTP port, I'd have to remove the port offset in the config file and add it to the other ports by hand. That is inconvenient and makes the port offset variable pointless.
Unfortunately I have to deal with several Widlfy instances of different versions and just setting the port offset in the config makes it easier to have them running in parallel. 

Probably the best is to scrap my commits and add a new field in the server wizard where one can specify the port offset, which is then passed to Wildfly via `-Djboss.socket.binding.port-offset=Y`. I am not keen on doing Swing stuff so I tried to fix the problem with the commits you checked. 

What do you think?

**Comment by ehsavoie** [comment]
Yes I'd like this idea . Also note that the plugin is able to connect to a running instance.

**Comment by akronenw** [comment]
I will open a new PR for the new approach.

**Comment by ehsavoie** [comment]
@akronenw maybe you would want to take a look at https://github.com/ehsavoie/netbeans/pull/new/support_port_offset_for_wildfly_server

**Pull request closed without merging**
