### PR TITLE
Remove discontinued Javeleon integration.

### PR DESCRIPTION
**Pull request by mbien**
Javeleon (https://javeleon.com/) is no longer available.

This removes the friend dependency exports and the integration code.

### CODE REVIEW

**Review by lkishalmi — APPROVED** [review]
Get out with that rusty thing!

**Comment by mbien** [comment]
@lkishalmi should I remove those bits?

https://github.com/apache/netbeans/blob/503dd1f12e28153ed240ab8ae06a30464b367e4d/platform/core.startup/arch.xml#L707-L709

and

https://github.com/apache/netbeans/blob/503dd1f12e28153ed240ab8ae06a30464b367e4d/platform/o.n.bootstrap/arch.xml#L762-L764

**Comment by mbien** [comment]
updated the two arch.xml files

**Comment by mbien** [comment]
all green again, merging.

**Pull request merged**
