### PR TITLE
[NETBEANS-3745] Clean up abandoned user dirs

### PR DESCRIPTION
**Pull request by lkishalmi**
This one is pretty trivial.

### CODE REVIEW

**Comment by lkishalmi** [comment]
Janitor1

**Comment by ebarboni** [comment]
@lkishalmi I put in beta 2.

**Comment by neilcsmith-net** [comment]
@lkishalmi any way to only run this on first launch, or offer the option to mute rather than remove?  This is rapidly becoming my least favourite feature of beta2.  cc/ @geertjanw

**Comment by GeertjanWielenga** [comment]
Would indeed be an idea to have it disabled by default and require a setting in netbeans.conf and/or Options window to enable it. The feature itself is very useful but also potentially very noisy in its current default state.

**Comment by neilcsmith-net** [comment]
@geertjanw I agree with the idea of having it enabled by default, because for many users that's right (at least once), but there really needs to be a way to tell it to shut up - I get what you were complaining about at FOSDEM now! :smile:

@lkishalmi or maybe we use similar logic as https://github.com/apache/netbeans/blob/master/platform/uihandler/src/org/netbeans/modules/uihandler/Installer.java#L331 to only run this on _second_ run of IDE?  I assume there's no chance of overlap with import upgrade task with this - ie. removing a userdir in process of being imported?

**Comment by ebarboni** [comment]
I did not notice the annoyance but any PR to solve welcome.

**Comment by lkishalmi** [comment]
I'm going to work something out for that.

**Comment by lkishalmi** [comment]
See #1925

**Pull request merged**
