### PR TITLE
Update Spring Framework to version 4.3.29

### PR DESCRIPTION
**Pull request by hectorespert**
Update Spring Framework to version 4.3.29

### CODE REVIEW

**Comment by lkishalmi** [comment]
Hmmm isn't the upgrade happens from 4.3.25 -> 4.3.29?

**Comment by hectorespert** [comment]
> Hmmm isn't the upgrade happens from 4.3.25 -> 4.3.29?

Was my fault, I wrote in the commit and the description that the version updated is the 4.2.25, when it is the 4.2.29.

**Comment by lkishalmi** [comment]
Now it conflicts with the 5.2.9 change. Could you resolve?

**Comment by hectorespert** [comment]
> Now it conflicts with the 5.2.9 change. Could you resolve?

Conflict resolved. Tanks @lkishalmi

**Pull request merged**
