### PR TITLE
[NETBEANS-2783] Fix missing dependencies nodes in Project view when editing POM file

### PR DESCRIPTION
**Pull request by AlexFalappa**
This PR fixes [NETBEANS-2783](https://issues.apache.org/jira/browse/NETBEANS-2783).

One liner, no side effects introduced as far I can tell. Tested also with a maven modular project under JDK-11.

### CODE REVIEW

**Comment by AlexFalappa** [comment]
I know that this is very late but this could even be merged in NB11.1.

**Comment by neilcsmith-net** [comment]
Late as in past the deadline, sorry.  Build for vote has been made already.  Tag it with NB 11.2 if it's otherwise ready for merging when the merge window opens again and has been reviewed.

**Comment by AlexFalappa** [comment]
@neilcsmith-net it seems I cannot tag PRs as well as assign labels or set reviewers as I am not a committer.

I will ask on dev mailing list for someone to review after NB11.1 release, there is no reason to hurry.

**Comment by matthiasblaesing** [comment]
Fix looks sane - the case of names with trailing number was already fixed, but for other cases it might still be worth it.

**Pull request merged**
