### PR TITLE
[NETBEANS-4289] Updated JGit to 5.7.0.202003110725

### PR DESCRIPTION
**Pull request by matthiasblaesing**

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@mcdonnell-john could you please have a look at this? This is essentially the PR you created in the past to bring JGit to 5.7.0. I ran it through the unittests and the only failing unittest I got was broken before and after the change.

**Comment by matthiasblaesing** [comment]
Forget it - there are classloading issues. I suspect this hits a limitation of the osgi support in netbeans.

**Comment by mcdonnell-john** [comment]
Hi @matthiasblaesing,

Yes, I was jus checking this PR to see if you hit the same issues I had.  I struggled to overcome them, so closed my previous PR.

**Comment by matthiasblaesing** [comment]
I'm looking into this further, but if anyone else wants to look into it too, this is the problem:

```
    [junit] Caused: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.internal.storage.file.WindowCache
    [junit] 	at org.eclipse.jgit.internal.storage.file.WindowCursor.<init>(WindowCursor.java:64)
    [junit] 	at org.eclipse.jgit.internal.storage.file.FileObjectDatabase.newReader(FileObjectDatabase.java:37)
    [junit] 	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.newReader(ObjectDirectory.java:1)
    [junit] 	at org.eclipse.jgit.lib.Repository.newObjectReader(Repository.java:243)
    [junit] 	at org.eclipse.jgit.treewalk.TreeWalk.<init>(TreeWalk.java:306)
    [junit] 	at org.netbeans.libs.git.jgit.commands.RemoveCommand.run(RemoveCommand.java:76)
    [junit] 	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:57)
    [junit] 	at org.netbeans.libs.git.jgit.commands.GitCommand$1.run(GitCommand.java:54)
    [junit] 	at java.security.AccessController.doPrivileged(Native Method)
    [junit] 	at org.netbeans.libs.git.jgit.commands.GitCommand.execute(GitCommand.java:54)
    [junit] 	at org.netbeans.libs.git.GitClient.remove(GitClient.java:1080)
    [junit] 	at org.netbeans.modules.git.client.GitClient$44.call(GitClient.java:678)
    [junit] 	at org.netbeans.modules.git.client.GitClient$44.call(GitClient.java:674)
    [junit] 	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1$1.call(GitClient.java:933)
    [junit] 	at org.netbeans.modules.git.client.GitClient$CommandInvoker$1.call(GitClient.java:956)
    [junit] 	at org.netbeans.modules.git.FilesystemInterceptor.runWithoutExternalEvents(FilesystemInterceptor.java:473)
    [junit] 	at org.netbeans.modules.git.Git.runWithoutExternalEvents(Git.java:259)
    [junit] 	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethodIntern(GitClient.java:966)
    [junit] 	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethod(GitClient.java:893)
    [junit] Caused: org.netbeans.libs.git.GitException
    [junit] 	at org.netbeans.modules.git.client.GitClient$CommandInvoker.runMethod(GitClient.java:909)
    [junit] 	at org.netbeans.modules.git.client.GitClient$CommandInvoker.access$300(GitClient.java:869)
    [junit] 	at org.netbeans.modules.git.client.GitClient.remove(GitClient.java:674)
    [junit] 	at org.netbeans.modules.git.FilesystemInterceptor.doDelete(FilesystemInterceptor.java:209)
    [junit] Caused: java.io.IOException
    [junit] 	at org.netbeans.modules.git.FilesystemInterceptor.doDelete(FilesystemInterceptor.java:223)
    [junit] 	at org.netbeans.modules.versioning.DelegatingVCS$4.doDelete(DelegatingVCS.java:284)
    [junit] 	at 
```

**Comment by matthiasblaesing** [comment]
@mcdonnell-john I tracked the problem down into the OSGI runtime. Reading the error message completely would also have helped, but my debugger in the end told me, that the class `javax.management.MalformedObjectNameException` could not be found. Looking at the MANIFEST of the jgit jar, indeed the `javax.management` package is not imported and thus the classes not resolveable. I adjusted the build process to fix the MANIFEST and now the problematic versioning integration test runs green. The travis builds are all green, apart from the Visual Studio Code extension, which I will ignore.

I'm building master with this applied (and the broken terminal modification removed) and will test in real life, a second look/tester would be appreciated though.

**Comment by mcdonnell-john** [comment]
Looks good to me, I tested this PR and it seemed to work properly again.

I'll be honest I don't know much about OSGI, so struggled to work this out.  Just for curiosity, which class were you debugging when you found this error? (If you still remember)

**Review by mcdonnell-john — APPROVED** [review]

**Comment by matthiasblaesing** [comment]
> Looks good to me, I tested this PR and it seemed to work properly again.

Thank you - I'll merge then, if we get it in early, potential regressions can be found in advance before next release.

> I'll be honest I don't know much about OSGI, so struggled to work this out. Just for curiosity, which class were you debugging when you found this error? (If you still remember)

I knew that OSGI ties deep into the classloader infrastructure, but I thought it might be a problem in the code of (java) code of jgit. So I started from the stack trace element:

```
   [junit] Caused: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.internal.storage.file.WindowCache
    [junit] 	at org.eclipse.jgit.internal.storage.file.WindowCursor.<init>(WindowCursor.java:64)
```

I checked out the jgit source code and switched to the 5.7 tag. I set a break point in the constructor of the `WindowCursor` class, as that was the last place where things worked correctly. I single stepped through it, I stepped into the static intializer of `WindowCache` as the `NoClassDefFoundError` came from there.

I then used "Evaluate Expression" to exercise the WindowCache loading manually and the exception reported was more helpful, as it explicitly pointed to the "javax.management.MalformedObjectNameException" not being found. That lead me to look at the OSGI metadata. There the import was missing.

I then remembered, that I had seen, that for jsch the manifest was also added in the build system and used that as a template. The rest was fiddling with ant. Hope that is the info you were interested in.

**Pull request merged**
