### PR TITLE
[NETBEANS-6218] An infinite loop may occur when parsing Groovy sources

### PR DESCRIPTION
**Pull request by ppisl**
The fix and test.

### CODE REVIEW

**Review by sdedic — APPROVED** [review]

**Review by JaroslavTulach — APPROVED** [review]

**Comment by matthiasblaesing** [comment]
@JaroslavTulach @sdedic someone needs to merge this, as the author does not seem to be a committer.
@ppisl I assume, that you read the license headers of the files you modified and created and thus acknowledge, that you are the author of the changes and donate them to the ASF?

**Comment by ppisl** [comment]
I can confirm that I have read the license and I acknowladge that I'm author of these changes and I donate them to the ASF.

**Comment by junichi11** [comment]
@ppisl You are one of the initial committers, I suppose. 
See: 
- https://cwiki.apache.org/confluence/display/incubator/NetBeansProposal
- https://cwiki.apache.org/confluence/display/NETBEANS/Becoming+a+committer

@geertjanw Can @ppisl become a committer yet?

**Comment by ppisl** [comment]
@junichi11 Yes, you are right. Thanks

**Pull request merged**
