### PR TITLE
Sync delivery to master after 24-rc5

### PR DESCRIPTION
**Pull request by ebarboni**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
The conflict is expected and discussed previously with @mbien (somewhere, Slack??)  Need to keep the spec version in master.

We _really_ need to stop having spec version increments in pull requests.  They're already handled in the release process cc/ @dbalek

**Comment by ebarboni** [comment]
what should be done, add new PR to delivery to make the 2 sync PR to be valid?

**Comment by mbien** [comment]
https://github.com/apache/netbeans/pull/8006 an attempt to resolve the conflict without touching delivery.

It clones **delivery** and edits the merge commit so that it is compatible with a merge back to master.

**Comment by ebarboni** [comment]
#8007 is the one :D

**Pull request closed without merging**
