### PR TITLE
Removing delay after launch Project action terminates.

### PR DESCRIPTION
**Pull request by sdedic**
There is a delay between a message is sent to a LSP client that a project Run/Debug action termianted. I've checked the project layer, and it seems that Out/Err streams are closed / flushed before the callback is called. Also Maven implementation seems to finish the output gathering task before declaring the execution complete and so seems Gradle.

So that would allow for a "strawman" fix - just remove the delay. Please review - anyone who remembers why the delay was introduced in the original LSP client implementation. Thanks.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
My approval is just a _process-like approval_. I have no knowledge of the code and technical review must be done by Martin.

**Comment by entlicher** [comment]
I'll need to test this change on the delivery branch with the applied PR to verify that this is fine. I'll do that ASAP. But with this, also please remove the `waitForDebuggeeConsole` variable altogether as it's presence makes no sense any more. And please wait for the delivery branch to be merged as this will cause conflicts.

**Review by entlicher — CHANGES_REQUESTED** [review]
Looks good, we get all the output even when the wait is removed.
But please remove all occurrences of `waitForDebuggeeConsole` and wait for
https://github.com/apache/netbeans/pull/2725 to merge before this so that Neil doesn't get conflicts.

**Comment by sdedic** [comment]
OK, I'll wait for the other PR to merge, then I'll rebase.

**Comment by neilcsmith-net** [comment]
Is this targeted for 12.3 or 12.4? If 12.3 and merging to delivery, feel free to merge #2725 before us if you need to rebase on it.

**Comment by sdedic** [comment]
Rebased on & retargetted to `delivery` branch. Cleaned up `waitForDebuggeeConsole`.

**Review by entlicher — APPROVED** [review]
Great, thanks.

**Review by entlicher — APPROVED** [review]

**Pull request merged**
