### PR TITLE
JS: Improve handling of export declarations (references and classes)

### PR DESCRIPTION
**Pull request by matthiasblaesing**
At least two issues are fixed by this:

- "export class XY" construct is not parsed correctly resulting in
  a JS model for that class, that his missing methods
- "class XY {}; export {XY}" is not correctly parsed resulting missing
  declaration handling for that member

Example that was not correctly parsed:

```javascript
export class test {
	method(param){
		param;
	}
};

// this shows in navigator / highlighting works
class test2{
	method(param){
		param;
	}
}

// no highlighting, Go to declaration does not work
export {test2};
```

Closes: https://github.com/apache/netbeans/issues/5184

### CODE REVIEW

**Review by junichi11 — APPROVED** [review]
Looks good.

Missing a unit test for `GoToDeclarationTest`?

Before:
nb-gh-5796-before

After:
nb-gh-5796-after

nb-gh-5796

**Comment by matthiasblaesing** [comment]
@junichi11 thank you for the review and hint. I added a testcase to the `GoToDeclarationTest`.

**Comment by junichi11** [comment]
Great!

**Comment by matthiasblaesing** [comment]
Tests are green, I'll give a few more days to settle. I'll merge once feedback back from the reporter comes in (test requested via the issue report) or at latest friday.

**Pull request merged**
