### PR TITLE
Kotlin Plugin Donation

### PR DESCRIPTION
**Pull request by SerVB**
This is a follow up of the https://github.com/JetBrains/kotlin-netbeans/issues/137 .

@mglukhikh , @geertjanw

### CODE REVIEW

**Comment by mglukhikh** [comment]
I should mention that we intentionally do not include content of https://github.com/JetBrains/kotlin-netbeans/tree/master/lib folder in this donation. This folder contain jar files built from intellij-community and kotlin project sources. Of course you can use them if you wish, but we can't donate them because they are parts of other JetBrains projects.

Of course it would be much better (in both legal and technical aspects) for these jars not to be stored in the repo directly. I can give some advices how to avoid it (but sorry, can't do it myself due to lack of time):

- intellij-core.jar artifact could be directly taken from here: https://www.jetbrains.com/intellij-repository/releases
- for other artifacts, I recommend to look at https://github.com/JetBrains/kotlin-eclipse project, kotlin-bundled-compiler folder. As I can see it download everything (including even intellij-core) needed via Gradle getBundled task declared at the end of build.gradle. Probably for NetBeans plugin it could be done in the same manner

**Comment by geertjanw** [comment]
Great and many thanks.

**Comment by fwcd** [comment]
What do you think about combining the efforts on building great Kotlin support by focusing on improving the [Kotlin language server](https://github.com/fwcd/KotlinLanguageServer)?

LSP support for NetBeans seems to have been merged recently (#629) and having a well-maintained language server would benefit other editors/IDEs too.

**Comment by jlahoda** [comment]
> What do you think about combining the efforts on building great Kotlin support by focusing on improving the [Kotlin language server](https://github.com/fwcd/KotlinLanguageServer)?
> 
> An LSP client for NetBeans seems to have been merged some time ago (#629) and having a well-maintained language server would benefit other editors/IDEs too.

I think using the LSP server may be a viable alternative, but those who will decide to work on the support for Kotlin in NetBeans will need to decide between two alternatives:
-using the LSP server, which is easier to integrate (the biggest issue will probably be categorizing licenses and finding places from where NB can download the binaries - the NetBeans build likes to download stuff from Maven central, but my understanding is that most of the binaries required here are not in central), the con being that there are limits in how well such integration may work without special tweaks in the IDE. (Like having a Java class referring to a Kotlin class, or support for features that are not supported by the LSP.)

-have a plugin directly in the IDE, where there are no limits on the integration with other features; the obvious con being this is much more work.

**Comment by dejlek** [comment]
Any progress here?

**Comment by geertjanw** [comment]
Nope, though you can take charge, pick it up, engage with the community on the dev mailing list, and make it happen. :-)

**Comment by dejlek** [comment]
I would rather do that with the nbpython plugin...

**Comment by ebarboni** [comment]
Hi, we must go through ip clearance process.
The most paperwork are from donators 
 JetBrains s.r.o should transmit a software agreement https://www.apache.org/licenses/software-grant-template.pdf 
 It's important that each contributor (I hope the list is complete here: https://github.com/JetBrains/kotlin-netbeans/graphs/contributors) also have iCLA  
Workflow may be found over here.
https://www.apache.org/licenses/contributor-agreements.html

Then Apache NetBeans PMC have to vote for accepting code.

Then a lazy vote occurs on incubator list to ip clear.

Regards

**Comment by mglukhikh** [comment]
> Hi, we must go through ip clearance process.
> The most paperwork are from donators
> JetBrains s.r.o should transmit a software agreement https://www.apache.org/licenses/software-grant-template.pdf
> It's important that each contributor (I hope the list is complete here: https://github.com/JetBrains/kotlin-netbeans/graphs/contributors) also have iCLA
> Workflow may be found over here.
> https://www.apache.org/licenses/contributor-agreements.html
> 
> Then Apache NetBeans PMC have to vote for accepting code.
> 
> Then a lazy vote occurs on incubator list to ip clear.
> 
> Regards

Hi Eric, Ok, we will process your request and answer after some time.

**Comment by ebarboni** [comment]
I cannot check all parameters, but I guess a package refactory to org.apache.netbeans (or org.netbeans) will also be needed.

**Comment by mglukhikh** [comment]
@ebarboni Hi, excuse me, do you have an editable version of the software agreement you need? (https://www.apache.org/licenses/software-grant-template.pdf). Our (JetBrains) legal department are now processing it, and they need to change something.

**Comment by mglukhikh** [comment]
Also I cite below the comment from our (JetBrain) legal department about iCLA.

The individual contribution agreements (CLAs) should be modified to reflect that they cover only your contributions to the NetBeans plugin project, not all other contributions you may have made or might make in the future. Apache should be able to narrow it down easily but if not we can help them with the wording provided that we have an editable version of their documentation.

@ebarboni So you or somebody other from Apache could either modify iCLA this way yourself or provide an editable version for us.

**Comment by vieiro** [comment]
Hi @mglukhikh ,
I think you'd better fitted with the Corporate Contributor License Agreement (CCLA). Please see [1].

If you read point number 8. there:

> It is your responsibility to notify the Foundation when any change
is required to the list of designated employees authorized to submit
Contributions on behalf of the Corporation, or to the Corporation's
Point of Contact with the Foundation.

You'll see that JetBrains has the possibility to modify the list of designated employees authorized to submit Contributions on behalf of JetBrans **at any time**. 

So, for instance, JetBrains could authorize you to submit this contribution and once the contribution is made then remove your authorization to submit any futher contributions.

Would that fit JetBrains' Legal needs?

Thanks,
Antonio


[1]
https://www.apache.org/licenses/contributor-agreements.html

**Comment by vieiro** [comment]
Hi @mglukhikh ,

We could find no CCLA or SGA from JetBrains.

The purpose of IP clearance is to make sure that the owners of any IP explicitly grant Apache the rights needed to modify and redistribute the material.

If JetBrains owns all of the IP, then a CCLA or SGA is usually needed. 
- The SGA is typically used if it is a one-time grant. 
- The CCLA is typically used if there will be continuing grants done by employees (named in the CCLA). 

Where there is a small number of people who wrote all of the material, even if the IP is owned by their employer, then having each of them submit an ICLA (which states in section 4 that they have permission of the IP owner to contribute) will suffice. If there are other IP owners of material here, we need another discussion.

To make forward progress, it might be useful for JetBrains to create a new repository containing only the material that they are granting to Apache.

Please feel free to contact the NetBeans PMC with any questions at private@netbeans.apache.org.

Thanks,
Antonio

**Comment by mglukhikh** [comment]
Hi Antonio @vieiro ,

Our legal department is still processing CCLA. I think this process will be finished after the New Year. 

Thanks, Mikhail.

**Comment by mglukhikh** [comment]
Hi, I have just sent CLA & iCLA to private@netbeans.apache.org.

**Comment by Chris2011** [comment]
Hey, what is the state here?

**Comment by mglukhikh** [comment]
> Hey, what is the state here?

+1. Signed documents were sent long ago in January...

**Comment by geertjanw** [comment]
Did you hear back from Apache about it? If not, we can find out. 

Once we’re able to do so, we should create a Kotlin branch on our NetBeans GitHub for the contributed Kotlin code.

**Comment by mglukhikh** [comment]
> Did you hear back from Apache about it? If not, we can find out.

I received only a short e-mail confirming that documents arrived to Apache, nothing else.

**Comment by geertjanw** [comment]
That's all that you need, great. The documents have been received, there are no objections, so we can go ahead and create a branch with your code -- do you foresee any problems with it, how solid is it in your opinion?

**Comment by mglukhikh** [comment]
I'd say that when you are doing something first time, you almost always have some problems. This code will definitely need some attention, see e.g. issues in https://github.com/JetBrains/kotlin-netbeans/issues.

**Comment by asbachb** [comment]
I wonder if there's any status update and/or if someone is working on this and/or the issues @mglukhikh mentioned is blocking getting this into NetBeans.

**Comment by mglukhikh** [comment]
I just don't know. I was asked about CLA & iCLA, well, we have signed & sent them in the beginning of 2020.

**Comment by Chris2011** [comment]
Maybe we should ask @SerVB here. I mean there is still a branch at his repo as far as I can see. The thing is what needs to be done to merge this into master. I think we should not merge this into master until it is stable to use. My 2 cents.

**Comment by SerVB** [comment]
Sorry, I've just opened the PR to the apache/netbeans repo – my work starts and ends here.

We haven't been asked and haven't planned to make this plugin "stable to use" before merging. That's the idea – we just donate it as is. We hope the new owner will make the plugin working and stable again. I think we've done anything that's required from our side.

**Comment by SerVB** [comment]
Probably we should try to ask @geertjanw because he asked the initial question here: https://github.com/JetBrains/kotlin-netbeans/issues/137#issue-438694751

**Comment by neilcsmith-net** [comment]
Agree with @Chris2011 that it probably shouldn't be merged to master until stable to use (although could be left out of builds). Suggest we need a person or persons who have an interest to take ownership, set up a kotlin branch here, and change the base branch for the PR.  Probably worth asking about that / galvanising action on dev@ otherwise it's probably going to keep sitting here.

**Comment by hectorespert** [comment]
I created a new branch called `kotlin-donation` on Netbeans project. 
If there isn't any objection, I will merge this PR in that branch.

**Comment by dayron9110** [comment]
Any update?

**Comment by jkost** [comment]
Thank you for your reply @SerVB. Since it is not a good idea to pollute the NetBeans (or any) repository with binaries, I instead modified the `pom.xml` like so:

- removed all the jars from `<build><executions>`
- applied what is mentioned [here](https://kotlinlang.org/docs/maven.html)

but then I get a number of unresolved references in kotlin code, like e.g.:

```
--- kotlin-maven-plugin:1.5.31:compile (compile) @ kotlin.netbeans.plugin ---
/Projects/netbeans/netbeans/contrib/kotlin/src/main/java/org/jetbrains/kotlin/completion/KotlinCompletionProposal.kt: (66, 44) Unresolved reference: rawCommentText
/Projects/netbeans/netbeans/contrib/kotlin/src/main/java/org/jetbrains/kotlin/completion/KotlinKeywordCompletion.kt: (39, 66) Unresolved reference: INNER_CLASS
/Projects/netbeans/netbeans/contrib/kotlin/src/main/java/org/jetbrains/kotlin/completion/KotlinKeywordCompletion.kt: (278, 63) Unresolved reference: possibleParentTargetMap
/Projects/netbeans/netbeans/contrib/kotlin/src/main/java/org/jetbrains/kotlin/completion/KotlinKeywordCompletion.kt: (281, 65) Cannot access 'deprecatedParentTargetMap': it is private in 'ModifierCheckerCore'
/Projects/netbeans/netbeans/contrib/kotlin/src/main/java/org/jetbrains/kotlin/completion/completionUtils.kt: (96, 22) Unresolved reference: isVisibleWithAnyReceiver
....
```
and many many others which I 'm not sure if they are due to the kotlin version (1.5.31) or to something else (I 'm new to kotlin).

**Comment by ebresie** [comment]
Are any of the dependencies found here?

https://mvnrepository.com/artifact/org.jetbrains.kotlin

**Comment by devMls** [comment]
Maybe for NetBeans 16?

**Comment by xhevahir** [comment]
Seems like a functioning Kotlin plugin might be a good way to bring in more users (if indeed they're wanted). Netbeans came in first in the StackOverflow survey's Most Dreaded IDE category:  https://survey.stackoverflow.co/2022/?utm%5C_source=so-owned&utm%5C_medium=announcement-banner&utm%5C_campaign=dev-survey-2022&utm%5C_content=results#section-most-loved-dreaded-and-wanted-integrated-development-environment

**Comment by jkost** [comment]
> Are any of the dependencies found here?
> 
> https://mvnrepository.com/artifact/org.jetbrains.kotlin

Unfortunately not. As explained in the [wiki](https://cwiki.apache.org/confluence/display/NETBEANS/Kotlin+plugin), there is already an editor that recognized .kt file if you switch to 'kotlin-donation' branch.

**Comment by sndcrde** [comment]
> Ioannis (John) Kostaras has managed to resolve the maven dependencies.

Is it versioned somewhere (I mean the code with resolved dependencies) and, if so, can you post a link to it?

> there is already an editor that recognizes .kt files.

What good does it really do? Can you compile Kotlin files in NB? Can compiler errors be easily traced back to the source? Anyhow, please post a link to that editor.

Regards,

**Comment by devMls** [comment]
I agree with @jkost . Kotlin Will be a Big annunce yo the ide

**Comment by jkost** [comment]
Please see this page
<https://cwiki.apache.org/confluence/display/NETBEANS/Kotlin+plugin> for
more information.

Regarding the original plugin <https://github.com/JetBrains/kotlin-netbeans>
donated by JetBrains, help is needed to fix the bugs in the Kotlin code.
Anyone fluent in Kotlin that could help?

Regarding the Kotlin support that can already be found under contrib folder
of NetBeans, more work is required. What you can do with it is already
described in the above page. This page
<https://cwiki.apache.org/confluence/display/NETBEANS/Adding+New+Language+Support>
is also useful.

**Comment by jkost** [comment]
Hello again,

the Kotlin editor (using TextMate language support) can be found here
<https://github.com/apache/netbeans/tree/kotlin-donation/java/kotlin.editor>.
The JetBrains contribution (JavaCC) can be found here
<https://github.com/apache/netbeans/tree/kotlin-donation/contrib/kotlin>. I
will push my progress to my personal git repo in order not to pollute the
NetBeans repo.

Thanks.

John.

**Comment by jkost** [comment]
It seems that the only thing I must have done (it was sometime ago) was to
follow the JetBrains' guys advice and update my local maven repo with the
dependencies from the kotlin-eclipse plugin (see this thread
<https://github.com/apache/netbeans/pull/1398>) as I don't see and local
commits or changed files from my side.

Here are only a few of the compiler errors I see when I maven build the
plugin.

Module name is kotlin.netbeans.plugin
Supertypes of the following classes cannot be resolved. Please make sure
you have the required dependencies in the classpath:
    class org.jetbrains.kotlin.installer.Yenta, unresolved supertypes:
ModuleInstall
    class org.jetbrains.kotlin.filesystem.KotlinVirtualSourceProvider,
unresolved supertypes: VirtualSourceProvider

kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(19, 29) Unresolved reference: util
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(20, 29) Unresolved reference: util
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(21, 29) Unresolved reference: vfs
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(22, 21) Unresolved reference: psi
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(23, 21) Unresolved reference: psi
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(32, 29) Unresolved reference: idea
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(33, 29) Unresolved reference: idea
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(35, 29) Unresolved reference: psi
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(36, 21) Unresolved reference: api
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(37, 21) Unresolved reference: api
kotlin-netbeans/src/main/java/org/jetbrains/kotlin/builder/KotlinPsiManager.kt:
(38, 12) Unresolved reference: openide
....

I would propose to use the #plugin-developers slack channel to provide
support to those who wish to help resolve these issues on how to build the
java part and then concentrate on the kotlin part.

Kind regards,

John.

**Comment by bdrx312** [comment]
I was looking to use gradle with netbeans, but want to kotlin to have statically type configuration instead of groovy. Having a kotlin plugin in order to better use gradle in netbeans would be useful. Did netbeans ever get a functioning kotlin plugin?

**Comment by jkost** [comment]
Please look at the current status here
<https://cwiki.apache.org/confluence/display/NETBEANS/Kotlin+plugin>.

K/r,

John

**Pull request merged**
