### PR TITLE
WIP: Removed primitive wrapper constructor calls from the platform cluster

### PR DESCRIPTION
**Pull request by lkishalmi**

### CODE REVIEW

**Comment by mbien** [comment]
I went through the commits and it looks good to me.
 
Do you think there is a chance to rebase this? Would be nice to get this in early for NB 13 to avoid it conflicting again. This would fix a lot of deprecation warnings.

**Comment by mbien** [comment]
@lkishalmi this has only one small conflict. Could you rebase this so we can merge it? Even if this PR is still wip, it does not have to cover all cases, other PRs can deliver the rest incrementally.

**Comment by lkishalmi** [comment]
Well, there is another problem with this PR. It breaks the unit tests.
Especially the clipboard related ones.
Anyway, I'm going to rebase this.

**Comment by mbien** [comment]
travis has the following tests failing atm (might be all lookup related):

```
org.netbeans.jellytools.QuestionDialogOperatorTest

    failed: testConstructorWithParameter name
    
org.netbeans.core.windows.services.DialogDisplayer128399Test

    failed: testDefaultOptionWithStandardOk
    
org.openide.util.lookup.AbstractLookupArrayStorageTest

    failed: testReplaceByEqualInstance name

org.openide.util.lookup.AbstractLookupExecutorTest

    failed: testReplaceByEqualInstance name

org.openide.util.lookup.AbstractLookupTest

    failed: testReplaceByEqualInstance name

org.openide.util.lookup.ExcludingLookupTest

    failed: testReplaceByEqualInstance name

org.openide.util.lookup.LookupsProxyTest

    failed: testReplaceByEqualInstance name

org.openide.util.lookup.ProxyLookupTest

    failed: testReplaceByEqualInstance name

org.openide.util.lookup.ProxyProxyLookupTest

    failed: testReplaceByEqualInstance name

org.openide.util.lookup.SimpleProxyLookupIssue42244Test

    failed: testReplaceByEqualInstance name
```

**Comment by mbien** [comment]
the lookup tests use Integers for object equality/identity checks. Its probably better to revert them since any replacement of `new Integer` will likely break them. They have to be rewritten using something which isn't a cached number (e.g BigInteger or a proper test object with equals/hashcode etc implemented).

**Comment by lkishalmi** [comment]
Closing in favor of #3656

**Comment by BradWalker** [comment]
Hey @lkishalmi , your work was good. But, more encompassing than what I was working on.

Okay with you if I pick up where you stopped and moved forward with it?

**Comment by lkishalmi** [comment]
That's fine for me. I'm not planning to work on this anytime soon. I have 2-3 new Gradle stuff in my queue I would like to focus on.

**Pull request closed without merging**
