### PR TITLE
Refresh unloadable Gradle/Maven project after successful build

### PR DESCRIPTION
**Pull request by JaroslavTulach**
Continuation of #2464 - once a build on unloadable Gradle project successfully finishes, then let's schedule a reload to bring the module to loadable state:
* opening unloadable project shall show a fix https://user-images.githubusercontent.com/26887752/96404352-fff94100-11da-11eb-931b-d6cdcbf1ed95.png 
* after invoking it, the build is started
* when finished, the project is refreshed

Ideally the fix disappears and one can invoke "Start Debugging".

### CODE REVIEW

**Review by lkishalmi — CHANGES_REQUESTED** [review]
Well, let's talk about this one.
The functionality you are looking for is there. Through it is provided by using actions, more properly ActionMapping-s. It is not the duty of the executor to re-evaluate the internal GradleProject structure, that is decided at around:
https://github.com/apache/netbeans/blob/0ec46b545cc9d1f1b5649fa2fbb735bf9dc56aa3/extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java#L243

Also if you're using the built-in actions, make sure that the project is opened, that's the only way to set the NbGradleProjectImpl's AimedQuality property to FULL, which means it can turn to Gradle to fetch the information. (though if this patch is working, that means the project aims are higher than FALLBACK)

**Comment by JaroslavTulach** [comment]
OK, I'll investigate the `getReloadRule()` and why it is not in action in my case.

**Comment by JaroslavTulach** [comment]
The problem with the current approach is that the
```
     task.addTaskListener((Task t) -> {
                try {
                    OutputWriter out1 = task.getInputOutput().getOut();
                    boolean canReload = project.getLookup().lookup(BeforeReloadActionHook.class).beforeReload(action, outerCtx, task.result(), out1);
                    if (needReload && canReload) {
                        String[] reloadArgs = RunUtils.evaluateActionArgs(project, mapping.getName(), mapping.getReloadArgs(), outerCtx);
                        prj.reloadProject(true, maxQualily, reloadArgs);
                    }
                    project.getLookup().lookup(AfterBuildActionHook.class).afterAction(action, outerCtx, task.result(), out1);
                    for (AfterBuildActionHook l : context.lookupAll(AfterBuildActionHook.class)) {
                        l.afterAction(action, outerCtx, task.result(), out1);
                    }
                } finally {
                    task.getInputOutput().getOut().close();
                    task.getInputOutput().getErr().close();
                }
            });
```
code is invoke too late!

I'd like the reload of the project to happen immediately after the build is over. However the task listener is notified tens of seconds later.

**Comment by JaroslavTulach** [comment]
d7d4faf comes with a solution that (tries to) honor the existing `getReloadRule()`. As soon as the build succeeds, the `ExecutorTask` wrapper listeners are notified and may immediately refresh the build state.

Btw. the refresh is also made synchronous and only then the build is claimed to be over.

**Review by lkishalmi — APPROVED** [review]
Let's give it a go! Thank you!

**Comment by JaroslavTulach** [comment]
Thanks Laszlo, however I have added few more changes meanwhile, so let's review again:
* support for `ActionProgress` added to Gradle project, that's for @lkishalmi to review
* `java.lsp.server` modified to invoke `BUILD` when the project seems misconfigured - a bit of `CompletableFuture` for @sdedic and @entlicher 
* Maven project changes to refresh its state before build is over to be consistent with Gradle.

With these changes running VSCode "Start Debugging" on broken Gradle (just create new project) and broken Maven (remove some `.m2/repository` entries) seems to work.

**Review by entlicher — APPROVED** [review]
The changes look fine to me. Thanks.

**Comment by JaroslavTulach** [comment]
OK, let's try. Everything is green (except on `java.hints` batch), so I assume the change passes existing tests. Let's integrate.

**Pull request merged**
