### PR TITLE
Fixes wrong detection message when selecting a GF6.2 location.

### PR DESCRIPTION
**Pull request by nicolaken**
When adding a new server, after selecting "Glassfish Server" and pressing next, when selecting an install location, the GUI searches for a valid instance by comparing all possible instances (versions) with the one found in the location specified.

```
org.netbeans.modules.glassfish.common.wizardsServerWizardIterator::isValidInstall
org.netbeans.modules.glassfish.common.ServerDetails::isInstalledInDirectory
```

If the Glassfish version is 6.2, it shows it has found 6.1, but then goes on with the 6 version, as the 6.1 instance says it's 6.

`org.netbeans.modules.glassfish.common.ServerDetails::getVersion`

Now 6.1 says it's 610 and 6.0 says it's 600 as other versions do.

Fixes small bug in Jakarta EE 9 GlassFish 6 Support (#2902).

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Base branch for this should be `delivery` not `release125` - can be edited above.

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me. @juneau001 could you please also have a look?

**Comment by juneau001** [comment]
Built and tested successfully.  Thanks for the PR!

**Comment by matthiasblaesing** [comment]
@juneau001 thanks for the check
@nicolaken thank you for the fix

Lets get this into delivery.

**Pull request merged**
