### PR TITLE
reintroduce getallmavencoordinates

### PR DESCRIPTION
**Pull request by ebarboni**
Removed this target as I though it was no more used but it allow to shorten the external artefacts

### CODE REVIEW

**Review by neilcsmith-net — APPROVED** [review]

**Review by mbien — APPROVED** [review]

**Comment by neilcsmith-net** [comment]
btw. I assume this should be targetted at `delivery`?

**Comment by mbien** [comment]
yes, this has to be delivery, otherwise rc2 jenkins build will have those exceptions too:
```
[ERROR] 
java.nio.file.NoSuchFileException: /home/jenkins/jenkins-agent/workspace/netbeans-TLP_netbeans_release150/build-release-temp/nbbuild/build/external.info
    at sun.nio.fs.UnixException.translateToIOException (UnixException.java:92)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:111)
    at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:116)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel (UnixFileSystemProvider.java:219)
    at java.nio.file.Files.newByteChannel (Files.java:371)
    at java.nio.file.Files.newByteChannel (Files.java:422)
    at java.nio.file.spi.FileSystemProvider.newInputStream (FileSystemProvider.java:420)
    at java.nio.file.Files.newInputStream (Files.java:156)
    at java.nio.file.Files.newBufferedReader (Files.java:2839)
    at java.nio.file.Files.readAllLines (Files.java:3330)
    at java.nio.file.Files.readAllLines (Files.java:3370)
    at org.apache.netbeans.nbm.repository.PopulateRepositoryMojo.findExternal (PopulateRepositoryMojo.java:974)
(...)
```

**Comment by neilcsmith-net** [comment]
Changed the base branch.  Looks OK to me.  @ebarboni please double check and merge.

**Comment by ebarboni** [comment]
sorry github error on PR, I've checkout -b base on delivery

**Pull request merged**
