### PR TITLE
Entities from Database: Improve DB connection selection

### PR DESCRIPTION
**Pull request by matthiasblaesing**
- local DB connections can always be selected, independently of the state of support of the JakartaEE server

- if the project supports a JPADataSourcePopulator, the server based selection dialog is always visible and not only visible on explicitly supported JakarrtaEE servers

image

image

image

Closes: #3813

### CODE REVIEW

**Comment by akaouane** [comment]
When I do :

1 - "Create new entity class from database" 
2 - Select "Server data source"
3 - New data source (for example 'myDS')

The data source 'myDS' is created and appear in the list but with no effect.
That means no table is showed in the list.

But if I close NB and Open it and Do :

1 - "Create new entity class from database" 
2 - Select "Server data source"
3 - Select 'myDS'

The tables appear in the list.

**Comment by akaouane** [comment]
When I try to create "New Jsf page from entity class", I get all entity class created by the older projects even if they are not in the current project.

**Comment by matthiasblaesing** [comment]
@akaouane I think you are mixing issues here and that does not help to get things fixed. I tested your first case and it worked as it should. I used Glassfish 5.1.0 and a freshly generated Maven Jakarta EE 11 Web project. It also worked with GF 7.0.11 and a maven jakarta EE 10 project.

There seem to be issues when refreshing classes (this is what happens when you select a table that is already mapped) for some of the generated methods, but that is a different problem.

**Comment by akaouane** [comment]
@matthiasblaesing I think I am not mixing issues because both are related to the "Entities from Database" and "Jsf Pages from Entities".
Any way, thank you for your remarque.
For my case I used NB 20 and GF 7.0.11 and I get those issues.

**Comment by matthiasblaesing** [comment]
@akaouane and everything is related to java the language, yet you don't report the issues to Oracle/OpenJDK. I bet there is a huge number of issues here, but they are separate issues. If you want to prove me wrong, create a reproducible testcase, that shows the problem, because else the answer will always be "works for me". The testcase can be manual, but it must start from a common ground, like fresh glassfish installation and NetBeans with a fresh userdir.

**Pull request merged**
