### PR TITLE
[NETBEANS-5499] Upgrade Felix library, works on JDK16.

### PR DESCRIPTION
**Pull request by sdedic**
I have tried Felix 7.0.0 with a minimal application and it seems that URL handling is fixed.

### CODE REVIEW

**Comment by sdedic** [comment]
Recommitted with the necessary `project.{xml,properties}` changes. Sorry for the inconvenience.

**Comment by JaroslavTulach** [comment]
```
Test org.netbeans.core.netigso.EnabledAutoloadTest FAILED
```

**Review by JaroslavTulach — APPROVED** [review]
Once the tests pass, feel free to integrate.

**Comment by sdedic** [comment]
Had to upgrade OSGi as well, Felix 7.0 seems to require OSGI 8 core. `osgi-cmp` remains at 7.0 (Compendium 8.0 spec is still draft) while `osgi-core` 8.0 was released in December 2020.

Please re-review.

**Review by JaroslavTulach — APPROVED** [review]
Would having a test failing on JDK16 before and succeeding with this change be beneficial?

**Comment by sdedic** [comment]
> Would having a test failing on JDK16 before and succeeding with this change be beneficial?

Can you suggest how to proceed with such test implementation ? i.e. two variants of the Felix (OSGi ?) library wrapper modules - how ? Or some simpler way ?

**Comment by JaroslavTulach** [comment]
> Can you suggest how to proceed with such test implementation ? ... Or some simpler way ?

The problems only appears on JDK16, right? We should have JDK16 gate running commit validation and failing with some older commit like 5a9c949e8e4e282 - then apply this PR and the gate starts passing. Simple.

**Comment by geertjanw** [comment]
Is this ready to merge, for 12.4 inclusion, please do so if so @JaroslavTulach @sdedic.

**Comment by sdedic** [comment]
@jtulach I have modified a `commit-validation` test to parse an URL - which (on my machine) fails on JDK16 without the felix change. But I failed to enable `commit-validation` testsuite on JDK16. At least locally, I need a ton of `--add-opens` (copied from `etc/netbeans.conf`) and even then a consistency test fails:
```
Some files do not provide valid menu elements[ File MultiFileObject@115e5315[Toolbars/Memory/org-netbeans-modules-timers-OpenTimeComponentAction.shadow] does not provide correct instance: java.lang.Object@739d42c5 url: nbfs://nbhost/SystemFileSystem/Toolbars/Memory/org-netbeans-modules-timers-OpenTimeComponentAction.shadow]
```

**Review by geertjanw — APPROVED** [review]

**Comment by sdedic** [comment]
@geertjanw  there was a real travis failure before the last push (that's why I recommitted the changes). Please let the builds for PRs to finish / settle ... I hope the master won't be broken :)

**Comment by geertjanw** [comment]
OK. Delivery branch exists. Please say when you're happy and will then continue the process.

**Pull request merged**
