### PR TITLE
[NETBEANS-1936] Version splitting Testcode

### PR DESCRIPTION
**Pull request by gbrinkmann**
test method testSplitting added

see https://github.com/apache/netbeans/pull/1244

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
As this is a followup for #1244, this commit should be part of that PR (you can update the PR by cherry picking this commit into the branch, that backs the PR and push it.

**Comment by gbrinkmann** [comment]
Thank you.
As this is my first contribution, I've edited these two fragments on github (and should learn better how to work with branches and pull requests).
I cannot cherry pick on github, right?

**Comment by matthiasblaesing** [comment]
You can update PRs by pushing new commits into the branch that was used to create the PR. That even works if you force-push. In your checkout do this:

```shell
# switch to patch-1 branch
git checkout patch-1
# cherry-pick the tests into this branch
git cherry-pick 8becb206246d4b01dd18095d50621acb150a3a82
# Run unittests and see if everything works
# Push updated branch - this assumes your first push of patch-1 set the github branch as upstream
git push
```

On github you will now see two commits in the "Commits" tab. By this time you can close #1248 as the code lives in this PR.

**Comment by gbrinkmann** [comment]
cherry picked to patch-1, closing.

**Pull request closed without merging**
