### PR TITLE
Enabling the scripting.sh tests in travis

### PR DESCRIPTION
**Pull request by JaroslavTulach**
Trying to understand what's the probilem with `scripting.sh` tests.

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
The failure seems to be
```
Testcase: testEngine(org.netbeans.core.network.proxy.pac.PacEngineTest):	FAILED

expected:<[DIRECT]> but was:<[HTTP @ myIpAddress:1]>
junit.framework.AssertionFailedError: expected:<[DIRECT]> but was:<[HTTP @ myIpAddress:1]>
  at org.netbeans.core.network.proxy.pac.PacEngineTest.testPacFile2(PacEngineTest.java:105)
  at org.netbeans.core.network.proxy.pac.(PacEngineTest.java:76)
  at org.netbeans.junit.NbTestCase.access$200(NbTestCase.java:77)
  at org.netbeans.junit.NbTestCase$2.doSomething(NbTestCase.java:460)
  at org.netbeans.junit.NbTestCase$1Guard.run(NbTestCase.java:386)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by matthiasblaesing** [comment]
Just an idea: if I remember correctly, the build script modifies the proxy settings - could this interfere with the test?

**Comment by blackleg** [comment]
Could it be related to a problem with OpenJDK? https://github.com/apache/netbeans/pull/1296

**Comment by JaroslavTulach** [comment]
My Ubuntu returns `dellxps/127.0.1.1` (the value I have in my `etc/hosts`) as the `myIpAddressEx()`. The builder machine returns `localhost/127.0.0.1`. The `PacEngineTest` then breaks. I believe the test is buggy, but I haven't yet understood the code to be sure.

**Comment by blackleg** [comment]
I can reproduce the same error that appears in a Travis build in an Ubuntu 16.04 VM.
```
------------- ---------------- ---------------
Testcase: testEngine(org.netbeans.core.network.proxy.pac.PacEngineTest):	FAILED
expected:<[DIRECT]> but was:<[HTTP @ myIpAddress:1]>
junit.framework.AssertionFailedError: expected:<[DIRECT]> but was:<[HTTP @ myIpAddress:1]>
	at org.netbeans.core.network.proxy.pac.PacEngineTest.testPacFile2(PacEngineTest.java:105)
	at org.netbeans.core.network.proxy.pac.PacEngineTest.testEngine(PacEngineTest.java:76)
	at org.netbeans.junit.NbTestCase.access$200(NbTestCase.java:77)
	at org.netbeans.junit.NbTestCase$2.doSomething(NbTestCase.java:460)
	at org.netbeans.junit.NbTestCase$1Guard.run(NbTestCase.java:386)
	at java.lang.Thread.run(Thread.java:748)
```

The  `/etc/hosts` file in my vm was like this:
```
127.0.0.1	localhost
127.0.1.1	netbeans

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
The localhost is the first entry in the file and I changed the order of the hosts entries in the file setting the localhost entry after the hostmane entry.
```
127.0.1.1	netbeans
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Seems that Travis environment define the localhost entry is the last entry in the `/etc/host' file when it is generated.
```
$ cat /etc/hosts

## Managed by Chef on packer-5d50120d-4b05-ab59-5515-59dd47766322.c.eco-emissary-99515.internal :heart_eyes_cat:

## cookbook:: travis_build_environment

##     file:: templates/default/etc/cloud/templates/hosts.tmpl.erb

127.0.1.1 travis-job-3c6e8424-4231-4d1e-9363-09717682cdc2 travis-job-3c6e8424-4231-4d1e-9363-09717682cdc2 ip4-loopback xenial64

127.0.0.1 localhost nettuno travis vagrant travis-job-3c6e8424-4231-4d1e-9363-09717682cdc2  netbeans
```

**Comment by eirikbakke** [comment]
Not very farmiliar with either Travis nor the PAC firewall code. Is this a test that's supposed to be able to run even with no internet connection?

**Comment by lkishalmi** [comment]
Restarted failing Travis jobs to see if it passes now. One issue was the usual hibernate dependenct, I haven't checked the other.

**Comment by matthiasblaesing** [comment]
_No_ hibernate is not (as was never) the issue of unittest failures. I wager you mean this message:

```
 Scanning for modules in /home/matthias/src/netbeans
[insert-module-all-targets] Cannot find build prerequisite org.netbeans.modules.hibernate of /home/matthias/src/netbeans/contrib/hibernateweb
```

This is always there (at least for two years) since hibernate was removed. It can be easily fixed by removing hibernateweb from contrib or reincluding hibernate into contrib. It is just normaly not in the focus because the netbeans build is chatty as hell. It would be great if everybody could stop jumping to this conclusion.

**Comment by blackleg** [comment]
@JaroslavTulach @matthiasblaesing I created a script to modify Travis instance `/etc/hosts` file and it allow we to run core network module tests. See this PR: https://github.com/apache/netbeans/pull/1773

**Comment by matthiasblaesing** [comment]
After the merge of #1748 I think this can be closed.

**Comment by JaroslavTulach** [comment]
Yes, I think this one is now obsolete.

**Pull request closed without merging**
