### PR TITLE
Fix java/j2ee.persistence test and add it to build pipeline

### PR DESCRIPTION
**Pull request by matthiasblaesing**

### CODE REVIEW

**Comment by mbien** [comment]
cool! Should we move this down to the enterprise job?

The java job is quite long already and I believe enterprise would also fit better for `j2ee.*` tests.

**Comment by matthiasblaesing** [comment]
I have mixed feelings here. I agree, that when I read JPA, I immediately think JakartaEE, but JPA is perfectly capable of running standalone. What is more, contrary to many `j2ee.*` modules, `j2ee.persistence` is part of the `java` cluster, not the `enterprise` on. That is the reason I added it to the java set of test.

But I have no strong feelings here and can move.

**Comment by matthiasblaesing** [comment]
@pepness you might also want to have a look. From my POV this was just a typo in the tests added in 6f869f28eaedd456c40e47b2fefdefee45310aac. Apart from fixing that, this PR just wires the tests to be run as part of the CI/CD pipeline.

**Comment by mbien** [comment]
> I have mixed feelings here. I agree, that when I read JPA, I immediately think JakartaEE

If this would intuitively cause someone to set the enterprise or Jakarta label -> it would work as intended I think.

> What is more, contrary to many j2ee.* modules, j2ee.persistence is part of the java cluster, not the enterprise on. That is the reason I added it to the java set of test.

The `Java Modules` job is a little bit of a catch-all job at the moment and is together with PHP the longest job with >40mins runtime. The `Enterprise` job is at 10 mins for comparison.

I was looking at it a bit from the load balancing perspective - I do also not feel strongly about it.

**Comment by matthiasblaesing** [comment]
@mbien valid points. Test is moved.

**Review by mbien — APPROVED** [review]

**Pull request merged**
