### PR TITLE
NETBEANS-876: Made the default userdir to 9.0, and removed -J-ea from the command line

### PR DESCRIPTION
**Pull request by lkishalmi**
Partial work for NETBEANS-876 issue related with the startup script.
Userdir and cache now points to 9.0 instead of dev.
Assertions has been disabled.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
The change looks reasonable. @jkovalsky @geertjanw @jlahoda you have more experience with the release process of netbeans in the past - is this in line with it?

**Comment by emilianbold** [comment]
It would be nice if netbeans_default_options would be on multiple lines. Really hard to notice from the diff what was changed.

**Comment by lkishalmi** [comment]
That's possible on Linux, though I do not know whether the Windows Launcher is capable to parse the conf-file in that case.

**Comment by matthiasblaesing** [comment]
My reading of the config file parser (`/ide/launcher/windows/nblauncher.cpp`) is, that does not allow multiline options (see the use of `fgets` in line 448).

**Comment by emilianbold** [comment]
> That's possible on Linux, though I do not know whether the Windows Launcher is capable to parse the conf-file in that case.
> My reading of the config file parser (/ide/launcher/windows/nblauncher.cpp) is, that does not allow multiline options (see the use of fgets in line 448).

Too bad, it would have made the file more readable imho.

Anyhow, +1 on the PR.

**Pull request merged**
