### PR TITLE
Upgrade Gradle Tooling API to 8.10

### PR DESCRIPTION
**Pull request by mbien**
- full JDK 23 support
 - https://docs.gradle.org/8.10/release-notes.html

### CODE REVIEW

**Comment by sid-srini** [comment]
Hi @mbien. I was wondering if this PR is ready for review or do you expect more changes? Would this be planned for NB23 delivery? Thanks.

**Comment by mbien** [comment]
> Hi @mbien. I was wondering if this PR is ready for review or do you expect more changes? Would this be planned for NB23 delivery? Thanks.

@sid-srini this PR wasn't picked up for NB 23 so it is likely going to end up in NB 24 or closed.

I posted two mails to the dev list when I opened the maven/gradle PRs:
https://lists.apache.org/thread/4pswdxf89szssxjsck95jgj0dj3ydhf4 (maven, https://github.com/apache/netbeans/pull/7683)
https://lists.apache.org/thread/w53t2240ny5lzpfypm6bc5bm6gw833zm (gradle, this PR)

the way I understand this is that the gradle tooling upgrade is not technically needed since the gradle project init script is already using "newest", which should init with the latest available wrapper. However I never could get this to work (it always picked 8.9), others reported that it does work though.

**Comment by sid-srini** [comment]
Thanks @mbien for the delivery references.
> 
> the way I understand this is that the gradle tooling upgrade is not technically needed since the gradle project init script is already using "newest", which should init with the latest available wrapper. However I never could get this to work (it always picked 8.9), others reported that it does work though.

- Your PR does work for me.
    - When I created a new project with this in place, the gradle wrapper set up contains the `distributionUrl` for gradle-8.10-bin in the *gradle-wrapper.properties*; instead of the previous version.
    - An older existing project, on the other hand, continued to use the previous version of gradle that was configured in it.
    - In terms of Java toolchain support for version 23, gradle 8.10 was able to understand the version number, and auto-download some version of JDK 23 (in concert with the foojay plugin).
    - On the other hand, gradle 8.9 was unable to do so and gave an error.
- I expect that it would work for others too in the same way.
- So, I urge you to submit this PR for review and not close it. :)

Thank you.

**Comment by mbien** [comment]
> When I created a new project with this in place, the gradle wrapper set up contains the distributionUrl for gradle-8.10-bin in the gradle-wrapper.properties; instead of the previous version.

yep. but in theory this should already happen with NB 22. (it didn't work for me either, but others claimed that it does work)

https://github.com/apache/netbeans/blob/c934998bdaf751819d75ad4d097b40cfea9caf86/extide/gradle/src/org/netbeans/modules/gradle/spi/newproject/GradleInitWizard.java#L210

it tells gradle to use the latest available wrapper

**Comment by mbien** [comment]
due to popular demand I rebased this on top of delivery in case there is spare capacity to review this for NB 23 - if not I can move it back to master/NB24 - no problem.

PR produces a dev build for convenient testing.

**Comment by mbien** [comment]
@sid-srini has any testing been done with the patch outside quick checks if new-project init works on JDK 23?

**Comment by sid-srini** [comment]
> @sid-srini has any testing been done with the patch outside quick checks if new-project init works on JDK 23?

Yes, I have checked the following with NB running on both JDK 22 and 23:
    - New project init
    - Project loading
    - Clean, Compile and Run the app
    - Basic code editing, quick fixes and refactoring.
    - Using some locally available external libraries in the project.

> > When I created a new project with this in place, the gradle wrapper set up contains the distributionUrl for gradle-8.10-bin in the gradle-wrapper.properties; instead of the previous version.
> 
> yep. but in theory this should already happen with NB 22. (it didn't work for me either, but others claimed that it does work)
> 

This did not work for me either. I got the following results for the gradle versioned link that is stored in the wrapper on init:
1. With NB 22: gradle-8.7-bin
2. With the rc1 PR #7583: gradle-8.9-bin
3. With this PR: gradle-8.10-bin

**Comment by ebarboni** [comment]
LGTM

**Comment by mbien** [comment]
@sid-srini thanks a lot for the info! It helps to know what has been tested in such last-minute PRs.

**Comment by MartinBalin** [comment]
sdedic is on vacation this afternoon. Seeing he did not objected and was on PR for a while I think it is OK to merge to NB23. So merge it

**Comment by neilcsmith-net** [comment]
One (small?) problem with this update is that the wizard now defaults to JDK 23, which then takes a while downloading a JDK via Disco without much feedback.  Probably not a showstopper for NB24, and mainly the behaviour that was already there, but the wizard should probably default to the running JDK if possible in NB24?

**Comment by mbien** [comment]
I think what it could do is to indicate if it will dl a JDK or not. User can decide what to do. The default of Java 23 (essentially latest known) is probably fine for NB 23 since it overlaps with JDK 23 GA. (also note that the draft of the NB download page does also mention JDK 23 as supported runtime JDK https://github.com/apache/netbeans-antora-site/pull/29)

I vaguely remember pointing out that gradle simply downloading stuff without asking is probably not ideal on the PR which implemented this.

**Pull request merged**
