### PR TITLE
[NETBEANS-5338] Updated link to issue reporting

### PR DESCRIPTION
**Pull request by KacerCZ**
https://issues.apache.org/jira/browse/NETBEANS-5338

Link points to same URL as menu action Help > Report Issue.

### CODE REVIEW

**Comment by KacerCZ** [comment]
@geertjanw @neilcsmith-net Please consider this change for 12.3.

**Comment by neilcsmith-net** [comment]
Thanks. Good if we also update the redirects at https://github.com/apache/netbeans-website/blob/master/netbeans.apache.org/src/content/.htaccess#L24

Inbound links from the IDE should all be under `/nb/` (as you have done) so we can update the destination post-release when needed.

**Comment by KacerCZ** [comment]
Related PR for website is also ready :)
https://github.com/apache/netbeans-website/pull/520

**Comment by neilcsmith-net** [comment]
> Related PR for website is also ready :)

So it is - think I read the commits for PR 519 twice instead! :smile:  Looks good to me.

On the website side, the landing page should probably get a button to link across to JIRA to make it more obvious if we add this?  Similar to the download one on https://netbeans.apache.org/download/nb122/index.html eg. `link:/download/nb122/nb122.html[Download, role="button success"]`

**Comment by KacerCZ** [comment]
> On the website side, the landing page should probably get a button to link across to JIRA to make it more obvious if we add this? Similar to the download one on https://netbeans.apache.org/download/nb122/index.html eg. `link:/download/nb122/nb122.html[Download, role="button success"]`

I agree. Here is the PR: https://github.com/apache/netbeans-website/pull/521

**Comment by KacerCZ** [comment]
My intention of recent changes in NetBeans and website is to channel users reporting issue through single page (https://netbeans.apache.org/participate/report-issue.html) instead of direct links to JIRA.

PR https://github.com/apache/netbeans-website/pull/519 you mentioned is another place where reporter is linked to JIRA directly and it is link on main page.

**Pull request merged**
