### PR TITLE
[NETBEANS-3630] - Upgrade javaee8.api binaries

### PR DESCRIPTION
**Pull request by pepness**
Notes:
- Update JSR-250 Common Annotations for the Java Platform Maintenance Review 3
- Update javaee from 8.0 to 8.0.1
- Update javax.mail from 1.6.0 to 1.6.2
- Update javax.resource-api from 1.7 to 1.7.1
- Update javax.management.j2ee-api from 1.1.1 to 1.1.2
- Update javax.security.jacc-api from 1.5 to 1.6
- Update javax.enterprise.concurrent-api from 1.0 to 1.1
- Update javax.enterprise.deploy-api from 1.6 to 1.7
- Update javax.xml.registry-api from 1.0.7 to 1.0.8
- Update javax.xml.rpc-api from 1.1.1 to 1.1.2
- Update module 'j2ee.platform' (javadoc) from 7.0 to 8.0.1
- Update module 'web.jsf.editor' (javadoc) from 2.0 to 2.3

[JAVA EE 8 Spec](https://github.com/javaee/javaee-spec/blob/master/download/JavaEE8_Platform_Spec_FinalRelease.pdf)
See page 159 for the technologies with their required versions

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Looks sane to me - could please give me an indication why these are the "right" versions for java ee8?

**Comment by pepness** [comment]
The latest version of JAVA EE 8 is 8.0.1 which was released a year and a half later than 8.0. This was the latest revision that oracle did before donating the project to the Eclipse Foundation.

Some jars update their dependencies like JUnit, some have bug fixes and enhancements and some update their pom to reference the github where the source code is.

`j2ee.platform` is the javadoc that NetBeans create for JAVAEE, currently javaee7 instead of javaee8.
`web.jsf.editor` is the javadoc that NetBeans create for JSF, currently JSF 2.0 instead of JSF 2.3

**Comment by matthiasblaesing** [comment]
@pepness thank you for the reply. The javadoc updates look sensible to me, the update of patch releases alo. What I meant were these updates:

- javax.security.jacc-api from 1.5 to 1.6
- javax.enterprise.concurrent-api from 1.0 to 1.1
- javax.enterprise.deploy-api from 1.6 to 1.7

do these belong to JavaEE 8 and is the version documented there or are they loosely coupled? In the context of the java ee this triggered my reply:

- jaxws-api from 2.2.8 to 2.3.1

I read this as a feature release and not a pure patch release, so does 2.3 belong to java ee 6?

**Comment by pepness** [comment]
I check the [JAVA EE 6 Spec](https://jcp.org/en/jsr/detail?id=316), [JAVA EE 7 Spec](https://jcp.org/en/jsr/detail?id=342) and [JAVA EE 8 Spec](https://github.com/javaee/javaee-spec/blob/master/download/JavaEE8_Platform_Spec_FinalRelease.pdf) and find that:
- JAX-WS 2.1 for JEE 6
- JAX-WS 2.2 for JEE 7
- JAX-WS 2.3 for JEE 8

But I do not update that jar in this PR or the javaee 6 PR(I got the description wrong). For the others there where just changes in minor details mostly preparing the donation to the Eclipse Fundation:

- javax.enterprise.concurrent-api 
-- update the pom to reference the github where the source code is and the JUnit dependency
-- update the location of the license
-- update the copyright 

- avax.security.jacc-api
-- update the pom to reference the github where the source code is
-- update the location of the license
-- update the copyright 

- javax.enterprise.deploy-api
-- update the pom to reference the github where the source code is and some plugins
-- update the location of the license
-- update the copyright

**Comment by pepness** [comment]
I updated the description to reference the JAVA EE 8 Specification.

**Comment by matthiasblaesing** [comment]
Thank you.

**Pull request merged**
