### PR TITLE
Add class-file format to the file properties sheet

### PR DESCRIPTION
**Pull request by mbien**
- will now display the class-file version and the preview flag in the file properties table
 - little cleanup in the touched file

image
(last entry)

### CODE REVIEW

**Review by matthiasblaesing — COMMENTED** [review]
Nice. Only eyeballed, but looks sane to me.

**Review by matthiasblaesing — APPROVED** [review]

**Comment by mbien** [comment]
noticed a little issue: the property will also show up on `.java` files and display "unknown". Going to take a look if this can be improved.

converting to draft.

**Review by lkishalmi — APPROVED** [review]
Useful, indeed!

**Comment by matthiasblaesing** [comment]
Ok, a bit surprising, that `.class` files are handled by `JavaNode`, but the fix looks straight forward, so my positive review still stands.

**Comment by mbien** [comment]
awesome -> merging

I have also put two more items related to this on my todo list:
 - something similar for jars which would print some manifest info, e.g if its a multi release jar
 - JDK picker for "single-file-java-programs"

**Comment by mbien** [comment]
damn. the JDK bump causes the last two remaining jdk8 locked tests to fail. I take a quick look and might turn them off since last time I tried I gave up https://github.com/apache/netbeans/pull/5166 on it.

**Comment by mbien** [comment]
-> https://github.com/apache/netbeans/pull/7527

**Pull request merged**
