### PR TITLE
[NETBEANS-4177] Add another check for valid parameter list position to avoid exception if sourcecode is incorrect

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by graben** [comment]
@eirikbakke : Should fix your mentioned issue

**Comment by eirikbakke** [comment]
Reading through the method, this seems straightforward enough. Thank you!

**Comment by graben** [comment]
@jlahoda : Simple test added.

**Comment by graben** [comment]
@jlahoda : Should be considered for 12.0, too?

**Comment by jlahoda** [comment]
Yes, I believe this should be considered for 12.0. Eirik - what do you think?

**Comment by eirikbakke** [comment]
Looks completely safe to include to me.

**Comment by eirikbakke** [comment]
If you still have this patch running on your build, could you see if this also handles the following case?

```
public class FooTest {
  public void someMethod() {
    List<String> someFoo = listOf(transform(null, s -> new Integer(5)));
  }

  public static <E> List<E> listOf(E element) {
    throw new UnsupportedOperationException();
  }

  public static <F, T> Iterable<T> transform(
      Iterable<F> fromIterable, Function<? super F, ? extends T> function)
  {
    throw new UnsupportedOperationException();
  }
}
```

**Comment by graben** [comment]
Hi @eirikbakke, works for me on master build [1578](https://builds.apache.org/view/M-R/view/NetBeans/job/netbeans-linux/1578/).

**Comment by eirikbakke** [comment]
@graben Excellent--thank you!

**Pull request merged**
