### PR TITLE
[NETBEANS-4341] Disable maven global cache

### PR DESCRIPTION
**Pull request by matthiasblaesing**
With the cache enabled updates to the pom or the dependencies are not
picked up correctly.

Diagnosis and work-around was provided by Christian Oyarzun.

Closes: #2176

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@oyarzun @neilcsmith-net @ebarboni could you please have a look?

**Comment by oyarzun** [comment]
@matthiasblaesing pulled your branch and rebuilt. Your implementation of the fix works as intended.

**Comment by ebarboni** [comment]
@matthiasblaesing its works for me.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing haven't tested functionality yet, but thanks for the already set check. Seems safe to merge?  And I guess this needs considering as a cherry-pick (+ spec version increment) for a release branch PR too?

**Pull request merged**
