### PR TITLE
LSP Improvement

### PR DESCRIPTION
**Pull request by matthiasblaesing**
There are two problems in the LSP client code that prevent it from working with rust-analyzer, these are fixed here.

The core set of changes is more or less:

- handle `null` being returned from `codeAction`
- Send `initialized` event after we got `initServer` reply

The rest is nicer formatting and integration with logging for the JSON stream.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@arsi-apli @vieiro you might be interested in this, as this makes it possible to run rust-analyzer.

https://github.com/matthiasblaesing/netbeans/tree/rust-analyser has one more commit, that allows you to tie rust-analyzer into NetBeans, but it collides with the facilities provided by the rust CSL integration. We need to figure out how to dynamically switch from analysis with the antlr grammar to LSP (breadcrumbs, structure scanner) if we want to support both approaches.

**Review by vieiro — APPROVED** [review]
It's ages since I last saw a `StringBuffer` anywhere! This is indeed needed here.

It seems to be working fine, a quick & dirty LSP test shows like so:

imagen

This is a step towards integrating `rust-analyzer` in NetBeans.

**Comment by vieiro** [comment]
> @arsi-apli @vieiro you might be interested in this, as this makes it possible to run rust-analyzer.
> 
> https://github.com/matthiasblaesing/netbeans/tree/rust-analyser has one more commit, that allows you to tie rust-analyzer into NetBeans, but it collides with the facilities provided by the rust CSL integration. We need to figure out how to dynamically switch from analysis with the antlr grammar to LSP (breadcrumbs, structure scanner) if we want to support both approaches.

Note that the `rust-analyzer` integration in NetBeans needs some prior investigation, we first should decide if a single `rust-analyzer` instance is good enough for different "projects" or if each "project" should have a single `rust-analyzer` instance (see [1]). We should also decide what a NetBeans Rust Project is (a package, a workspace with many packages?, etc.). Also all this may require further changes in `ide/lsp.client`.


[1] - https://github.com/helix-editor/helix/discussions/5889

**Comment by arsi-apli** [comment]
> Note that the rust-analyzer integration in NetBeans needs some prior investigation, we first should decide if a single rust-analyzer instance is good enough for different "projects" or if each "project" should have a single rust-analyzer instance (see [1]). We should also decide what a NetBeans Rust Project is (a package, a workspace with many packages?, etc.). Also all this may require further changes in ide/lsp.client (adding support to ide/lsp.client for LSP workspaces, for instance, which rust-analyzer seems to support [2])

If I open the LSP configuration in NB and I don't know anything about it so I logically consider it as universal support. (After adding the `initialized` is probably already..) Therefore, there should be an option in the GUI to switch: one instance for all projects/new instance for each project. And the default option should be new instance for each project. And a link to the wiki page, where there will be a list of currently verified LSPs with the correct settings..

**Pull request merged**
