### PR TITLE
CssSemanticAnalyser needs to flatten OffsetRanges for highlights 

### PR DESCRIPTION
**Pull request by matthiasblaesing**
CssSemanticAnalyser reported overlapping ranges for highlights, for
example when an attribute is used in a :not() pseudo class construct.

The formatting behind the embedded range is lost and results in a
broken view.

The embedded OffsetRanges need to be flattened into a sequenze of
non-overlapping ranges.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
A test build is available from: https://doppel-helix.eu/NetBeans-dev-dev-36a8505c1a01bf5f6f4545b4e078efae31bfd658-release.zip

**Comment by mbien** [comment]
@matthiasblaesing not sure if you know. But we can now also create test builds by simply adding the https://github.com/apache/netbeans/labels/ci%3Adev-build label. It has a 7 day retention time atm.

**Comment by matthiasblaesing** [comment]
@mbien I knew this in the back of my mind. When it became important, my mind did not want to help in remembering. Thanks for the input!

**Comment by matthiasblaesing** [comment]
Reduced logging verbosity and will merge when unittests come back green

**Pull request merged**
