### PR TITLE
NETBEANS-3604 Supports for Records (JEP 359) in JDK-14

### PR DESCRIPTION
**Pull request by singh-akhilesh**
Fix formatting of record with no args. e.g 
**Input** :  public 
        record 
        Test3(
        ){
    }
**Output before fix**
    public record Test3(
            
){
    }
**Output after fix**
public record Test3(){
}

### CODE REVIEW

**Comment by singh-akhilesh** [comment]
@ebarboni  Would it be possible for you to review this and accommodate in current release?

**Comment by ebarboni** [comment]
@singh-akhilesh would it possible to format adjust the format ( else on same line of curly bracket, + space after else)

**Comment by singh-akhilesh** [comment]
> @singh-akhilesh would it possible to format adjust the format ( else on same line of curly bracket, + space after else)

Comment addressed...

**Comment by ebarboni** [comment]
thks merging

**Pull request merged**
