### PR TITLE
[cnd] revive go to header/source action from cnd.navigation

### PR DESCRIPTION
**Pull request by bitrunner**
This brings back the "Go to Header/Source" action to switch between C/C++ source and header files.  It includes the toolbar icon at the top of the editor, right click menu items, and keybinding.  It's a copy of the original implementation from contrib/cnd.navigation minus the part that used CSM.  It's just a simple filename matcher with no added intelligence to fall back on.  It's still useful like that.

This would be better if it could use the [non-standard clangd LSP textDocument/switchSourceHeader extension](https://clangd.llvm.org/extensions#switch-between-sourceheader) when available but I could not figure out how to add non-standard extensions to ide/lsp.client.  It seems possible to do it directly in lsp4j, but please enlighten me if there's a way to add non-standard extensions via the netbeans ide/lsp.client wrapper.

### CODE REVIEW

**Comment by vieiro** [comment]
Great contribution!

It seems this is also working for Objective-C sources, too...

imagen

**Review by vieiro — APPROVED** [review]
We could rebase on `cnd`  to build against JDK21ga (now in `cnd`), but I don't think this is required (we don't use fancy Java here).

CppSwitchAction` is a singleton (and is registered in `layer.xml` as a singleton) but then it has a public constructor, that shuould be private. That's ok, though.

**Comment by bitrunner** [comment]
Objective-C might work because netbeans classifies the implementation files as the C mime type.  I'm actually not sure.

I rebased and fixed the CppSwitchAction constructor access and the naming convention violation on the action name constant.

My only concern is that if we intend to bring back cnd.navigation some day, this will be redundant.  Is cnd.navigation shunned for good?

**Comment by mbien** [comment]
> We could rebase on cnd to build against JDK21ga (now in cnd)

CI is only building the full cluster and cnd isn't part of it atm. So it doesn't matter for now what the build does. It all depends what the next steps are. We could setup a job which builds CND separately or ignore CI and wait till its part of the full cluster.

**Comment by bitrunner** [comment]
> We could setup a job which builds CND separately or ignore CI and wait till its part of the full cluster.

That seems like a decent reason to merge cnd into master.  I seem to be able to have cpplite and cnd coexist peacefully enough for development by disabling one or the other module, but I'm pretty clueless.  We would probably not want to release netbeans with CND and cpplite at this point, but having both requiring someone to choose one to enable seems fine for development if I'm not missing some terrible side effects of this configuration.

> My only concern is that if we intend to bring back cnd.navigation some day, this will be redundant. Is cnd.navigation shunned for good?

I think it's important to understand that accepting this pull request is effectively pounding some nails in cnd.navigation's coffin and maybe we don't want to do that.  Not understanding why it was mothballed leaves me unsure of the path forward for bringing back features the cnd modules that now live in contrib provide.  There are lots of alternatives to what I did in this pull request which is akin to haphazardly copy/pasting the feature from cnd.navigation into the somewhat arbitrary cnd.editor module.

Here are two other things that are important enough to me that I'd like to try to do something about them soon-ish (there are many other useful features in contrib/cnd.*):
* the 'Go to Declaration/Implementation' feature provided by cnd.completion
* cnd.discovery is needed to create a new "C/C++ Project with Existing Sources".
  * The current state of this feature in cnd is broken.  The wizard fails because the DiscoveryExtension class in cnd.discovery is a service provider for the IteratorExtension.class that is needed to finalize/save the project.  cnd.discovery needs cnd/cnd.discovery/external/cnd-build-trace-1.0.zip native binaries as noted in [jira](https://issues.apache.org/jira/browse/NETBEANS-5486).  Based on the disposition of that ticket, I assume that's hopeless effectively killing cnd.discovery.  Do we need to devise some simpler alternative  to the vast array of complex capabilities cnd.discovery has for creating a C/C++ project from existing sources?

**Comment by vieiro** [comment]
> > We could rebase on cnd to build against JDK21ga (now in cnd)
> 
> CI is only building the `full` cluster config and cnd isn't part of it atm. So it doesn't matter for now what the build does. It all depends what the next steps are. We could setup a job which builds CND separately or ignore CI and wait till its part of the full cluster.
> 
> Let me know if you need anything.

D'oh! I thought we had cnd in the full cluster on this branch. Too bad we don't. We could remove cpplite and add cnd instead.

**Comment by vieiro** [comment]
Changes look perfect. Let's merge.

**Pull request merged**
