### PR TITLE
Snapshot of APIs as of NetBeans 14

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Snapshot of APIs as of NetBeans 14.  For review (sorry, bit late, should have started at branch).  Not to be merged as / until release vote completes.

Built in the usual way -

```
# checkout branch (or release tag)
git checkout release140
ant clean
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb140
git stash pop
git add -A
git commit -m "Snapshot of APIs as of NetBeans 14"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

### CODE REVIEW

**Comment by ebarboni** [comment]
not able to see where the conflict is

**Comment by matthiasblaesing** [comment]
The conflict is in `extide/gradle/nbproject/org-netbeans-modules-gradle.sig`. I assume, that a recent update of the gradle module  broadend the API and thus both branches have changes in that file. The diff looks trivial:

```diff
diff --cc extide/gradle/nbproject/org-netbeans-modules-gradle.sig
index a1d7b3483313,10434b6c15b2..000000000000
--- a/extide/gradle/nbproject/org-netbeans-modules-gradle.sig
+++ b/extide/gradle/nbproject/org-netbeans-modules-gradle.sig
@@@ -280,6 -297,24 +280,27 @@@ meth public static org.netbeans.modules
  meth public static org.netbeans.modules.gradle.api.NbGradleProject$Quality[] values()
  supr java.lang.Enum<org.netbeans.modules.gradle.api.NbGradleProject$Quality>
  
++<<<<<<< HEAD
++=======
+ CLSS public abstract interface org.netbeans.modules.gradle.api.NbProjectInfo
+ innr public abstract interface static Report
+ intf org.gradle.tooling.model.Model
+ intf org.netbeans.modules.gradle.tooling.Model
+ meth public abstract boolean getMiscOnly()
+ meth public abstract java.util.Map<java.lang.String,java.lang.Object> getExt()
+ meth public abstract java.util.Map<java.lang.String,java.lang.Object> getInfo()
+ meth public abstract java.util.Set<java.lang.String> getProblems()
+ meth public abstract java.util.Set<org.netbeans.modules.gradle.api.NbProjectInfo$Report> getReports()
+ 
+ CLSS public abstract interface static org.netbeans.modules.gradle.api.NbProjectInfo$Report
+  outer org.netbeans.modules.gradle.api.NbProjectInfo
+ meth public abstract int getLineNumber()
+ meth public abstract java.lang.String getErrorClass()
+ meth public abstract java.lang.String getMessage()
+ meth public abstract java.lang.String getScriptLocation()
+ meth public abstract org.netbeans.modules.gradle.api.NbProjectInfo$Report getCause()
+ 
++>>>>>>> github/pr/4189
  CLSS public abstract interface org.netbeans.modules.gradle.api.execute.ActionMapping
  fld public final static java.lang.String CUSTOM_PREFIX = "custom-"
  innr public final static !enum ReloadRule
```

I suggest to merge locally and accept the version from master for this file.

**Comment by neilcsmith-net** [comment]
@ebarboni I "cheated" and used GitHub's UI for conflicts.  Think it's fine.  Feel free to merge if OK, or I can handle locally and re-do.

**Comment by ebarboni** [comment]
@neilcsmith-net  sorry forget to press the button

**Pull request merged**
