### PR TITLE
JEDDICT-322 org.netbeans.modules.db.metadata.model convert friend to public packages

### PR DESCRIPTION
**Pull request by jGauravGupta**
Github issue: https://github.com/jeddict/jeddict/issues/322

Friend API of the Apache NetBeans Platform used by Jeddict modules:

| NetBeans Module name | NetBeans Module location | APIs | Used by Jeddict modules | Requirement |  Why access needed? |
| --- | --- | --- | --- | --- | --------- |
| org.netbeans.modules:org-netbeans-modules-db-metadata-model | netbeans\ide\db.metadata.model | org.netbeans.modules.db.metadata.model.api |  io.github.jeddict.jpa.modeler, io.github.jeddict.db.modeler | public-packages | To visualize Tree-Structured tables from Services > Database in Jeddict modeler |

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
What was done to verify, that the exported API is sane?

**Comment by jGauravGupta** [comment]
PR https://github.com/apache/netbeans/pull/1405 is now separated in multiple PR per modules. Updated the description for the usage of API in Jeddict plugin.

**Comment by matthiasblaesing** [comment]
Don't take this wrong, but I repeat my question: What was done to verify, that the API is sane? I'm not too happy with the DB modules api.

**Comment by jGauravGupta** [comment]
Hi @matthiasblaesing,

What's the process to check the sanity of the module e.g more unit tests, examples needed etc?

**Comment by junichi11** [comment]
Can't we add your codenamebase to api friend? Maybe, it is better than changing to public, I suppose.
My Plugins do it:
- https://github.com/apache/netbeans/blob/master/ide/bugtracking.commons/nbproject/project.xml
- https://github.com/junichi11/netbeans-github-issues-plugin/blob/master/pom.xml

**Comment by jGauravGupta** [comment]
Hi @junichi11,

In the PR https://github.com/apache/netbeans/pull/1405, I have added the codenamebase as a friend but @neilcsmith-net suggested to remove the friend-only restrictions. 
So I am creating PRs for all the modules required by Jeddict which have API/SPI packages and exported to friends marked as public.

**Comment by junichi11** [comment]
@jGauravGupta I see. I'm not sure whether it is good. Maybe, @JaroslavTulach can advise the proper way?

**Comment by neilcsmith-net** [comment]
@junichi11 we had a lot of discussion on public vs friend APIs about a year ago. There was little consensus aside from a recognition that we need to move towards stabilising and exposing necessary APIs.  These APIs may not be perfect, and perhaps we need a better in-development and deprecation mechanism, but IMO we should not be adding in friend access for third-party projects - that is just adding a stability issue by the back door.

I suggested @jGauravGupta propose a PR to expose what is required, and (I think) also start a mailing list thread on this.  With a move to quarterly releases we need to move away from plugin authors requiring either use of implementation versions or friend access.

Adding in a review request from @lkishalmi who started that earlier conversation on public vs friend.

**Comment by matthiasblaesing** [comment]
> What's the process to check the sanity of the module e.g more unit tests, examples needed etc?

That is a good question, but I think outside the scope of a PR discussion: this is the reason I asked what was done. I would like to discuss this on the mailinglist to get some more people to voice their opinion.

As we are nearing feature freeze, I would like to postpone this till release of 11.2 is done. As a work around, could you use yenta (https://github.com/jglick/yenta)?

**Comment by jGauravGupta** [comment]
Cool, I was not aware of **yenta**, I will check it out. Thanks @matthiasblaesing.

**Comment by neilcsmith-net** [comment]
> As we are nearing feature freeze, I would like to postpone this till release of 11.2 is done. As a work around, could you use yenta (https://github.com/jglick/yenta)?

I'd somehow missed that was an option for IDE plugins as well as RCP applications?!  @jGauravGupta if that can handle requirements for 11.2, great!  If not, another workaround that could be considered is a PR for the friend dependencies against the 11.2 release branch (when it exists)?  With a view to a better fix in master by 11.3 in line with @matthiasblaesing comment on postponing?

**Comment by JaroslavTulach** [comment]
It would be better to see the generated Javadoc before approving the integration. Anyway I think it is relatively good. Let's go on and I hope you'll be able to fix problems later.

**Pull request merged**
