### PR TITLE
Update FlatLaf from 1.6.1 to 2.0

### PR DESCRIPTION
**Pull request by DevCharly**
Update FlatLaf to v2: https://github.com/JFormDesigner/FlatLaf/releases/tag/2.0

There are (nearly) no visual differences compared to previous used version, except the slightly changed [check boxes and radio buttons](https://github.com/JFormDesigner/FlatLaf/pull/414).

The main benefits of FlatLaf v2 for NetBeans are the reworked [core themes](https://github.com/JFormDesigner/FlatLaf/pull/390) (easier changing colors), the possibility to [change the accent color](https://github.com/JFormDesigner/FlatLaf/pull/375) and the [FlatLaf Theme Editor](https://www.formdev.com/flatlaf/theme-editor/). This should it make it relative easy to change colors/style of the light and dark themes to differentiate more from IntelliJ IDEA look.

E.g. adding following to `platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties`
~~~
@background = #f3f3f3
@accentColor = #007aff
~~~

would change the look to (blue accent color; background minimally lighter):

image

Or adding following to `platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties`

~~~
@background = #333
@foreground = #c4c4c4
@accentColor = darken(#007aff,5%)

Button.default.foreground = #ddd
~~~

would make NetBeans darker and give text more contrast:

image

Not sure how to "organize" work/ideas on such theme changes...
Maybe create two "Draft PRs" (for light and dark) where interested people can comment and add commits?

### CODE REVIEW

**Comment by mbien** [comment]
nice! 

Regarding the theme adjustments and feedback: You could combine a draft PR with a forum thread since its probably easier to post images there compared to mailing lists.

**Comment by neilcsmith-net** [comment]
+1 Nice!

Putting NB13 milestone on this.

Now just need to convince @eirikbakke of the merits of CSS styling SVG icons to pick up the accent colour! :smile:

**Review by eirikbakke — APPROVED** [review]
Great to hear of the FlatLAF 2.0 release!

(@neilcsmith-net My NetBeans Platform app actually uses accent colors already! Except prior to FlatLAF 2.0, I had to set 80 different FlatLAF properties for this. The main reason I don't try to do it with icons is because the existing NetBeans icon style is multi-colored, and not duotone.)

**Comment by neilcsmith-net** [comment]
@eirikbakke at no point have I suggested switching to duotone icons in order to integrate with this change! You keep saying I have. Let's leave the practicalities of that discussion on dev@, but let's also tie in to what @DevCharly says about organizing ideas on theme changes.

**Comment by mbien** [comment]
this seems to be a fairly uncontroversial lib update, lets merge this for NB13.

**Pull request merged**
