### PR TITLE
Fix code completion for parent's trait #3486

### PR DESCRIPTION
**Pull request by junichi11**
#3486

### CODE REVIEW

**Comment by junichi11** [comment]
@tmysik Could you please have a look at this?
@neilcsmith-net Is this OK?

**Review by tmysik — APPROVED** [review]

**Comment by tmysik** [comment]
Looks good to me. Please, let me know if I should merge it (but I don't think so, right?). Thanks!

**Review by neilcsmith-net — APPROVED** [review]
Feel free to merge.

**Comment by junichi11** [comment]
Thank you, guys!
@tmysik Let's merge it after CI passes.

**Pull request merged**
