### PR TITLE
option window layout adjustments and UI fixes.

### LINKED ISSUE #4973: Improve padding size in the "Options" dialog
### Description

The "Options" dialog does not look polished and one of the problems is that components have different padding sizes.
Or sometimes does not have padding at all.

- different padding
image
image
image
image
- no top padding
image
- different padding
image
image
- no bottom padding and unnecessary resize bar
image
- different top padding
image

### Use case/motivation

Would to see a consistent design for all tabs of the "Options" dialog.

### Related issues

_No response_

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

### PR DESCRIPTION
**Pull request by mbien**
consistent (+symmetric) insets, margins, improved widget positioning and layout fixes. fixes #4973

some of those were quite hard to find + cascading JScrollPanes are my nemesis.

Screenshots:
old then new - those aren't all but most of them, at some point I gave up taking screenshots.

formatting0
formatting1

highlighting0
highlighting1

janitor0
janitor1

tabs0
tabs1

versioning0
versioning1

keymap0
keymap1

language-server0
language-server1

maven0
maven1

templates-dialog-displayer0
templates-dialog-displayer1

android0
android1

flatlaf0
flatlaf1

folding0
folding1

as bonus: template manager and DTD/XML Schema manager:
template-manager0
template-manager1

### CODE REVIEW

**Review by lkishalmi — APPROVED** [review]
Skimmed trough. Have not seen anything sore to the eye.

I have to admit I've also lost in the attached screenshots.

We have people with better eye than me among the reviewers, so let them speak as well.

Thank you for the effort!

**Comment by mbien** [comment]
[option-window.zip](https://github.com/apache/netbeans/files/10917848/option-window.zip) added a zip with the images. Makes it easier to inspect if you don't have to scroll.

**Comment by BradWalker** [comment]
There were a couple of spots in the code I might have made a comment. But decided not to as it was so minor.

Nice work! I really had to "look" at some of those screenshots to see the difference. 8-)

**Review by eirikbakke — APPROVED** [review]
Nice work! Touches a lot of files, but these are all either GUI cosmetics or code style fixes, so I think the patch isn't particularly risky. Any bugs in the PR are likely to be cosmetic, and can be fixed later without too much consequence.

It's also nice to see that the old "form" files are still usable in the NetBeans Swing GUI editor, and can produce working initComponents code.

It's probably good to get these changes merged within a few days, before merge conflicts start popping up.

**Comment by mbien** [comment]
@BradWalker my original plan was to mark the changes in the screenshot. But after taking so many it would have been too much work using gimp. The second idea was to use the `mouseover` feature of the img tag to switch between images on hover, but github doesn't support it either.

So the easiest way to see the difference is to download the zip, open an image with a viewer tool and quickly toggle with the  arrow keys between before/after. Some changes only make sense in context, e.g if you switch between tabs in the UI.

Looking at the linked issue can also help to know what to look for.

@eirikbakke the UI snapshot feature of the debugging session was vital to find where stuff is implemented. It allows to jump directly to the implementation. Although some layout issues were super sneaky, e.g some code somewhere else adding a empty border with insets to patch something, or even worse: code replacing components, borders or even layout managers outside of the actual component code.

thanks everyone for review. I will do another manual test and then merge.

**Comment by eirikbakke** [comment]
Yeah, the UI Snapshot feature is really useful, especially for inspecting form layouts in NetBeans itself.

To compare before/after images, I usually just open each image in a different Chrome tab (Ctrl+Click the image to open just the image in a new tab) and do Ctrl+PgUp/PgDown to switch between them. Or for downloaded images on Windows, I use IrfanView as my image viewer of choice (press enter twice to full-screen, then left/right arrows to switch between images in the same folder).

**Comment by Chris2011** [comment]
I think it should be aligned with the text field, a bit smaller, because it is to prominent and just a hint for the field. Maybe also the brackets can be removed

Current
image

Potential solution
maven version

**Comment by Chris2011** [comment]
Oh I see, I was a bit late to the party. Sry.

**Pull request merged**
