### PR TITLE
[NETBEANS-2775] Fix duplicate server entries by filtering using PlatformFactory

### PR DESCRIPTION
**Pull request by jGauravGupta**
Reverted the previous PR https://github.com/apache/netbeans/pull/1347 which causes unavailability of `org.netbeans.modules.cloud.amazon.ui.serverplugin.AmazonJ2EEServerWizardComponent` during maven web application creation.

And filtered the server entries with different URI fragment based on unique J2eePlatformFactory e.g [gfv3ee6, gfv5ee8] & [pfv3ee6, pfv4ee7, pfvee8].

### CODE REVIEW

**Comment by peedeeboy** [comment]
Tested this, and was able to create Amazon Beanstalk servers for Maven, Ant & Gradle Java Web Application projects, and to successfully deploy in all cases.

However, I'm not sure if you are aware / this is intended, but Payara Server is no longer an option in Project -> New Project -> Java Web -> Severs, only in the Services -> New Server or Tools -> Servers dialogs.

This may be unrelated (and in fact related to the fact I had to manually install Oracle JS Parser to activate JavaEE in the current Master branch), but I also couldn't get Payara to activate by choosing it in Tools -> Servers -> Payara Server.  It just gets stuck on the "Activating feature" dialog. No errors in the Netbeans log that I can see...

Hope that helps :)

**Comment by neilcsmith-net** [comment]
> It just gets stuck on the "Activating feature" dialog

@peedeeboy I assume this may be the existing ergonomics issue, or it's because you have a slightly older revision without the merged UC fix.  Either way @jGauravGupta please note the discussion thread at https://lists.apache.org/thread.html/69de8f6e1cdcfcc65b0c92a81ea9c3724058b89e5a56adea0b3d79cd@%3Cdev.netbeans.apache.org%3E  The Payara related ergonomics fixes went into the _release111 branch only_.  The fix needs reviewing, and possibly adapting, for master.

**Comment by jGauravGupta** [comment]
Hi @peedeeboy,

I have tested Payara/GlassFish server registration from Maven, Gradle, and Ant web project and found no issue so far except missing localization bundle warning in Ant Web project.

@neilcsmith-net, Yes I am aware of Payara Micro ergonomics issue and I will fix it in upcoming next week. But it should only disable the Payara Micro application and must not have any impact on Payara Server tooling.

**Comment by neilcsmith-net** [comment]
@jGauravGupta the stuck dialog suggests an ergonomics issue, which could be the update center URLs issue (also suggested by manual Oracle JS comment) - that's now fixed.  But it also might be a sign that something else needs adding to the kit dependencies.  I added minimum required to get Payara Micro enabled in 11.1, but suggest logging and reviewing all module enabling via ergonomics before fixing in master because I'm not 100% sure my fix in 11.1 does all required.

**Comment by peedeeboy** [comment]
@neilcsmith-net @jGauravGupta just to say that I tested this by cloning a fresh copy of master, then fetching this PR and building NB from that branch.  

So I do think enabling Payara getting stuck on "Activating feature is unrelated to this PR itself, and as Neil's suggests is because I didn't have an ergonomics fix locally - I don't think it should hold up this PR.. ?

Hope that helps :)

**Comment by jGauravGupta** [comment]
Hi @peedeeboy,

I have fixed the ergonomics error, May you test the PR again with the latest commit?

**Comment by peedeeboy** [comment]
Thanks @jGauravGupta !  I will test within next couple of days :)

**Comment by peedeeboy** [comment]
Tested.  Was able to create and deploy a JavaEE Web Application to an AWS EB instance *AND* I was able to download * register a Payara server locally.  Perfect :)  Thank you, @jGauravGupta !! :D

**Comment by geertjanw** [comment]
This is good to go, it seems? Please confirm and I'll merge.

**Comment by jGauravGupta** [comment]
Hi @geertjanw,

Yes, this PR can be merged now, @peedeeboy also confirmed.

**Comment by jGauravGupta** [comment]
Thanks @geertjanw  and @peedeeboy

**Pull request merged**
