### PR TITLE
Sync delivery to master after 17-rc3

### PR DESCRIPTION
**Pull request by neilcsmith-net**

### CODE REVIEW

**Comment by sdedic** [comment]
@neilcsmith-net I can assist with the DownloadWalletAction.java conflict; can I commit into this PR ?

**Comment by neilcsmith-net** [comment]
@sdedic not as far as I know, as that will affect the delivery and release branches. What do you have in mind?

Previous times I've taken a separate branch off delivery after sync has happened and fixed in a PR from that. Whatever we do has to keep delivery mergeable into release170 and master.

**Comment by neilcsmith-net** [comment]
Slightly incorrect above.  Looking back at 15-rc3 and #4486  After we've merged to release branch and successfully built 17-rc3, we need to take a separate branch off master, merge delivery into it handling the conflicts, then open a new sync PR based on that for tests.  This PR will then be closed.

Nothing to do here until after delivery has merged to release170 as there will likely be more commits before then.

@sdedic either you or I can handle the above.  Is it everything from delivery but the regex from master?  Does that regex change need to be in NB17?

**Comment by neilcsmith-net** [comment]
Closed in favour of #5404

**Pull request closed without merging**
