### PR TITLE
[NETBEANS-5719] Unused property hint is shown when the property is used as a constructor argument

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-5719

- Scan constructor arguments of an anonymous class

#### Before:
netbeans5719-before

#### After:
netbeans5719-after

### CODE REVIEW

**Comment by junichi11** [comment]
@ebarboni Can we include this in 12.5 yet?

**Comment by ebarboni** [comment]
Yes we can

**Comment by ebarboni** [comment]
I cannot test PHP maybe good to wait for @tmysik review ?

**Comment by junichi11** [comment]
@ebarboni 
> I cannot test PHP
No problem.

> maybe good to wait for @tmysik review ?
Yes.

I saw your email (preparing for 12.5: https://lists.apache.org/thread.html/rc9866241a10ef7deda1f9235426909fde433b988888e75049d0362b4%40%3Cdev.netbeans.apache.org%3E).
So, Just in case, I added you as a reviewer because I was not sure whether we can include this in 12.5. Thanks!

**Review by tmysik — APPROVED** [review]

**Comment by tmysik** [comment]
Approved, merging then...

**Comment by junichi11** [comment]
@tmysik Thank you for your review :)

**Pull request merged**
