### PR TITLE
[NETBEANS-1341] NPE NBJavadocMemberEnter

### PR DESCRIPTION
**Pull request by rtaneja1**
Added null check, not able to reproduce the NPE.

### CODE REVIEW

**Comment by RicNmn** [comment]
> Added null check, not able to reproduce the NPE.

This prevents the NPE for sure, but seems to result in incorrect code completion...so a small improvement.

I'm still trying to see (find documentation) how I could debug the code myself, after building NB 10 VC1, so I could provide more details to this P.R. Any help is welcome of course...

**Comment by rtaneja1** [comment]
Sure, can you please share sample project where this issue is reproducible.
For debugging, if you have built NB10 and running using ant tryme, run with -Dtryme.debugPort=<port> and open the sources in another NetBeans instance. Invoke Debug - Attach Debugger (SocketAttach, same port).

**Comment by RicNmn** [comment]
Thx... will try to debug later.

How I reproduced:
- checkout nbm-maven-plugin from its internet repo
- open AbstractNbmMojo.java
- arround line 260, inside an if statement, start typing 'log.'
- code completion popup is shown
- now type (add) 'debug' and wait
- the code completion popup should now only show three possible options
- make sure the first item in the popup has focus ( log.debug(CharSequence ) 
- press enter
- now the exception has occured with exact same stacktrace

**Comment by rtaneja1** [comment]
Still unable to reproduce this exception, tried in Windows 7, Linux 7, both Jdk 10 and JDK8 , nb-javac plugin version 1.5.

**Comment by RicNmn** [comment]
During debugging, I noticed that the line numbers in the exception appear to be confusing...the debugger stepped into whitespace here and there....as if some optimization is done by the compiler or vm...

I also noticed that during the handling of the 'accept', when the exception is shown, that cancelling the exception causes the correct code to be completed, even the parameter name is correct..

So what I will look into some time is, if the last piece of the execution stack should actually not be executed to prevent the problem....

**Comment by RicNmn** [comment]
Running java 1.8.0_191 on Windows 10

Rebuilt nb-10-vc1 from clean folder, where I unzipped the source zip that I downloaded.
Executed
Ant clean
Ant build
Ant tryme

During tryme, I activated sone plugins in Netbeans and the Netbeans asked to dowload version 1.4 (!) Of the nb-javac plugin.
Inside the plugin, in the ext folder, are the wrappex javac jars, but they have no version specified in their meta files.


So how do you get the 1.5 version of the plugin?

**Comment by rtaneja1** [comment]
Tools: plugins : check for updates, else under settings add http://plugins.netbeans.org/nbpluginportal/updates/10.0/catalog.xml.gz 
and check for updates.

**Comment by RicNmn** [comment]
Am I mistaking or is the NB 10 built process using the nb javac 1.4 impl and api instead of the 1.5 versions?

**Comment by geertjanw** [comment]
Use 10vc2, please: https://cwiki.apache.org/confluence/display/NETBEANS/10vc2

**Comment by RicNmn** [comment]
10vc2 seems to work fine regarding this issue and by default it fetches the 1.5 nbjavac plugin.

(Nb: 10vc1 still had the issue, even after I installed nbjavac 1.5 plugin)

I do see a new minor issue ( incorrect parameter name added in the auto completed code. Will double check and report in new issue if necessary)

**Pull request closed without merging**
