### PR TITLE
Regenerate sigfiles

### PR DESCRIPTION
**Pull request by junichi11**

### CODE REVIEW

**Comment by junichi11** [comment]
@tmysik I would like to merge this into the `delivery` branch (for NB13) if possible. If it's OK, one of the release managers(maybe @neilcsmith-net) merges this. Thanks!

**Comment by junichi11** [comment]
It seems that https://netbeans.osuosl.org/binaries/4EA0C90D7EB03DEC5AC2AD19FE33C3A9F71AD790-phpsigfiles-1.4.zip is not downloaded often. (I've uploaded it yesterday.)

**Review by neilcsmith-net — APPROVED** [review]
OK with me.  I'll merge in a couple of days - need to complete rc2 first.  This will go in before rc3.

**Review by tmysik — APPROVED** [review]

**Comment by neilcsmith-net** [comment]
OK, couple of days turned into 6hrs :smile: Merging!

**Comment by neilcsmith-net** [comment]
Not sure the link is working? Currently failing tests on download.

**Comment by junichi11** [comment]
@neilcsmith-net As I wrote above, it is not downloaded sometimes... The link should be available because some jobs pass. I'll rerun jobs. If they passed, I'll let you know. Thanks.

**Comment by neilcsmith-net** [comment]
@junichi11 I already set to rerun.  Yes, let's see how it goes.  I understand your comment now.  Works sometimes in browser.

We really need to try and move away from OSUOSL, but I'm not sure where else these could be?!

**Comment by junichi11** [comment]
All checks have passed.

**Comment by neilcsmith-net** [comment]
Thanks.  Yes, I noticed that, but I'm still getting a 404 from direct download.  I'm going to try a local build with your changes and see if that works here first before merging.

**Comment by junichi11** [comment]
Maybe, we should merge this later to avoid failing CI with other PRs.

**Comment by neilcsmith-net** [comment]
Yes, that's my concern, as well as people building locally.  Still breaks local build for me too.

**Comment by neilcsmith-net** [comment]
@junichi11 this sounds like a possible culprit - https://lists.apache.org/thread/xw4o1joztm3q1gvlq9dyskfbmmbkyyty

**Comment by junichi11** [comment]
@junichi11 Yes, I completely forgot to run the script this time.

**Comment by neilcsmith-net** [comment]
@junichi11 no worries! :smile: All resolved, let's merge.

**Pull request merged**
