### PR TITLE
Snapshot of APIs as of NetBeans 21

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Snapshot of APIs as of NetBeans 21.  For review purposes only at this stage.  Not to be merged as / until release vote completes and updated if necessary.

<details><summary>Built in the usual way ...</summary>

```bash
# checkout branch (or release tag)
git checkout release210
git clean -dxf
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb210
git stash pop
git add -A
git commit -m "Snapshot of APIs as of NetBeans 21"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

Filtered diff created using -

```bash
curl -L https://github.com/apache/netbeans/pull/<PR_ID>.diff | filterdiff -#2- > filtered-apis-nb210.txt
```
</details>

Filtered diff : [filtered-apis-nb210.txt](https://github.com/apache/netbeans/files/13949719/filtered-apis-nb210.txt)

### CODE REVIEW

**Review by mbien — APPROVED** [review]
looks good I think

**Review by ebarboni — APPROVED** [review]

**Review by MartinBalin — APPROVED** [review]

**Review by junichi11 — APPROVED** [review]
Looks good.

cc: @tmysik 

php.editor: 
https://github.com/apache/netbeans/pull/6960/files#diff-8026dd3d7e719e301146e76cf2b33c8ea2209a162f6e12e5cfd82b933fcd1a1c

php.api.phpmodule: https://github.com/apache/netbeans/pull/6960/files#diff-83729044e1d93ea85b3cf6bd188fec49bfbb5b4cd0b9e9ace771a88afd97b5e3

**Comment by neilcsmith-net** [comment]
@ebarboni @mbien updated this as Gradle changes brought in some additions.  Then rebased on current master because of a conflict.  Hopefully correct now - more eyes appreciated! :eyes:

**Review by mbien — APPROVED** [review]
i diffed the diff files of  5e5e614, de78725 and  6b7e3a9 and changes looked good

**Comment by neilcsmith-net** [comment]
Please do!

**Pull request merged**
