### PR TITLE
json.g4 wrong licenses

### PR DESCRIPTION
**Pull request by vieiro**
The "json.g4" antlr grammar generates files with wrong licenses.

### CODE REVIEW

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me.

**Comment by vieiro** [comment]
Maybe @geertjanw and @neilcsmith-net  want to include this within the new release. Once upon a time we had labels for this, but I cannot find the proper one right now...

**Comment by matthiasblaesing** [comment]
@vieiro just merge to master, branching of the release has not happened yet

**Comment by vieiro** [comment]
Ah, good to know. I thought we did already fork for next release. Anyway they can cherry-pick later on if they want. Merging then...

**Pull request merged**
