### PR TITLE
[NETBEANS-5054] include web.bootsfaces in cluster.properties #2357

### PR DESCRIPTION
**Pull request by t-oster**
I am not even sure what the cluster.properties does, but since I want my #2357 to be in the next distribution, I guess this is what I have to do?!

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
> @matthiasblaesing is #2559 what I should do? I added it underneath web.primefaces, because that's what it is based on.

The failing unittests give the answer (isn't it nice to get clear errors for once :-)):

https://travis-ci.org/github/apache/netbeans/jobs/745509166#L446

i.e. you need to fix the order. I don't want to discourage you, but this will become part of 12.3.

**Comment by matthiasblaesing** [comment]
To give some context: Clusters in Netbeans sources group modules and the build is defined by the set of clusters that are included. The full IDE contains all clusters, one other popular cluster "platform", which only contains the core modules to get a good basis for a swing application. If a module is not part of a cluster it is not reached by the build system and thus not included.

**Comment by matthiasblaesing** [comment]
And one final thing: Please update the commit message to hold the reference to the issue in the summary:

"[NETBEANS-5054] include web.bootsfaces in cluster.properties"

**Comment by t-oster** [comment]
@matthiasblaesing thanks for the infos. I did as requested. I overlooked the meesage with the order in the logs... sorry

**Comment by matthiasblaesing** [comment]
I'll merge, if you change the whitespace. The file is indentet with spaces and the addition is a tab.

**Comment by t-oster** [comment]
done. my bad, didn't see that in Netbeans ;)

**Comment by junichi11** [comment]
@t-oster It's still a tab.

**Comment by t-oster** [comment]
I am sorry this took so long for such stupid things. I just forgot to git add before amend. However I wouldn't have minded if anyone had just changed the line in this file and closed this PR since my code is already in #2375

**Comment by matthiasblaesing** [comment]
Thank you.

**Comment by junichi11** [comment]
@t-oster Don't worry :)

**Pull request merged**
