### PR TITLE
Update FlatLaf from 2.6 to 3.0 and add macOS light and dark themes

### PR DESCRIPTION
**Pull request by DevCharly**
Update FlatLaf to v3.0.

Changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/3.0

### macOS themes

FlatLaf 3 comes with two new themes, which look similar to macOS:

macOS themes

I've added both to the list of look and feels (on all platforms, screenshots are from Windows 11):

grafik

grafik

### Rounded outlined icons

FlatLaf 3 has new modern rounded outlined icons for `JFileChooser`, `JOptionPane`, `JPasswordField` and `JTree`:

image

They are e.g. used in project/file trees and in file choosers (in all FlatLaf themes):

grafik

### CODE REVIEW

**Comment by DevCharly** [comment]
> I like the new icons.

Thx 😄 

> The dark mac theme might be interesting for those who prefer higher contrast themes.

Yes, definitely. That's why I've not limited those themes to mac platform 😉

**Comment by mbien** [comment]
@DevCharly its off topic but since I see it in the screenshots. I feel like I am missing out on those nice shortcut buttons on the left side of the file chooser dialog as linux user :)

**Comment by neilcsmith-net** [comment]
Looks great!  I was somewhat tempted to squeeze it in just before I branched, although hadn't had a chance to look properly so didn't want to make the call. :smile:

One concern would be whether we should be using the name `macOS` in the UI here?  Maybe something like `FlatLaf Cupertino Light`?

Are the mentioned fonts included in this change for NetBeans?

**Comment by mbien** [comment]
> One concern would be whether we should be using the name macOS in the UI here? Maybe something like FlatLaf Cupertino Light?

agreed. Mac OS is also changing the theme periodically, so it would be better the not associate a Look and Feel with a OS theme to have more flexibility if it needs adjustments. I like Cupertino since it still alludes to the origin.

**Comment by mbien** [comment]
@neilcsmith-net yes mine too. I already looked up bug species which like apples but they all have fairly complicated names :)

I only wanted to bring up a technical reason why naming it after an OS might not be a good idea. If it would start diverging from the mac look it might be perceived as a bug.

**Comment by DevCharly** [comment]
> @DevCharly its off topic but since I see it in the screenshots. I feel like I am missing out on those nice shortcut buttons on the left side of the file chooser dialog as linux user :)

Yes, unfortunately the shortcuts are only available on Windows because the used Java API provides the information only on Windows 😞

**Comment by DevCharly** [comment]
>One concern would be whether we should be using the name macOS in the UI here? Maybe something like FlatLaf Cupertino Light?

Good idea 👍 
I'm fine with Cupertino 

> Are the mentioned fonts included in this change for NetBeans?

No. They are in extra JARs.

**Review by eirikbakke — APPROVED** [review]
Looks great--applause!

(Also second the "Cupertino" name, for the trademark reasons and since it's a useful theme even on Windows.)

**Comment by eirikbakke** [comment]
I tested this patch in its current form on my private NetBeans build; works as expected with no problems.

**Comment by mbien** [comment]
if the `Cupertino` renaming makes it in time before RC2 we should rebase this PR on `delivery` and get this in for NB 17 in my opinion.

This is technically a bugfix since it removes 8 superfluous pixels on the file open dialog I _totally_ noticed while working with NB 16 :)

**Comment by DevCharly** [comment]
I've renamed the new themes to Cupertino.

Please let me know if there is a need to rebase this PR to `delivery`.

But since the branch for this PR was created before the `delivery` branch was created, there is actually no need to rebase it.
It can be merged directly into the `delivery` branch. Rebasing makes no difference...

**Review by neilcsmith-net — APPROVED** [review]

**Comment by Chris2011** [comment]
Great icons, but is it possible, that I can change it via the flatlaf properties file? I don't like this mixed stuff what we have. Most of the NetBeans Icons are not outlined and now it looks a bit odd with those all not outlined Icons in the Project window with the just folder outlined ones. As long as we can't switch all icons to either outline or not, I would like to change them by my own. Is this easy possible?

**Comment by DevCharly** [comment]
@Chris2011 yes, this really looks odd.

Have created PR #5760 to replace FlatLaf outlined folder icons with NetBeans style icons.

**Pull request merged**
