### PR TITLE
[NETBEANS-4235]:Fixed formatting issue in Java Record

### PR DESCRIPTION
**Pull request by arusinha**

### CODE REVIEW

**Comment by ebarboni** [comment]
doable for 12.0 beta 5  ?

**Comment by arusinha** [comment]
hi @ebarboni , We can move it to 12.1 release

**Comment by ebarboni** [comment]
up to you, beta5 not yet cut, merge if you are ok

**Comment by arvindaprameya** [comment]
+1 Approved, this can go into 12.0 if there is a possibility.

**Comment by arusinha** [comment]
@ebarboni , yeah you can consider it for 12.0

**Pull request merged**
