### PR TITLE
README and CHANGELOG update

### PR DESCRIPTION
**Pull request by MartinBalin**
Added badges into VSNetBeans README.MD and added 21.0.0 into CHANGELOG.MD. A little late for 21.0.0 unfortunately but these are just doc changes so can go into next build of 21.0.0

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
We don't currently have a plan for a 21-rc4.  If we get a high priority PR for NB21 that forces one we can merge this.  If not, I'll rebase and merge to master.  Or is this high priority?

**Comment by MartinBalin** [comment]
Not a high priority. Can be just in master, number of code changes in VSNetBeans between 20.0.301 and 21.0 was small.

**Review by dbalek — APPROVED** [review]

**Comment by neilcsmith-net** [comment]
@MartinBalin this has do not merge on if for a reason.  We're meant to use the same hash for last release candidate and release.  Your comment above said it could just be in master.

**Comment by MartinBalin** [comment]
@neilcsmith-net - my appologies. It was again my confusion with `delivery` usage vs `master`. What can I do to revert it now?

**Comment by neilcsmith-net** [comment]
@MartinBalin no worries! Definitely not revert. If delivery ever needs reverting it needs force pushing back to the required commit.

However, leave this for now. If another issue comes in over the next few days that requires an rc4, it can go in with it. If not, we can add to master before deleting the delivery branch.

**Pull request merged**
