### PR TITLE
PHP 8.2 Support

### PR DESCRIPTION
**Pull request by junichi11**
#4725 
This is a partial support. Some features don't work.

### CODE REVIEW

**Comment by tmysik** [comment]
I plan to merge this PR later today, once the checks are finished. Please, let me know if I should not do it. Thanks.

CC @junichi11 @matthiasblaesing

**Comment by junichi11** [comment]
It should be no problem. Thanks!

**Comment by mbien** [comment]
restarted the failing job which is unrelated to this PR.

This branch here seems to be fairly old since I still see travis in the checks. Although it would be better to rebase it to latest master, i think it might be still ok to merge since the PHP job didn't have any changes recently (and wasn't tested on travis).

**Comment by tmysik** [comment]
OK, so merging :crossed_fingers:

**Pull request merged**
