### PR TITLE
[NETBEANS-3106] Add javahome property to groovyc task

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@lkishalmi OK, so for 11.2?  Add milestone if you're happy with this.

**Comment by graben** [comment]
@neilcsmith-net: Does that mean approval okay from your side?

**Comment by lkishalmi** [comment]
I've added the milestone 11.2. I assume there are relative small audience of groovy projects, as the code completion bug for groovy arrived quite late after we broke that on 11.1. So let's have this in 11.2 beta 2.

**Comment by graben** [comment]
@lkishalmi: 👍

**Pull request merged**
