### PR TITLE
[NETBEANS-2788] The link provided for downloading Groovy is obsolete

### PR DESCRIPTION
**Pull request by ramiswailem**
Changed the old URL to a new one:  https://groovy.apache.org/download.html
Jira Ticket: https://issues.apache.org/jira/projects/NETBEANS/issues/NETBEANS-2788

### CODE REVIEW

**Comment by geertjanw** [comment]
Nice, thanks a lot.

**Comment by lkishalmi** [comment]
Thank you!

**Comment by junichi11** [comment]
@ramiswailem Do you mind closing PRs(1478, 1479)? Please have a look at @lkishalmi 's comment again. (Changes requested) Thanks!

**Comment by geertjanw** [comment]
Is this ready to merge, all comments completed?

**Comment by lkishalmi** [comment]
@neilcsmith-net You can merge this whenever you find it ideal.

**Pull request merged**
