### PR TITLE
update npm module semver (moderate severity vulnerability)

### PR DESCRIPTION
**Pull request by MartinBalin**
Cherrypick of commit fc06b786 to update semver from master done originally by T.Hurka.
Merged in master already.

### CODE REVIEW

**Review by neilcsmith-net — APPROVED** [review]
Looks OK.

Have added `do not merge` label just in case this causes a merge conflict and breaks CI testing in #6314 (identical changes sometimes OK)

I'll merge as last task before building rc5.

**Comment by neilcsmith-net** [comment]
As @thurka confirmed on #6319 that this isn't (despite the title) a security issue in VSNetBeans, can we close this instead?  Or do you still want to pull in the fix?

**Comment by MartinBalin** [comment]
Yes, close and build final NB 19.0.0 build.

**Comment by neilcsmith-net** [comment]
I'll close, but we'll definitely have a 19-rc5 as we have changes already.  Also waiting to see if we get a final Gradle release in the next few days.

**Pull request closed without merging**
