### PR TITLE
Add blank lines for formatting options(Between Use Types) when use statements are inserted by "Fix Imports" #6238

### PR DESCRIPTION
**Pull request by junichi11**
- https://github.com/apache/netbeans/issues/6238
- Add unit tests

### CODE REVIEW

**Review by tmysik — APPROVED** [review]
A lot of tests, that is perfect 👍 Thanks!

**Comment by junichi11** [comment]
Thank you, Tomas! 

For the release team: Ready to merge :)

**Comment by tmysik** [comment]
@junichi11 Nothing to thank for, really.

**Comment by neilcsmith-net** [comment]
Thanks, merging!

One of those times I look with concern at the number of changed files on delivery, then remember to filter out tests! :laughing:

**Comment by junichi11** [comment]
Ah, Yes, almost all are unit tests :) Thank you!

**Pull request merged**
