### PR TITLE
#7606: process daemon's stdout to avoid lockup

### LINKED ISSUE #7606: Netbeans 22 does not load a 8.9 gradle wrapper in project. Infinite loop.
### Apache NetBeans version

Apache NetBeans 22

### What happened

If you have a project with a gradle wrapper 8.9. Netbeans 22 cannot load it. It just starts an infinite loop but does not load anithing.

### Language / Project Type / NetBeans Component

_No response_

### How to reproduce

Just make a project with a gradle 8.9 wrapper in it.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux Ubuntu 24.04 LTS

### JDK

Jdk 17.0.11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

_No response_

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by sdedic**
Accidentally (try-and-error) I discovered that when the daemon's output stream is not processed, the daemon hangs on reading the stdin even though stdin is empty. So I've attached the piped output stream + reading daemon unconditionally, so that gradle daemon correctly processes the empty stdin.

Closes #7606.

After testing, this can be eventually cherrypicked to `delivery` if @ebarboni agrees.

### CODE REVIEW

**Comment by mbien** [comment]
> After testing, this can be eventually cherrypicked to delivery if @ebarboni agrees.

this would need to target delivery right away. We can't cherry pick from master since this would cause it to show up in the release notes of two releases.

also if we test, we should test it on the delivery branch, not the master branch which diverged already and then switch last minute.

**Comment by ebarboni** [comment]
@sdedic  would be perfect based on delivery

**Comment by sdedic** [comment]
yes, I can rebase it if the issue is seen as "wanted" in NB23.

**Comment by ebarboni** [comment]
If it's ok for you lets do this.

**Comment by sdedic** [comment]
Rebased onto `delivery`, milestone changed.

**Comment by ebarboni** [comment]
LGTM, not the best gradle user but no issue for me

**Review by ebarboni — APPROVED** [review]

**Comment by mbien** [comment]
just as general comment since this PR is linked to close the issue: the infinite loop during priming would have to be addressed separately. A loop is not a good failure mode, it should be caught somewhere / propagated and stop with an error.

**Comment by sdedic** [comment]
> just as general comment since this PR is linked to close the issue: the infinite loop during priming would have to be addressed separately. A loop is not a good failure mode, it should be caught somewhere / propagated and stop with an error.

Hm, are you sure that there's an **infinite loop** ? What I saw during debugging / investigation was not a infinitely **repeated** attempt to load a project, but rather a *stuck*  project load, that blocks all other loads (all gradle project loads are serialized to a RP).

**Comment by sdedic** [comment]
> @sdedic the user mentioned several times that the symptom was an "infinite loop" e.g. [#7606 (comment)](https://github.com/apache/netbeans/issues/7606#issuecomment-2315813845)
> 
> I haven't tried to reproduce the original issue so I don't know.

OK, I'll perhaps leave this open for someone to investigate more. I could not reproduce anything that actually *is* a loop. The user might be mistaken and mislead by the fact that a message "loading..." was stuck in the status line, but I cannot prove it and will not bother prove the otherwise.

**Review by lkishalmi — APPROVED** [review]
Run a minimal test with this one. Gradle Daemons tends to get stuck after exiting the IDE. It seem this one has helped on that as well.

**Comment by ebarboni** [comment]
merging this. waiting for sync pr and baking rc3

**Pull request merged**
