### PR TITLE
JEDDICT-322 Export public-packages & friend-packages to Jeddict modules

### PR DESCRIPTION
**Pull request by jGauravGupta**
Github issue: https://github.com/jeddict/jeddict/issues/322

Internal API of the Apache NetBeans Platform used by Jeddict modules:

| Netbeans Module name | Netbeans Module location | APIs | Used by Jeddict modules | Requirement |  Why access needed? |
| --- | --- | --- | --- | --- | --------- |
| org.netbeans.modules:org-netbeans-modules-j2ee-persistenceapi | netbeans\java\j2ee.persistenceapi |  org.netbeans.modules.j2ee.persistence.api, org.netbeans.modules.j2ee.persistence.spi | io.github.jeddict.jcode.util, io.github.jeddict.jpa.modeler, io.github.jeddict.reveng | friend-packages | Java persistence is core feature of Jeddict modeler so persistence.api module is needed to find persistence.xml location in project, to identify persistence descriptor properties, to list available Java Entity classes in project during Java Classes reverse engineering, etc. |
| org.netbeans.modules:org-netbeans-modules-j2ee-persistence | netbeans\java\j2ee.persistence | org.netbeans.modules.j2ee.persistence.dd, org.netbeans.modules.j2ee.persistence.dd.common, org.netbeans.modules.j2ee.persistence.unit, org.netbeans.modules.j2ee.persistence.entitygenerator, org.netbeans.modules.j2ee.persistence.jpqleditor, org.netbeans.modules.j2ee.persistence.jpqleditor.ui, org.netbeans.modules.j2ee.persistence.editor, org.netbeans.modules.j2ee.persistence.provider, org.netbeans.modules.j2ee.persistence.wizard, org.netbeans.modules.j2ee.persistence.wizard.jpacontroller, org.netbeans.modules.j2ee.persistence.wizard.fromdb, org.netbeans.modules.j2ee.persistence.wizard.library, org.netbeans.modules.j2ee.persistence.wizard.unit | io.github.jeddict.jcode.util, io.github.jeddict.jpa.modeler, io.github.jeddict.reveng, io.github.jeddict.orm.generator,  io.github.jeddict.runtime, io.github.jeddict.rest.generator, io.github.jeddict.mvc.generator, io.github.jeddict.infra | friend-packages | JPQL Editor integration in JPA Modeler, persistence.xml updated during source generation |
| org.netbeans.modules:org-netbeans-modules-j2ee-persistence | netbeans\java\j2ee.persistence | org.netbeans.modules.j2ee.persistence.jpqleditor, org.netbeans.modules.j2ee.persistence.jpqleditor.lexer, org.netbeans.modules.j2ee.persistence.jpqleditor.ui, org.netbeans.modules.j2ee.persistence.editor, org.netbeans.modules.j2ee.persistence.editor.completion, org.netbeans.modules.j2ee.persistence.dd.persistence.model_1_0, org.netbeans.modules.j2ee.persistence.dd.persistence.model_2_0, org.netbeans.modules.j2ee.persistence.dd.persistence.model_2_1 | io.github.jeddict.jpa.modeler | export new friend package | JPQL Editor integration in JPA Modeler, To create new persistence.xml |
| org.netbeans.modules:org-netbeans-modules-j2ee-common | netbeans\enterprise\j2ee.common | org.netbeans.modules.j2ee.common, org.netbeans.modules.j2ee.common.dd | io.github.jeddict.jcode.util | friend-packages | Helper utilities classes are used to create web.xml and to identify Java EE features & spec/component version for given project |
| org.netbeans.modules:org-netbeans-modules-db-metadata-model | netbeans\ide\db.metadata.model | org.netbeans.modules.db.metadata.model.api |  io.github.jeddict.jpa.modeler, io.github.jeddict.db.modeler | friend-packages | To visualize Tree-Structured tables from Services > Database in Jeddict modeler |
| org.netbeans.modules:org-netbeans-modules-dbschema | netbeans\java\dbschema | org.netbeans.modules.dbschema | io.github.jeddict.reveng | friend-packages | To create modeler diagram from database connection via reverse engineering |
| org.netbeans.api:org-netbeans-modules-db | netbeans\ide\db | org.netbeans.modules.db.explorer, org.netbeans.modules.db.explorer.node, org.netbeans.modules.db.explorer.sql.editor, org.netbeans.modules.db.explorer.action, org.netbeans.lib.ddl, org.netbeans.lib.ddl.impl, org.netbeans.lib.ddl.util | io.github.jeddict.jpa.modeler, io.github.jeddict.db.modeler, io.github.jeddict.relation.mapper | public-packages | To import Tables from Service > Database in modeler db diagram via drag n drop, To execute db command from db diagram  |
| org.netbeans.modules:org-netbeans-modules-db-core | netbeans\ide\db.core | org.netbeans.modules.db.api.sql.execute | io.github.jeddict.jpa.modeler | friend-packages |  SQL Editor integration in JPA Modeler |
| org.netbeans.modules:org-netbeans-modules-utilities | netbeans\ide\utilities | org.netbeans.modules.openfile | io.github.jeddict.jpa.modeler | friend-packages | To open the generated Java source files directly from modeler |
| org.netbeans.modules:org-netbeans-modules-maven | netbeans\java\maven |org.netbeans.modules.maven.api, org.netbeans.modules.maven.api.customizer, org.netbeans.modules.maven.configurations, org.netbeans.modules.maven.execute.model | io.github.jeddict.jcode.util | friend-packages | To parse or update the project pom during source code generation |
| org.netbeans.modules:org-netbeans-modules-maven | netbeans\java\maven | org.netbeans.modules.maven.configurations | io.github.jeddict.jcode.util | export new friend package | To fetch or update the active maven configuration from nbactions.xml |
| org.netbeans.modules:org-netbeans-modules-maven-model | netbeans\java\maven.model | org.netbeans.modules.maven.model.pom | io.github.jeddict.jcode.util, io.github.jeddict.runtime, io.github.jeddict.rest.generator | friend-packages | To parse or update the project pom during source code generation |
| org.netbeans.modules:org-netbeans-modules-maven-embedder | netbeans\java\maven.embedder | org.codehaus.plexus.util.xml | io.github.jeddict.jcode.util, io.github.jeddict.runtime, io.github.jeddict.rest.generator | friend-packages | To update the project pom during source code generation |

The main features of Jeddict are ORM/DB modeler and source generator (currently only for maven project) hence API access required for the persistence, db, and maven modules.

### CODE REVIEW

**Comment by geertjanw** [comment]
Would be better if the friend request commits were to be separate from the public API commits, and then we can simply merge the first, and we'll need to review the second.

**Comment by jGauravGupta** [comment]
Sure I will create the separate PR for friend request in next couple of days.

**Comment by neilcsmith-net** [comment]
Or even better, open a PR (or discussion thread) to remove the friend-only restrictions from all of those modules!

**Comment by JaroslavTulach** [comment]
Opening up the modules in individual pull requests is probably better plan. Closing.

**Pull request closed without merging**
