### PR TITLE
[NETBEANS-5210] Export code inspection settings

### PR DESCRIPTION
**Pull request by KacerCZ**
https://issues.apache.org/jira/browse/NETBEANS-5210

Inspection settings (from Code > Inspect) can be exported from Tools > Options.
Settings are registered under Miscellaneous > Code Inspections.

### CODE REVIEW

**Comment by KacerCZ** [comment]
Travis failed becaue it run too long.

**Comment by matthiasblaesing** [comment]
There are unittest failures. The failing test can be run with `ant commit-validation`. The results can be then found in  `<nb-checkout>/nbbuild/build/test/commit-validation/results/html/index.html`. I find:

`ValidateLayerConsistencyTest#testFolderOrdering`

```
No warnings relating to folder ordering; cf: http://deadlock.netbeans.org/job/nbms-and-javadoc/lastSuccessfulBuild/artifact/nbbuild/build/generated/layers.txt Not all children in OptionsExport/Advanced/ marked with the position attribute: [CssPreprocessors, Databases, Debugger, Diff, Favorites, Files, HTMLPalette, J2EE, JSPPalette, JavaPlatform, ProjectLibraries, Toolbars, outputOptions], but some are: [Inspections]

junit.framework.AssertionFailedError: No warnings relating to folder ordering; cf: http://deadlock.netbeans.org/job/nbms-and-javadoc/lastSuccessfulBuild/artifact/nbbuild/build/generated/layers.txt
Not all children in OptionsExport/Advanced/ marked with the position attribute: [CssPreprocessors, Databases, Debugger, Diff, Favorites, Files, HTMLPalette, J2EE, JSPPalette, JavaPlatform, ProjectLibraries, Toolbars, outputOptions], but some are: [Inspections]
at org.netbeans.core.validation.ValidateLayerConsistencyTest.assertNoErrors(ValidateLayerConsistencyTest.java:157)
at org.netbeans.core.validation.ValidateLayerConsistencyTest.testFolderOrdering(ValidateLayerConsistencyTest.java:806)
at org.netbeans.junit.NbTestCase.access$200(NbTestCase.java:77)
at org.netbeans.junit.NbTestCase$2.doSomething(NbTestCase.java:476)
at org.netbeans.junit.NbTestCase$1Guard.run(NbTestCase.java:402)
```

**Comment by KacerCZ** [comment]
I've fixed layer.xml so test passed locally.
Thank you.

**Comment by matthiasblaesing** [comment]
This was not tested - I build from source, opened Options, went to Export and directly got:

```
    [exec] Caused: java.util.MissingResourceException: No such bundle org.netbeans.modules.analysis.ui.resources.Bundle
     [exec] 	at org.openide.util.NbBundle.getBundle(NbBundle.java:426)
     [exec] 	at org.openide.util.NbBundle.getBundle(NbBundle.java:358)
     [exec] [catch] at org.netbeans.core.startup.layers.BinaryFS$AttrImpl.getValue(BinaryFS.java:676)
     [exec] 	at org.netbeans.core.startup.layers.BinaryFS$BFSBase.getAttribute(BinaryFS.java:506)
     [exec] 	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:918)
     [exec] 	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:851)
     [exec] 	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:914)
     [exec] 	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:851)
     [exec] 	at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:772)
     [exec] 	at org.netbeans.modules.options.export.OptionsExportModel$Category.getItems(OptionsExportModel.java:626)
     [exec] 	at org.netbeans.modules.options.export.OptionsChooserPanel.createOptionsTreeModel(OptionsChooserPanel.java:431)
     [exec] 	at org.netbeans.modules.options.export.OptionsChooserPanel.access$700(OptionsChooserPanel.java:72)
     [exec] 	at org.netbeans.modules.options.export.OptionsChooserPanel$6.run(OptionsChooserPanel.java:339)
     [exec] ALL [null]: Offending classloader: SystemClassLoader[445 modules]
     [exec] CONFIG [null]: Missing resource from class: org.netbeans.modules.analysis.ui.resources.Bundle
     [exec] SEVERE [global]
     [exec] java.lang.AssertionError: Display name of export option item not defined in layer.
     [exec] 	at org.netbeans.modules.options.export.OptionsExportModel$Category.getItems(OptionsExportModel.java:627)
     [exec] 	at org.netbeans.modules.options.export.OptionsChooserPanel.createOptionsTreeModel(OptionsChooserPanel.java:431)
     [exec] 	at org.netbeans.modules.options.export.OptionsChooserPanel.access$700(OptionsChooserPanel.java:72)
     [exec] [catch] at org.netbeans.modules.options.export.OptionsChooserPanel$6.run(OptionsChooserPanel.java:339)
```

From a quick look the display name was defined in the wrong bundle.

**Comment by KacerCZ** [comment]
Sorry, that's embarassing :(
I tried export/import but somehow I made error in commiting changes.

**Comment by matthiasblaesing** [comment]
Looks good to me. Thank you.

**Comment by KacerCZ** [comment]
Thanks for review.
Please set milestone to 12.3.

**Comment by matthiasblaesing** [comment]
Done - sorry, did not think about it.

**Pull request merged**
