### PR TITLE
[NETBEANS-6217] Allow Convert Visibility Suggestion to be disabled

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-6217

- Convert from SuggestionRule to HintRule

Options:

netbeans-6217-convert-visibility-options

### CODE REVIEW

**Comment by mbien** [comment]
looks good to me

**Comment by junichi11** [comment]
@tmysik Could you please have a look at this? Let's merge it if there is no problem. Thanks!

**Review by tmysik — APPROVED** [review]

**Comment by tmysik** [comment]
@junichi11 Looks good to me, thank you!

**Comment by junichi11** [comment]
@tmysik Thank you, Tomas!

**Pull request merged**
