### PR TITLE
Rust options panel and Cargo executable selection

### PR DESCRIPTION
**Pull request by vieiro**
- Rust Option panel with Cargo subpanel.
- Cargo path is used in Cargo commands.
- When cargo path is not found a Notification is shown to the user, easing opening the options panel focused on Rust/Cargo tab.

---
**^Add meaningful description above**

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

If you're a committer, please label the PR before pressing "Create pull request" so that the right test jobs can run.

### CODE REVIEW

**Comment by mbien** [comment]
I like the icon.

So, when the cargo text field is empty, it will try the default location? If yes I believe the UI should have it right away when the option window opens. 

As minor nitpick: I saw a fairly large vertical scrollbar even though the panel doesn't need one. To prevent this, you can usually make the panel as small as possible till it snaps to default. Once its at default size the layout manager will take over.

**Comment by vieiro** [comment]
Thanks @mbien . Very true! In fact the whole "Find in path" button can be removed.

**Comment by vieiro** [comment]
Well, this should do it. I've also added rust.options to rust.kit.

**Comment by mbien** [comment]
tested again:
 - panel size fixed, yey!
 - unfortunately it can't find cargo now for some reason :( I swear it worked yesterday

**Comment by vieiro** [comment]
>     * unfortunately it can't find cargo now for some reason :( I swear it worked yesterday, as a result clean/build/run do nothing, and the option ui shows a notification that cargo can't be found

Mmm... That's weird. It's working perfectly here. What OS are you using? Does "$HOME/.cargo/bin/cargo" exist for you?

**Comment by mbien** [comment]
```
> whereis cargo
cargo: /usr/bin/cargo /usr/share/man/man1/cargo.1.gz
> cargo --version
cargo 1.67.1
```
`~/.cargo` is empty though.
OS is manjaro linux. It's a bit like arch. 

Did you reset your netbeans conf folder before testing the new build again? (I did)

**Comment by vieiro** [comment]
> `~/.cargo` is empty though. OS is manjaro linux. It's a bit like arch.
> 
> Did you reset your netbeans conf folder before testing the new build again? (I did)

The `Find in path` button is no more (i.e. we don't search in $PATH, just in $HOME/.cargo/bin). You now have to select the `cargo` executable using the "Browse" button. Have you tried that?

imagen

**Comment by mbien** [comment]
@vieiro no i haven't. NB should try to do this automatically IMO, thats what I tried to say with https://github.com/apache/netbeans/pull/5651#issuecomment-1465088003. Why should the user go to options, only to press a button? :)

The options are still useful for configuring non standard paths, e.g for someone who puts a cargo build on a custom location. I remember the very first time I tested your branch it worked out of the box. I could build and run without any options available.

**Comment by vieiro** [comment]
> NB should try to do this automatically IMO

Ah, I see. This is the dilemma of a project automatically executing stuff on one's personal computer without user permission. Modern IDEs request permission from user before running stuff. I'll give it a thought during the week.

**Comment by mbien** [comment]
ah, now I understand your concern! You don't want that NB is running cargo on build, unless the user set the path manually or somehow verified it first.

I believe it is ok to trust default paths. If something is installed in `/usr/bin/cargo` it is probably ok for an IDE to run it. I actually liked the "Find in PATH" button, I was just wondering why I had to press it to fill a text field, the text field could have been filled already for me :)

I am sorry if I caused confusion!

**Comment by vieiro** [comment]
Hi @mbien , I'm not sure how to proceed. I like NetBeans detecting cargo, but let's ask in the mailing list to see how people is doing / wants to do this. Otherwise we may end up with a security problem.

**Comment by vieiro** [comment]
Well, it seems we have consensus on the mailing list. Let's go for it. We now use NbPreferences too.

**Review by mbien — APPROVED** [review]
looks good to me and it found my cargo :)

The get-version button worked too!

I was thinking if the option API should return Path instead of String but it is more a matter of preference and how its used later etc so String is probably fine.

**Comment by vieiro** [comment]
> I was thinking if the option API should return Path instead of String but it is more a matter of preference and how its used later etc so String is probably fine.

Well, that's very true! Good point!

After all, if it looks like a Path, swims like a Path, and quacks like a Path, then it probably is a File. :-).

Let me change that!

**Comment by vieiro** [comment]
Hi @mbien , I think we're ready to merge, right?

**Pull request merged**
