### PR TITLE
[NETBEANS-3649] - Update jruby libraries joni & jcodings

### PR DESCRIPTION
**Pull request by pepness**
Notes:
- Update jcodings from 1.0.18 to 1.0.46
- Update joni from 2.1.11 to 2.1.30

[jcodings Web Page](https://github.com/jruby/jcodings)
[joni Web Page](https://github.com/jruby/joni)

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
With this applied netbeans warns at runtime, that the jcodings.jar is loaded from multiple users. I suggest to create new library module for jcodings and let bytelist and tmlexer both depend on this. @jlahoda  what do you think? You are directly affected, as you had most investment into the textmate lexer.

**Comment by neilcsmith-net** [comment]
@ebarboni given neither PR summary or JIRA issue explain what problem the upgrade is solving, probably safer to push back to 12.1 IMO.

**Comment by neilcsmith-net** [comment]
With branch conflict, comment from @matthiasblaesing and still pending review from @jlahoda I'm bumping this to 12.2, unless anyone wants to fix it up and test?

**Comment by matthiasblaesing** [comment]
@pepness  still interested in this or should this be closed?

**Comment by pepness** [comment]
Directory structure change, I will close this PR and create another one when I re-review the benefits of upgrading these libraries.

**Pull request closed without merging**
