### PR TITLE
Fix bitshfits in the OS constants after the removal of OS_WIN95 and OS_WIN98

### PR DESCRIPTION
**Pull request by lkishalmi**
This PR restores the bit assignment to the OS constants before #4025

### CODE REVIEW

**Comment by lkishalmi** [comment]
I was not able to add @BradWalker to the reviewers, so I mention him here.

**Comment by neilcsmith-net** [comment]
Opened #4498 as alternative option for discussion - either need to revert entirely or patch additional fixes in this PR.

@lkishalmi the typo in your title is fantastic - describes the situation perfectly :laughing:

**Comment by BradWalker** [comment]
Okay, I much prefer to fix the bitshift in the field than revert the changes!

**Comment by lkishalmi** [comment]
> @lkishalmi the typo in your title is fantastic - describes the situation perfectly laughing
Sometimes I have very bad typo days. This PR was created on such a day. I think I typed bitshit at leasr 2 times before filing the PR unintentionally. Well shift happens...

**Comment by neilcsmith-net** [comment]
Closed in favour of full revert of #4025 in #4498

**Pull request closed without merging**
