### PR TITLE
[NETBEANS-1615] fixed @throws hint for type variable

### PR DESCRIPTION
**Pull request by wal-jan**

### CODE REVIEW

**Comment by mbien** [comment]
PR looks good as far as I can tell, @matthiasblaesing could you restart the CI for this one?

**Comment by matthiasblaesing** [comment]
This needs
- the statement from the author, that he donates the change to the ASF
- valid author information (realname and a real email)

**Comment by wal-jan** [comment]
@matthiasblaesing meanwhile Apache foundation acknowledged receipt of my ICLA and I updated my Github profile. Please let me know if missed something else which prevents to remove the "do not merge" label from this PR.

Do I have to create a copy of the Jira issue in Github?

**Comment by neilcsmith-net** [comment]
@wal-jan we don't need an ICLA for you to contribute.  We don't really need a statement from you on donating, actually, as the license covers this already.  However, what we do need is valid author info.

The author line in your commit shows -

```
Author: janw <janw@nowhere>
```

This needs changing to be your real name and an actual email address.

**Comment by wal-jan** [comment]
Fixes https://issues.apache.org/jira/browse/NETBEANS-1615

**Comment by wal-jan** [comment]
I do not have any clue why this test failed on MacOS/JDK 11
```
2022-10-17T20:34:27.4239760Z     [junit] Testcase: org.netbeans.core.validation.ValidateModulesTest:testConsistency:	Caused an ERROR
2022-10-17T20:34:27.4240650Z     [junit] Timeout occurred. Please note the time in the report does not reflect the time until the timeout.
```

**Comment by mbien** [comment]
@wal-jan happens sometimes. I restarted it. Wouldn't worry about it unless it keeps happening.

**Comment by mbien** [comment]
@wal-jan sorry this PR fell a bit under the radar. Would you like to rebase again on top of latest master since we have the `java/javadoc` tests enabled now which means that your new test should run now too.

**Comment by matthiasblaesing** [comment]
Checks are running via https://github.com/apache/netbeans/pull/5245

**Comment by mbien** [comment]
> Checks are running via 5245

good idea. All green over there.

**Pull request merged**
