### PR TITLE
JS CDT Debugger: Improve path handling and remember connection settings

### PR DESCRIPTION
**Pull request by matthiasblaesing**
- JS CDT Debugger: Remember connection settings for remote attach
- JS CDT Debugger: Improve handling of paths
- CDT Protocol allows to store "names" in url fields, which ware not URL compatible and thus break parsing

Closes: #7797

### CODE REVIEW

**Comment by Chris2011** [comment]
@matthiasblaesing will check it tomorrow, thx.

**Comment by Chris2011** [comment]
@matthiasblaesing thx, it seems to work now :)

**Comment by matthiasblaesing** [comment]
@Chris2011 thanks for checking

For anyone else reading: I plan to merge this by next weekend. If anyone want to object, please do so now.

**Comment by matthiasblaesing** [comment]
Just one month late. Lets get this in.

**Pull request merged**
