### PR TITLE
[NETBEANS-5299] Update FlatLaf from 1.0-rc1 to 1.0-rc2

### PR DESCRIPTION
**Pull request by DevCharly**
Updates FlatLaf to latest version to fix `Enter` key regression:
https://issues.apache.org/jira/browse/NETBEANS-5299

https://github.com/JFormDesigner/FlatLaf/releases/tag/1.0-rc2

### CODE REVIEW

**Review by neilcsmith-net — APPROVED** [review]

**Comment by DevCharly** [comment]
Sorry, there were wrong line separators in one file.
Have fixed them and did forced-push.

Also noticed that I forgot to create a separate branch.
The branch in my repo is also named `delivery`.
Is this a problem?

**Comment by neilcsmith-net** [comment]
@DevCharly thanks, was just writing to ask if this was complete? Will be merging things for beta2 tomorrow.

The branch shouldn't be a problem as long as you don't update it before it's merged.

**Review by KacerCZ — APPROVED** [review]
Tested. It fixes the problem.
Thank you.

**Comment by DevCharly** [comment]
> @DevCharly thanks, was just writing to ask if this was complete?

Yes. is now complete.

Tests look better. Some still fail on Travis, but seems not related to this PR. They fail also in other PRs.

**Comment by neilcsmith-net** [comment]
Travis failures are just some usual suspects at the moment.

**Review by geertjanw — APPROVED** [review]

**Pull request merged**
