### PR TITLE
[NETBEANS-2873] Suggest using combined assignment operators

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-2873
e.g.
```php
// ??
$string = $string ?? "value"; // before
$string ??= "value"; // after

// +
$x = $x + 100; // before
$x += 100; // after
```
netbeans-2873-suggest-using-combined-assignment-operators

### CODE REVIEW

**Comment by tmysik** [comment]
@junichi11 Nice, thank you!

**Comment by tmysik** [comment]
@junichi11 Could you please investigate the CI failure? Thank you.

**Comment by junichi11** [comment]
@tmysik It failed because of timeout. I'm not sure about the cause. I'll try to restart the Travis CI build later or tomorrow. Thanks!

**Comment by tmysik** [comment]
@junichi11 I see. OK, thanks!

**Comment by junichi11** [comment]
The Travis CI build passed :) Merging.

**Pull request merged**
