### PR TITLE
Fix cycle in problem reporter with unreachable artifacts.

### PR DESCRIPTION
**Pull request by sdedic**
There was a bug in the loop that causes the values NOT to be cached when the loop exited unsuccessfully, so the detection happened over and over again - computation intensive. This PR makes just one repeated attempt to resolve the artifacts, then reports whatever results are computed.

The reported error was made possible also because simple file-exists check is not enough: in the situation described by #6176, the artifact file physically exists locally (so priming detection evaluated that as an inconsistency and looped again), but is actually refused by Maven, as it is recorded to belong to a remote repository, but was never downloaded from there. The changes to `MavenEmbedder` use EnhancedLocalRepository that checks that thoroughly (the same way as Maven does during build). In addition `MavenEmbedder.resolve()` method never threw exceptions declared in the signature: partly they were swallowed by Maven library (in `DefaultArtifactResolver`) and partially they were ignored if present in `result.getExceptions()` - this affected existing clients that do exception hadling.

### CODE REVIEW

**Comment by mbien** [comment]
the second commit appears to be the cause of the test failures.

I ran a quick local test and they appear to pass using only the first commit. This was no full rebuild and I tested on JDK 20 for time reasons.

**Comment by matthiasblaesing** [comment]
Tested with the original problematic maven project and the constructed testcase from the issue and seems to work as it should. Thank you.

**Comment by sdedic** [comment]
I'll take care of the tests tomorrow / till Monday. Either adapt code (tests) to the suddenly-working artifact resolution, or discard the embedder change.

**Comment by mbien** [comment]
adding all-tests label since who knows what else uses the embedder/model indirectly

**Review by mbien — APPROVED** [review]

**Review by matthiasblaesing — APPROVED** [review]
Checked again and still works :+1: 

The behavioral change of the `#resolve` method seems reasonable as both exceptions are checked exceptions so users are clearly warned. The code indicated, that the exception should have been thrown, so the fix brings the code into the intended line.

**Review by dbalek — APPROVED** [review]

**Comment by mbien** [comment]
thanks everyone, merging in an hour or two so that it doesn't miss the deadline.

**Pull request merged**
