### PR TITLE
[NETBEANS-3807] - cleanup ArrayList rawtype warnings..

### PR DESCRIPTION
**Pull request by BradWalker**
This change cleans up the following warning..

   [repeat] /home/bwalker/src/netbeans/webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java:1454: warning: [rawtypes] found raw type: ArrayList
   [repeat]             private List<VarNode> declaredVars = new ArrayList();
   [repeat]                                                      ^
   [repeat]   missing type arguments for generic class ArrayList<E>
   [repeat]   where E is a type-variable:
   [repeat]     E extends Object declared in class ArrayList

### CODE REVIEW

**Comment by eirikbakke** [comment]
Removing build warnings is an "honorable cause"; thank you!

**Comment by ebarboni** [comment]
@eirikbakke can you please revert. 
Would be nice to wait until vote is finished and a few mandatory commit are done then will I, will tell dev list that we can merge again.

**Comment by eirikbakke** [comment]
Oh, sorry--didn't realize merges here impacted the ongoing release. Feel free to revert.

**Comment by eirikbakke** [comment]
Or I can revert myself, hold on...

**Comment by eirikbakke** [comment]
Revert done. Sorry about that.

**Comment by eirikbakke** [comment]
Oh, now I see that github has it's own "Revert" button here. I did it manually through the command-line client, so the revert won't show up on this PR. I'll have to reapply the patch at a later date.

**Pull request merged**
