### PR TITLE
Revert "Use resolve() method that actually throws exception."

### LINKED ISSUE #6222: ArtifactResolutionExceptions when working with certain maven projects
### Apache NetBeans version

Apache NetBeans 19 rc 1

### What happened

Tried to open the parent project of https://github.com/apache/maven-indexer/ and got several exceptions. The exceptions already start before the project is open, as soon it is selected in the project open dialog (NB is loading the model to try to find sub projects).

Once the project is open the exceptions will keep showing up while working with the pom etc.

```
[org.netbeans.modules.project.ui.ProjectChooserAccessory$ModelUpdater] INFO org.eclipse.aether.internal.impl.DefaultArtifactResolver - Artifact org.apache:apache:pom:29 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [apache.snapshots (https://repository.apache.org/snapshots, default, snapshots)]
SEVERE [org.openide.util.Exceptions]
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache:apache:pom:29
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:450)
Caused: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.apache:apache:pom:29 (present, but unavailable): Could not find artifact org.apache:apache:pom:29
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:242)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:277)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:197)
Caused: org.apache.maven.artifact.resolver.ArtifactNotFoundException: The following artifacts could not be resolved: org.apache:apache:pom:29 (present, but unavailable): Could not find artifact org.apache:apache:pom:29

  org.apache:apache:pom:29

from the specified remote repositories:
  apache.snapshots (https://repository.apache.org/snapshots, releases=false, snapshots=true)

	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:200)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveAlways(DefaultArtifactResolver.java:152)
	at org.netbeans.modules.maven.embedder.MavenEmbedder.resolve(MavenEmbedder.java:380)
[catch] at org.netbeans.modules.maven.embedder.NBRepositoryModelResolver.resolveModel(NBRepositoryModelResolver.java:74)
	at org.netbeans.modules.maven.embedder.NBRepositoryModelResolver.resolveModel(NBRepositoryModelResolver.java:88)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1009)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:801)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:327)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:243)
	at org.netbeans.modules.maven.embedder.impl.NBModelBuilder.build(NBModelBuilder.java:53)
	at org.netbeans.modules.maven.embedder.MavenEmbedder.executeModelBuilder(MavenEmbedder.java:445)
	at org.netbeans.modules.maven.NbMavenProjectImpl.getRawModel(NbMavenProjectImpl.java:216)
	at org.netbeans.modules.maven.api.NbMavenProject.getRawModel(NbMavenProject.java:392)
	at org.netbeans.modules.maven.MavenProjectPropsImpl.lambda$get$0(MavenProjectPropsImpl.java:93)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:188)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.modules.maven.MavenProjectPropsImpl.get(MavenProjectPropsImpl.java:78)
	at org.netbeans.modules.maven.MavenProjectPropsImpl.get(MavenProjectPropsImpl.java:74)
	at org.netbeans.modules.maven.MavenProjectPropsImpl$PackagingProviderImpl.packaging(MavenProjectPropsImpl.java:306)
	at org.netbeans.modules.maven.api.NbMavenProject.getPackagingType(NbMavenProject.java:378)
	at org.netbeans.modules.maven.NbMavenProjectImpl$PackagingTypeDependentLookup.check(NbMavenProjectImpl.java:1050)
	at org.netbeans.modules.maven.NbMavenProjectImpl$PackagingTypeDependentLookup.<init>(NbMavenProjectImpl.java:1008)
	at org.netbeans.modules.maven.NbMavenProjectImpl.<init>(NbMavenProjectImpl.java:274)
	at org.netbeans.modules.maven.NbMavenProjectFactory.loadProject(NbMavenProjectFactory.java:98)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.createProject(NbProjectManager.java:376)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.access$300(NbProjectManager.java:69)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:289)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:218)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:188)
	at org.openide.util.Mutex.readAccess(Mutex.java:232)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:218)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:142)
	at org.netbeans.modules.project.ui.OpenProjectList.fileToProject(OpenProjectList.java:1257)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.getProject(ProjectChooserAccessory.java:363)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.access$000(ProjectChooserAccessory.java:67)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory$1.run(ProjectChooserAccessory.java:236)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

### How to reproduce

open the above mentioned project

### Did this work correctly in an earlier version?

18

### Operating System

linux

### JDK

20

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

_No response_

### Are you willing to submit a pull request?

Maybe

### PR DESCRIPTION
**Pull request by mbien**
This reverts commit e2a14bf32a5bddabee71e0fc2e35f575f7d1aacc, targets delivery

fixes #6222 ArtifactResolutionExceptions when working with maven projects

regression reproducible in RC1, see issue

### CODE REVIEW

**Comment by sdedic** [comment]
I don't think that just throwing out a change is a good idea; without the change, the `resolve` method actually does not report ArtifactNotFound resolution failures (it returns artifacts that have isResolved() == false) and does not respect well recorded artifact origin (which was the reason for changing the implementation). In addition, the reason of inability to resolve the artiact (isResolved() == false) is discarded during the course.

I an on vacation, and not really able to make a change until Sun 23; an option would be to have two `resolve()` methods - one broken retaining the old behaviour, the other the corrected one

**Comment by mbien** [comment]
I am sure there are good reasons to propagate the exception down to the API users but this can't be simply enabled without making sure all API users are prepared for this change. Thats why this is causing regressions. I don't want to start fixing things during the RC phase, we can apply this again for NB 20 and stabilize is there.

**Comment by neilcsmith-net** [comment]
> I don't think that just throwing out a change is a good idea;

Personally, I'm in favour of fast revert on regression, on both master (which is always meant to be release ready) and especially on delivery.  Then introduce the corrected change via another PR taking care to review against the regression.  Otherwise, some things become harder to revert later.

In short, +1 to this PR, and we should take this approach more often.

**Review by matthiasblaesing — APPROVED** [review]
I build this branch and my test cases still load clean (no excessive CPU use).

For the stacktrace I think the non-throwing behavior of `MavenEmbedder#resolve` masked a bug in `NBRepositoryModelResolver.resolveModel`, but I agree, getting this back into the know state is better, than having this bug.

**Review by neilcsmith-net — APPROVED** [review]
Tested the dev build with a few clean starts and seems to address issues I was seeing when opening projects.

**Pull request merged**
