### PR TITLE
[NETBEANS-1295] Add groovy to release config

### PR DESCRIPTION
**Pull request by svenreimers**

### CODE REVIEW

**Comment by geertjanw** [comment]
Should Grails project template be hidden or deleted or is its version not too old?

**Comment by geertjanw** [comment]
Also, there is a Travis problem here, can you investigate.

**Comment by svenreimers** [comment]
Looks like there is a problem with a test dependency to some stuff in enterprise cluster. What is the deal with running unit / function-qa tests on Jenkins?

**Comment by svenreimers** [comment]
Reason is:
```
 [nb-javac] /home/travis/build/apache/incubator-netbeans/groovy/groovy.kit/test/qa-functional/src/org/netbeans/modules/groovy/qaf/GrailsTestCase.java:28: error: package org.netbeans.jellytools.modules.j2ee.nodes does not exist
 [nb-javac] import org.netbeans.jellytools.modules.j2ee.nodes.J2eeServerNode;
 [nb-javac]                                                  ^
 [nb-javac] 1 error
```

Seems groovy cluster needs also enterprise cluster - at least for some tests. (Taken from travis output)
How to take this further?

**Comment by sdedic** [comment]
@geertjanw: is the issue number correct ? NETBEANS-1296 talks about AutoUpdate

**Comment by svenreimers** [comment]
Sorry wrong number, I just fixed the issue in the PR number.

**Comment by svenreimers** [comment]
Any objections to merge? According to e-mail I think we are now good to go.

**Comment by geertjanw** [comment]
No objections, you've done all the work, jumped through the hoops, got everything done in time, so let's go for it.

**Pull request merged**
