### PR TITLE
Jdk13 text block support

### PR DESCRIPTION
**Pull request by rtaneja1**

### CODE REVIEW

**Comment by geertjanw** [comment]
Please merge when you're ready to include this @rtaneja1.

**Comment by junichi11** [comment]
@jlahoda PHP editor unit test[1] seems to fail after this change(ide/editor.lib/src/org/netbeans/editor/BaseKit.java).

[1] https://github.com/apache/netbeans/blob/0580490be48a9a2ec6279218fd0e39561affdab8/php/php.editor/test/unit/src/org/netbeans/modules/php/editor/typinghooks/PhpTypedTextInterceptorTest.java#L645-L647

**Comment by jlahoda** [comment]
@juneau001 - I'll take a look.

**Comment by junichi11** [comment]
@jlahoda Thank you! I'm not sure but `ide/editor.indent` may be also related. (Maybe changes of editor area.)

**Comment by junichi11** [comment]
Submitted it as a new issue: https://issues.apache.org/jira/browse/NETBEANS-3085

**Pull request merged**
