### PR TITLE
[NETBEANS-5682] - cleanup more of the raw type iterator warnings..

### PR DESCRIPTION
**Pull request by BradWalker**
I've been away for a little while due to life happening.. But, the Netbeans Rust Remover is back.. 8-)

This issue cleans up more of the raw type iterator warnings..

   [repeat] /home/bwalker/src/netbeans/enterprise/web.freeform/src/org/netbeans/modules/web/freeform/ui/NewWebFreeformProjectWizardIterator.java:111: warning: [rawtypes] found raw type: Iterator
   [repeat]                         Iterator iter = webModules.iterator();
   [repeat]                         ^
   [repeat]   missing type arguments for generic class Iterator<E>
   [repeat]   where E is a type-variable:
   [repeat]     E extends Object declared in interface Iterator

### CODE REVIEW

**Comment by BradWalker** [comment]
Please DO NOT integrate this after approval. I want to test my new commit privileges to make sure I know what I'm doing..

Thanks.

**Review by mklaehn — APPROVED** [review]
Nice. All changes method internal.
A few explicit casts will become redundant by this change

**Comment by BradWalker** [comment]
> Nice. All changes method internal.
> A few explicit casts will become redundant by this change

Hey @mklaehn , I agree some casts will become redundant.. I have another change that will clean up a LOT of the redundant casts. I'm waiting to do that all at once.

Thanks for the approval!

**Comment by ebarboni** [comment]
hi @BradWalker would you try to merge using your commiter privilege?

**Comment by BradWalker** [comment]
> hi @BradWalker would you try to merge using your commiter privilege?

Hey @ebarboni , sorry to be such a slacker.. Busy summer with family.. I will get this done within the next day..

**Comment by ebarboni** [comment]
No problemo, feel free to merge your others approved PR.

**Comment by BradWalker** [comment]
> No problemo, feel free to merge your others approved PR.

Hey @ebarboni , thanks very much for the help today!! That was exactly what I needed..

**Pull request merged**
