### PR TITLE
Exclude last line from fold block.

### LINKED ISSUE #6504: Unable to unfold code block in java editor
### Apache NetBeans version

Apache NetBeans 19

### What happened

When folding the if part of an if/else statement the if part becomes impossible to unfold. This only happens if the else is on the same line as the closing curly brace.

image

image

### How to reproduce

Just open a file with a if/else statement where the else is on the same line as the closing curly brace of the if.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Fedora 38

### JDK

OpenJDK 64-Bit Server VM 11.0.20+8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

_No response_

### Are you willing to submit a pull request?

Yes

### PR DESCRIPTION
**Pull request by zephyrgr**
This fixes #6504

### CODE REVIEW

**Comment by mbien** [comment]
i think this is a good hotfix for the linked issue, however this makes it look ugly in some situations.
If someone formats the code like this:
```java
if (asdf)
{
    // asdf
}
```
the closing `}` will always remain visible when folded. One way to solve this would be to check if the closing token stands alone in that line or not. If it is alone, add it to the fold like before, if it is not, keep it outside the fold like in this fix - but that would be more work most likely.

@dbalek do we have any code folding tests?

**Comment by zephyrgr** [comment]
Hello @mbien.

I've been exploring a little bit more and I think I found a solution that does what you mentioned, if the closing token is alone in the line it is included in the fold, if it has other tokens in the same line it is excluded from the fold.

The problem with this solution is that if the line were the block ends is empty , it is not hidden when the fold is collapsed.

image

It looks to me that this problem is not related to my changes but to how the collapsing works.

How should I proceed?

**Review by mbien — APPROVED** [review]
I think it is fine to merge it as is for now since:
 - it fixes the original problem of not being able to expand the folds again
 - the new issue is just a visual issue happening with "opening brace on next line" formatting
 - "opening brace on next line" formatting is less common than the "on same line" formatting

**Comment by Chris2011** [comment]
This is confusing. It shows "{ ... n lines }" and there is still the last } seen in the code. I'm not really for it to merge. We should remove both brackets from the folded stuff that means that the first braket should be there too, becuase it will confusing of brackets matching.

**Comment by mbien** [comment]
as mentioned in https://github.com/apache/netbeans/pull/6541#issuecomment-1751681361 the closing bracket is only a problem if it stands alone in the line. Since this improves the situation significantly since the user can't be locked out anymore from opening the folds, I am ok with merging this as hotfix.

There is still time before feature freeze, there is also the option to revert the commit which added folding for inner blocks for NB 20 if no satisfying solution can be found.

image


however:
>  I would try to get rid of the first bracket of the fold and also get rid of both bracktes from the folded part "{ ... 3 lines }" should be just "... 3 lines"

this is off topic, it is just the indicator that a block is folded and has nothing to do with folding issues and should be discussed separately if needed.

**Comment by sdedic** [comment]
I don't like the solution - while it hides opening brace, it shows the paired one. In addition, folding itself is not blocked - one can do CTRL+ plus on a folded method's declaration (modifiers, name) to unfold. 

So the really buggy thing is just the indicator (appearance) and its handling.

I would suggest to add a different indicator in this case, to signal that both operations are possible. In addition, if the expand sign handler just gives a preference to "expand" (now it prefers collapse, if there are more options on the same line), it could be satisfactory.  If not, then I suggest to enhance the handler so that it recognizes some modifier (shift ?) and od expand or collapse, depending on it.

I've just briefly checked IntelliJ and vscode.
- IntelliJ shows just "expand" marker if there are both collapsed and expanded fold regions on the line. Clicking it expands the 1st folded region
- vscode leaves BOTH {} visible, replaces just the content.

I'd prefer the IntelliJ way :)

**Comment by mbien** [comment]
@sdedic yeah I had similar thoughts here https://github.com/apache/netbeans/issues/6504#issuecomment-1741878426, I think that when the expand action is given an higher priority than collapse, most of this issue is already solved.

**Comment by Chris2011** [comment]
I would like not to do the shift indicator because we can use it for another type of collapsing/expanding. In VS Code or IntelliJ u can use shift + alt to expand/collapse everything else except from that where you clicked on. So expand/collapse should be a normal operation with one click and nothing else as in all  editors. There is no need to use another key to just handle this normal behaviour.

For IntelliJ there is one more thing to know, that they have also an indicator to expand/collapse on the closing bracket which seems also need if you have long code parts.

But for me i prefer the VS Code way to not include the braces into the fold state. So maybe an option is better than some hardcoded stuff as you can see, we have different preferences. And if we can't find the best way, I'm for an option.

**Comment by Chris2011** [comment]
I also need to say that IntelliJ with the legacy UI has this feature, the new UI has an arrow similar to vs code.

**Comment by mbien** [comment]
code folding to me is a visual aid to collapse lines of code vertically to parse code faster in some situations.
collapsing a try-catch with 3 catches becomes this in NB 19:
image

With this patch applied we get this:
image

all visual arguments aside (if it should show brackets in the placeholder or not), one of the two is useful the other is not in my opinion :)

**Comment by Chris2011** [comment]
I already had a look into the code and we should make it consistent for all languages. Here it is just for Java, but it should be also changed int the CSL or GSF? Somewhere, for JS, JSON, PHP, CSS + preprocessor supported langs, etc.

**Review by neilcsmith-net — CHANGES_REQUESTED** [review]
Given this was not merged as a hot fix, and that I agree with @sdedic comments, removing from milestone pending rethought.

**Comment by zephyrgr** [comment]
Ok @neilcsmith-net. I still want to try and fix this problem but I'll need some pointers.

**Comment by Chris2011** [comment]
Hey @zephyrgr can you tell us why you just closed the pr? What was the adventure for you? Can we help here somewhere?

**Comment by zephyrgr** [comment]
@Chris2011 I deleted it by mistake.

**Comment by Chris2011** [comment]
Do you still nSo we can reopen the PR? Do you need help here?

**Pull request closed without merging**
