### PR TITLE
fix wrong maven dependency versions in binariesembedded-list.

### PR DESCRIPTION
**Pull request by mbien**

### CODE REVIEW

**Comment by ebarboni** [comment]
@mbien I'm very sorry for the overhead. 

groupid  for commons-codec is wrong should be commons-codec:commons-codec:1.11 (not seen commons-codec in org.apache.commons)
groupid for org.aopalliance is wrong should be aopalliance:aopalliance:1.0 (not seen org.aopalliance in the central repo)
typo too many : in the maven-resolver-provider should be org.apache.maven:maven-resolver-provider:3.9.1 (if I'm correct)

**Comment by mbien** [comment]
updated

**Review by ebarboni — APPROVED** [review]

**Comment by mbien** [comment]
quickly wrote a util which generates a maven dependency section:
```java
    public static void main(String[] args) throws IOException {
        Path path = Path.of("/home/mbien/NetBeansProjects/netbeans/java/maven.embedder/external/binariesembedded-list");
        try(Stream<String> lines = Files.lines(path)) {
            // 321C614F85F1DEA6BB08C1817C60D53B7F3552FD;org.fusesource.jansi:jansi:2.4.0
            lines.filter(l -> !l.startsWith("#") && l.contains(";"))
                 .map(l -> l.substring(l.indexOf(';')+1))
                 .forEach(l -> {
                String[] comp = l.split("\\:");
                System.out.println(
                                """
                                        <dependency>
                                            <groupId>%s</groupId>
                                            <artifactId>%s</artifactId>
                                            <version>%s</version>
                                        </dependency>
                                """.formatted(comp[0], comp[1], comp[2]));
            });
            
        }
    }
```
then pasted it into a project and hit clean build. This found another typo which I fixed.

**Comment by neilcsmith-net** [comment]
@mbien you and me both in different ways! :smile: https://github.com/apache/netbeans/compare/master...neilcsmith-net:netbeans:fix-binaries-embedded-version

Please consider the test task update - run using `ant -f java/maven.embedder/ checkhash`.  It should now pick up wrong filenames as well as missing hashes.

**Comment by mbien** [comment]
applied the changes to the ant task. We should probably store the dependencies in a pom right away and let ant parse it :)

gives us editor support and error checks for free.

**Comment by neilcsmith-net** [comment]
Thanks. Well, I'd certainly like to generate the list and hashes from the info in the jars. A job for NB19!

@ebarboni is the checkhash task run at any point?

**Comment by mbien** [comment]
requesting a sync back to master once its on delivery so that I can do the same thing again for maven 3.9.2 in the other PR

**Comment by neilcsmith-net** [comment]
Don't worry.  Anything added to delivery until the release will be synced to master.  May be a few days, until after 18-rc4 is built.

**Comment by ebarboni** [comment]
checkhash is to be run manually If I remember well. Helper only.

But the javax.annotation is generated well on the pom because hash is populated first bcevause getallmavencoordinate build a concat of every binaries-list + binariesembeded-list. I guess first found first returned.

I think downloading with "normal" download of external should fail also. it could be an option maybe.

**Comment by ebarboni** [comment]
in nbbuild/build.xml

```
<target name="download-all-extbins" unless="ext.binaries.downloaded" depends="bootstrap">
    <echo>Downloading external binaries (*/external/ directories)...</echo>
    <!-- optionnal reporttofile used to speed resolving artefacts resolution for maven artefacts -->
    <downloadbinaries cache="${binaries.cache}" server="${binaries.server}" repos="${binaries.repos}"  >
        <manifest dir="${nb_all}">
            <include name="**/external/binaries-list"/>
            <include name="**/external/binariesembedded-list"/>
        </manifest>
    </downloadbinaries>
    <property name="ext.binaries.downloaded" value="true"/>
  </target>
```

this task is the one used mostly during build => may be hacked too but have to understand it first ;D
```
 <target name="download-selected-extbins" unless="ext.binaries.downloaded" depends="init-module-list">
    <echo>Downloading external binaries (*/external/ directories) for cluster.config=${cluster.config}...</echo>
    <pathconvert property="modules.binaries-list" pathsep=",">
        <path>
            <dirset dir="${nb_all}" includes="nbbuild,${allmodules}"/>
        </path>
        <map from="${nb_all}/" to=""/>
        <globmapper from="*" to="*/external/binaries-list"/>
    </pathconvert>
    <downloadbinaries cache="${binaries.cache}" server="${binaries.server}" repos="${binaries.repos}">
        <manifest dir="${nb_all}" includes="${modules.binaries-list}"/>
    </downloadbinaries>
  </target>
```

**Comment by neilcsmith-net** [comment]
@ebarboni well, we could also change the extraction task in `maven.embedder` to run the test?

```xml
    <target name="-release.files" depends="projectized.-release.files">
        <mkdir dir="${cluster}/maven"/>
        <unzip src="external/${bundled.maven}-bin.zip" dest="${cluster}/maven">
            <mapper type="glob" from="${bundled.maven}/*" to="*"/>
        </unzip>
        <taskdef name="checkjarssha1" classname="org.netbeans.nbbuild.extlibs.CheckEmbeddedBinaries" classpath="${nbantext.jar}"/>
        <mkdir dir="build/tmptesting"/>
        <unzip src="external/${bundled.maven}-bin.zip" dest="build/tmptesting">
            <patternset>
                <include name="**/*.jar"/>
            </patternset>
            <mapper type="flatten"/>
        </unzip>
        <checkjarssha1 dir="build/tmptesting" shalist="external/binariesembedded-list" />
        <delete dir="build/tmptesting"/>
    </target>
```

**Comment by neilcsmith-net** [comment]
Anyway, for delivery are we OK we this as it stands now?

**Comment by mbien** [comment]
should be correct now
 - we know that the coordinates work with the help of the pom
 - the task checks the hashes
 - the zip has 48 jars, the list has 48 entries

**Pull request merged**
