### PR TITLE
[NETBEANS-5772] replace dashes with underscores

### PR DESCRIPTION
**Pull request by nigjo**

### CODE REVIEW

**Comment by ebarboni** [comment]
it builds, not sure the impact of the changes asking @JaroslavTulach for a review

**Comment by JaroslavTulach** [comment]
The change itself looks OK. It would be good to have a test somewhere to ensure the positive effect of the change remains. A sample project using such OSGi bundle, perhaps?

**Comment by nigjo** [comment]
I'm also trying to create tests for the AutoupdateInfoParser

**Review by JaroslavTulach — APPROVED** [review]
Replacing `-` with `_` is correct. Tests are written. I agree with integration. I've added Matthias to review the code as well. He is the author of most recent significant contributions to update centers infrastructure.

**Review by matthiasblaesing — APPROVED** [review]
I'm not that deep into the OSGI part of the NetBeans infrastructure, but I eyeballed the change and checked in the other OSGI related places in the codebase and it looks like this behavior brings the autoupdate code in line with the rest of the codebase.

There should be no backwards compatibility problem, as that would have crashed in other locations. So LGTM. Thank you.

**Comment by matthiasblaesing** [comment]
@nigjo If I remember correctly, this is not your first contribution, so you are aware, that we assume that agree to donate the contribution to the ASF. If that is so, please squash the two commit into one, then one of the committers will integrate, if noone beats me to it, I'm willing to do it.

**Comment by nigjo** [comment]
I am sorry, but git is not my home tool and I am failing to squash anything. (tried in another PR, sorry)

**Comment by matthiasblaesing** [comment]
@nigjo do you have "Allow edits from maintainers" checked for this PR? See: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

If not, please enable - I tried to squash and push the change to your repository, but it gets rejected by github.

**Comment by nigjo** [comment]
grafik
The option is enabled (did not change the default)

**Comment by nigjo** [comment]
I managed to squash the commits. Should be ready to merge.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing aside - check you're not using refs/pull for this https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#error-failed-to-push-some-refs

**Comment by matthiasblaesing** [comment]
@nigjo I saw the squash yesterday, but the automatic tests were not yet green - fixed now. As before: I assume you are the author of the change and are aware, that you donate the changes to the ASF. Thank you.

@neilcsmith-net thank you for the pointer I might see where I went wrong, will try next time again.

**Pull request merged**
