### PR TITLE
Cleanup redundant casts

### PR DESCRIPTION
**Pull request by BradWalker**
The compiler is warning us we have many redundant casts.

They look like this.
```
[repeat] /home/bwalker/src/netbeans/platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/naming/NamingFactory.java:253: warning: [cast] redundant cast to FileNaming
 [repeat] FileNaming cachedElement = (ref != null) ? (FileNaming) ref.get() : null;
 [repeat] 
```

So just simply clean it up..

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@BradWalker I'm currently working through this - one request: Don't merge branches after you created a PR (if not for a very good reason). I tried to rebase your patch and the merge of Erics branch makes it unnessary difficult.

**Comment by matthiasblaesing** [comment]
Merged via https://github.com/apache/netbeans/commit/f1592df218c1add0f4088c0cb2f58eed02f649d4. Thank you.

I'm not sure if I asked about it in the past - you are doing valuable work and I understood, that you plan to continue. It would be helpful if you could get a ICLA on file. See here: https://www.apache.org/licenses/contributor-agreements.html

**Comment by BradWalker** [comment]
Hey @matthiasblaesing thanks for the feedback! Also, I filed an ICLA this weekend, FYI.

**Comment by matthiasblaesing** [comment]
@BradWalker great! Thank you.

**Pull request closed without merging**
