### PR TITLE
NETBEANS-4533 : Netbeans 4533 chinese char problem table header

### PR DESCRIPTION
**Pull request by adrienDG**

### CODE REVIEW

**Comment by lkishalmi** [comment]
Just some info from the issue here:
Please note that this is a duplicate of a bug already logged in the old Bugzilla : https://bz.apache.org/netbeans/show_bug.cgi?id=270091

**Comment by lkishalmi** [comment]
Checked the email address, it seems to be correctly provided. I'm going to merge this.
Thank you for your contribution!

**Comment by lkishalmi** [comment]
@adrienDG could you make your email public on github? Squash and merge produces: 72509841+adrienDG@users.noreply.github.com email address in the repository.

**Comment by adrienDG** [comment]
> @adrienDG could you make your email public on github? Squash and merge produces: [72509841+adrienDG@users.noreply.github.com](mailto:72509841+adrienDG@users.noreply.github.com) email address in the repository.
I changed my settings, it is now public.
Are we not supposed to close the related issue? Do you know in which release it will be available?
Thanks!

**Comment by lkishalmi** [comment]
I need to revert this change. You need to file a new PR. I'm sorry for the inconveniences.

**Comment by adrienDG** [comment]
I'll create a new PR. Can I know what is the problem with the merge please?

**Pull request merged**
