### PR TITLE
Updating GPL-2 license

### PR DESCRIPTION
**Pull request by geertjanw**
Should be the same as this: https://hg.netbeans.org/main/nb-java-x/file/tip/LICENSE

### CODE REVIEW

**Comment by geertjanw** [comment]
For changes to this file vs the previous that was here, see the diffs here:

https://hg.netbeans.org/main/nb-java-x/log/tip/LICENSE

**Comment by matthiasblaesing** [comment]
I only had a quick look at this, but am I right, that the only content change is the substitution of Sun with Oracle? That would make sense. 

For the test failure - the licenses of external files also need to be updated:

/home/travis/build/apache/netbeans/nbbuild/build.xml:1614: Failed VerifyLibsAndLicenses test(s):

Some license files have incorrect headers

extra/libs.javafx.linux/external/javafx-linux-13-license.txt
extra/libs.javafx.macosx/external/javafx-mac-13-license.txt
extra/libs.javafx.win/external/javafx-win-13-license.txt
java/libs.javacapi/external/nb-javac-13-api-license.txt
java/libs.javacimpl/external/nb-javac-13-impl-license.txt 
java/libs.jshell.compile/external/jshell-9-license.txt
nbbuild/external/langtools-9-license.txt 
nbbuild/external/sigtest-maven-plugin-1.2-license.txt
platform/javahelp/external/jhall-2.0_05-license.txt
platform/libs.javafx/external/lib-javafx-13.03-beta-license.txt

**Comment by jlahoda** [comment]
FWIW, fixed the copies of the license in the -license files. Sorry, I always forget about the duality.

I believe the intent is that the only changes should be Sun->Oracle and a change in the FSF address.

**Comment by ebarboni** [comment]
merging to beta2

**Pull request merged**
