### PR TITLE
Interpret profiles and property definitions from .mvn/maven.config when present

### PR DESCRIPTION
**Pull request by jglick**
Motivated by [JENKINS-50696](https://issues.jenkins-ci.org/browse/JENKINS-50696) and [JEP-305](https://github.com/jenkinsci/jep/blob/master/jep/305/README.adoc#setup). See [MNG-5767](https://issues.apache.org/jira/browse/MNG-5767) and [release notes](https://maven.apache.org/docs/3.3.1/release-notes.html#JVM_and_Command_Line_Options): a `.mvn/maven.config` file will be interpreted when command-line `mvn` is run, so the NetBeans project model ought to honor this as well.

### CODE REVIEW

**Comment by geertjanw** [comment]
Great. Any reasons not to merge?

**Comment by ebarboni** [comment]
not at all

**Comment by matthiasblaesing** [comment]
I extended the unittest a bit and I think it misses cases, and thus the parser also misses cases:
- long argument names (I would consider it good practice to use these in config files)
- spaces between short option character and value
- multiple profiles separated by coma

I think this should cover most cases, though is is still missing the handling of quote characters and disabled profiles.

```diff
--- a/java/maven/test/unit/src/org/netbeans/modules/maven/NbMavenProjectImplTest.java
+++ b/java/maven/test/unit/src/org/netbeans/modules/maven/NbMavenProjectImplTest.java
@@ -32,9 +32,11 @@
 import org.netbeans.api.project.ProjectManager;
 import org.netbeans.junit.NbTestCase;
 import org.netbeans.junit.RandomlyFails;
+import org.netbeans.modules.maven.api.NbMavenProject;
 import org.netbeans.modules.projectapi.nb.TimedWeakReference;
 import org.netbeans.spi.project.LookupMerger;
 import org.netbeans.spi.project.ProjectServiceProvider;
+import org.netbeans.spi.project.ProjectState;
 import org.openide.filesystems.FileObject;
 import org.openide.filesystems.FileUtil;
 import org.openide.filesystems.test.TestFileUtils;
@@ -149,7 +151,10 @@
                 + "<properties><java>1.5</java></properties>"
                 + "<build><plugins><plugin><artifactId>maven-compiler-plugin</artifactId><version>2.1</version>"
                 + "<configuration><source>${java}</source></configuration></plugin></plugins></build>"
-                + "<profiles><profile><id>new</id><properties><java>1.6</java></properties></profile></profiles>"
+                + "<profiles>"
+                + "<profile><id>new</id><properties><java>1.6</java></properties></profile>"
+                + "<profile><id>new2</id><properties><java>1.6</java></properties></profile>"
+                + "</profiles>"
                 + "</project>");
         FileObject source = TestFileUtils.writeFile(wd, "src/main/java/p/C.java", "package p; class C {}");
         ((NbMavenProjectImpl) ProjectManager.getDefault().findProject(wd)).attachUpdater();
@@ -158,9 +163,25 @@
         TestFileUtils.writeFile(wd, ".mvn/maven.config", "-Pnew");
         assertEquals("1.6", slqr.getSourceLevel());
         wd.getFileObject(".mvn/maven.config").delete();
+        TestFileUtils.writeFile(wd, ".mvn/maven.config", "-P new");
+        assertEquals("1.6", slqr.getSourceLevel());
+        wd.getFileObject(".mvn/maven.config").delete();
+        TestFileUtils.writeFile(wd, ".mvn/maven.config", "--activate-profiles new");
+        assertEquals("1.6", slqr.getSourceLevel());
+        wd.getFileObject(".mvn/maven.config").delete();
+        TestFileUtils.writeFile(wd, ".mvn/maven.config", "--activate-profiles new,new2");
+        assertEquals("1.6", slqr.getSourceLevel());
+        wd.getFileObject(".mvn/maven.config").delete();
         assertEquals("1.5", slqr.getSourceLevel());
         TestFileUtils.writeFile(wd, ".mvn/maven.config", "-Djava=1.7");
         assertEquals("1.7", slqr.getSourceLevel());
+        wd.getFileObject(".mvn/maven.config").delete();
+        TestFileUtils.writeFile(wd, ".mvn/maven.config", "-D java=1.7");
+        assertEquals("1.7", slqr.getSourceLevel());
+        wd.getFileObject(".mvn/maven.config").delete();
+        TestFileUtils.writeFile(wd, ".mvn/maven.config", "--define java=1.7");
+        assertEquals("1.7", slqr.getSourceLevel());
+        wd.getFileObject(".mvn/maven.config").delete();
     } 
 }
```

**Comment by jglick** [comment]
BTW if you have small changes to propose in a PR, use GH’s suggested edit feature; for larger changes, rather than pasting in a patch you can just file a PR against the author’s fork proposing your own additional commits that can be merged in or not.

In this case I will adopt a variant of your test to make it a bit stronger. Thanks!

**Pull request merged**
