### PR TITLE
[NETBEANS-3999] - Upgrade GraalVM from 19.3.0 to 19.3.1

### PR DESCRIPTION
**Pull request by pepness**
Notes:
- 13 Fixed Bugs
- 7 Improvements
- Update Java to 8u241 for Java 8 based GraalVM
- Update Ruby to 2.6.5
- Update Node.js to 12.14.0

[GraalVM Web Page](https://www.graalvm.org/)
[GraalVM Release Notes](https://www.graalvm.org/docs/release-notes/19_3/)

### CODE REVIEW

**Comment by pepness** [comment]
The MacOs Test failed with:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

I force-pushed without modifying the PR.

**Comment by lkishalmi** [comment]
@pepness can we get this one updated? Probably to 20.2.0?

**Comment by pepness** [comment]
Of course, will update to latest and re-test.

**Comment by matthiasblaesing** [comment]
@pepness @daemontus There is another PR proposed in #2372, I think it would be good to coordinate the efforts

**Comment by pepness** [comment]
Just checked the PR and it has everything. Closing this PR in favor of [PR-2372](https://github.com/apache/netbeans/pull/2372)

**Pull request closed without merging**
