### PR TITLE
Fix test window for multi-module maven projects

### PR DESCRIPTION
**Pull request by mbien**
check the reports directory of the sub project instead of the root project if the information is available in the context.

symptom:
When a project with maven modules is built, no sub-project test results are shown in the test window, even though the tab opens. Building the sub project directly however would show results.

### CODE REVIEW

**Review by matthiasblaesing — APPROVED** [review]
Change looks sane to me. I assume, that this is intended for #7710?

Did a quick check with a multi-module maven project and could reproduce the issue with surefire 2.19+ (tested with 2.22) and found it fixed with this changeset.

Thank you.

**Comment by mbien** [comment]
@matthiasblaesing btw I thought about targeting NB 23, but there is a chance that the info in the visitor context isn't always correct, so this could cause failures in different places. I don't want to take the risk right now so late in the release cycle.

**Comment by mbien** [comment]
so I thought about this and I believe that this should probably cause no problems since:
 - if `mvnd` is used in parallel mode (which is the default) the eventspy won't be added -> context will be empty -> old behavior
 - concurrent `mvn` tests are already not working very well (#7710), so a wrong context couldn't make it worse

@matthiasblaesing so I am going to rebase this for delivery, if you think this is ok for NB23 too, please let me know, otherwise i can put it back to NB24 no problem.

**Comment by ebarboni** [comment]
LGTM

**Comment by mbien** [comment]
> Not for release 23, too late and it is not a showstopper.

thanks! going to retarget it again later.

**Comment by mbien** [comment]
pushed the old branch again, retargeted to master. Going to merge it soon for NB 24.

thanks for reviews / delivery + triaging

**Pull request merged**
