### PR TITLE
Set DB environment for java+ as well as for java

### PR DESCRIPTION
**Pull request by jhorvath**
To correctly set environment variables for database connection we need to register DBConfigurationProvider for both targets - java+ and java.

### CODE REVIEW

**Review by sdedic — APPROVED** [review]
I would suggest to make 2 instances of `DBConfigurationProvider` instead of using a global variable -- but it seems a matter of style here: none of the reloadable NBLS-related state is used.

**Comment by neilcsmith-net** [comment]
@jhorvath only the release team should be merging to delivery.

**Comment by neilcsmith-net** [comment]
cc/ @mbien out of interest, when you were setting up branch protection, did you notice whether `asf.yml` exposed the ability to restrict committing on certain branches to certain accounts?

**Comment by MartinBalin** [comment]
> @jhorvath only the release team should be merging to delivery.

@neilcsmith-net sorry, I've suggested to Jan he should merge to delivery.

**Comment by mbien** [comment]
> cc/ @mbien out of interest, when you were setting up branch protection, did you notice whether `asf.yml` exposed the ability to restrict committing on certain branches to certain accounts?

@neilcsmith-net I don't think this is possible. The [doc](https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection) at least is not listing this capability

**Pull request merged**
