### PR TITLE
Ensure common project actions are available in Rust projects

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The NetBeans infrastructure provides common actions for projects. Covered by this change are:

- Versioning
- History
- Open in Terminal
- Open in System
- Find...
- Close
- Rename
- Move
- Copy
- Delete

The Debug action was removed as it is not yet implemented.

Before:

Bildschirmfoto vom 2023-06-16 23-56-24

After:

image

### CODE REVIEW

**Comment by Chris2011** [comment]
Thx for that. I miss the close and the delete action here.

**Review by BradWalker — APPROVED** [review]

**Review by vieiro — APPROVED** [review]
Looks fine to me. Thanks, @matthiasblaesing .

**Comment by matthiasblaesing** [comment]
@Chris2011 valid point, updated. @BradWalker @vieiro could you please have another look? The followup changes are done as two additional Commits.

**Review by BradWalker — APPROVED** [review]

**Review by BradWalker — APPROVED** [review]

**Comment by BradWalker** [comment]
> @Chris2011 valid point, updated. @BradWalker @vieiro could you please have another look? The followup changes are done as two additional Commits.

Done on my end.. Good stuff !!

**Review by vieiro — APPROVED** [review]
Cool

**Review by vieiro — APPROVED** [review]
Great job!

**Comment by matthiasblaesing** [comment]
Thank you for review!

**Pull request merged**
