### PR TITLE
NETBEANS-3290 fix common xml

### PR DESCRIPTION
**Pull request by ebarboni**
assumption of being in root were false. fixing delta in path

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@ebarboni added Cherry Pick label. If we shipped an NB 11.2 update to `org-netbeans-modules-apisupport-harness.nbm` I'm assuming this would get picked up OK?

**Comment by ebarboni** [comment]
ok,this is to flag for in case of update

**Comment by oyarzun** [comment]
I've tested this as well and it fixes the issue.

**Comment by neilcsmith-net** [comment]
@ebarboni can you merge this, then cherry pick locally on top of release112 (probably with spec version increment to apisupport.harness) and see if installing that updated NBM in 11.2 release fixes the issue?  If so, can you then open a PR against release112 and I'll look at shipping this with other updates.  Thanks!

**Pull request merged**
