### PR TITLE
Generate Java Sources from ANTLR grammars pre-compile

### PR DESCRIPTION
**Pull request by lkishalmi**
This is just a quick draft, to remove the ANTLR generated sources for ANTLR grammars from the repository, and have them generated during the build.

Related to: #7180

### CODE REVIEW

**Review by vieiro — COMMENTED** [review]
- We may want to fetch the latest grammars from github __manually__ (not automatically on each build) by dropping the `depends=init` in the [build.xml file](
https://github.com/apache/netbeans/blob/4f3e3584af0b42d665f919da06638d611c9dada4/java/languages.antlr/build.xml#L29). If these grammars are updated to newest Antlr versions in the future (say Antlr5, or whatever) we may still keep the old Antlr4 ones for a while, decoupling whatever version is published at github from our builds.

- I think [`licenseinfo.xml`](https://github.com/apache/netbeans/blob/4f3e3584af0b42d665f919da06638d611c9dada4/java/languages.antlr/licenseinfo.xml#L24) paths to `g4` grammars have to be updated for the build to pass.

**Comment by mbien** [comment]
+1 to the effort generating grammar during build

> So, for instance, we may run ant download-antlr-grammar whenever we upgrade ide/libs.antlr4.runtime, and not on each build.

+1 This sounds like a super important thing we should do, otherwise issues could suddenly start appearing and we don't know why.

However I think we have to discuss one thing: having code generated during build does not automatically exclude having it also checked into the repo.


I have a slight preference of not checking generated code in, however the safer approach in big projects with many cooks and imperfect code coverage is to check everything in. I don't have the experience to know how much noise this would cause, however, with @vieiro's point above this might be an option, since we should only see changes to generated code during lib upgrades - hopefully not during builds on different systems.

**Comment by lkishalmi** [comment]
Well, the `download-antlr-grammar` target is not executed during the build. it just /depends/ on the `init` not extends that.
The whole purpose of that task is to document the changes needs to be done on the sources when they are manually updated.

**Comment by lkishalmi** [comment]
@mbien Are you saying to keep the generated code in the repository, but do the generation on each build, so if the tool changes we would see the difference (or the lack of that) in the generated code?

**Comment by mbien** [comment]
@lkishalmi yes. But the more I think about this the less I like it, I would say lets remove the generated code from repo, if its hooked to the build.

**Review by vieiro — APPROVED** [review]
This looks great.

**Comment by vieiro** [comment]
We could also create a non-ASF repository with a Maven project holding different build-time binaries (with different licenses) and upload it to Maven Central. In order to get rid of OSOUL hosting. 

That could be a good place to update these rarely updated dependencies.

**Comment by matthiasblaesing** [comment]
> We could also create a non-ASF repository with a Maven project holding different build-time binaries (with different licenses) and upload it to Maven Central. In order to get rid of OSOUL hosting.
> 
> That could be a good place to update these rarely updated dependencies.

I don't see a connection to the problem fixed here. The problem here is, that antlr4 declares itself as unstable and now we need to regenerate the parsers everytime antlr4 does a minor release and we update our copy. I (and it seems others two) thought, that once generated parser code will continue to be useable for the future.

Hosting of binaries is a different problem and in fact already partly solved as you suggested. The issue here is, that you shift the problem from the ASF to individuals, that upload.

**Pull request merged**
