### PR TITLE
Add support for Chrome DevTools Protocol for NodeJS Debugging

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Highlight the hit breakpoint (see Marker in the "Breakpoints" Tab):

image

In the Global Node Configuration the debug protocol to be used can be selected, it defaults to the "Chrome DevTools protocol":

image

It would have been possible to select the protocol based on the version information from node, however the node from graalvm can't be safely and quickly detected, so the user has to choose.

In the per Project Settings the Node Debug Protocol can be overridden together with the node binary, as the two depend on each other:

image

### CODE REVIEW

**Comment by Chris2011** [comment]
Just a question, will this also work out of the box for TypeScript?

**Comment by matthiasblaesing** [comment]
> Just a question, will this also work out of the box for TypeScript?

I don't think so. The foundations could be used, but it needs to be integrated.

**Review by lkishalmi — APPROVED** [review]
Well, this is a pretty big one. I do not have JS knowledge to judge it. Also just skimmed through. Besides of the friend api-s there is nothing sore to my eyes.

As this one is a big one, I'd propose to merge early in the NB16 phase, so people could test it out,

**Comment by ebarboni** [comment]
Can we merge this one ?

**Review by svenreimers — APPROVED** [review]

**Comment by neilcsmith-net** [comment]
@matthiasblaesing we're getting close to freeze now, so need a call whether to merge for NB16, punt to NB17, or close.

**Comment by matthiasblaesing** [comment]
Moved to 17 - I'd like to have another look at this.

**Comment by matthiasblaesing** [comment]
I intent to merge this by next week, so if anyone wants to object, please do so now.

**Comment by ebarboni** [comment]
I see no milestone but this PR looks ok. Could we make it for NB 22 ?

**Comment by matthiasblaesing** [comment]
This was tested and is reviewed. I rebased on master, gave it another mini-spin and if tests run clean, I plan to merge tomorrow.

**Pull request merged**
