### PR TITLE
Upgrade commons libs, asm, jgit, jna, jackson, felix, jacoco and junit

### PR DESCRIPTION
**Pull request by mbien**
tried to find some low hanging fruits using the dependency checker: https://github.com/apache/netbeans/actions/runs/8543693772

one commit per library, if I should drop a commit please say so.

- ~Upgrade jsch from 0.1.72 to [0.2.17](https://github.com/mwiede/jsch/blob/master/ChangeLog.md)~ outside of jgit*s declared range
- Upgrade jackson from 2.16.1 to 2.17.0
- Upgrade jacoco.core from 0.8.7 to 0.8.12
- Upgrade junit from 5.6.0 to 5.10.2
- Upgrade JNA from 5.12.1 to 5.14.0
- Upgrade felix from 7.0.3 to [7.0.5](https://github.com/apache/felix-dev/blob/master/framework/doc/changelog.txt)
- Upgrade jgit from 9.8.0 to [9.9.0](https://projects.eclipse.org/projects/technology.jgit/releases/6.9.0)
  -  Upgrade JavaEWAH from 1.1.6 to 1.2.3
- Upgrade ASM from 9.6 to 9.7
- Upgrade commons-compress from 1.25.0 to 1.26.1
- Upgrade commons-logging from 1.3.0 to 1.3.1
- Upgrade commons-io from 2.15.1 to 2.16.0
- Upgrade commons-codec from 1.16.0 to 1.16.1

### CODE REVIEW

**Comment by ebarboni** [comment]
Nice.
What is the issue with jsch ?

**Comment by mbien** [comment]
> Nice. What is the issue with jsch ?

I should have checked what version jgit needs first before updating that. Jgit is loaded as osgi module and it won't load dependencies which are outside the declared range -> classloader error. The manifest has `com.jcraft.jsch;version="[0.1.37,0.2.0)"` in it.

**Comment by mbien** [comment]
PHP test failure on win is likely file path length / max cp length / max arg size related. The forked JVM can't start. Will try to debug this on windows and check what is causing this.

alternative is to drop the `commons-io` commit since this seems to be sufficient to "resolve" this.

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me. Only eyeballed this.

**Comment by mbien** [comment]
did some manual testing and everything worked fine, all tests green -> merging

**Pull request merged**
