### PR TITLE
Stabilize some unreliable tests for smoother CI operation

### LINKED ISSUE #5955: platform/core.windows + platform/favorites tests fail too often
this started happening not too long ago and requires too many restarts atm, e.g:
https://github.com/apache/netbeans/actions/runs/4992043385
https://github.com/apache/netbeans/actions/runs/4962612141 
both passed after 8 runs of `Platform Modules batch1`.

```
  [junit] java.lang.AssertionError: Should have found a nonproblematic provider of needs org.openide.modules.jre.JavaFX among
StandardModule:org.netbeans.libs.javafx.linux jarFile: /home/runner/work/netbeans/netbeans/nbbuild/netbeans/extra/modules/org-netbeans-libs-javafx-linux.jar, 
... long list of jars
  [junit] 	at org.netbeans.ModuleManager.maybeAddToEnableList(ModuleManager.java:1858)
  [junit] 	at org.netbeans.ModuleManager.maybeAddToEnableList(ModuleManager.java:1815)
  [junit] 	at org.netbeans.ModuleManager.simulateEnable(ModuleManager.java:1703)
  [junit] 	at org.netbeans.ModuleManager.simulateEnable(ModuleManager.java:1675)
  [junit] 	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:290)
  [junit] 	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:252)
  [junit] 	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
  [junit] 	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:173)
  [junit] 	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:142)
  [junit] 	at org.netbeans.core.startup.Main.start(Main.java:303)
  [junit] 	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
  [junit] 	at java.lang.Thread.run(Thread.java:750)
  [junit] Testsuite: org.netbeans.core.windows.awt.ValidateLayerToolbarTest
```
It isn't always the same test, but usually one of the following:
```
org.netbeans.core.windows.awt.ValidateLayerMenuTest:BeforeFirstTest
org.netbeans.core.windows.awt.ValidateLayerToolbarTest:BeforeFirstTest
org.netbeans.modules.favorites.AddToFavoritesTest:BeforeFirstTest
```
which fail during setup, outside of the actual test cases

### PR DESCRIPTION
**Pull request by mbien**
I checked the last 10 merges to master and all of them failed on first attempt. Most failures were caused by the issue described in #5955

last 10 merge failures including test restarts till green:
```
BeforeFirstTest: org.netbeans.core.windows.awt.ValidateLayerMenuTest
BeforeFirstTest: org.netbeans.core.windows.awt.ValidateLayerToolbarTest

BeforeFirstTest: org.netbeans.modules.favorites.AddToFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.AddToFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.HomeFolderTest
BeforeFirstTest: org.netbeans.modules.favorites.RemoveFromFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.RemoveFromFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.RemoveFromFavoritesTest

BeforeFirstTest: org.netbeans.modules.settings.convertors.MimeTypeTest
BeforeFirstTest: org.netbeans.modules.settings.convertors.MimeTypeTest

testEnumCaseFix_02b: org.netbeans.modules.php.editor.verification.IntroduceSuggestionTest
testEnumCaseFix_02b: org.netbeans.modules.php.editor.verification.IntroduceSuggestionTest
testEnumCaseFix_02b: org.netbeans.modules.php.editor.verification.IntroduceSuggestionTest

testEnumerations_43: org.netbeans.modules.php.editor.csl.GotoDeclarationPHP81Test
testMarkAsRead: org.netbeans.modules.notifications.center.NotificationCenterManagerTest
testPHPTags: org.netbeans.modules.php.editor.csl.FoldingTest
```

~The javafx modules wouldn't load anyway -> lets turn off the javafx cluster for those tests.~ didn't work

failure:

```
java.lang.AssertionError: Should have found a nonproblematic provider of needs org.openide.modules.jre.JavaFX among
StandardModule:org.netbeans.libs.javafx.linux jarFile: /home/runner/work/netbeans/netbeans/nbbuild/netbeans/extra/modules/org-netbeans-libs-javafx-linux.jar,  ... long list of jars
```

fixes #5955

### CODE REVIEW

**Comment by mbien** [comment]
well, this didn't work at all. Looks like this fixes a harmless exception which does not cause the test startup failure.

**Comment by mbien** [comment]
lets try plan b:
 1) separate reliable from unreliable tests
 2) wrap unreliable tests into retry script

**Review by neilcsmith-net — APPROVED** [review]
Thanks. Good move, for now at least (unreliable tests is something of an oxymoron :smile: )

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me. Thank you for looking into this.

**Pull request merged**
