### PR TITLE
version bump: require javac 18.

### PR DESCRIPTION
**Pull request by mbien**
NetBeans 14 expects javac 18 which means we have to increment the version for the javac checks too.

### CODE REVIEW

**Review by matthiasblaesing — APPROVED** [review]
Eyeballed this and looks sane to me.

**Review by neilcsmith-net — APPROVED** [review]
Looks good, at least for a short term solution. A proper API for this, and linked to nb-javac updates in some way so the increment _can't_ be missed, might be useful in the future?

**Comment by mbien** [comment]
> Looks good, at least for a short term solution. A proper API for this, and linked to nb-javac updates in some way so the increment _can't_ be missed, might be useful in the future?

@neilcsmith-net I thought about this a bit. 

It is essentially a runtime dependency check. Someone gonna have to bump the number no matter where it is taken from. We can't put it into the nb-javac module since the check has to work without it.

an assert could potentially check:
`assert ((NB_VERSION / 2 + 11) == REQUIRED_JAVAC_VERSION)`
which would fail if someone forgets the bump REQUIRED_JAVAC_VERSION in NB 16. However, where do we get `NB_VERSION` from? The release would have a system property for that, but a dev version doesn't.

**Comment by mbien** [comment]
integrating this one. We can further improve those version checks for the next release.

**Pull request merged**
