### PR TITLE
Temporary lightweight C/C++ support

### PR DESCRIPTION
**Pull request by jlahoda**
It seems the full CND (C/C++) support may take some time to cleanup. As an interim improvement, I'd like to propose to add a simple, lightweight C/C++ support. The editor features are provided by the ccls server, which the users need to install on their own.

In most aspects, it should automatically be superseded by CND when installed/included.

### CODE REVIEW

**Comment by geertjanw** [comment]
Very cool and thank you for doing this.

**Comment by neilcsmith-net** [comment]
@jlahoda this remaining draft and bumping to 12.2, or will it be ready to merge for 12.1?

**Comment by jlahoda** [comment]
@neilcsmith-net - it would be IMO awesome if we would have a C/C++ support in 12.1, but not sure if any further discussions/reviews are needed.

**Comment by neilcsmith-net** [comment]
@jlahoda sounds good to me.  But would like to ensure it's in first beta for testing, so if it's ready then could you merge by Monday?  Maybe a lazy consensus thread on the mailing list to say you plan to do so if you feel needs further discussion/review given limited timescale?

**Comment by rspecioso** [comment]
Hello I love NetBeans with Java, HTML and PHP but we lost the C++ support. I did add the 8.2 plugin to the 12 version but it is not up to date, many of the new C++ feature are not there. Maybe I need to do something in the configuration but I cannot see anything. I am a professor that would like to use this for all my courses which I can except for the C++ courses. Anytime frame when the support will be there for version 12 or how to improve it using the 8.2 plugin. I see talk about a lightweight version but I do not see how to add it.

**Comment by rimmartin** [comment]
Hi @jlahoda,
Are NetBeans c++ users really wanting the full CND (C/C++) as it was?  Or is there some effort to collect newer ideas in the support of c++?

For example I've been using yarn & package.json to organize c++ projects and dependencies.  (I would use pnpm but it doesn't yet clone from github dependent projects without  their own package.json)

Then I use the nodejs NetBeans plugin to see my c++ project files in NetBeans. Though C++ code completion would be nice to have again:-)

**Comment by jlahoda** [comment]
@rimmartin, I know people are using one of (many) features CND has that cpplite does not. Like e.g. Configurations in the project.

If you can get/generate compile_commands.json[1] in the project's root directory (for the one with packga.json for npm projects, I think), and install either clangd or ccls, then the code completion might actually work.

[1] https://sarcasm.github.io/notes/dev/compilation-database.html

**Comment by Llerr** [comment]
I use NetBeans as C++ IDE. But i need use  8.2 plugin.

**Comment by graham8** [comment]
Good to see C/C++ getting some love.  I use NB just for editing C and C++, building on another device without using NB as a debugger. The 8.2 plug-in works fine for that, except navigating to definitions (Ctrl-B) is patchy - sometimes it works, sometimes not.  I've never found out whether it's supposed to be doing a complete symbol scan.  Will this lite version do that more reliably?

**Pull request merged**
