### PR TITLE
Removed from code semicolon ;; duplicates

### PR DESCRIPTION
**Pull request by tbw777**
Removed unnecessary characters from code.

### CODE REVIEW

**Comment by mbien** [comment]
@tbw777 thanks for the cleanup. Since you are a first time contributor I assume that you read the PR template and are willing to contribute this code to the apache foundation.

```
By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

    are all your own work, and you have the right to contribute them.
    are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).
```

**Comment by neilcsmith-net** [comment]
@tbw777 yes, thanks for the cleanup PRs.

@mbien as we're less than 2 weeks from freeze and branch for NB17, I intend to punt these forward to NB18 as we've done previously with code cleanup late in the cycle, unless you have other thoughts on any?

**Comment by mbien** [comment]
@neilcsmith-net we could get a trivial change like this one in I think. We have to put space between big merges anyway, since project wide cleanups cause a lot of trouble if you do too many at once - most of the issues can be avoided if enough time is given to devs to pull from master.

@tbw777 can you please stop closing PRs and opening new ones which replace them? Simply push again if you have changes to make. Tests were running already and some were reviewed.

**Comment by tbw777** [comment]
@mbien
Agree

**Review by mbien — APPROVED** [review]
code looks good.

@tbw777 thanks and congrats on your first contribution to this project.

**Comment by tbw777** [comment]
wow )

**Pull request merged**
