### PR TITLE
Upgrading jgit to 7.0.0.202409031743-r

### PR DESCRIPTION
**Pull request by lahodaj**
As a draft for now, needs testing. The main reason for the upgrade is that it seems this version supports git worktrees, at least partially.

### CODE REVIEW

**Comment by mbien** [comment]
thanks, I read the release notes for [jgit 7.0.0](https://projects.eclipse.org/projects/technology.jgit/releases/7.0.0) a while ago but never got into updating it.

comparing it with https://github.com/apache/netbeans/commit/151d4d24240985c3be38d90736dcfbc7327a0d72, the project.xmls and ignore-overlaps needs to be updated too I believe. We removed a lot of deprecations in past - if the 7.0 release applies without code changes, it means we didn't overlook anything which would be great.

**Comment by mbien** [comment]
for future reference the dependency trees:
```
mvn eu.maveniverse.maven.plugins:toolbox:gav-tree -Dgav=org.eclipse.jgit:org.eclipse.jgit:7.0.0.202409031743-r
[INFO] org.eclipse.jgit:org.eclipse.jgit:jar:7.0.0.202409031743-r
[INFO] ├─com.googlecode.javaewah:JavaEWAH:jar:1.2.3 [compile]
[INFO] ├─org.slf4j:slf4j-api:jar:1.7.36 [compile]
[INFO] ╰─commons-codec:commons-codec:jar:1.17.1 [compile]
```

```
mvn eu.maveniverse.maven.plugins:toolbox:gav-tree -Dgav=org.eclipse.jgit:org.eclipse.jgit.gpg.bc:7.0.0.202409031743-r
[INFO] org.eclipse.jgit:org.eclipse.jgit.gpg.bc:jar:7.0.0.202409031743-r
[INFO] ├─org.eclipse.jgit:org.eclipse.jgit:jar:7.0.0.202409031743-r [compile]
[INFO] │ ├─com.googlecode.javaewah:JavaEWAH:jar:1.2.3 [compile]
[INFO] │ ╰─commons-codec:commons-codec:jar:1.17.1 [compile]
[INFO] ├─org.bouncycastle:bcpg-jdk18on:jar:1.78.1 [compile]
[INFO] ├─org.bouncycastle:bcprov-jdk18on:jar:1.78.1 [compile]
[INFO] ├─org.bouncycastle:bcutil-jdk18on:jar:1.78.1 [compile]
[INFO] ├─org.bouncycastle:bcpkix-jdk18on:jar:1.78.1 [compile]
[INFO] ╰─org.slf4j:slf4j-api:jar:1.7.36 [compile]
```

```
mvn eu.maveniverse.maven.plugins:toolbox:gav-tree -Dgav=org.eclipse.jgit:org.eclipse.jgit.lfs:7.0.0.202409031743-r
[INFO] org.eclipse.jgit:org.eclipse.jgit.lfs:jar:7.0.0.202409031743-r
[INFO] ├─org.eclipse.jgit:org.eclipse.jgit:jar:7.0.0.202409031743-r [compile]
[INFO] │ ├─com.googlecode.javaewah:JavaEWAH:jar:1.2.3 [compile]
[INFO] │ ├─org.slf4j:slf4j-api:jar:1.7.36 [compile]
[INFO] │ ╰─commons-codec:commons-codec:jar:1.17.1 [compile]
[INFO] ╰─com.google.code.gson:gson:jar:2.11.0 [compile]
[INFO]   ╰─com.google.errorprone:error_prone_annotations:jar:2.27.0 [compile]
```

```
mvn eu.maveniverse.maven.plugins:toolbox:gav-tree -Dgav=org.eclipse.jgit:org.eclipse.jgit.ssh.jsch:7.0.0.202409031743-r
[INFO] org.eclipse.jgit:org.eclipse.jgit.ssh.jsch:jar:7.0.0.202409031743-r
[INFO] ├─org.eclipse.jgit:org.eclipse.jgit:jar:7.0.0.202409031743-r [compile]
[INFO] │ ├─com.googlecode.javaewah:JavaEWAH:jar:1.2.3 [compile]
[INFO] │ ╰─commons-codec:commons-codec:jar:1.17.1 [compile]
[INFO] ├─com.jcraft:jsch:jar:0.1.55 [compile]
[INFO] ├─com.jcraft:jzlib:jar:1.1.3 [compile]
[INFO] ╰─org.slf4j:slf4j-api:jar:1.7.36 [compile]
```

note: last time I tried, I couldn't update bouncycastle https://github.com/apache/netbeans/pull/7569, the jsch is locked too and tracked tracked via https://github.com/apache/netbeans/issues/7572

**Comment by lahodaj** [comment]
(As a note to myself - Git/Diff/To HEAD does not seem to work with worktrees, even with this upgrade. It is a bit surprising to me, as the line marks in the editor do work.)

**Review by mbien — APPROVED** [review]
changes look good to me, I did also run some smoke testing e.g git init, commits, history, diff, cherry pick and clone and everything worked fine

**Comment by lahodaj** [comment]
Thanks. The diff started to work for me, maybe it was just slow :-(. In any case, unless there are objections, I'll integrate in the next day or two.

**Pull request merged**
