### PR TITLE
Log exception when running NbClipboard.GetContents#run fails with an exception

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Only to create a testable build.

### CODE REVIEW

**Review by mbien — COMMENTED** [review]
makes sense, thats likely it.

be aware that there is a second call to `getContents()` in line 206 (which is logging the exception at least), outside of the task. Might be good to extract the logic to a utility method and use it from both call sites.

**Comment by neilcsmith-net** [comment]
Good call on the exception and retry.

> Might be good to extract the logic to a utility method and use it from both call sites.

Which logic?  I would be wary of using the retry loop there, unless there's a check it's in the RP thread first.

**Comment by mbien** [comment]
> 
> > Might be good to extract the logic to a utility method and use it from both call sites.
> 
> Which logic? I would be wary of using the retry loop there, unless there's a check it's in the RP thread first.

the call is known to randomly fail. If retry mitigates the issue it is worth to consider it there too. How often and with what delay can/should be tweaked once confirmed that this is fixing the issue.

We should also check how long a failing call takes. Since a succeeding call can take ~100ms. So retry + sleep might take longer than expected. (maybe we have luck and a failing call returns immediately in which case we don#t have to worry about that)

**Comment by neilcsmith-net** [comment]
@mbien just saying that line 206 might be in the EDT, so sleeping for a second if the clipboard is permanently inaccessible is possibly a bad move.

Just noticed from the stack trace shared in the issue that `NbClipboard.SetContents` already has a continuous retry by rescheduling itself.

**Comment by mbien** [comment]
> just saying that line 206 might be in the EDT, so sleeping for a second if the clipboard is permanently inaccessible is possibly a bad move.

@neilcsmith-net I think we are still in the phase of getting data and getting to the root of the problem - this is a draft to test things. I am not advocating to block for one second in any thread. I even said to be careful while reading the comment in this PR which essentially notes that sleeping 50x20ms is one second, not taking into account how long the call actually blocks - which might be impl dependent.

It could even turn out that NB is locking itself out by calling the system function from too many threads too often.

**Comment by neilcsmith-net** [comment]
> It could even turn out that NB is locking itself out by calling the system function from too many threads too often.

I've wondered about this too. Although there aren't that many possible threads, and as far as I can tell the access in the JDK is thread safe.

There is also a flag which should be turning off the background thread behaviour, and most affected users who've tested that have reported it not helping.

**Comment by eirikbakke** [comment]
Thanks for this patch! I'll be using it in my development IDE, modified to also log on retries, to observe if the exception occurs and if retries help.

(If the sleep+retry actually works, an alternative to running Thread.sleep() directly on the EDT is to use java.awt.SecondaryLoop to keep the event loop going while waiting.)

**Comment by eirikbakke** [comment]
I ran my IDE with a version of this patch for 24 hours now. Reviewing the IDE log, the "cannot open system clipboard" condition occurred 8 times, in each case succeeding after 10, 14, 1, 7, 1, 1, 2, and 1 retries, respectively (with the 20ms delay between each retry). During those times I observed no problems with cut/paste.

I managed to trigger the error intentionally once, by doing Ctrl+C from Microsoft Excel. In that case I was not able to paste what I had copied from Excel into NetBeans, but the clipboard worked properly again once I had copied something from NetBeans. (This matches my previous experience.) Though I wasn't able to reproduce this again yet...

**Pull request closed without merging**
