### PR TITLE
[NETBEANS-4050] - cleanup uses of EMPTY_LIST, EMPTY_SET, EMPTY_MAP

### PR DESCRIPTION
**Pull request by BradWalker**
[NETBEANS-4050] - cleanup uses of EMPTY_LIST, EMPTY_SET, EMPTY_MAP
    
         Clean up a bunch of compiler warning messages related to the use of Collections.[EMPTY_LIST, EMPTY_SET, EMPTY_MAP]..
    
         [repeat] /home/bwalker/src/netbeans/java/ant.debugger/src/org/netbeans/modules/ant/debugger/RunTargetsAction.java:145: warning: [unchecked] unchecked conversion
         [repeat] allTargets = Collections.EMPTY_SET;
         [repeat] ^
         [repeat] required: Set<Target>
         [repeat] found: Set

### CODE REVIEW

**Comment by ebarboni** [comment]
Would be good to have a technical review from other than me.

**Comment by neilcsmith-net** [comment]
@ebarboni not reviewing, but all the warning fixes by @BradWalker (which are welcome) have not been merged during freezes.  Should be left for review for 12.1 window in my opinion.

**Comment by BradWalker** [comment]
> @BradWalker is this clear to merge?

Hey @matthiasblaesing, it's ready to go.. I rebased to latest master last night..

**Comment by matthiasblaesing** [comment]
Merging - thank you.

**Pull request merged**
