### PR TITLE
NETBEANS-2883 Remove link to bits.netbeans.org/maven2 + test

### PR DESCRIPTION
**Pull request by ebarboni**
Add test and remove former repository (oracle) from the maven apisupport

### CODE REVIEW

**Comment by ebarboni** [comment]
I do not understand the travis issue :/

**Comment by junichi11** [comment]
@ebarboni 
```
 [nb-javac] /home/travis/build/apache/netbeans/apisupport/maven.apisupport/test/unit/src/org/netbeans/modules/maven/apisupport/NBMNativeMWITest.java:144: error: try-with-resources is not supported in -source 1.6
 [nb-javac]         try (OutputStream os = parentpomFile.getOutputStream()) {
 [nb-javac]             ^
 [nb-javac]   (use -source 7 or higher to enable try-with-resources)
 [nb-javac] 1 error
```
in maven.apisupport
`javac.source=1.6`

**Comment by ebarboni** [comment]
thanks @junichi11. I had some obscure token expired travis and was not able to see that. Now it seems accessible.

What is the good way, changing javac version ? or make the old vintage try catch finaly block ?

**Comment by junichi11** [comment]
Let's update it :) e.g. `javac.source=1.8`

**Comment by ebarboni** [comment]
@neilcsmith-net is this good too merge now ? Or master still locked?

**Comment by matthiasblaesing** [comment]
Master was already open, we have two positive reviews, will merge. Thank you.

**Pull request merged**
