### PR TITLE
[NETBEANS-2418][NETBEANS-2298] update suggested MySQL Driver to latest

### PR DESCRIPTION
**Pull request by mcdonnell-john**
There was a defect related to the JDBC Connection String for MySQL, I took a look and noticed we were suggesting an older driver.

I've updated the suggested driver to the latest, and ran some CRUD DB tests with it with NB 11.0 with no issues

### CODE REVIEW

**Comment by mcdonnell-john** [comment]
Not sure, but looking at Travis:
The Checks fail on the check: RUN_TESTS_JDK9PLUS

But theres no errors and the end of the logs say:
"The job exceeded the maximum log length, and has been terminated."

Are we running too many checks in these Travis builds?

**Comment by wadechandler** [comment]
Could be John. The changes themselves look just fine. Will check the mailing lists to see if this is a known thing too. On mobile right now.

**Comment by matthiasblaesing** [comment]
One think that the driver reminded me at work: The driver class was moved to `com.mysql.cj.jdbc.Driver`, should that also be updated?

**Comment by mcdonnell-john** [comment]
I didn't come across a change to the class when testing but will double check before merging to be sure

**Comment by wadechandler** [comment]
It is more likely a deprecation warning https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-api-changes.html

Notice the old class name is deprecated. I would expect tests to fail, but it makes sense to update.

**Comment by matthiasblaesing** [comment]
@mcdonnell-john should we mark this as work in progress?

**Comment by mcdonnell-john** [comment]
Yep. My laptop broke a while back and only got a replacement a while back. I'm looking at the changes to driver and datasource classes at the moment but won't make 11.1

**Comment by mcdonnell-john** [comment]
Closing due to re-basing issue

**Pull request closed without merging**
