### PR TITLE
NETBEANS-888 Open Recent file not working

### PR DESCRIPTION
**Pull request by michaelsembwever**
- update menuItems under RecentFileAction via a RecentFiles property change listener, rather than popup menu listener

### CODE REVIEW

**Comment by geertjanw** [comment]
Wow, cool. Why was this needed, why did it work in earlier releases but not anymore requiring this PR? Thanks for this great work.

**Comment by michaelsembwever** [comment]
@geertjanw ,

> Wow, cool. Why was this needed, why did it work in earlier releases but not anymore requiring this PR? Thanks for this great work.

I suspect it never worked on the combination of
 - macos
 - `apple.laf.useScreenMenuBar=true`
 - jdk >1.8 (currently experiencing it with 11.0.3)

and that these users using Java9 or above is a relatively new phenomena.

**Comment by geertjanw** [comment]
So it was macos specific, didn't know that. And also related to some change in the JDK after 1.8, but what could it be (just curious really).

**Comment by michaelsembwever** [comment]
@geertjanw ,

> So it was macos specific, didn't know that. And also related to some change in the JDK after 1.8, but what could it be (just curious really).

I didn't (don't) have the time to hunt that down.
The existing code was recreating the menuItems every time the popup menu listener notified the jmenuitem was made visible. The ScreenMenuItems was then without reference back to these menuItems, and so there's was no actionListener and the event was not enabled.

Changing it so that the menuItems were only recreated when the history in RecentFiles changed, solved the problem, probably because the ScreenMenuItems <-> menuItem referencing is done before the popup menu change support kicks in, but that's just a guess.

There's a bit more of my analysis info in https://issues.apache.org/jira/browse/NETBEANS-888

**Comment by michaelsembwever** [comment]
@geertjanw ping.

**Comment by GeertjanWielenga** [comment]
Sure, how ready is this for merging? Happy to merge if you’re confident about this pr.

**Comment by michaelsembwever** [comment]
I've been using it now the past week.

**Comment by geertjanw** [comment]
OK, merged.

**Comment by matthiasblaesing** [comment]
@michaelsembwever please update your git settings. I just noticed, that the history does not reflect your real name. For commits valid realname and email information should be present.

**Comment by michaelsembwever** [comment]
@matthiasblaesing , thanks for the heads up. Has been set to `Author: Mick Semb Wever <mck@apache.org>`

**Comment by matthiasblaesing** [comment]
@michaelsembwever thank you, we welcome your future changesets :-)

**Pull request merged**
