### PR TITLE
Fix tests for Neon language

### PR DESCRIPTION
**Pull request by KacerCZ**
Test data were created from scratch
Enabled tests in Travis CI

### CODE REVIEW

**Comment by KacerCZ** [comment]
@tmysik Please review.

**Comment by tmysik** [comment]
@junichi11 Junichi, we can now merge PRs, right? Feel free to merge it if it is true, of course.

Thanks!

**Comment by junichi11** [comment]
@tmysik 

> we can now merge PRs, right? Feel free to merge it if it is true, of course.

Yes :)

**Comment by junichi11** [comment]
@hectorespert Is `.travis.yml` OK?

**Comment by tmysik** [comment]
@junichi11 @hectorespert 

Sorry, I already merged it now. If there is any problem, please create a new PR. Sorry for inconveniences.

**Comment by junichi11** [comment]
@tmysik Travis has already passed. So, no problem at all :) Just in case, I asked him.

**Comment by hectorespert** [comment]
> @hectorespert Is `.travis.yml` OK?

It's ok.Good job

**Comment by junichi11** [comment]
Thanks!

**Comment by KacerCZ** [comment]
Thank you all.

**Comment by KacerCZ** [comment]
Please add PHP label and set milestone to 12.1.

**Pull request merged**
