### PR TITLE
ignore ISSUE_TEMPLATE for rat

### PR DESCRIPTION
**Pull request by ebarboni**
netbeans-license job show issue for  files in ISSUE_TEMPLATE folder
https://github.com/apache/netbeans/tree/master/.github/ISSUE_TEMPLATE

We can ignore by merging this PR.

### CODE REVIEW

**Review by neilcsmith-net — CHANGES_REQUESTED** [review]
In my opinion, this should be all files under `.github/`. At least one of the failures (PR template) is not in the issue template folder.  We may put other things in here in future too.

Sorry, I thought I'd checked RAT with these at the time.  Failures of RAT should show in PRs.

**Comment by mbien** [comment]
@neilcsmith-net @ebarboni  heads up: travis didn't start for this PR and I tried to restart a job on a different PR and it didn't work there too. Any idea what is going on there? Something similar happened around new year i believe.

**Review by neilcsmith-net — APPROVED** [review]

**Comment by neilcsmith-net** [comment]
Thanks @ebarboni 

@mbien it's been happening a bit recently too. Not sure why. Maybe hitting an ASF limit?

**Comment by mbien** [comment]
@neilcsmith-net filed an issue at infra https://issues.apache.org/jira/browse/INFRA-23188

**Comment by mbien** [comment]
@ebarboni Hi Eric, could you force push (e.g squash commits) into this issue to confirm that travis is working again (see dev mail for details).

**Comment by ebarboni** [comment]
@mbien travis works but got an issue on lsp server seems unrelated

**Comment by mbien** [comment]
@ebarboni everything seems to be tested twice on this PR, I can't quite explain why.

"Branch" tests:
```
$ git clone --depth=50 --branch=ebarboni-issuetemplate-ratignore --quiet https://github.com/apache/netbeans.git apache/netbeans
$ cd apache/netbeans
$ git checkout -qf b8159cc30bbc8bf2ecb051a449469d9a085e6616
```

"Pull Request" tests:
```
$ git clone --depth=50 --quiet https://github.com/apache/netbeans.git apache/netbeans
$ cd apache/netbeans
$ git fetch origin +refs/pull/4020/merge: --quiet
$ git checkout -qf FETCH_HEAD
```
the second run is green. I think the first tests a version which still has the LSP issue in master. "Branch" usually doesn't exist on other PRs. Anything unusual how you branched for this PR?

**Review by mbien — APPROVED** [review]

**Pull request merged**
