### PR TITLE
Snapshot of APIs as of 12.5

### PR DESCRIPTION
**Pull request by ebarboni**
```
# checkout branch (or release tag)
git checkout release124
ant clean
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb125a1
git stash pop
git add -A
git commit -m "Snapshot of APIs as of 12.5"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

I had to do the find getPeer line otherwise it was introducing back deprectated getPeer call.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
Looks fine at first glance.

**Comment by ebarboni** [comment]
Merging in a few moment. Next step would be to merge release125 to master. (I'm stressed :D)

**Comment by neilcsmith-net** [comment]
@ebarboni keep calm! 😄  But don't merge release125 to master - it's delivery to master - not quite the same.

I think removing getPeer() is no longer necessary.  But not a problem either.

**Comment by ebarboni** [comment]
Ok delivery not release125 :D. 

I did a pr #3172 just to show that getPeer is not removed on a run with no getpeer removal.

**Pull request merged**
