### PR TITLE
[NETBEANS-3407] - Updating to jsr305 3.0.2

### PR DESCRIPTION
**Pull request by pepness**
Update jsr305(findbugs) to 3.0.2. This is the last version since the project was [abandoned](https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004321.html).

- [Release Notes](http://findbugs.sourceforge.net/Changes.html)

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Please remove the notice file - none of the jars on maven central contain it or any indication, that it exists. The code hosted on google code:

https://code.google.com/archive/p/jsr-305/source/default/source

Shows this license:

```
Copyright (c) 2007-2009, JSR305 expert group
All rights reserved.

http://www.opensource.org/licenses/bsd-license.php

Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.
    * Neither the name of the JSR305 expert group nor the names of its 
      contributors may be used to endorse or promote products derived from 
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
POSSIBILITY OF SUCH DAMAGE.
```

please add it as a new license - suggested name: BSD-jsr305 (you need to update the local license file and add a new file to the `nbbuild/licenses` directory.

**Comment by pepness** [comment]
Thank for the review Matthias, I pushed the new commit.

**Comment by matthiasblaesing** [comment]
Thank you.

**Comment by matthiasblaesing** [comment]
Merged via 226fa4411850a0b1ec00c2198039ef51ffb1af76

**Pull request closed without merging**
