### PR TITLE
[NETBEANS-3428] Update FlatLaf from 0.22 to 0.23

### PR DESCRIPTION
**Pull request by DevCharly**
Here is a full list of changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/0.23

### CODE REVIEW

**Comment by DevCharly** [comment]
The "Versioning modules (ide/versioning and ide/versioning.core) tests" fail.
Has this something to do with my changes?

**Comment by lkishalmi** [comment]
We have some flaky test/build from time to time. Rerunning the failed job helped, so I've merged this.

**Comment by lkishalmi** [comment]
@DevCharly https://issues.apache.org/jira/browse/NETBEANS-3657 could you check this one? It happens both with FlatLaf 0.22 and 0.23

**Comment by DevCharly** [comment]
@lkishalmi yes, I'll check it

**Pull request merged**
