### PR TITLE
[NETBEANS-4763] Handling switch expressions, case rules and exhaustive switches more correctly.

### PR DESCRIPTION
**Pull request by jlahoda**
---
**^Add meaningful description above**

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

If you're a committer, please label the PR before pressing "Create pull request" so that the right test jobs can run.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@sdedic @jtulach would be good if either/both of you could take a look, confirm the fix and merge before freeze.

**Review by sdedic — APPROVED** [review]

**Comment by mbien** [comment]
this looks ready to merge to me, tests are green too. @jlahoda @matthiasblaesing should we get this in?

**Comment by matthiasblaesing** [comment]
@mbien I saw this yesterday and I agree. I ran test tonight and locally I saw failures, but these were timeouts and language depedneded problems. The corresponding tests were ran on the github actions infrastructure and there they worked. So yes this should go in.

**Comment by mbien** [comment]
going to risk it and merge. `java.hints` batch1 and batch2 ran on CI and this particular test does also run locally for me (started with IDE).

**Comment by jlahoda** [comment]
Thanks for merging - I don't see a reason why not!

**Comment by mbien** [comment]
> Thanks for merging - I don't see a reason why not!

We are always a bit careful with reviewed PRs which didn't have their tests run for a long time. It happened before that it broke master which isn't a huge problem since it can be fixed again but it still is annoying so we try to avoid it if possible.

The problem here is that travis is now gone but was still there when this PR ran, so to run the tests again someone would have to push into this PR and rebase. Since this is a small PR and is easy to check I think its fine to simply merge it without the extra steps (master is green so everything is looking good so far :)).

**Pull request merged**
