### PR TITLE
[cnd] merge master into cnd

### PR DESCRIPTION
**Pull request by bitrunner**
This merges master into the cnd branch bringing it up to date with the changes since May 2022.

1 conflict with nbbuild/cluster.properties was resolved by taking the changes from master.

1 build error in cnd/cnd.ui/src/org/netbeans/modules/cnd/loaders/QtUiDataLoader.java due to changes to org.openide.util.MapFormat API was resolved by doing a type conversion.

### CODE REVIEW

**Comment by vieiro** [comment]
Hi @bitrunner ,

Thanks for your interest in the cnd branch!

I think it's better to discuss in the mailing list how to proceed with the cnd branch. Maybe we want to integrate it with master and disable the cluster by default, much like the `rust` branch is being moved forward.

Thanks,
Antonio

**Comment by bitrunner** [comment]
As someone new to netbeans development, I don't feel comfortable offering an opinion on or injecting myself into big picture decisions.  I'm just a long time CND user with enough free time and motivation right now to try to help make CND great again.  Let's make some forward progress happen.

**Comment by vieiro** [comment]
> As someone new to netbeans development, I don't feel comfortable offering an opinion on or injecting myself into big picture decisions. I'm just a long time CND user with enough free time and motivation right now to try to help make CND great again. Let's make some forward progress happen.

Hi @bitrunner ,

I see. We'll, I think we'll have to decide how to move cnd forward. There're many different possibilities. Let's see what people say in the mailing list and then we'll move things forward. 

"long time CND user" opinions are indeed welcome in the mailing list, even more if those users are motivated :-).

**Comment by vieiro** [comment]
Hi @matthiasblaesing , this looks fine to me. Mind taking a second look?

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me. I had a look at the merge and the decisions look sane to me. @bitrunner @vieiro  thank you for continued working on this.

**Pull request merged**
