### PR TITLE
VersionVault integration with Netbeans

### PR DESCRIPTION
**Pull request by GaneshrajS30**
VersionVault is a SCM
URL: https://www.hcltechsw.com/versionvault/
which we like to integrate with Netbeans.

---
**^Add meaningful description above**

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for your PR, but why not deliver this as a plugin?

The code has multiple license headers, and it is unclear what the provenance of that code is.  It has both (c) Oracle (GPL/CDDL) and (c) HCL (Apache) headers!

If the reason for not making this a plugin aligns with the addition of the friend dependency, then we probably need to discuss opening up the relevant API.

In current state, sorry -1 from me.

**Comment by GaneshrajS30** [comment]
We feel if this plugin is getting distributed along with the Netbeans product, it will help BOTH VersionVault and ClearCase user, which means this plugin will work for both VersionVault and ClearCase.
It looks ClearCase plugin was obosolete some time ago and we took(from - https://github.com/emilianbold/netbeans-releases/tree/master/clearcase) that as a base and we upgraded and rebranded it to VersionVault. 

We have forked a copy of netbeans sources https://github.com/apache/netbeans/ and included upgraded netbeans-versionvault/clearcase plugin.
Also included the copyright statements for the files we have modified/upgraded, rest are same as from old ClearCase plugin  https://github.com/emilianbold/netbeans-releases/tree/master/clearcase. 

You have mentioned to distribute as a plugin, which means we need to upload the binaries to a netbeans market place from which our customer can pick it up? if yes, can you please share the location or process for that?

**Comment by vieiro** [comment]
Hi @GaneshrajS30 , as Neil has detected this code is not compatible with the Apache License.

You can create your own plugin instead, following the instructions here https://cwiki.apache.org/confluence/display/NETBEANS/How+to+get+plugin+on+Plugin+Portal+Update+Center

**Comment by lkishalmi** [comment]
It's better if you publish this one on the plugin portal, and file a PR against your required friend dependencies or make those requested API/SPI-s public.

Thank you for the contribution and to keep NetBeans in mind!

The code is a swampland of potential legal issues. I see old NetBeans ClearCase files from original NB authors, which were not donated by Oracle to ASF. Also the dual ASF license header is not good for code that you would contribute.

I'm going to close this PR now. Waiting for the plugin on the plugin portal!

**Pull request closed without merging**
