### PR TITLE
Fix LSP test using the New Gradle Wizard

### PR DESCRIPTION
**Pull request by lkishalmi**
Trivial change, as far as I could test it seems to work.

### CODE REVIEW

**Comment by mbien** [comment]
@lkishalmi the `ProjectViewTest` is using gradle project support in the test cases, do you think I should change CI so that LSP tests run when the `Gradle` label is set?

**Review by mbien — APPROVED** [review]
thanks for looking into this!

**Comment by neilcsmith-net** [comment]
@mbien other option might be to relook at using merge queue?

**Comment by mbien** [comment]
@neilcsmith-net I don't quite see how merge queues relate to this here. Merge queues also require reliable tests which NB is far from at the moment. Failing tests in a merge queue will trigger automated response - at least thats how the classic mechanism works.

**Comment by neilcsmith-net** [comment]
@mbien my understanding (maybe incorrect) would be that it could allow for all tests to run before the merge to master occurs, so could act as a failsafe for missing labels rather than adding more tests on labels where they might not be necessary. Just a thought. Can follow up on that elsewhere.

**Pull request merged**
