### PR TITLE
Snapshot of APIs as of NetBeans 19

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Snapshot of APIs as of NetBeans 19.  For review purposes only at this stage.  Not to be merged as / until release vote completes and updated if necessary.

<details><summary>Built in the usual way ...</summary>

```bash
# checkout branch (or release tag)
git checkout release190
git clean -dxf
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb190
git stash pop
git add -A
git commit -m "Snapshot of APIs as of NetBeans 19"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

Filtered diff created using -

```bash
curl -L https://github.com/apache/netbeans/pull/<PR_ID>.diff | filterdiff -#2- > filtered-apis-nb190.txt
```
</details>

Filtered diff : [filtered-apis-nb190.txt](https://github.com/apache/netbeans/files/12160957/filtered-apis-nb190.txt)

### CODE REVIEW

**Review by MartinBalin — APPROVED** [review]

**Comment by ebarboni** [comment]
LGTM huge changes with index bump also.

**Review by ebarboni — APPROVED** [review]

**Comment by ebarboni** [comment]
I do not get any conflicts. I'm not sure what the issue there

**Comment by neilcsmith-net** [comment]
@ebarboni I can handle next week if you want? This needs regenerating too before merge as I think there may be a couple of extra minor changes from the first RC.

**Comment by neilcsmith-net** [comment]
@ebarboni regenerated and fixed against current master.  Just waiting for tests.

In future we might want to consider doing this via delivery, with a second merge commit.  The commit is not an accurate snapshot of APIs, as it includes changes to sigfiles from master since branch.

**Comment by ebarboni** [comment]
LGTM by the way. Any workflow that ease is welcome

**Review by ebarboni — APPROVED** [review]

**Comment by neilcsmith-net** [comment]
Thanks @ebarboni Tests look good so merging.

> Any workflow that ease is welcome

It won't make it any easier!  It will just ensure that there is a commit somewhere that actually contains an accurate snapshot.

**Pull request merged**
