### PR TITLE
WIP: Integration of Graal.js parser with NetBeans

### PR DESCRIPTION
**Pull request by sdedic**
Jarda updated my abandoned attempt to integrate a new JS parser with NetBeans. Code in this PR is  in no way complete: many tests fail, positions are misreported from Graal.js code etc.

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
There is a [Jenkins job](https://builds.apache.org/job/incubator-netbeans-jsparser/) associated with the `sdedic:experimental/graaljs_parser` that builds the IDE and runs all `webcommon/*` tests. One it becomes green, this PR will be eligible for integration.

**Comment by Chris2011** [comment]
Will have a look, how I can help on the weekend. Maybe.

**Comment by matthiasblaesing** [comment]
The jenkins job was moved after graduation too:  https://builds.apache.org/job/netbeans-jsparser/

I put some work into it and while not finished, I think this is moving into the right direction:
https://github.com/matthiasblaesing/netbeans/tree/graaljs2

There are the updates in the tree:
- merge master into the branch to keep up with the recent changes
- fix compilation errors caused by changes in the graal.js API
- fix unittests in the webcommon cluster
- remove broken unittests in the webcommon cluster. They are not broken by the graaljs update, but by missing files, that were not donated

What reamains are mainly changed structures in the parser tree, these need further looking at.

@sdedic please consider pulling this in

**Comment by sdedic** [comment]
The GraalJS parser's integration, in the state when I had to left it 
around NB 10 release, was rather unpleasant: there were a lot of cases 
when the (current) GraalJS parser misreported text positions - non-issue 
for runtime, but critical for editing features.

Are you sure all that is fixed ?

-S.

Dne 13. 07. 19 v 13:01 Matthias Bläsing napsal(a):

**Comment by matthiasblaesing** [comment]
@sdedic no no everything is fixed. But I did not mean that it is ready, but that the changes improve the situation. I had to wade through compilation errors and non-graaljs caused unittest failures and if someone wants to pick up there he/she should not have to wade through the same mess.

I don't see this in master, but as an incremental update of this PR (still unfinished).

**Comment by sdedic** [comment]
Ah, excellent, then: wouldn't it hep to change this PR's contents to a branch in NB repo, so you (others) can make PRs more easily against the work-in-progress code ?

**Comment by JaroslavTulach** [comment]
>     * remove broken unittests in the webcommon cluster. They are broken by missing files, that were not donated

Fixing the tests in the `master` is something that should be integrated first. Rather than deleting the tests, I'd prefer to fix them. Just take the files from http://hg.netbeans.org/releases - the fact that Oracle hadn't donated some files, doesn't mean they cannot be used - CDDL is an Apache friendly license.

In any case, if you can create a PR fixing the tests in master, that would be excellent.

**Comment by matthiasblaesing** [comment]
@JaroslavTulach there is a slight missunderstanding: I improved the situation to the point where you can at least work with the code base and are not halted by false positives. I put some serious time into this - if you want it, take if not leave it, but I won't fix the mess others created again.

**Comment by matthiasblaesing** [comment]
I pushed my updated tree into the repository as the `graaljs2` branch. I experimented today a bit and it looks like graaljs will stay a moving target. Judging from signature check errors, methods were removed going from 19.0.0 to 19.1.0.

**Comment by matthiasblaesing** [comment]
I'm removing the `graaljs2` branch, as @jtulach created a relicensed graaljs parser and I'm preparing an update PR, that only contains the unittest fixes.

**Comment by sdedic** [comment]
@matthiasblaesing I would advise to keep the branch yet for a while. As far as I understand what was done, the OLD code was relicensed; so newer developments and newer JS specification is still not supported by the now-UPL js parser. Right, @JaroslavTulach  ?

**Comment by JaroslavTulach** [comment]
> newer JS specification is still not supported by the now-UPL js parser

Right. The language is at most ES2015. `let` isn't recognized as keyword, for example.

**Comment by JaroslavTulach** [comment]
> keep the branch yet for a while

What is a while?

If this PR is dormant, then let's close the PR! I don't want to prevent anyone to fix the tests or update the parser to more recent specs, but it seems that people are in general OK with the parser as currently integrated and I see no strive to drive this PR to conclusion.

Btw. I am closing just the PR, the branch stays untouched.

**Pull request closed without merging**
