### PR TITLE
nbjavac-upgrade-to-jdk-16

### PR DESCRIPTION
**Pull request by singh-akhilesh**

### CODE REVIEW

**Comment by geertjanw** [comment]
Hi @singh-akhilesh, please say so when this pull request is ready to be merged from your point of view, once we have merged this, we'll be ready for putting together the delivery branch and rc1.

**Comment by singh-akhilesh** [comment]
> Hi @singh-akhilesh, please say so when this pull request is ready to be merged from your point of view, once we have merged this, we'll be ready for putting together the delivery branch and rc1.

Hi @geertjanw , After my last commit few travis build jobs were failed. I am working on the this right now. Once all the jobs run successfully and code gets review by peers then this pull request is ready to be merge.

**Comment by singh-akhilesh** [comment]
Hi @geertjanw, all Travis jobs are passed now. PR is ready to review and merge for rc1.

**Comment by geertjanw** [comment]
Thanks for all the work.

Should this be merged or squash-and-merged?

**Comment by singh-akhilesh** [comment]
> Thanks for all the work.
> 
> Should this be merged or squash-and-merged?

I am waiting for reviewers @jlahoda or @Akshay-Gupta-Oracle to review it once.

**Review by lahodaj — APPROVED** [review]
Looks reasonable.

**Comment by arvindaprameya** [comment]
Approved, Thank you Akhilesh, looks good to go.

**Review by Akshay-Gupta-Oracle — APPROVED** [review]
Looks correct.

**Pull request merged**
