### PR TITLE
NETBEANS-3575 initial implementation.

### PR DESCRIPTION
**Pull request by GitHubb3R**

### CODE REVIEW

**Comment by eirikbakke** [comment]
This one will need a better commit title and description.

**Comment by GitHubb3R** [comment]
> This one will need a better commit title and description.

Does the original JIRA ticket suffice?
https://issues.apache.org/jira/browse/NETBEANS-3575

**Comment by eirikbakke** [comment]
The JIRA report is good, we just need a short summary for the git log as well. E.g. use title "[NETBEANS-3575] Fix ordering of j2ee.platform.classpath entires" for the commit title and a shorter summary of the bug in the commit description.

Also check that you have a real name/email in the git commit. (I'm not sure how to check this from the GitHub interface... but I remember we've had trouble with getting this info correct in the past once we merge the PR.)

The code changes look good--thank you!

**Comment by GitHubb3R** [comment]
> The JIRA report is good, we just need a short summary for the git log as well. E.g. use title "[NETBEANS-3575] Fix ordering of j2ee.platform.classpath entires" for the commit title and a shorter summary of the bug in the commit description.
> 
Thank you for the clarification! I've amended the commit in a way you requested.

> Also check that you have a real name/email in the git commit. (I'm not sure how to check this from the GitHub interface... but I remember we've had trouble with getting this info correct in the past once we merge the PR.)
>
I have no idea how to check this, or by checking so I would have no idea what I would be doing :)
But in any case the corresponding git properties should be configured properly. Furthermore GitHub doesn't let me push unless I'm logged in. Obviously I did not try a configuration that does not much the login information.

**Comment by matthiasblaesing** [comment]
The author information is partially ok - the email is present and looks correct, the real name though does not. You can use the git command to see the information:

`git log -n 3`

Shows the last three commits.

This PR must not be squashed, as the author information in the github profile is not public and thus will cause invalid author information on the squashed commit.

**Comment by GitHubb3R** [comment]
Sorry about that, I think I managed to correct the real name issue.

Is it OK if I'd like to keep my email hidden?

**Comment by matthiasblaesing** [comment]
Sorry, no correct author information is required. For larger contributions the ASF even requires an signed ICLA. For small contributions we are already relaxing the rules, but we still need to be able to determine the author.
The above is true for the git history (although that is public), you can keep your name out of the github profile, to do so see here:
https://github.com/apache/netbeans/pull/2061#issuecomment-612475333

**Comment by GitHubb3R** [comment]
Okay, if I configured things properly it should not be hidden.

**Comment by GitHubb3R** [comment]
Can I ask now if this request is all right to proceed?

I do not wish to rush anyone, but certainly would like to use a future NetBeans again instead of my own build (with the changes patched in each time) :-)

**Comment by hectorespert** [comment]
You should sync your code with the last changes in the origin repository.

**Comment by GitHubb3R** [comment]
Thank you for the links! It should OK now.

**Comment by eirikbakke** [comment]
Could you make this into a single commit that has all the relevant changes, and then force push again?

**Comment by GitHubb3R** [comment]
I think and really hope it is OK now :)

**Comment by GitHubb3R** [comment]
Any chance for this making it into 12.0 LTS :-) ?

**Comment by neilcsmith-net** [comment]
Can but ask! Over to @ebarboni

**Comment by ebarboni** [comment]
Hi author real name is sik.andra this should be changed I think, mail is ok

**Comment by GitHubb3R** [comment]
I have no idea how that got messed up again. I feel like a novice, sorry for the inconvenience!

This should really be OK now :)

**Comment by eirikbakke** [comment]
@ebarboni How do I see which author name/email will be associated with the commit?

**Comment by GitHubb3R** [comment]
Its mentioned in a previous commit:

> The author information is partially ok - the email is present and looks correct, the real name though does not. You can use the git command to see the information:
> 
> `git log -n 3`
> 
> Shows the last three commits.

Now looking back, I think the author info might have become incorrect, when I did the rebase the first time without properly amending the commit and correcting the author. (That was because I was unable to properly squash the commits since I did merge into my fork instead of a rebase after trying to complete the request to make the changes into a single commit.)

**Comment by ebarboni** [comment]
I  open this in GitHub Desktop  then wait for sync of PR (open in terminal)  and do git log -n3 
@hectorespert  and @matthiasblaesing are on a PR to help this process

**Comment by eirikbakke** [comment]
I was hoping for a way to do it from the web interface, rather than having to clone the branch to my own computer. Git operations on the big NetBeans repo are really slow from WSL...

**Comment by GitHubb3R** [comment]
> 
> 
> I was hoping for a way to do it from the web interface, rather than having to clone the branch to my own computer. Git operations on the big NetBeans repo are really slow from WSL...

Hmm, what if you use the patch link?
https://patch-diff.githubusercontent.com/raw/apache/netbeans/pull/1968.patch

**Comment by eirikbakke** [comment]
I tried that, but it doesn't say "Author:" like in the usual git commit messages, it says "From:". Perhaps they mean the same.

**Comment by ebarboni** [comment]
seems ok merging

**Pull request merged**
