### PR TITLE
Revert "Fix Imports" changes

### PR DESCRIPTION
**Pull request by junichi11**
Revert the following PRs:

- https://github.com/apache/netbeans/pull/5579
- https://github.com/apache/netbeans/pull/5681
- https://github.com/apache/netbeans/pull/5758
- https://github.com/apache/netbeans/pull/5801

Regression:

- https://github.com/apache/netbeans/issues/6039
- https://github.com/apache/netbeans/issues/6056
- https://github.com/apache/netbeans/issues/6082

Add unit tests
- Add unit tests for #6056 and #6082

### CODE REVIEW

**Comment by junichi11** [comment]
@tmysik I would like to revert these PRs because there are some problems(Especially, it's hard to investigate the performance problem #6039) as regression.

**Review by tmysik — APPROVED** [review]

**Comment by tmysik** [comment]
This is unfortunate but I can imagine that there is no other way... perhaps trying bisect or applying reverted changes one by one could help here, hopefully. Thanks!

**Comment by junichi11** [comment]
@tmysik Yes, I'll try to reimplement them one by one. Thank you!

**Comment by thanasis-oob** [comment]
In version 18, on ubuntu 22 that uses snap, the problem persists. In addition, the problem is appeared in some classes.

**Comment by neilcsmith-net** [comment]
@thanasis-oob this change is in NetBeans 19, see milestone.

**Pull request merged**
