### PR TITLE
StringBuilder related performance improvements - no logic changes

### PR DESCRIPTION
**Pull request by lbownik**
fixed few "concatenation in append" issues
initialized String builders to larger size to mitigate internal realocations
removed one unnecessary StringBuilder creation

### CODE REVIEW

**Comment by tbw777** [comment]
I have a branch where append is fixed for 2000+ files. But I'm not allowed to make that kind of change anymore

**Comment by tbw777** [comment]
`JavaCodeTemplateProcessor.java:212: error: ')' expected`

**Comment by neilcsmith-net** [comment]
Please at least check things build and run before opening a PR.  Thanks!

**Comment by matthiasblaesing** [comment]
@lbownik  and @tbw777 
> But I'm not allowed to make that kind of changes anymore

This is nonsense. There is a small number of active reviewers. @BradWalker gives a pretty good advice here:

https://github.com/apache/netbeans/pull/5332#issuecomment-1399174804

If you did not already do so, I strongly advice you to subscribe to dev@netbeans.apache.org (https://netbeans.apache.org/community/mailing-lists.html#dev), where you can raise questions and read about current discussions.

I think it is worth reading.

**Pull request closed without merging**
