### PR TITLE
[NETBEANS-4275] Add code completion for @inheritDoc

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-4275

netbeans-4275-cc-for-inheritDoc

### CODE REVIEW

**Comment by junichi11** [comment]
@ebarboni This is a small change. So, I don't think it will cause any problems in 12.5.

**Review by tmysik — APPROVED** [review]

**Comment by tmysik** [comment]
@ebarboni @junichi11 

The patch is OK, feel free to merge this PR if there is no problem with it. Thanks.

**Comment by ebarboni** [comment]
it s ok

**Comment by junichi11** [comment]
Thank you, guys!

**Pull request merged**
