### PR TITLE
Removed a lot of compiler warnings. Part 2

### PR DESCRIPTION
**Pull request by tbw777**
Inserted diamond in constructions like this:
`ArrayList<Strings> = new ArrayList();`
No any interfaces was changed

Part 2:
Replaced on already defined generics:
```
Collections.EMPTY_SET -> Collections.emptySet()
Collections.EMPTY_LIST -> Collections.emptyList()
Collections.EMPTY_MAP -> Collections.emptyMap()
```

Previos part 1: #5487

### CODE REVIEW

**Comment by BradWalker** [comment]
I did a substantial amount of cleanup in this area previously.

I count 149 remaining examples of this. Why is your code change much more than this?

**Comment by tbw777** [comment]
Thereis a more difficult search patterns was found, for example

two lines:
```
List<String> test = condition ? Empty
: new ArrayList()
```

And so on

**Comment by tbw777** [comment]
DefaultComboBoxModel will be refactor in the feature in separate PRs, therefore excluded

**Comment by BradWalker** [comment]
Here's what I would suggest and what I've previously done..

Reduce this check-in to 3 separate PRs. One for each of EMPTY_SET, EMPTY_LIST, and EMPTY_MAP.

It's just too large for me. But, if you do this, I will promptly review it.

Keep things simple. Really simple and you much more likely to get help.

**Comment by mbien** [comment]
we can do one PR, 3 commits. review and then squash before merge. This conserves resources.

**Comment by mbien** [comment]
simply force push into this PR. no need to start new ones.

**Comment by BradWalker** [comment]
@mbien , works for me..

**Comment by neilcsmith-net** [comment]
> we can do one PR, 3 commits. review and then squash before merge.

Also, those seem fine as 3 commits to me without squashing - potentially worth keeping in history as is.

**Comment by mbien** [comment]
@tbw777 I believe you misunderstood what @BradWalker said here: https://github.com/apache/netbeans/pull/5491#issuecomment-1429790958

please do the following:
 - remove the two commits which do the diamond changes since this PR is already large enough
 - split the empty collection commit into 3: one for Set, one for Map, one for List
 - force push into this PR

thanks!

**Comment by tbw777** [comment]
i lost all changes ))

**Comment by tbw777** [comment]
recovered

**Pull request closed without merging**
