### PR TITLE
StartupPage: switch whats new feed to release list.

### PR DESCRIPTION
**Pull request by mbien**
the blog is no more

switches the feed to the release list / change log:
start-page_release-feed

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
-0 from me, sorry.  I'm not sure hard-coding a link to a feed we don't control is a good idea.  The summary as is doesn't look great (although might get us to write better release notes!).  We should think about whether advertising unreleased rc's here is a good idea.  And it doesn't address the issue of all the extant other releases of the IDE that won't get this fixed.

Personally, I'd stick with what we do control, request infra help in redirecting the existing links to static files, including a (for now) static feed file.  Almost the only thing that's gone in for a while is new releases, so not too much work to keep up-to-date pending replacing this with something else.

**Comment by mbien** [comment]
ok with me, I am not going to do the infra part though. Only had time for this hotfix.

**Comment by mbien** [comment]
> Personally, I'd stick with what we do control,

I do get what you mean, but we do control the content of the feed. Only committer can add feed entries by creating releases.

**Comment by neilcsmith-net** [comment]
Yes, but we don't have control of how that content is used to generate the feed, or whether it will continue to exist.

I'll ping infra to see what's possible.  The main link is fine, except it redirects to a page that doesn't currently exist, just need to redirect https://blogs.apache.org/netbeans/feed/entries/atom to something I guess?

**Comment by mbien** [comment]
@neilcsmith-net  eric is on it already: https://github.com/apache/netbeans-website/pull/659

**Pull request closed without merging**
