### PR TITLE
[NETBEANS-3428] Update FlatLaf from 0.18 to 0.20

### PR DESCRIPTION
**Pull request by DevCharly**
Hi there, I'm Karl, creator of FlatLaf. This is my first (but not last) PR. Hope it is OK 😉 

This PR updates FlatLaf to 0.20, which includes following fixes/improvements for NetBeans:

- ComboBox: Fixed issues with NetBeans `org.openide.awt.ColorComboBox`
  component.
- Fixed color of links in HTML text.
- Button: Make button square if button text is "..." or a single character.
- Look and feel identifier returned by `FlatLaf.getID()` now always starts with
  "FlatLaf". Use `UIManager.getLookAndFeel().getID().startsWith( "FlatLaf" )` to
  check whether the current look and feel is FlatLaf.

Here is a full list of changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/0.20

### CODE REVIEW

**Comment by geertjanw** [comment]
Wow, brilliant.

**Comment by lkishalmi** [comment]
Huh.
Thank you and welcome here!
It seems Flatlaf is pretty swift on releases. I'm also tinkering on a gruvbox theme based on Flatlaf.
So I've thought it would be better to move the actual flatlaf jar into a separate library embedder module.
I'm just finished PR, and it also contains the 0.20 upgrade.
I hope you don't mind if I'd close this PR in favor of that one.

**Comment by DevCharly** [comment]
> It seems Flatlaf is pretty swift on releases.

Yes, currently pushing FlatLaf forward to reach 1.0 in the next months...

> I hope you don't mind if I'd close this PR in favor of that one.

No problem 👍 

BTW many thanks for adding FlatLaf to NetBeans. This is amazing.
Started the FlatLaf project only 3 months ago and now it is in NetBeans...

**Comment by lkishalmi** [comment]
Well, Thanks for Flatlaf as well I think NetBeans badly needs a good flexible HiDPI aware LaF.
Closed in favor of #1699

**Comment by Chris2011** [comment]
Thx for creating flatlat @DevCharly :)

**Pull request closed without merging**
