### PR TITLE
Implement repeatExecution for GradleItem

### PR DESCRIPTION
**Pull request by alex268**
Fixed non working RepeatExecution action for Gradle projects.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
What does not work without this? I created a gradle project with the IDE wizard and rerunning tasks seems to work correctly. Can you give steps to reproduce?

**Comment by alex268** [comment]
Netbeans IDE has action "Repeat Build/Run", located in "Run" menu. For example, you can run any project action (build, clean, test project, test single file) in any way like context menu or the editor's badges and then repeat this action without return to project or file. It's very useful if this action will be binded on keyboard shortcut.
I often used this action for Maven projects and was upset, that it doesn't work for Gradle projects

**Comment by matthiasblaesing** [comment]
@alex268 thanks for explaining. Indeed my focus was wrong, I was focused on the output window, and indeed this is a feature I have not yet used and might make it easier for me in the future.

@lkishalmi to me this looks trivially correct. Do you agree?

**Review by lkishalmi — CHANGES_REQUESTED** [review]
Well, not all tasks are repeatable, so let's check for that:
```java
            if (config.getExecFlags().contains(REPEATABLE)) {
                RunUtils.executeGradle(config, null);
            }
```

**Comment by lkishalmi** [comment]
I know two of them `compile.single` and `debug.fix` . As the repeat action repeats previously executed Gradle command line, these make sense, as the command line has to be re-evaluated, also the debug fix might have other quirks.

**Comment by matthiasblaesing** [comment]
@lkishalmi ah - thank you. Could you please have a another look? As the solution matches your request - good to go?

**Comment by matthiasblaesing** [comment]
I intent to merge this some time this week. @lkishalmi please speak up if I should wait.

**Comment by matthiasblaesing** [comment]
@alex268 thank you for your work!

**Pull request merged**
