### PR TITLE
Including nb-javac binaries in all the complementary distributions

### PR DESCRIPTION
**Pull request by jtulach**
[LEGAL-563](https://issues.apache.org/jira/browse/LEGAL-563) has been approved and maybe the time has come to implement the approval. This is my attempt to do so.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
As per comment on list, -1 for 12.6, should definitely be considered for 13.

**Comment by JaroslavTulach** [comment]
Let's give this one more try.

**Comment by matthiasblaesing** [comment]
I did a first pass on the verification errors and pushed this (feel free to squash into your changes): https://github.com/matthiasblaesing/netbeans/tree/pr-3251

There are four commits (I think the descriptions are self explaining):
https://github.com/matthiasblaesing/netbeans/commit/08395c1f7a564012332cb4f46a7693cdecfef5ff
https://github.com/matthiasblaesing/netbeans/commit/5e84be74a54a0cf698ee85b629270f9bdbb4223e
https://github.com/matthiasblaesing/netbeans/commit/e2dd5f1bb200f4caf68f722cfdebae1d4bf1edb2
https://github.com/matthiasblaesing/netbeans/commit/4c120ca0156294cd2ef31954a2690136d5f9162e

The fourth needs an explanation why this is -CP save (see "Comment" fields changed there).

Rebuilding from source from maven central fails and I though the build had a state, where a java compiler was used to build javac and not the some derived version (frgaal). My understanding was, that jackpot should be used to patch out all problems and then let the JDK8 or JDK11 javac do the work to compile its newer counter part.

**Comment by JaroslavTulach** [comment]
Thanks a lot for your review and commits Matthias. I'll address them by end of November. Now I am busy elsewhere.

> explanation why this is -CP save

The build copies some files from JDK. The best would be to copy only those that contain "Classpath Exception" substring.

> Rebuilding from source from maven central fails

I'll investigate and fix.

> jackpot should be used to patch out all problems

Jackpot is used to fix problems of "too new API". Potentially it could be used to fix also syntax, but using retrofitting compiler is easier.

> maven distribution should also point to the correct github repository

I see. I fix that. The ultimate goal would (in my opinion) be to eliminate the repo altogether and put the build scripts into NetBeans repository. That's certainly not going to be part of this PR however.

**Comment by neilcsmith-net** [comment]
> The ultimate goal would (in my opinion) be to eliminate the repo altogether and put the build scripts into NetBeans repository.

That would involve getting rid of every bit of GPL+CPE licensed code in the build process and patches before donation. Doable?

**Comment by JaroslavTulach** [comment]
> code in the build process and patches before donation. Doable?

Build script is written by me and I can donate it under Apache license. The `nbjavac.*` classes are also written by me and could also be hosted directly in NetBeans repository. However that's a bit distant goal outside of scope of this PR.

**Comment by neilcsmith-net** [comment]
Thanks @JaroslavTulach . I think the viability of the end goal is of some relevance, even if out of direct scope of the changes here.  I agree with you that it would be the best ultimate goal.

Agree with issues @matthiasblaesing highlighted for addressing before merging, but let's add milestone.

**Comment by jtulach** [comment]
> > Rebuilding from source from maven central fails
> 
> I'll investigate and fix.

I've just tried:
```bash
$ wget https://repo1.maven.org/maven2/com/dukescript/nbjavac/nb-javac/jdk-17+35/nb-javac-jdk-17+35-sources.jar
$ unzip nb-javac-jdk-17+35-sources.jar
$ JAVA_HOME=~/bin/jdk-17/ ant -f ./make/langtools/netbeans/nb-javac clean jar
$ $ ls make/langtools/netbeans/nb-javac/dist/
nb-javac-jdk-17+35-api.jar  nb-javac-jdk-17+35-impl.jar
```
I'd say: It builds! One just has to use JDK17. Readme updated in https://github.com/JaroslavTulach/nb-javac/commit/9dfc98261ae8dbce33fc5cf958e4054d64718fec

> > maven distribution should also point to the correct github repository

Done: https://github.com/JaroslavTulach/nb-javac/commit/1c51ff89c690a4b0cd88f2449df8d78c34e77558

These changes will be part of subsequent releases of automatically generated nb-javac. For purposes of this PR (which doesn't update to new version of JARs at all), we can live with current JARs. I expect an update will be needed before January release of NetBeans anyway as additional issues accumulate.

**Comment by matthiasblaesing** [comment]
Thank you for the hint - my error was, that I read the README and used JDK-14, with 17 it seems to work. I will have a closer look in the next few days. In the mean time I tested this update and it breaks hard if nbjavac was installed:

```
java.lang.IllegalStateException: Missing hosting module org.netbeans.libs.javacimpl for fragment org.netbeans.modules.nbjavac.impl
	at org.netbeans.ModuleManager.refineClassLoader(ModuleManager.java:909)
	at org.netbeans.StandardModule.classLoaderUp(StandardModule.java:527)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1330)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
	at org.netbeans.core.startup.Main.start(Main.java:282)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I did not try this with a completely clean environment, but I build master and install nbjavac, then I build this branch and tried to run this.

**Comment by JaroslavTulach** [comment]
`org.netbeans.libs.javacimpl` module is being removed by this PR. Clean build recommended.

**Comment by matthiasblaesing** [comment]
> `org.netbeans.libs.javacimpl` module is being removed by this PR. Clean build recommended.

Yes, *I* know how to fix the broken installation, but what I don't understand is: Why do we break it in the first place? From the description of 82662d3 is the commit, that breaks the case. Why not live on with the unmerged module?

**Review by dbalek — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
> Why not live on with the unmerged module?

I have never understood the separation between the Javac API and Javac impl. They have the closest [proximity](http://wiki.apidesign.org/wiki/Proximity) possible. Different versions are unlikely to work with each other. [NetBeans Runtime Container](http://wiki.apidesign.org/wiki/NetBeans_Runtime_Container) has other ways to hide the implementation - not expose its packages to public. 

With two modules we are facing classloading issues: when the `javax/tools/ToolProvider` from Javac API is using `ServiceLoader`, it may not find the right implementation, but rather an implementation from the JDK. That doesn't happen with a single module.

We have problems with enabling/disabling. Both the API and the Impl need to be enabled & disabled at once (ability to disable the `nbjavac` requested by Michael). While it might be possible to use autoload/eager properly, putting both JARs into the same module solves the problem without any intricate hassle.

**Comment by sdedic** [comment]
I would recommend to consider moving
```
OpenIDE-Module-Recommends: org.netbeans.libs.nbjavac
```
from `java.kit` to `java.source.base` - so that in any situation that depend on java src model nbjavac gets activated, if possible. The LSP server AFAIK does not bundle entire java.kit, still it could benefit from nbjavac enabled.

**Comment by JaroslavTulach** [comment]
> I would recommend to consider moving `OpenIDE-Module-Recommends: org.netbeans.libs.nbjavac` from `java.kit` to `java.source.base` - so that in any situation that depend on java src model nbjavac gets activated, if possible. The LSP server AFAIK does not bundle entire java.kit, still it could benefit from nbjavac enabled.

Great idea, Sváťo! Done in 9dd5693

**Review by matthiasblaesing — COMMENTED** [review]
Thank you for the explanation - so we are between a rock and a hard place. Given that only users of nightlies are affected (I assume after an update users can't import the nbjavac modules, so they should be save), it is IMHO ok.

The changes look good, I have a minimal nitpick, these files and directories should be removed:

```
nb/updatecenters/extras/
nb/updatecenters/extras/nbjavac.impl
nb/updatecenters/extras/nbjavac.impl/build
nb/updatecenters/extras/nbjavac.impl/build/classes
nb/updatecenters/extras/nbjavac.impl/build/classes/org
nb/updatecenters/extras/nbjavac.impl/build/classes/org/netbeans
nb/updatecenters/extras/nbjavac.impl/build/classes/org/netbeans/modules
nb/updatecenters/extras/nbjavac.impl/build/classes/org/netbeans/modules/nbjavac
nb/updatecenters/extras/nbjavac.impl/build/classes/org/netbeans/modules/nbjavac/impl
nb/updatecenters/extras/nbjavac.impl/build/classes/org/netbeans/modules/nbjavac/impl/Bundle.properties
nb/updatecenters/extras/nbjavac.impl/build/no-license.txt
nb/updatecenters/extras/nbjavac
nb/updatecenters/extras/nbjavac/build
nb/updatecenters/extras/nbjavac/build/classes
nb/updatecenters/extras/nbjavac/build/classes/org
nb/updatecenters/extras/nbjavac/build/classes/org/netbeans
nb/updatecenters/extras/nbjavac/build/classes/org/netbeans/modules
nb/updatecenters/extras/nbjavac/build/classes/org/netbeans/modules/nbjavac
nb/updatecenters/extras/nbjavac/build/classes/org/netbeans/modules/nbjavac/Bundle.properties
nb/updatecenters/extras/nbjavac/build/no-license.txt
nb/updatecenters/extras/nbjavac.api
nb/updatecenters/extras/nbjavac.api/build
nb/updatecenters/extras/nbjavac.api/build/classes
nb/updatecenters/extras/nbjavac.api/build/classes/org
nb/updatecenters/extras/nbjavac.api/build/classes/org/netbeans
nb/updatecenters/extras/nbjavac.api/build/classes/org/netbeans/modules
nb/updatecenters/extras/nbjavac.api/build/classes/org/netbeans/modules/nbjavac
nb/updatecenters/extras/nbjavac.api/build/classes/org/netbeans/modules/nbjavac/api
nb/updatecenters/extras/nbjavac.api/build/classes/org/netbeans/modules/nbjavac/api/Bundle.properties
nb/updatecenters/extras/nbjavac.api/build/no-license.txt
```

**Review by matthiasblaesing — APPROVED** [review]

**Review by sdedic — APPROVED** [review]
thanks, @JaroslavTulach

**Comment by JaroslavTulach** [comment]
> directories should be removed

Thanks. Done in 2f9952f

**Comment by JaroslavTulach** [comment]
Everything is green except `"ant $OPTS -f ide/xml.retriever test" exited with 1` in [Travis CI run](https://app.travis-ci.com/github/apache/netbeans/jobs/549753669) which fails also locally and in other PRs with:
```
    [junit] Testcase: shouldUseKeyStoreFromSystemProperties(org.netbeans.modules.xml.retriever.impl.SecureURLResourceRetrieverTest):    Caused an ERROR
    [junit] Server returned HTTP response code: 400 for URL: https://client.badssl.com/
    [junit] java.io.IOException: Server returned HTTP response code: 400 for URL: https://client.badssl.com/
    [junit]     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    [junit]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
    [junit]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
    [junit]     at java.security.AccessController.doPrivileged(Native Method)
    [junit]     at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
    [junit]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
    [junit]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
    [junit]     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
    [junit]     at org.netbeans.modules.xml.retriever.impl.URLResourceRetriever.getInputStreamOfURL(URLResourceRetriever.java:164)
    [junit]     at org.netbeans.modules.xml.retriever.impl.SecureURLResourceRetriever.retrieveDocument(SecureURLResourceRetriever.java:81)
    [junit]     at org.netbeans.modules.xml.retriever.impl.SecureURLResourceRetrieverTest.shouldUseKeyStoreFromSystemProperties(SecureURLResourceRetrieverTest.java:87)
    [junit] Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://client.badssl.com/
    [junit]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
    [junit]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
    [junit]     at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    [junit]     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
    [junit]     at org.netbeans.modules.xml.retriever.impl.URLResourceRetriever.getInputStreamOfURL(URLResourceRetriever.java:147)
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.xml.retriever.impl.SecureURLResourceRetrieverTest FAILED

```
I don't thing the SSL failure is related to my changes, so I merge anyway. CCing @asbachb

**Comment by jtulach** [comment]
> ... why this is -CP save...

The best way to ensure only files covered by _Classpath exception_ are used is to automate it: https://github.com/JaroslavTulach/nb-javac/pull/1

**Pull request merged**
