### PR TITLE
Fix the syntax error for the constant array access #4684

### PR DESCRIPTION
**Pull request by junichi11**
#4684 

- Fix the grammar file
- Add unit tests

#### Screenshot

Before:

nb-gh-4684-syntax-before

After:

nb-gh-4684-syntax

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
It seems github actions did not pick up the PHP label. I'll try the "super secret" trick that was added (locking + unlocking this PR). Please don't be irritated.

**Comment by junichi11** [comment]
@tmysik Could you please have a look at this? If there is no problem, let's merge it :) Thanks!

**Review by tmysik — APPROVED** [review]

**Comment by junichi11** [comment]
@tmysik Thank you for your review!

**Comment by tmysik** [comment]
@junichi11 Nothing to thank for, really. Thanks for your work!

**Pull request merged**
