### PR TITLE
[NETBEANS-1309] add support for @summary javadoc tag

### PR DESCRIPTION
**Pull request by jherkel**
original issue https://issues.apache.org/jira/browse/NETBEANS-1309

### CODE REVIEW

**Comment by mbien** [comment]
NetBeans 16 already has auto completion for the summary tag. What is this PR adding to that?

**Comment by jherkel** [comment]
@mbien  With this patch you can see content of "@summary" tag when javadoc popup is displayed and also reformatting of "@summary" tag should be working.

**Comment by matthiasblaesing** [comment]
@mbien I think this comparison shows the fix. Compare the contents of the javaodoc comment and the rendering.

Before:

image

After:

image

**Review by matthiasblaesing — APPROVED** [review]
Change looks sane to me.

**Review by mbien — APPROVED** [review]
awesome - code looks good. Thanks a lot for the screenshots, I was testing it but must have overlooked that detail.

Screenshots are great in general since PRs are directly linked from the release notes.

**Comment by mbien** [comment]
merging since we just fixed master :)
thanks @jherkel!

**Pull request merged**
