### PR TITLE
Java EE 8 Support Updates

### PR DESCRIPTION
**Pull request by juneau001**
This PR includes new resource files and two minor code modifications.  The code modifications update the webapp-javaee8 maven archetype version to 1.3.  Updates in this PR address the following issues:

NETBEANS-2811
NETBEANS-2810
NETBEANS-2799
NETBEANS-2779
NETBEANS-2776
NETBEANS-2761

### CODE REVIEW

**Comment by geertjanw** [comment]
Awesome. :-)

**Comment by neilcsmith-net** [comment]
Great!  Is this ready to merge for NB11.1?  If so, or when it is, please tag me as a reviewer and label with NB11.1 so I know it's ready.  Thanks!

**Comment by neilcsmith-net** [comment]
Are the commit dates right?!

**Comment by juneau001** [comment]
I only intended to open the PR for the last two commits (both took place on 7/9/2019).  However, when I synced my fork from upstream and then committed my updates, it fell out this way (showing all of the previous commits for Java EE 8 support).  I initially closed the PR and I was going to try and do something different, but I reopened so that someone could advise.  There are only 12 file changes with this PR, but all of my previous commits are appearing in the list...will that cause an issue?  Thanks

**Comment by neilcsmith-net** [comment]
Probably because I squashed and merged your previous PR I guess.  Will try same with this one and see where we get to.

It's a good idea to have your own master synced to upstream and create a temporary branch per PR.

**Comment by neilcsmith-net** [comment]
Can you do a sanity check on the merge commit so we can revert if required before I sync with release branch tomorrow?  Thanks!

**Comment by juneau001** [comment]
Thanks @neilcsmith-net I will take a look and let you know if I see any issues.  In the future, I will create a temporary branch per PR, as you recommend.  My apologies for not doing so this time.

**Pull request merged**
