### PR TITLE
Fix: Multiple CustomIndexer with same Mime-Type use the priority of the IndexerFactory + Tooltip of columns in result-table

### PR DESCRIPTION
**Pull request by ses1112**
If you have multiple CustomIndexer with the same Mime-Type and you override the method "getPriority" in the corresponding IndexerFactory, this priority is ignored/never used.
So there is the bug, that sometimes it can be that this CustomIndexers are executed in the wrong order.

If you execute a query on the db, a result-table appears. There you can hover about the column-name und you can see some additional information about the structure of the column. If the column is of the type string, it also shows the attribute "length" with the precision of the column. This doesn't make sense, because by string there is no precision.
It occured with MariaDB and with a column of the type char(36).

### CODE REVIEW

**Review by matthiasblaesing — CHANGES_REQUESTED** [review]
I verified the database issue and the change looks sane. 

The change to the indexer sound sane but would get preferably a test to verify the change.

The changes can't be merged as is. PRs should be grouped by theme/area, which is not the case here. In addition we need to track contributions and record keeping is done in jira. Please create an issue on the netbeans jira (https://issues.apache.org/jira/secure/Dashboard.jspa) and reference the issue. It is referenced by fomatting the subject line of the commit as "[NETBEANS-XXXX] YYYY", where XXXX is the issue number and YYYY is the summary.

**Comment by lkishalmi** [comment]
@ses1112  please address the requested changes by EOB tomorrow (PDT). Otherwise I have to move this PR out of the 12.2 release train.

**Comment by neilcsmith-net** [comment]
Still marked as changes requested from @matthiasblaesing and needs the base branch changed to master if to be merged prior to freeze.

**Comment by ses1112** [comment]
> 
> 
> Still marked as changes requested from @matthiasblaesing and needs the base branch changed to master if to be merged prior to freeze.

I don't have the knowledge to write a test.

**Comment by matthiasblaesing** [comment]
@ses1112 block results from this:

> The changes can't be merged as is. PRs should be grouped by theme/area, which is not the case here. In addition we need to track contributions and record keeping is done in jira. Please create an issue on the netbeans jira (https://issues.apache.org/jira/secure/Dashboard.jspa) and reference the issue. It is referenced by fomatting the subject line of the commit as "[NETBEANS-XXXX] YYYY", where XXXX is the issue number and YYYY is the summary.

This is independed of a test. The changes themselves are fine, this is just a matter of getting the tracking right.

**Comment by ses1112** [comment]
Thanks for your help, i created two issues and two pull requests. For a better overview, i close this request.

**Pull request closed without merging**
