### PR TITLE
TaskList Model issues broken table model change events (breaks on JDK21+)

### PR DESCRIPTION
**Pull request by matthiasblaesing**
With JDK21 validation of removeIndexInterval and addIndexInterval methods was improved. This reveals an issue in the table model change events, that are published by the TaskListModel. For example it was observed, that the startRow and endRow indices were issued in the wrong order.

This results in:

```
java.lang.IndexOutOfBoundsException: index or length is negative
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:656)
	at java.desktop/javax.swing.JTable.tableRowsInserted(JTable.java:4539)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4475)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:237)
	at org.netbeans.modules.tasklist.ui.TaskListModel$1.run(TaskListModel.java:143)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
```

### CODE REVIEW

**Review by lkishalmi — APPROVED** [review]
Haven't checked all the details in `tasksAdded` and `tasksRemoved` but the new lambda part seems to be pretty similar in them. Probably could be put together in a private method. 

Otherwise seems reasonable. +1 for removing the synchronization.

**Comment by matthiasblaesing** [comment]
@lkishalmi thanks for the review, unified the update code in 5dc3905

**Review by mbien — APPROVED** [review]
looks good.

`taskList.getTasks` returns a copy so there should be no race caused by the delay of  `invokeLater`.

**Review by lkishalmi — APPROVED** [review]
Thank you!

**Pull request merged**
