### PR TITLE
Netbeans license headers cleanup check-in #1

### PR DESCRIPTION
**Pull request by BradWalker**
Netbeans license headers cleanup check-in #1.. The first of several..
    
    Add missing ALv2 license headers to form files.

### CODE REVIEW

**Comment by junichi11** [comment]
@BradWalker `#xx` means issue/pr number in the GitHub. So, should use another one.

**Comment by junichi11** [comment]
@matthiasblaesing 

> I don't think the `#1` in the commit message is a deal breaker. That github decided to try to gather information from plain text insteaf of structured information is a problem of github, not Brad. Try to add some random "@" into messages and a random number of people get CCed.

I didn't mean that. Actually, I approved this. I just would like to avoid unnecessary notification/link. I meant I suggest use another one (from next time; It's OK with me to merge this as it is) if we need not use `#xx` absolutely. It's a problem of GitHub, but it's better if we can avoid that, I think.

**Comment by BradWalker** [comment]
Hey @junichi11 and @matthiasblaesing, thanks for the feedback.. I would NEVER have known that GitHub was trying to parse my pull request for notification.. Thanks.. I'll be more careful next time.. 

Can @junichi11 commit my changes for me?

Thanks to both of you!

**Comment by junichi11** [comment]
@BradWalker Never mind :) Merging.

**Comment by matthiasblaesing** [comment]
Thanks to the both of you. :+1:

**Pull request merged**
