### PR TITLE
Use StructureProvider to populate navigator

### PR DESCRIPTION
**Pull request by jtulach**
We at [Enso](http://enso.org) are finally adding _VSCode outline view_ into [Enso VSCode extension](https://marketplace.visualstudio.com/items?itemName=Enso.enso4vscode):

- https://github.com/enso-org/enso/pull/7054

We had to write our own [EnsoStructure provider](https://github.com/enso-org/enso/pull/7054/files#diff-48e5e6c6cd09cd1d1398cb39973470e4d85a212d0df83d8240186235e55fb483R19). As the snapshots in the [pull request demonstrate](https://github.com/enso-org/enso/pull/7054) it is _working fine in VSCode_.

However: I also **want it to work in NetBeans** and IGV!

I see little point writing own navigator implementation and registering it in the Enso NBM. Especially when my _original vision_ of the [LSP API](https://bits.netbeans.org/22/javadoc/org-netbeans-api-lsp/) saw it as a way to hook into VSCode **as well as** NetBeans by _writing one implementation_ and _using it in both_ systems. This PR is my attempt to contribute to that vision.

- Existing `lsp.client` module now checks for presence of [StructureProvider](https://bits.netbeans.org/22/javadoc/org-netbeans-api-lsp/org/netbeans/spi/lsp/StructureProvider.html)
- When found, it extracts the `StructureElement` hierarchy and builds nodes for the elements

The functionality is very close to the already existing functionality that works via LSP4J interfaces. Maybe there is a way to _share the navigators_ - either by abstracting the functionality to common interfaces or by bridging (now deprecated) `org.eclipse.lsp4j.SymbolInformation` to `StructureElement` - what do you think? **Abstracted common functionality** in 47d411b and **using it** in edf081f

In any case, I'd be thankful if NetBeans recognized various  [LSP API providers](https://bits.netbeans.org/22/javadoc/org-netbeans-api-lsp/) and used them in the classical UI where appropriate. This is how NetBeans look with this PR and [Enso4Igv NBM version v1.36.114](https://github.com/enso-org/enso/actions/runs/9509862775?pr=7054):

Enso Structure in NetBeans 22+

### CODE REVIEW

**Comment by ppisl** [comment]
Good idea. At first glance, it seems good.

**Review by dbalek — APPROVED** [review]
Looks fine to me.

**Review by lahodaj — COMMENTED** [review]
I am not much opposed to reusing the `StructureProvider`, but won't this mean we will get the dynamic LSP panel for all MIME types that have `StructurePovider`, in addition to their existing navigator panels?

**Comment by jtulach** [comment]
> I am not much opposed to reusing the `StructureProvider`, 

Great. I am glad you find the new dependency on `lsp.api` OK.

> but won't this mean we will get the dynamic LSP panel for all MIME types that have `StructureProvider`, 
> in addition to their existing navigator panels?

That was the case. Maybe it is not that bad, especially when the `StructureProvider` is listed as the last option. But for now, I am disabling this `StructureProvider` view when there is normal `Navigator/Panels/mime/type` registration.

Since 7ef43e0 we display `StructureProvider` navigator only when there is no better navigator showing.

**Pull request merged**
