### PR TITLE
Snapshot of APIs as of 12.3.

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Snapshot of APIs as of 12.3. Replacement of #2690 Not to be merged until 12.3 vc1 vote passes.

Created with following steps -

```bash
# checkout branch (or release tag)
git checkout release123
ant clean
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb123
git stash pop
git add -A
git commit -m "Snapshot of APIs as of 12.3"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
I have found a new useful utility `filterdiff`. It allows us to ignore the obvious version change (assuming it is the first change in each diff file) giving us only the differences we care about:
```bash
$ filterdiff -#2- 2788.diff | grep ^diff
diff --git a/cpplite/cpplite.debugger/nbproject/org-netbeans-modules-cpplite-debugger.sig b/cpplite/cpplite.debugger/nbproject/org-netbeans-modules-cpplite-debugger.sig
diff --git a/extide/gradle/nbproject/org-netbeans-modules-gradle.sig b/extide/gradle/nbproject/org-netbeans-modules-gradle.sig
diff --git a/groovy/libs.groovy/nbproject/org-netbeans-modules-libs-groovy.sig b/groovy/libs.groovy/nbproject/org-netbeans-modules-libs-groovy.sig
diff --git a/ide/gsf.testrunner.ui/nbproject/org-netbeans-modules-gsf-testrunner-ui.sig b/ide/gsf.testrunner.ui/nbproject/org-netbeans-modules-gsf-testrunner-ui.sig
diff --git a/ide/html.editor/nbproject/org-netbeans-modules-html-editor.sig b/ide/html.editor/nbproject/org-netbeans-modules-html-editor.sig
diff --git a/ide/lib.terminalemulator/nbproject/org-netbeans-lib-terminalemulator.sig b/ide/lib.terminalemulator/nbproject/org-netbeans-lib-terminalemulator.sig
diff --git a/ide/libs.jaxb/nbproject/org-netbeans-libs-jaxb.sig b/ide/libs.jaxb/nbproject/org-netbeans-libs-jaxb.sig
diff --git a/ide/projectapi/nbproject/org-netbeans-modules-projectapi.sig b/ide/projectapi/nbproject/org-netbeans-modules-projectapi.sig
diff --git a/ide/spi.debugger.ui/nbproject/org-netbeans-spi-debugger-ui.sig b/ide/spi.debugger.ui/nbproject/org-netbeans-spi-debugger-ui.sig
diff --git a/ide/xml.jaxb.api/nbproject/org-netbeans-modules-xml-jaxb-api.sig b/ide/xml.jaxb.api/nbproject/org-netbeans-modules-xml-jaxb-api.sig
diff --git a/ide/xml.multiview/nbproject/org-netbeans-modules-xml-multiview.sig b/ide/xml.multiview/nbproject/org-netbeans-modules-xml-multiview.sig
diff --git a/java/dbschema/nbproject/org-netbeans-modules-dbschema.sig b/java/dbschema/nbproject/org-netbeans-modules-dbschema.sig
diff --git a/java/debugger.jpda.truffle/nbproject/org-netbeans-modules-debugger-jpda-truffle.sig b/java/debugger.jpda.truffle/nbproject/org-netbeans-modules-debugger-jpda-truffle.sig
diff --git a/java/debugger.jpda.ui/nbproject/org-netbeans-modules-debugger-jpda-ui.sig b/java/debugger.jpda.ui/nbproject/org-netbeans-modules-debugger-jpda-ui.sig
diff --git a/java/debugger.jpda/nbproject/org-netbeans-modules-debugger-jpda.sig b/java/debugger.jpda/nbproject/org-netbeans-modules-debugger-jpda.sig
diff --git a/java/java.lsp.server/nbproject/org-netbeans-modules-java-lsp-server.sig b/java/java.lsp.server/nbproject/org-netbeans-modules-java-lsp-server.sig
diff --git a/java/java.testrunner.ui/nbproject/org-netbeans-modules-java-testrunner-ui.sig b/java/java.testrunner.ui/nbproject/org-netbeans-modules-java-testrunner-ui.sig
diff --git a/java/websvc.jaxws21/nbproject/org-netbeans-modules-websvc-jaxws21.sig b/java/websvc.jaxws21/nbproject/org-netbeans-modules-websvc-jaxws21.sig
diff --git a/php/php.editor/nbproject/org-netbeans-modules-php-editor.sig b/php/php.editor/nbproject/org-netbeans-modules-php-editor.sig
diff --git a/php/php.project/nbproject/org-netbeans-modules-php-project.sig b/php/php.project/nbproject/org-netbeans-modules-php-project.sig
diff --git a/platform/api.progress.compat8/nbproject/org-netbeans-api-progress-compat8.sig b/platform/api.progress.compat8/nbproject/org-netbeans-api-progress-compat8.sig
diff --git a/platform/api.progress.nb/nbproject/org-netbeans-api-progress-nb.sig b/platform/api.progress.nb/nbproject/org-netbeans-api-progress-nb.sig
diff --git a/platform/api.progress/nbproject/org-netbeans-api-progress.sig b/platform/api.progress/nbproject/org-netbeans-api-progress.sig
diff --git a/platform/libs.flatlaf/nbproject/org-netbeans-libs-flatlaf.sig b/platform/libs.flatlaf/nbproject/org-netbeans-libs-flatlaf.sig
diff --git a/platform/libs.junit4/nbproject/org-netbeans-libs-junit4.sig b/platform/libs.junit4/nbproject/org-netbeans-libs-junit4.sig
diff --git a/platform/openide.compat/nbproject/org-openide-compat.sig b/platform/openide.compat/nbproject/org-openide-compat.sig
diff --git a/platform/openide.explorer/nbproject/org-openide-explorer.sig b/platform/openide.explorer/nbproject/org-openide-explorer.sig
diff --git a/platform/openide.util.ui/nbproject/org-openide-util-ui.sig b/platform/openide.util.ui/nbproject/org-openide-util-ui.sig
diff --git a/platform/openide.util/nbproject/org-openide-util.sig b/platform/openide.util/nbproject/org-openide-util.sig
```

**Review by JaroslavTulach — APPROVED** [review]
Analyzing `curl https://github.com/apache/netbeans/pull/2788.diff | filterdiff -i a/platform* -#2- 2788.diff | less` reveals no surprises.

**Comment by neilcsmith-net** [comment]
@JaroslavTulach @dbalek it looks like #2766 might be cause of a sigtest failure - eg. https://travis-ci.com/github/apache/netbeans/jobs/487518703#L9412 ?  Not sure how you want to handle?  Assuming a fix is required, merge this then fix things or vice versa?

**Comment by JaroslavTulach** [comment]
> @dbalek it looks like #2766 is causing a [sigtest failure](https://travis-ci.com/github/apache/netbeans/jobs/487518703#L9412)

```
Class org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController$TestMethod

  "E5.4 - Removing constructor" : constructor public org.netbeans.modules.gsf.testrunner.ui.api.TestMethodController$TestMethod.init(org.netbeans.spi.project.SingleMethod,javax.swing.text.Position,javax.swing.text.Position)
```

> Not sure how you want to handle? Assuming a fix is required, merge this then fix things or vice versa?

I suggest to return the removed constructor back.

**Comment by neilcsmith-net** [comment]
> I suggest to return the removed constructor back.

Thanks @JaroslavTulach  I assumed that was probably the case.  Personally would rather merge a PR to do that, then retrigger tests on this, and merge this assuming green.

**Comment by neilcsmith-net** [comment]
OK, nothing further as of now, so I'm going to merge this as we need to get it in anyway.  @dbalek can you look at bringing the removed constructor back?  Thanks.  Travis will have to keep complaining in the interim.

**Pull request merged**
