### PR TITLE
[NETBEANS-5301] Fixed readability of HTML code completion items

### PR DESCRIPTION
**Pull request by KacerCZ**
https://issues.apache.org/jira/browse/NETBEANS-5301

- Fixes color of elements in code completion.
- Fixes color of directories in code completion.
- Simplifies code for completion item coloring.

### CODE REVIEW

**Comment by KacerCZ** [comment]
Before:
netbeans-5301-elements-before netbeans-5301-dirs-before

After - light theme:
netbeans-5301-elements-after-light netbeans-5301-dirs-after-light

After - dark theme:
netbeans-5301-elements-after-dark netbeans-5301-dirs-after-dark

**Comment by KacerCZ** [comment]
@neilcsmith-net @geertjanw Please consider inclusion of this fix in 12.3.

**Comment by geertjanw** [comment]
Looks very useful, thanks.

**Review by geertjanw — APPROVED** [review]

**Review by DevCharly — APPROVED** [review]
LGTM

**Pull request merged**
