### PR TITLE
.c/.h/.hpp files: Register WhereUsedAction and RenameAction in correct mime paths

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Closes: #7686

### CODE REVIEW

**Comment by Marisa-Chan** [comment]
Thanks! I prepare another, more correct patch, but it's already done correct!

**Comment by matthiasblaesing** [comment]
@lahodaj @vieiro given, that this is a trivial typo fix, I think it would be a candidate for NB23. Could you please have a look?

@Marisa-Chan yeah - in your issue report you indicated, that you don't plan to create a PR, so I had a look. 

Could you please check the nightly build available from the checks page (or directly: https://github.com/apache/netbeans/suites/27439737814/artifacts/1838598363)?

For the timeframe: I retargetted this to delivery, if review can be done in time, this might(!) make it into NB23

**Review by mbien — APPROVED** [review]
makes sense (was clearly a copy/paste issue).

Not tested, but I agree this would be a good candidate for NB 23 due to low risk of side effects.

**Comment by vieiro** [comment]
Hi @matthiasblaesing , I think @jlahoda  is more knowledgeable on the  `cpplite` cluster modules than I am.

**Review by lahodaj — APPROVED** [review]
Looks reasonable to me.

**Pull request merged**
