### PR TITLE
Improved Toolbar overflow impl.

### LINKED ISSUE #7000: Customizing Toolbar Can Overflow Without Creating Dropdown
### Apache NetBeans version

Apache NetBeans 20

### What happened

When using the Customize Toolbars feature, if the Netbeans window is just larger than the existing toolbars, adding a new toolbar button can cause the buttons to overflow out of the window (the right-most buttons are not displayed) rather than converting to a dropdown as they should.

I suspect there is a slight miscalculation somewhere or an event getting lost such that it doesn’t think it needs the overflow dropdown.

### Language / Project Type / NetBeans Component

All

### How to reproduce

Launch netbeans
Make not fullscreen
Create a new project (I used the default reactjs)
Select View->Toolbars->Use Small Icons
Select View->Toolbars-> `<Select all toolbars>`
Select View->Toolbars->Customize
Move Performance to the far-right of the toolbar space
Resize the window so it's just wider than the existing toolbar buttons so they all just barely fit.
Add a new icon from the Customize Toolbar window into the Performance toolbar.

At this point the existing far-right button slides off the screen, rather than becoming a dropdown as it should. If it works correctly, remove the icon you just added and slightly adjust the width of the window. Try different widths until it fails. Once you have the right window width it should be reliably reproducible, but only certain widths will fail.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 Pro 22H2

### JDK

openjdk 17.0.8 2023-07-18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

I have been unable to reproduce this problem on Linux. It can be frustrating to reproduce because it will work properly for most window widths, but get it just right and it fails every time.

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
The overflow handling is now in `doLayout()` and runs when `invalidate()` was called instead of listening to resize events. See https://github.com/apache/netbeans/issues/7000#issuecomment-1913782189

Misc impl improvements: fewer array copies and the toolbar should be rebuilt less often.

fixes #7000

### CODE REVIEW

**Comment by mbien** [comment]
this is for NB 22 so no hurry

**Comment by mbien** [comment]
oops. I assigned this PR by mistake instead of requesting review.

**Review by eirikbakke — APPROVED** [review]
Tested and found no new problems, though I wasn't able to reproduce the originally reported bug. (I tried on FlatLAF on Windows.)

**Comment by mbien** [comment]
cool! going to rebase the commit ontop of latest master to get a fresh CI run

**Pull request merged**
