### PR TITLE
Snapshot of APIs as of 12.4

### PR DESCRIPTION
**Pull request by ebarboni**
replace #2940

```
# checkout branch (or release tag)
git checkout release124
ant clean
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb124
git stash pop
git add -A
git commit -m "Snapshot of APIs as of 12.4"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

Had hard time to put code markup. I used the 1.75 version for groovy. Maybe was incremented on master

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks @ebarboni for picking up.

The conflict with `groovy/groovy.editor/nbproject/org-netbeans-modules-groovy-editor.sig` now in #2940 looks suspicious given more recent updates on master?  I think that change might want removing from this commit?  @JaroslavTulach ?

Also, as far as I know, since 12.4 we no longer need to remove `getPeer()`, although assume not a problem to keep doing so?

**Comment by ebarboni** [comment]
Did cleanup Buildinfo, most of changes are groovy and jakarta related.

lots of removal like this 
```
hfds FOCUS_TRAVERSABLE_DEFAULT,FOCUS_TRAVERSABLE_SET,FOCUS_TRAVERSABLE_UNKNOWN,LOCK,acc,actionListenerK,adjustmentL```
and this
```hcls AWTTreeLock,BltSubRegionBufferStrategy,DummyRequestFocusController,FlipSubRegionBufferStrategy,ProxyCapabilities,SingleBufferStrategy
```

**Review by geertjanw — APPROVED** [review]

**Comment by geertjanw** [comment]
Please merge, @ebarboni, whenever you're ready.

**Comment by ebarboni** [comment]
merging this

**Pull request merged**
