### PR TITLE
Remove incubator parts

### PR DESCRIPTION
**Pull request by junichi11**
- Remove "incubator"
- Fix the Travis CI and the Jenkins build links
- Remove DISCLAIMER

### CODE REVIEW

**Comment by junichi11** [comment]
Travis CI build fails. I've just updated the README.md. So, the cause is not this change, I suppose...
 
<details>
<summary>Error log</summary>

```
-do-junit:
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTask110FeaturesTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTask110FeaturesTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTask110FeaturesTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTask111FeaturesTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTask111FeaturesTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTask111FeaturesTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTask112FeaturesTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTask112FeaturesTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTask112FeaturesTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTask15FeaturesTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTask15FeaturesTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTask15FeaturesTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTask17FeaturesTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTask17FeaturesTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTask17FeaturesTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTask18FeaturesTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTask18FeaturesTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTask18FeaturesTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTask19FeaturesTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTask19FeaturesTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTask19FeaturesTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTaskAdvancedTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTaskAdvancedTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTaskAdvancedTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTaskBasicTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTaskBasicTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTaskBasicTest FAILED (crashed)
    [junit] Unrecognized option: --add-exports=jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.completion.JavaCompletionTaskElementCreatingTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.completion.JavaCompletionTaskElementCreatingTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.completion.JavaCompletionTaskElementCreatingTest FAILED (crashed)

BUILD FAILED
/home/travis/build/apache/netbeans/nbbuild/templates/common.xml:709: The following error occurred while executing this line:
/home/travis/build/apache/netbeans/nbbuild/templates/common.xml:702: The following error occurred while executing this line:
/home/travis/build/apache/netbeans/nbbuild/templates/common.xml:736: The following error occurred while executing this line:
/home/travis/build/apache/netbeans/nbbuild/templates/common.xml:733: Some tests failed; see details above.
```
</details>

**Comment by lkishalmi** [comment]
Should we change the Travis CI link /config as well as it is still contains "incubating"?

**Comment by junichi11** [comment]
Needed it when I confirmed yesterday but need not it now :) So I'll also fix it. Thanks!

**Comment by lkishalmi** [comment]
The DISCLAIMER can go away as well (Just be cautious, we might have build dependencies on that.)
@geertjanw ?

**Comment by junichi11** [comment]
Removed DISCLAIMER. I'll revert it later if it's wrong.

**Comment by junichi11** [comment]
Applied. Thank you, Matthias!
I'm going to squash & merge this.

**Pull request merged**
