### PR TITLE
Incorporating new files and code modifications for adding Java EE 8 support.

### PR DESCRIPTION
**Pull request by juneau001**
Merged Java EE 8 support code that has been tested from repository https://github.com/juneau001/netbeans-javaee8-inprogress with the latest sources in apache/netbeans.  Built and tested.

### CODE REVIEW

**Comment by GeertjanWielenga** [comment]
Great job.

**Comment by juneau001** [comment]
Thanks, let me know how I should proceed now that Travis build failed.  I appreciate your time.

**Comment by matthiasblaesing** [comment]
For the build failures on travis, please rebase onto current master. @lkishalmi switched the builds to OpenJDK in https://github.com/apache/netbeans/commit/87c2a53c28a6e365bd75203100ddd3e77ce8e23b, that should fix your issue.

**Comment by juneau001** [comment]
Thanks @matthiasblaesing I appreciate your humble assistance, as always.  I believe I've re-based properly...let's see if Travis is happy now.

**Comment by juneau001** [comment]
I believe I have taken care of the Travis issues pertaining to the files I've committed.  These remaining Travis issues seem to pertain to files outside of the "enterprise" modules.  Please review and let me know how to proceed.

**Pull request merged**
