### PR TITLE
[NETBEANS-5109] Update to (Maven distributed) nbjavac15.0.0.2

### PR DESCRIPTION
**Pull request by Akshay-Gupta-Oracle**
New nbjavac version 15.0.0.2 build on JDK8 hosted on maven.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks.  Have added the 12.3 milestone for tracking for now.  Looks like still waiting on the staged repo?

This will need to be rebased on delivery to be included in 12.3 hence the label.  Tried changing the base branch but it's pulling in other things.

If we go for 12.3, maybe update this to reference [NETBEANS-5055] in the title?  That's the bug we're more interested in for the release, and good to tie that up with this in JIRA.

**Comment by matthiasblaesing** [comment]
I cherry picked this change onto delivery locally, build from that that with JDK 8, ran the IDE with JDK 8 and was able to use java code completion (-> indexing works) and observed, that classes in the maven project were rebuild on the fly (compile on save worked). The installation worked cleanly.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing thanks, good to know!  If you feel like opening a PR of that cherry pick, please feel free. :smile: Might save some duplication of effort.

I assume you verified use of `permits` as an identifier is fixed, and that such projects now compile with CoS enabled?

**Comment by matthiasblaesing** [comment]
@neilcsmith-net here you are: https://github.com/apache/netbeans/pull/2759

**Comment by neilcsmith-net** [comment]
Thanks @matthiasblaesing for the other PR to delivery, and to @Akshay-Gupta-Oracle and @eppleton Have merged via #2759 so closing this. Will be merged to master via the sync from delivery in a few days.

**Pull request closed without merging**
