### PR TITLE
[cnd] small-2.1 Merging from master

### PR DESCRIPTION
**Pull request by vieiro**
This brings master into cnd.
I don't see a problem in bringing the latest master stuff into cnd, but if we want to keep cnd with the donation and the enhancements only, then we can create a new "cnd-dev" branch and do the merge there.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Something is very wrong here. I looked at the commit and this does not look like a merge commit, it looks like a giant squashed changeset. The commit should have two parents: master and cnd and should then be in cnd itself.

I'll have a look at 17624e153c7979d69f14207a588987e7bd48c1c6 and 7c9326139ffcd06e4e65130153e4a8a233eb6398 and see whether I can extract the added files from these to compare them to the donation zip. There are two questions we might need to be able to answer: Where did code come from and why is it ok to be in the repository, so that we can defend against people claiming ownership and people copying code without following the rules of the ALv2.

**Comment by vieiro** [comment]
Very true! Thanks @matthiasblaesing 
It seems https://github.com/apache/netbeans/commit/17624e153c7979d69f14207a588987e7bd48c1c6 has no parents...

**Comment by vieiro** [comment]
Maybe we should create a "cnd-asf" branch, forked from master, and merge "cnd" in that one. The resulting commit is probably cleaner. See https://github.com/vieiro/netbeans/tree/cnd-asf commit https://github.com/vieiro/netbeans/commit/63276e4acae43befc0b753155eb02334b13332c0 for an example.

**Comment by matthiasblaesing** [comment]
`cnd-asf` looks sane to me. This is what I tried to describe. If you merge `master` into `cnd`, it should look identical, just not resulting in a new branch.

As indicated I had a look at two commits that contain the donated code and all looks good to me (not to surprising given, that @lahodaj  had plenty of experience from the first donations). If anyone wants to have a look, this is my approach:

- check the two commits, that brought in the donations: 7c9326139ffcd06e4e65130153e4a8a233eb6398 and 17624e153c7979d69f14207a588987e7bd48c1c6
- ensure that the commits have either exactly one parent (normal commit with new files) or no parent (orphan branch)
- ensure that only files were added
- ensure that all added files can be found either in donation4 or donation4.5

<details>
  <summary>I decided to write that down in java using jgit, feel free to use `CheckApacheNetBeansDonation.java` (Expand to see)</summary>

```java
package jgit;

import java.io.Closeable;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import org.eclipse.jgit.internal.storage.file.FileRepository;
import org.eclipse.jgit.lib.ObjectId;
import org.eclipse.jgit.lib.ObjectLoader;
import org.eclipse.jgit.lib.ObjectReader;
import org.eclipse.jgit.lib.Repository;
import org.eclipse.jgit.revwalk.RevCommit;
import org.eclipse.jgit.revwalk.RevWalk;
import org.eclipse.jgit.treewalk.AbstractTreeIterator;
import org.eclipse.jgit.treewalk.CanonicalTreeParser;
import org.eclipse.jgit.treewalk.EmptyTreeIterator;
import org.eclipse.jgit.treewalk.TreeWalk;

public class CheckApacheNetBeansDonation {

    private static final String[] commits = new String[]{
	"7c9326139ffcd06e4e65130153e4a8a233eb6398",
	"17624e153c7979d69f14207a588987e7bd48c1c6"
    };

    public static void main(String[] args) throws Exception {
	Repository repository = new FileRepository("/home/matthias/src/netbeans/.git");
	for (String commitId : commits) {
	    System.out.println("Commit: " + commitId);
	    try ( RevWalk walk = new RevWalk(repository);  ObjectReader or = repository.newObjectReader();  DonationZips dz = new DonationZips()) {

		dz.addDonationZip("/home/matthias/archiv/netbeans/ApacheDonation4.zip", "ApacheDonation4/");
		dz.addDonationZip("/home/matthias/archiv/netbeans/ApacheDonation4.5.zip", "ApacheDonation4.5/");

		RevCommit commit = walk.parseCommit(ObjectId.fromString(commitId));
		RevCommit parent = null;
		if (commit.getParentCount() == 1) {
		    parent = commit.getParent(0);
		} else if (commit.getParentCount() != 0) {
		    throw new IllegalStateException("Only non-merge commits are supported!");
		}

		AbstractTreeIterator commitTree = getCanonicalTreeParser(repository, commit);
		AbstractTreeIterator parentTree = null;
		if (parent != null) {
		    parentTree = getCanonicalTreeParser(repository, parent);
		} else {
		    parentTree = new EmptyTreeIterator();
		}

		try ( TreeWalk tw = new TreeWalk(repository)) {
		    tw.setRecursive(true);
		    tw.addTree(parentTree);
		    tw.addTree(commitTree);
		    while (tw.next()) {
			ObjectId parentObjectId = tw.getObjectId(0);
			ObjectId commitObjectId = tw.getObjectId(1);
			if (parentObjectId.equals(ObjectId.zeroId())) {
			    checkContentsInDonationZip(or, commitObjectId, tw.getPathString(), dz);
			} else if (commitObjectId.equals(ObjectId.zeroId())) {
			    //System.out.println("Removed:  " + tw.getPathString());
			    throw new IllegalStateException("Found Removal");
			} else if (!parentObjectId.equals(commitObjectId)) {
			    //System.out.println("Modified: " + tw.getPathString());
			    throw new IllegalStateException("Found Modification");
			}

		    }
		}
	    }
	}
    }

    private static void checkContentsInDonationZip(ObjectReader or, ObjectId objectId, String path, DonationZips dz) throws IOException {
	byte[] donatedData = dz.getData(path);
	if(donatedData == null) {
	    throw new IOException("Not found in donation: " + path);
	}
	ObjectLoader ol = or.open(objectId);
	if(! Arrays.equals(donatedData, ol.getBytes())) {
	    throw new IOException("Donated data not identical to repository: " + path);
	}
    }

    private static CanonicalTreeParser getCanonicalTreeParser(Repository repository, ObjectId commitId) throws IOException {
	try ( RevWalk walk = new RevWalk(repository)) {
	    RevCommit commit = walk.parseCommit(commitId);
	    ObjectId treeId = commit.getTree().getId();
	    try ( ObjectReader reader = repository.newObjectReader()) {
		return new CanonicalTreeParser(null, reader, treeId);
	    }
	}
    }

    private static class DonationZips implements Closeable {

	private final List<DonationZip> zips = new ArrayList<>();

	public DonationZips() {
	}

	public void addDonationZip(String pathToZip, String infilePrefix) throws IOException {
	    this.zips.add(new DonationZip(new File(pathToZip), infilePrefix));
	}

	public byte[] getData(String path) throws IOException {
	    for (DonationZip dz : zips) {
		byte[] result = dz.getData(path);
		if (result != null) {
		    return result;
		}
	    }
	    return null;
	}

	public void close() throws IOException {
	    List<IOException> exceptions = new ArrayList<>();
	    for (DonationZip dz : zips) {

	    }
	    if (!exceptions.isEmpty()) {
		IOException ex = new IOException("Failed to close some ZIPs");
		for (IOException ex2 : exceptions) {
		    ex.addSuppressed(ex2);
		}
		throw ex;
	    }
	}
    }

    private static class DonationZip implements Closeable {

	private final ZipFile zipFile;
	private final String infilePrefix;

	public DonationZip(File pathToZip, String infilePrefix) throws IOException {
	    this.zipFile = new ZipFile(pathToZip);
	    this.infilePrefix = infilePrefix;
	}

	public byte[] getData(String path) throws IOException {
	    String fullpath = infilePrefix + path;
	    ZipEntry ze = this.zipFile.getEntry(fullpath);
	    if (ze == null) {
		return null;
	    }
	    try ( InputStream is = this.zipFile.getInputStream(ze)) {
		return is.readAllBytes();
	    }
	}

	@Override
	public void close() throws IOException {
	    this.zipFile.close();
	}
    }
}

```
</details>

**Comment by vieiro** [comment]
Note that we're bringing _master_ into _cnd_ (`master->cnd`), not the other way around. 

"[cnd-asf](https://github.com/vieiro/netbeans/tree/cnd-asf)" is the other way around (i.e., `cnd -> master`), which is the "clean" commit you're looking for.

The idea is:
1.- `master -> cnd` (this one).
2.- do any fine-tuning _in cnd_, in case of need (I don't think anything is required, though):
- new libraries that may have been added in master during the last year and a half.
- pipelines/builds/checks that may have changed (rat, for instance)

3.- `cnd -> master` (this is where we get the  "clean" commit, including integration changes).

The objective is avoid any possible interruption in master (broken builds, or whatever).

Of course we can proceed with a `cnd->master` directly (aka [cnd-asf](https://github.com/vieiro/netbeans/tree/cnd-asf) and do any fine-tuning/development there.

**Comment by matthiasblaesing** [comment]
I agree with the idea, but this PR is broken, as it is _not_ a merge commit. I don't know how this commit was created, but this would be my approach:

```bash
# Switch to master branch
git checkout master
# Remove current broken branch
git branch -D feature/cnd-small-2-bis
# Update github checkup (depends on the name of the remote, that holds the upstream branches)
git fetch github
# Checkout CND into the new feature branch
git checkout -b feature/cnd-small-2-bis github/cnd
# Merge master into the new branch
git merge github/master
# The merge can't be done automatically, as the two branches have conflicting change.
# Fix merge conflict in nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps:
# The version from master is correct (the one with the added overlab ignores)
vim nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
git add nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
# Commit the merge
git commit
# Now you are in branch feature/cnd-small-2-bis
```

After this you are in the `feature/cnd-small-2-bis` branch and that branch holds the merge commit of CND and master. Creating a PR from that should to the trick.

If you look at the git log, you see the difference in the parents. The graphical version (using `gitk feature/cnd-small-2-bis` and `gitk github/pr/3423`):

This PR:

image

The suggested way with a merge:

image

In the first screenshot the commit only has a single parent (CND) and so all changes are be part of that commit and don't come from history. That should not be the case, we loose history this way.

Maybe this illustrates my idea better?

**Comment by vieiro** [comment]
Thanks, @matthiasblaesing for your patience :-).
I force-pushed on this branch, so things should look better now.
Let me know if you prefer to create a brand-new PR.

**Review by matthiasblaesing — APPROVED** [review]
Thank you. Looks good to me. It shows nicely how much was going on in the repository between creation of the CND branch and the current state.

**Comment by vieiro** [comment]
Thanks you, @matthiasblaesing . Yep, an impressive amount of work indeed!!

**Pull request merged**
