### PR TITLE
Update NbEventSpy for maven 4.

### PR DESCRIPTION
**Pull request by mbien**
- the session getter for the plexus container is deprecated and returns null on mvn 4
 - lets grab the container over the injection mechanism
 - convert from `components.xml` to `javax.inject`
 - tested on mvn 3 and 4

@cstamas will this work or can the session change the container later? In my tests the container of the context and the session were always the same instance.

### CODE REVIEW

**Comment by cstamas** [comment]
That's right

**Comment by mbien** [comment]
@cstamas awesome! thanks for checking.

**Comment by cstamas** [comment]
Ideally Plexus should be injected, but this seems not as a component?

**Comment by cstamas** [comment]
Oh, it is a plexus component:
https://github.com/apache/netbeans/blob/master/java/maven/mavensrc/org/netbeans/modules/maven/event/components.xml

**Comment by cstamas** [comment]
Ideally you want to get rid of Plexus XML files, especially those manually authored

**Comment by mbien** [comment]
i tested the event spy, but i have no clue what the other thingy does. Usage is here:
https://github.com/apache/netbeans/blob/0253a5dbb57e507aaae21e11443101f0fd08b971/java/maven/src/org/netbeans/modules/maven/cos/CosChecker.java#L555

**Comment by mbien** [comment]
ah I get it. COS stands for compile on save. As far as I see IDEWorkspaceReader1/2 classes are used to log changes, probably for debugging purposes, since I don't see anywhere attempts to parse the log lines on the other side (which is different to the event spy). So this should be fine. (curious that both files are identical)

I played with cos a bit and it isn't working properly in NB 22. I had "apply code changes on save" checked in the debugger settings and it didn't work. With cos disabled it was fine. So this PR should not affect anything there. I personally don't use this feature since I don't like when IDEs mess with the build.

**Comment by neilcsmith-net** [comment]
> ah I get it. COS stands for compile on save. 

Ah, I hadn't realised that the meaning of COS there was your stumbling point or I'd have mentioned it. 😄  Hopefully can be separated out from this change, and possibly a discussion to be had elsewhere on whether this slowly deteriorating feature should just be removed?!

**Comment by mbien** [comment]
> Hopefully can be separated out from this change,

What do you mean by that? All this does is to switch from component.xml to annotations. I think it would be more confusing/error prone when IDEWorkspaceReader1/2 would keep using component.xml while the NbEventSpy is using annotations and both are built in the same module.

**Comment by neilcsmith-net** [comment]
Sorry, badly worded. I just meant separating out the discussion on the other points your raised - whether it's actually working correctly, whether it needs fixing now or for Maven 4. As you said, this PR should not affect things there (or make it any worse!).

**Review by neilcsmith-net — APPROVED** [review]

**Comment by mbien** [comment]
@neilcsmith-net awesome. Yep agreed. Btw I updated https://github.com/apache/netbeans/pull/7529#issuecomment-2198498169 with a test case since I discovered that cos does work, just extremely delayed.

**Pull request merged**
