### PR TITLE
[NETBEANS-1696] PHP 7.4 Support

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-1696

We should be able to merge this branch into the master branch now :)
https://lists.apache.org/thread.html/22da8e632fbc043f70970428efbfd3ffe6198d504bfdc36d9844b9a6@%3Cdev.netbeans.apache.org%3E

### CODE REVIEW

**Comment by junichi11** [comment]
Yes, completed if I don't overlook anything.

**Comment by tmysik** [comment]
@junichi11 Should not we regenerate PHP sigfiles for PHP 7.4?

**Comment by junichi11** [comment]
@tmysik Yes, we should do it :) I'm going to do it in early September because Documentation may be updated. (NetBeans 11.2 will be released in October[1] and PHP 7.4 will be released in November[2].) 
I'll create an issue for that.

[1] https://cwiki.apache.org/confluence/display/NETBEANS/Release+Schedule
[2] https://wiki.php.net/todo/php74

**Comment by junichi11** [comment]
Created: https://issues.apache.org/jira/browse/NETBEANS-2893

**Comment by tmysik** [comment]
@junichi11 Perfect, I hope that the sigfile generator will still work :)

**Pull request merged**
