### PR TITLE
Testing sigfile generation for NB13 review. Not for merging!

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Testing sigfile generation for NetBeans 13.  Generated with JDK 8 for review of API purposes.

Generation on JDK 11 fails still with error below - needs to be fixed before release.

```
Warning: incorrect classpath parameter: /usr/lib/jvm/java-11-openjdk-amd64/lib/tools.jar (/usr/lib/jvm/java-11-openjdk-amd64/lib/tools.jar). This directory or jar file will be ignored!
Constant checking: on
Found in total: 948 classes
Fatal error: class com.sun.jdi.connect.IllegalConnectorArgumentsException not found
Fatal error: class com.sun.jdi.connect.IllegalConnectorArgumentsException not found
Fatal error: class com.sun.jdi.AbsentInformationException not found
Fatal error: class com.sun.jdi.AbsentInformationException not found
Fatal error: class com.sun.jdi.AbsentInformationException not found
Fatal error: class com.sun.jdi.AbsentInformationException not found
Fatal error: class com.sun.jdi.connect.IllegalConnectorArgumentsException not found
Fatal error: class com.sun.jdi.connect.IllegalConnectorArgumentsException not found
Warning: class com.sun.jdi.connect.ListeningConnector not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.connect.IllegalConnectorArgumentsException not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.connect.VMStartException not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.connect.Connector$Argument not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.StackFrame not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.VirtualMachine not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.Value not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.connect.AttachingConnector not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.AbsentInformationException not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.ReferenceType not found. Please, add required jar or directory to the classpath.
Warning: class com.sun.jdi.ObjectReference not found. Please, add required jar or directory to the classpath.
Selected by -Package: 83 classes
```

@JaroslavTulach any thoughts?

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
The debugger classes were in `tools.jar` and are in some special (not default) module of JDK-11.

**Comment by JaroslavTulach** [comment]
List of real (not only a version bump) changes:
```bash
$ curl -L https://github.com/apache/netbeans/pull/3503.diff | filterdiff -#2- | grep ^diff
diff --git a/enterprise/glassfish.eecommon/nbproject/org-netbeans-modules-glassfish-eecommon.sig b/enterprise/glassfish.eecommon/nbproject/org-netbeans-modules-glassfish-eecommon.sig
diff --git a/enterprise/glassfish.tooling/nbproject/org-netbeans-modules-glassfish-tooling.sig b/enterprise/glassfish.tooling/nbproject/org-netbeans-modules-glassfish-tooling.sig
diff --git a/enterprise/j2ee.api.ejbmodule/nbproject/org-netbeans-modules-j2ee-api-ejbmodule.sig b/enterprise/j2ee.api.ejbmodule/nbproject/org-netbeans-modules-j2ee-api-ejbmodule.sig
diff --git a/enterprise/j2ee.common/nbproject/org-netbeans-modules-j2ee-common.sig b/enterprise/j2ee.common/nbproject/org-netbeans-modules-j2ee-common.sig
diff --git a/enterprise/j2ee.dd.webservice/nbproject/org-netbeans-modules-j2ee-dd-webservice.sig b/enterprise/j2ee.dd.webservice/nbproject/org-netbeans-modules-j2ee-dd-webservice.sig
diff --git a/enterprise/j2ee.dd/nbproject/org-netbeans-modules-j2ee-dd.sig b/enterprise/j2ee.dd/nbproject/org-netbeans-modules-j2ee-dd.sig
diff --git a/enterprise/j2ee.ejbjarproject/nbproject/org-netbeans-modules-j2ee-ejbjarproject.sig b/enterprise/j2ee.ejbjarproject/nbproject/org-netbeans-modules-j2ee-ejbjarproject.sig
diff --git a/enterprise/payara.common/nbproject/org-netbeans-modules-payara-common.sig b/enterprise/payara.common/nbproject/org-netbeans-modules-payara-common.sig
diff --git a/enterprise/payara.tooling/nbproject/org-netbeans-modules-payara-tooling.sig b/enterprise/payara.tooling/nbproject/org-netbeans-modules-payara-tooling.sig
diff --git a/enterprise/web.el/nbproject/org-netbeans-modules-web-el.sig b/enterprise/web.el/nbproject/org-netbeans-modules-web-el.sig
diff --git a/enterprise/web.jsf/nbproject/org-netbeans-modules-web-jsf.sig b/enterprise/web.jsf/nbproject/org-netbeans-modules-web-jsf.sig
diff --git a/enterprise/websvc.restlib/nbproject/org-netbeans-modules-websvc-restlib.sig b/enterprise/websvc.restlib/nbproject/org-netbeans-modules-websvc-restlib.sig
diff --git a/extide/gradle/nbproject/org-netbeans-modules-gradle.sig b/extide/gradle/nbproject/org-netbeans-modules-gradle.sig
diff --git a/groovy/groovy.editor/nbproject/org-netbeans-modules-groovy-editor.sig b/groovy/groovy.editor/nbproject/org-netbeans-modules-groovy-editor.sig
diff --git a/ide/csl.api/nbproject/org-netbeans-modules-csl-api.sig b/ide/csl.api/nbproject/org-netbeans-modules-csl-api.sig
diff --git a/ide/csl.types/nbproject/org-netbeans-modules-csl-types.sig b/ide/csl.types/nbproject/org-netbeans-modules-csl-types.sig
diff --git a/ide/css.lib/nbproject/org-netbeans-modules-css-lib.sig b/ide/css.lib/nbproject/org-netbeans-modules-css-lib.sig
diff --git a/ide/db/nbproject/org-netbeans-modules-db.sig b/ide/db/nbproject/org-netbeans-modules-db.sig
diff --git a/ide/editor.completion/nbproject/org-netbeans-modules-editor-completion.sig b/ide/editor.completion/nbproject/org-netbeans-modules-editor-completion.sig
diff --git a/ide/editor.deprecated.pre65formatting/nbproject/org-netbeans-modules-editor-deprecated-pre65formatting.sig b/ide/editor.deprecated.pre65formatting/nbproject/org-netbeans-modules-editor-deprecated-pre65formatting.sig
diff --git a/ide/editor.plain.lib/nbproject/org-netbeans-modules-editor-plain-lib.sig b/ide/editor.plain.lib/nbproject/org-netbeans-modules-editor-plain-lib.sig
diff --git a/ide/html.editor/nbproject/org-netbeans-modules-html-editor.sig b/ide/html.editor/nbproject/org-netbeans-modules-html-editor.sig
diff --git a/ide/parsing.api/nbproject/org-netbeans-modules-parsing-api.sig b/ide/parsing.api/nbproject/org-netbeans-modules-parsing-api.sig
diff --git a/ide/parsing.indexing/nbproject/org-netbeans-modules-parsing-indexing.sig b/ide/parsing.indexing/nbproject/org-netbeans-modules-parsing-indexing.sig
diff --git a/ide/projectuiapi.base/nbproject/org-netbeans-modules-projectuiapi-base.sig b/ide/projectuiapi.base/nbproject/org-netbeans-modules-projectuiapi-base.sig
diff --git a/ide/projectuiapi/nbproject/org-netbeans-modules-projectuiapi.sig b/ide/projectuiapi/nbproject/org-netbeans-modules-projectuiapi.sig
diff --git a/ide/spi.editor.hints/nbproject/org-netbeans-spi-editor-hints.sig b/ide/spi.editor.hints/nbproject/org-netbeans-spi-editor-hints.sig
diff --git a/ide/xml.catalog.ui/nbproject/org-netbeans-modules-xml-catalog-ui.sig b/ide/xml.catalog.ui/nbproject/org-netbeans-modules-xml-catalog-ui.sig
diff --git a/ide/xml.text.obsolete90/nbproject/org-netbeans-modules-xml-text-obsolete90.sig b/ide/xml.text.obsolete90/nbproject/org-netbeans-modules-xml-text-obsolete90.sig
diff --git a/java/j2ee.persistence/nbproject/org-netbeans-modules-j2ee-persistence.sig b/java/j2ee.persistence/nbproject/org-netbeans-modules-j2ee-persistence.sig
diff --git a/java/java.completion/nbproject/org-netbeans-modules-java-completion.sig b/java/java.completion/nbproject/org-netbeans-modules-java-completion.sig
diff --git a/java/java.lsp.server/nbproject/org-netbeans-modules-java-lsp-server.sig b/java/java.lsp.server/nbproject/org-netbeans-modules-java-lsp-server.sig
diff --git a/java/java.source.base/nbproject/org-netbeans-modules-java-source-base.sig b/java/java.source.base/nbproject/org-netbeans-modules-java-source-base.sig
diff --git a/java/java.source/nbproject/org-netbeans-modules-java-source.sig b/java/java.source/nbproject/org-netbeans-modules-java-source.sig
diff --git a/java/libs.javacapi/nbproject/org-netbeans-libs-javacapi.sig b/java/libs.javacapi/nbproject/org-netbeans-libs-javacapi.sig
diff --git a/java/maven.embedder/nbproject/org-netbeans-modules-maven-embedder.sig b/java/maven.embedder/nbproject/org-netbeans-modules-maven-embedder.sig
diff --git a/java/maven/nbproject/org-netbeans-modules-maven.sig b/java/maven/nbproject/org-netbeans-modules-maven.sig
diff --git a/php/php.api.phpmodule/nbproject/org-netbeans-modules-php-api-phpmodule.sig b/php/php.api.phpmodule/nbproject/org-netbeans-modules-php-api-phpmodule.sig
diff --git a/php/php.editor/nbproject/org-netbeans-modules-php-editor.sig b/php/php.editor/nbproject/org-netbeans-modules-php-editor.sig
diff --git a/platform/api.htmlui/nbproject/org-netbeans-api-htmlui.sig b/platform/api.htmlui/nbproject/org-netbeans-api-htmlui.sig
diff --git a/platform/api.progress.nb/nbproject/org-netbeans-api-progress-nb.sig b/platform/api.progress.nb/nbproject/org-netbeans-api-progress-nb.sig
diff --git a/platform/api.templates/nbproject/org-netbeans-api-templates.sig b/platform/api.templates/nbproject/org-netbeans-api-templates.sig
diff --git a/platform/libs.flatlaf/nbproject/org-netbeans-libs-flatlaf.sig b/platform/libs.flatlaf/nbproject/org-netbeans-libs-flatlaf.sig
diff --git a/platform/o.n.swing.plaf/nbproject/org-netbeans-swing-plaf.sig b/platform/o.n.swing.plaf/nbproject/org-netbeans-swing-plaf.sig
diff --git a/platform/openide.compat/nbproject/org-openide-compat.sig b/platform/openide.compat/nbproject/org-openide-compat.sig
diff --git a/platform/openide.filesystems.compat8/nbproject/org-openide-filesystems-compat8.sig b/platform/openide.filesystems.compat8/nbproject/org-openide-filesystems-compat8.sig
diff --git a/platform/openide.filesystems.nb/nbproject/org-openide-filesystems-nb.sig b/platform/openide.filesystems.nb/nbproject/org-openide-filesystems-nb.sig
diff --git a/platform/openide.filesystems/nbproject/org-openide-filesystems.sig b/platform/openide.filesystems/nbproject/org-openide-filesystems.sig
diff --git a/platform/openide.loaders/nbproject/org-openide-loaders.sig b/platform/openide.loaders/nbproject/org-openide-loaders.sig
diff --git a/platform/openide.util.ui/nbproject/org-openide-util-ui.sig b/platform/openide.util.ui/nbproject/org-openide-util-ui.sig
diff --git a/webcommon/javascript2.types/nbproject/org-netbeans-modules-javascript2-types.sig b/webcommon/javascript2.types/nbproject/org-netbeans-modules-javascript2-types.sig
diff --git a/websvccommon/websvc.saas.api/nbproject/org-netbeans-modules-websvc-saas-api.sig b/websvccommon/websvc.saas.api/nbproject/org-netbeans-modules-websvc-saas-api.sig
```

**Comment by JaroslavTulach** [comment]
Changes in `platform/*` modules look sane to me.

**Comment by neilcsmith-net** [comment]
We may have to fix this in delivery post-release if we're going to have these files going forward.

**Review by JaroslavTulach — APPROVED** [review]
I've just got the same [JDK-11 sigtest failure](https://app.travis-ci.com/github/apache/netbeans/jobs/563009937) in #3744 - do we have a fix? Can it be integrated?

**Comment by neilcsmith-net** [comment]
No we don't.  I've certainly not looked further, and was not going to until release out and I can find some free time.

We need to get a fix into delivery branch, and then generate a new sigfiles PR for 13, or we're not going to have them.  This PR isn't intended to be merged anywhere so closing.

**Pull request closed without merging**
