### PR TITLE
Cleanup warning messages related to redundant cast

### PR DESCRIPTION
**Pull request by BradWalker**
Warning messages like this will no longer happen.

   [repeat] /home/bwalker/src/netbeans/enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/ui/ReflectionHelper.java:700: warning: [cast] redundant cast to JavaParameter
   [repeat]                     JavaParameter actualParameter = (JavaParameter) parameterList.get(ii);
   [repeat]                                                     ^

---
**^Add meaningful description above**

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

### CODE REVIEW

**Comment by lkishalmi** [comment]
So many deletions! Sweet!

**Comment by BradWalker** [comment]
And done by hand! My eyes were GLAZING OVER.. 8-)

**Comment by mbien** [comment]
> Well, it seems, you find fun at strange places!

don't listen to @lkishalmi  :) i can relate

**Review by mbien — APPROVED** [review]
looks good. CI seems to be happy too.

**Pull request merged**
