### PR TITLE
[NETBEANS-4521] Missing syntax highlighting for records

### PR DESCRIPTION
**Pull request by asotona**

### CODE REVIEW

**Comment by asotona** [comment]
I see failed: org.netbeans.modules.settings.RecognizeInstanceObjectsOnModuleEnablementTest FAILED
However I don't see any relation with the pull request fix.

Thanks

**Comment by jlahoda** [comment]
Hi Adam,

Thanks for the fix!

I have two suggestions:
-RECORD should probably be added to TreeUtilities.CLASS_TREE_KINDS directly, rather than check for it on usages. (Should be doable using Tree.Kind.valueOf("RECORD"), catching the IllegalArgumentException, if the kind does not exist.)
-it would be awesome if some tests could be updated, existing tests are e.g.:
https://github.com/apache/netbeans/blob/21e19a3f60e69935f7cfe5ff5b0110346bcd8aaf/java/java.editor.base/test/unit/src/org/netbeans/modules/java/editor/base/semantic/DetectorTest.java#L539

Thanks!

**Comment by neilcsmith-net** [comment]
@jlahoda what do you want to do on this one?  Still requiring changes?

**Comment by asotona** [comment]
Sorry for the delay, I'll improve it as suggested.

**Comment by asotona** [comment]
I'm sorry but I'm unable to execute the tests with JDK 14:
    [junit] -Xbootclasspath/p is no longer a supported option.
    [junit] Error: Could not create the Java Virtual Machine.
    [junit] Error: A fatal exception has occurred. Program will exit.
    [junit] Testsuite: org.netbeans.modules.java.editor.base.semantic.DetectorTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: org.netbeans.modules.java.editor.base.semantic.DetectorTest:null:	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.base/java.util.Vector.forEach(Vector.java:1358)
    [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.base/java.util.Vector.forEach(Vector.java:1358)
    [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 
    [junit] 
    [junit] Test org.netbeans.modules.java.editor.base.semantic.DetectorTest FAILED (crashed)

I'm also unable to manually confirm if new patch works or not as my IDE gets to some weird state where it highlights records even I rollback the original patch.

This is probably the best patch I can offer until NetBeans will be testable on JDK 14.

**Comment by neilcsmith-net** [comment]
Thanks @asotona At this point, I'm inclined to push this back to 12.2 rather than rush into 12.1, unless @jlahoda has another view on that?

**Comment by jlahoda** [comment]
Sorry, I forgot to respond sooner.

To run tests on JDK 9+ (and without nb-javac), currently the best way is:
-into nbbuild/user.build.properties put:
test.nbjdk.home=<path-to-test-JDK>

And into the given project's nbproject/private/private.properties:
test.use.jdk.javac=true

This should ensure the tests will be run using javac from the JDK.

**Comment by lkishalmi** [comment]
@asotona Can you do the recommended changes? 12.2 is around the corner.

**Review by lkishalmi — CHANGES_REQUESTED** [review]
The requested changes has not been provided yet.

**Pull request closed without merging**
