### PR TITLE
Fix: Enable to add docker instance via socket on mac with apple silicon

### PR DESCRIPTION
**Pull request by lazydan**
Enable to add docker instance via socket on mac with apple silicon.

#6326

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Is there a reason to keep the architecture check in here?  It's either relevant or it isn't!  What architecture and OS set is actually supported by the underlying implementation here?

**Comment by lazydan** [comment]
> Is there a reason to keep the architecture check in here? It's either relevant or it isn't! What architecture and OS set is actually supported by the underlying implementation here?

My device is macbook with apple silicon. And the Apple Silicon M1 (or M2) chip is an AArch64 architecture.

**Comment by matthiasblaesing** [comment]
I suspect that the architecture and OS check is in place to only offer unix domain sockets on systems where junixsocket can work. If this is agreed on, I suggest to update `DockerSupport#isSocketSupported` to read:

```java
    public boolean isSocketSupported() {
        return AFUNIXSocket.isSupported();
    }
```

Then all supported architectures will get this (Windows, Linux, mac OS, the various BSDs on aarch64, amd64, arm, ppc64, riscv64).

**Comment by mbien** [comment]
https://patch-diff.githubusercontent.com/raw/apache/netbeans/pull/6328.patch we would need the full name in the commit author field.

Also, please squash all commits into one and force push, thanks!

**Review by mbien — APPROVED** [review]
thanks. looks good.

**Review by neilcsmith-net — APPROVED** [review]
Thanks!  Haven't tested, but this is what my previous comment was suggesting to look for.

**Review by matthiasblaesing — APPROVED** [review]
Tested this successfully on linux and reviewed. I'll merge.

@lazydan Thank you for your contribution. For the future: You don't need to open an issue if you intent to open a PR immediately. 
@mbien thanks for the hint about the "patch" view, it is handy, I just hope I can remember ;-)

**Comment by mbien** [comment]
> thanks for the hint about the "patch" view, it is handy, I just hope I can remember ;-)

@matthiasblaesing agreed, sometimes very useful. Both `.diff` and `.patch` works, can be simply added to the PR url and it is generated for you.

**Pull request merged**
