### PR TITLE
[NETBEANS-2751] Register OpenJFX sample artifacts as NetBeans project…

### PR DESCRIPTION
**Pull request by geertjanw**
… templates

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
For the code itself: The javafx-archetype-simple archetype is invalid, it is only present in version 0.0.1, not 0.0.2, the same is true for javafx-archetype-fxml.

The list in the "Java with Maven" category becomes pretty long. Maybe we should use a subfolder "From Archetype", where the generic "Project from Archetype" is the first option and selected archetypes come after it. This is my try to illustrate it:

Before:

now

After:

after

**Comment by geertjanw** [comment]
0.0.2 was definitely available recently, will check.

Agree completely with your folder restructuring -- or maybe those from archetype should be in the Samples category instead?

**Comment by tiainen** [comment]
We've just released version 0.0.3 which updates to the latest release of OpenJFX 13.

**Comment by geertjanw** [comment]
Thanks for the info!

**Comment by geertjanw** [comment]
But I don't see it here: https://mvnrepository.com/artifact/org.openjfx/javafx-archetype-simple

That's maybe where @matthiasblaesing was looking for it too?

**Comment by matthiasblaesing** [comment]
I'm looking on maven central (the default maven repository): 
https://search.maven.org/search?q=javafx-archetype-simple

This indicates, that 2.0.0 was published yesterday, which would explain why it was not present when I tested.

**Comment by tiainen** [comment]
It was available from maven central when I posted my message. Synchronization with search.maven.org can take up to a few hours (it's listed there now btw). Synchronization with mvnrepository.com probably takes even longer.

**Comment by geertjanw** [comment]
Closing this one. Pushing a new one with a different and more complete solution.

**Pull request closed without merging**
