### PR TITLE
Revert PR #7579 ("Using LSP's ErrorProvider & another attempt at CompletionCollector")

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Closes: #7647

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@jtulach from my POV no problem. This PR is the safety net.

**Comment by jtulach** [comment]
If 
- #7659

gets in, then this revert will no longer be needed.

**Review by jtulach — CHANGES_REQUESTED** [review]
The problems reported by 
- #7647

are only related to [HintsCollector.setError](https://github.com/apache/netbeans/pull/7659#issuecomment-2282882099). However the #7579 PR introduces two things:
- `HintsCollector.setError`
- another attempt as `CompletionCollector`

there is no point in reverting all. If none of other solutions works (like #7659), then we need to revert only the `HintsCollector.setError` part.

**Comment by matthiasblaesing** [comment]
Lets keep the discussion in #7659.

**Comment by ebarboni** [comment]
as #7659 is closed maybe continuing discussion here ?
(sorry for delay but not in my place this time) Do not over rely on me.

**Review by neilcsmith-net — APPROVED** [review]

**Review by mbien — APPROVED** [review]
+1 for NB 23 revert (https://github.com/apache/netbeans/pull/7659#issuecomment-2284247217 for reasons)

**Comment by lahodaj** [comment]
FWIW, while I am not particularly happy the bridge between LSP API and client will cease to work for NB 23, I think this should be merged, and we should see if we can achieve the same end goal using a more scalable approach.

**Pull request merged**
