### PR TITLE
Smart stepping implemented for Groovy. SmartSteppingFilterWrapper introduced as a step-specific filter.

### PR DESCRIPTION
**Pull request by entlicher**
Smart-stepping changed to have a unique instance of `SmartSteppingFilter` per the ongoing step. Javadoc is improved accordingly.
Smart stepping is implemented for Groovy - `GroovySmartStepping`.

### CODE REVIEW

**Comment by entlicher** [comment]
This is necessary for stepping through Groovy code in debugger.

**Review by ppisl — APPROVED** [review]
Thanks for this patch. I have played with this and it is much better. I have tried debug this script:
`print "hello world\n"

class Man {
    int age;

    Man (int age) {
        this.age = age
    }

    int getAge() {
        return this.age;
    }
}

def sayHello() {
    print "I'm saying HELLO"
}

sayHello()

m = new Man(10);
println (m.getAge());`

and it still jump into java.lang.Integer.java, when I invoke step into on `m=new Man(10)` line. But after finishing this method it allows to debug the constructor correctly.

**Comment by entlicher** [comment]
Many thanks Petr for thorough review.
We do not have a special stepping filter for boxing/unboxing methods in Java debugger, hence the user gets there during stepping from Groovy.
We have a special logic around Step Into in Java debugger, which detects the available methods from the code. This is why you do not step into boxing methods like `Integer.valueOf()` during Java debugging. You will get there if "Step Into Next Method" (Shift-F7) is used, which is used in Groovy. Groovy has no special method-selection logic implemented.

**Comment by ebarboni** [comment]
rebased to delivery and green so merging

**Pull request merged**
