### PR TITLE
[NETBEANS-5768] Recognize gradle projects with settings.gradle only file

### PR DESCRIPTION
**Pull request by JaroslavTulach**
[NETBEANS-5768](https://issues.apache.org/jira/browse/NETBEANS-5768) reports that our Gradle support isn't able to properly recognize
```bash
gradle init --type java-application --test-framework junit-jupiter --dsl groovy --package com.example --project-name example
```
This PR fixes that. It also moves the Ergonomics registration of Gradle build scripts to `java` cluster - it is my understanding that groovy support isn't required when dealing with Gradle anymore.

### CODE REVIEW

**Review by sdedic — APPROVED** [review]
Great, thanks.

**Review by mklaehn — APPROVED** [review]

**Comment by lkishalmi** [comment]
I'd add a simple unit test in GardleFilesTest as well. Otherwise I approve. I'm using a mobile browser. I couldn't find how to officially approve this

**Comment by JaroslavTulach** [comment]
> I'd add a simple unit test in GardleFilesTest as well. 

Done with 1de12a7

**Comment by JaroslavTulach** [comment]
I cleaned up the history to avoid needless back and forth exploration and now we are greed.

**Pull request merged**
