### PR TITLE
Integrated try-with-resource with single style

### PR DESCRIPTION
**Pull request by tbw777**
Solved part of mem leaks. Reasons of leaks: unclosed streams and streams without closing if any exception occur

### CODE REVIEW

**Comment by tbw777** [comment]
I havent errors on ide/bugtracking tests local

**Comment by tbw777** [comment]
Also i found some places where transferTo can be used. Need to upgrade jvm bytecode version, also for collections too

**Comment by matthiasblaesing** [comment]
> Also i found some places where transferTo can be used. Need to upgrade jvm bytecode version and this will helpfullty for for collections too

As mentioned now in multiple PR comments: Discuss these ideas on the mailing list. I know some developers who will not react kindly to bumping bytecode level, just to get access to new methods, if there is not a _very_ good reason.

_This_ is not the place to discuss ideas.

**Comment by tbw777** [comment]
@matthiasblaesing 
ok, i entierly agree. Ty for fast feedback

**Pull request closed without merging**
