### PR TITLE
Use GitHub for netbeansrelease.json in Travis

### PR DESCRIPTION
**Pull request by lkishalmi**
Apache gitbox web is more than flaky lately causing many jobs fail when retrieving the netbeansrelease.json.
What about to use it's github mirror in our Travis CI tests?

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
+1. I did wonder whether it's gitbox being flaky or whether it's getting too many requests from Travis?  Might be worth also mentioning to infra if you haven't so cause can at least be looked at?

**Comment by lkishalmi** [comment]
[INFRA-20885](https://issues.apache.org/jira/browse/INFRA-20885) has been filed on this.

**Comment by ebarboni** [comment]
https://status.apache.org/#past-incidents gitbox had issue today.

But change is ok also.

**Review by hectorespert — COMMENTED** [review]
Could you change it in the GitHub actions too?

**Comment by lkishalmi** [comment]
Seems to work. I was sneaky to add a http://netbeans.apache.com -> https://netbeans.apache.com as well, considering how rigorous Apache became on https lately.

**Pull request merged**
