### PR TITLE
[NETBEANS-4667] Fix broken npm search

### PR DESCRIPTION
**Pull request by SiddheshRane**
IDE npm search (Web project > properties > npm > add) is broken due to output format change in npm.
This commit uses npm --parseable flag to fix and simplify output parsing.
Tested with npm 6.14.4

### CODE REVIEW

**Comment by Chris2011** [comment]
Cool, finally :). I had a look into the code, you removed a lot. So is this fix a general fix and will this work for those who not uses npm >= 6?

**Comment by Chris2011** [comment]
Also we should get rid of those hardcoded flags. But this is another task.

**Comment by SiddheshRane** [comment]
The `--parseable` flag was added to npm search around 4 years ago. Before that it was named  `--tab-seperated`. So I think it covers a lot of npm versions that people are actually using. 

This is a general fix for scraping cli output as was meant to be done.

**Comment by Chris2011** [comment]
Ok great. Thx for the info :)

**Comment by Chris2011** [comment]
From my pov it looks promising :)

**Comment by matthiasblaesing** [comment]
Thank you - change looks sane, unittests come back clean, author information looks good.

@SiddheshRane I assume, that you agree that the changeset is donated to the ASF, if that is not the case, please say so, the merge will then be reverted.

**Pull request merged**
