### PR TITLE
attemp to fix javadoc for release100

### PR DESCRIPTION
**Pull request by ebarboni**
Hi,
 I just started apidoc polish :D. Will take sometime I guess. To not alter release I choose the release100 to startwith.

Attempt so far
1)I reduced a lot of links issue by changing the nbbuild/antsrc/org/netbeans/nbbuild/CheckLinks.java pattern to tackle the id parameter and h3 element. 
2)The following code on element are no more tolerated on javadoc by default onclick="target='_blank'". I removed them in arch/apichanges. 
3) Replacing all http://bits.netbeans.org/html+java by https://bits.netbeans.org/html+java/dev/ in arch/apichanges

that lead to a shorter [checklinks-errors.txt](https://github.com/apache/netbeans/files/9132010/checklinks-errors.txt)

But know I have issues on a more highlevel matter.
One type of issue is for example 
org-netbeans-modules-editor-codetemplate would need the org-openide-options apidoc but we don't generate org-openide-options.
same issue for editor-lib we only have editor-libs2.
What could be the good practice to get apidoc consitent again.
Second issue
org-openide-awt/org/openide/awt/ActionState.html because ActionState.java is in another subfolder (package is ok )
[ org.openide.awt.awt folder ](https://github.com/apache/netbeans/tree/release100/platform/openide.awt/src/org/openide/awt/awt)
Could we move the file to fix ? (we will never cut a release from the old branch I guess) 

Any tips appreciated, and will later fix for other branches (once I have the good advices)

All the best

### CODE REVIEW

**Comment by ebarboni** [comment]
@neilcsmith-net @jtulach  with the 3 commit I'm able to down the error to 0 on my own build.
1) fix pattern for id and h3 [nbbuild/antsrc/org/netbeans/nbbuild/CheckLinks.java]
2) remove invalid target in arch.xml/apichanges.xml (onclick is forbidden)
3) move 3 files in openide awt to their correct public package
4) as we use config.javadoc.stable for release, I had to append this properties with the missing modules:
   openide.options,\
    editor,\
    editor.lib,\
    editor.indent,\
    editor.indent.support,\
    editor.bracesmatching,\
    editor.util

Step 4 is a bit ugly but on master, we should try to edit the arch file to match the real dependencies.

**Comment by neilcsmith-net** [comment]
> move 3 files in openide awt to their correct public package

That one is weird. They only seem to be in the `awt` subfolder for a period of time - didn't start there, aren't there on master.

**Comment by ebarboni** [comment]
it compile javac side (ant build) but javadoc tool miss them.

**Comment by jtulach** [comment]
Great work. The [list of broken links](https://github.com/apache/netbeans/files/9132010/checklinks-errors.txt) isn't that huge anymore!

`openide.options` has been deprecated, I believe. `editor.lib` may not be stable yet. That is why we don't include these modules in _stable javadoc_ configuration.

Files in `org.openide.awt.awt` package, that's horrible!

**Review by jtulach — APPROVED** [review]

**Comment by ebarboni** [comment]
In master I guess we should check some of the arch.xml but for the former I would like to be lazy a bit if you don't mind.

The deprecated, private modules are flagged by themselves so it's red or striked and will be showed to user.

**Comment by neilcsmith-net** [comment]
> `openide.options` has been deprecated, I believe. `editor.lib` may not be stable yet. That is why we don't include these modules in _stable javadoc_ configuration.

I'd be in favour of publishing everything on bits.netbeans.org, stable, development and (probably) deprecated.

> Files in `org.openide.awt.awt` package, that's horrible!

Seem to have ended up there as a side effect of #536

**Comment by ebarboni** [comment]
waiting a few hours and will try to merge if green on build I will propagate same workflow to others branches that build with jdk 8

**Comment by ebarboni** [comment]
it's green https://ci-builds.apache.org/job/Netbeans/job/netbeans-TLP/job/netbeans/job/release100/

**Pull request merged**
