### PR TITLE
[#3466]  do not show Convert Type to Var hint for method references

### LINKED ISSUE #3466: Hint: “Convert Explicit Type to Var” shouldn’t be reported for method references or lambda expressions
### Apache NetBeans version

Latest release

### What happened

**Convert Explicit Type to Var** is reported for method references and lambda expressions, e.g.:
```java
final Consumer<String> println = System.out::println;
```

But it's invalid to replace the above with:
```java
final var println = System.out::println;
```
which results in the compile error:
```
error: cannot infer type for local variable println
final var println = System.out::println;
          ^
  (method reference needs an explicit target-type)
```

### How to reproduce

See above

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 10

### JDK

OpenJDK Runtime Environment [Temurin](https://adoptium.net/)-17.0.1+12 (build 17.0.1+12)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

_No response_

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

### PR DESCRIPTION
**Pull request by oyarzun**
Fix #3466 do not provide hint to convert type to var for method references.

### CODE REVIEW

**Review by mbien — APPROVED** [review]
LGTM. Thanks.

**Comment by mbien** [comment]
wait with merging please. we might be able to sneak fixes like this into NB 13 rc builds.

**Comment by neilcsmith-net** [comment]
Please rebase the commit on top of delivery if it's a fix we want in NB13. Downside of incrementing spec version earlier is we can't just rebase the PR as it will bring in that change.

**Comment by oyarzun** [comment]
@neilcsmith-net and @mbien I've rebased the commit on delivery, should we merge the PR?

**Comment by neilcsmith-net** [comment]
Thanks @oyarzun Release team handle merges on delivery (for a number of reasons).  I've got a few things to do tomorrow to prepare rc1 and will look at this then.

**Pull request merged**
