### PR TITLE
fixed PropertyPanel fill background for flatlaf l&f

### PR DESCRIPTION
**Pull request by DJ-Raven**
This PR I has fixed fill the PropertyPanel background color for flatlaf look and feel. Can you please review it, Thank you.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
What's the issue you're fixing here, exactly?  The visual artefacts under `Editor:`. etc.?

-1 to any more checks for look and feel name (and is lowercase `flatlaf` correct anyway?)

**Comment by DJ-Raven** [comment]
> What's the issue you're fixing here, exactly? The visual artefacts under Editor:. etc.?

Yes in editor, I see this issue with TableCustomizer class

> -1 to any more checks for look and feel name (and is lowercase flatlaf correct anyway?)

`flatlaf` is the package name `com.formdev.flatlaf.FlatDarkLaf` I thing future netbean have `com.formdev.flatlaf.IntelliJTheme`

**Comment by DevCharly** [comment]
Better remove the `isGtk` field completely.
`isGtk` is only used in `PropertyPanel.paint()` to decide whether to fill the component background
and should be replaced with `isOpaque()` in that method.

Class `PropertyPanel` extends `JComponent`, which does not fill it background.
So when using `setOpaque(true)`, which is done in constructor of `PropertyPanel`, it is required to fill its background.

Following comment should be also removed:
https://github.com/apache/netbeans/blob/276a42363653d6cf44fded5a30c4c6f8d783b4b3/platform/openide.explorer/src/org/openide/explorer/propertysheet/PropertyPanel.java#L1155-L1157

**Comment by neilcsmith-net** [comment]
Was just writing the same comment as @DevCharly .  +1 to taking that approach.  Whoever wrote that comment misunderstood the use of `setOpaque`.  It's possible this should have been a JPanel to start with, but safer not to change now.

**Comment by neilcsmith-net** [comment]
Please can you rebase the branch on top of delivery - eg. `git rebase HEAD~1 --onto delivery`?  Would be good to get this fix in the next release, but needs to not bring in later commits from master.

**Comment by mbien** [comment]
@DJ-Raven also squash to one commit and push with `-f` to the remote branch. Then you can change the target here and everything will update.

**Comment by DJ-Raven** [comment]
@neilcsmith-net @mbien Sorry, I no experience with git rebase, I has try it but failed.

**Comment by mbien** [comment]
@DJ-Raven no worries, let me do this quickly.

**Comment by mbien** [comment]
@DJ-Raven could you check that the author information is correct? Patch file: https://github.com/apache/netbeans/pull/7332.patch

also please note that your `master` branch is now in fact the `delivery` branch ;). I can fix this again once this PR is integrated if you want.

**Comment by DJ-Raven** [comment]
Yes `raven`

> also please note that your master branch is now in fact the delivery branch ;). I can fix this again once this PR is integrated if you want.

I will check it

**Comment by mbien** [comment]
oh no you changed back :(

**Comment by DJ-Raven** [comment]
Ohh sorry that I have updated my master branch 😔.

**Comment by mbien** [comment]
going to force push again. don't touch anything please :D

**Review by mbien — APPROVED** [review]

**Review by ebarboni — APPROVED** [review]

**Comment by mbien** [comment]
@DJ-Raven congrats on your first contribution

**Pull request merged**
