### PR TITLE
NETBEANS-3777 Use pom type instead of jar for bom artefacts

### PR DESCRIPTION
**Pull request by ebarboni**
fix for missing dependencies  in springframework

### CODE REVIEW

**Comment by blackleg** [comment]
@ebarboni Could you add the spring-framework-bom dependency to the 5.2.2.RELEASE version? https://github.com/apache/netbeans/blob/master/java/libs.springframework/src/org/netbeans/libs/springframework/spring-framework500.xml

**Comment by ebarboni** [comment]
@blackleg, it was not part of the dependencies for 5.2.2, is it not working without bom ?

**Comment by blackleg** [comment]
>  is it not working without bom ?
How can I test if it is working?

**Comment by ebarboni** [comment]
You need to compile NetBeans. (I'm not javaee,spring expert)

But 5.x support is broken on ant and maven in NetBeans.

Some removed class are used in project setup (dispatcher-servlet).
Cannot find class [org.springframework.web.servlet.mvc.support.ControllerClassNameHandlerMapping

**Comment by ebarboni** [comment]
make it for all version

**Comment by lkishalmi** [comment]
Does it really work? I'm assuming this is for Ant projects. AFAIK the list of jar-s is provided instead of the bom, however if the bom is working, then probably we shall not set the list of jars.

**Comment by ebarboni** [comment]
This only fix the non downloadble dependencies for maven. Not sure the bom take all the other dependencies. 

maven and ant NetBeans created web application cannot be run with 5.x. (bad conf file)

**Comment by blackleg** [comment]
> maven and ant NetBeans created web application cannot be run with 5.x. (bad conf file)

Is it a blocking for the 11.3 release?

**Comment by ebarboni** [comment]
Will merge.
@blackleg would be good for 5.X to have a workaround saying how to modify config file to get it work
NETBEANS-3558

**Pull request merged**
