### PR TITLE
[NETBEANS-3342] Fix Netbeans Installer on macOS to work with Java 8 and Java 11+

### PR DESCRIPTION
**Pull request by oyarzun**
This pull request fixes the NetBean RCP installer on macOS with Java 11+ since `com.apple.eawt` classes were removed with JEP 272

Supersedes the following PRs and addresses their comments: 

-  Closes #1929
-  Closes #2015

@mcdonnell-john and/or @arusinha can you please review this PR.

Note: once this PR is merged and we have a new release, we will need to update https://github.com/apache/netbeans-mavenutils-nbm-maven-harness to use the latest nbi-engine nbm as it is currently using RELEASE112.

### CODE REVIEW

**Comment by arusinha** [comment]
@mcdonnell-john  request you to review the PR and verify  NB installer is working fine with this PR change.

**Comment by mcdonnell-john** [comment]
Hi @oyarzun @arusinha sorry for the delay, just got snowed under with work recently and forgot about this :(

I took a look at building the Apache NetBeans installer from this PR in a similar way to how I did the 12.1 installer earlier today.

Note: I had to move the build/antclasses folder as thats not in the normal distpreparation folder which we build the installer from.  If this PR was to be approved we would need to look into making sure that folder is moved when the distpreparation folder is created. @arusinha  Do you know where this is done, or should I ask @ebarboni.

I built this branch on JDK 8, and then I managed to build the installer using JDK 8 and JDK 11, but while the installer which was built using JDK8 installed NetBeans just fine, the one with JDK11 failed to install, and I got the following error.
```
2020-09-01 21:38:23+01 Johns-MacBook-Pro package_script_service[8331]: ./postinstall: Complete installation /Applications/NetBeans/Apache NetBeans 00.1.app
2020-09-01 21:38:23+01 Johns-MacBook-Pro package_script_service[8331]: ./postinstall: Result of populate_caches.sh : 0
2020-09-01 21:38:23+01 Johns-MacBook-Pro package_script_service[8331]: ./postinstall: /tmp/PKInstallSandbox.1lZ4gG/Scripts/org.netbeans.postinstallscripts.K4Du5O/postinstall: line 46: cd: /Applications/NetBeans/Apache NetBeans 00.1.app: No such file or directory
2020-09-01 21:38:23+01 Johns-MacBook-Pro package_script_service[8331]: Responsibility set back to self.
2020-09-01 21:38:23+01 Johns-MacBook-Pro install_monitor[86212]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: releasing backupd
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: allow user idle system sleep
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Cleared responsibility for install from 86206.
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Cleared permissions on Installer.app
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Apache NetBeans 00.1.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#postinstallscripts.pkg, PKInstallPackageIdentifier=org.netbeans.postinstallscripts, NSLocalizedDescription=An error occurred while running scripts from the package “Apache NetBeans 00.1.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cApache NetBeans 00.1.pkg\U201d.";
	    NSURL = "file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#postinstallscripts.pkg";
	    PKInstallPackageIdentifier = "org.netbeans.postinstallscripts";
	}
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Running idle tasks
2020-09-01 21:38:23+01 Johns-MacBook-Pro Installer[86206]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Apache NetBeans 00.1.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#postinstallscripts.pkg, PKInstallPackageIdentifier=org.netbeans.postinstallscripts, NSLocalizedDescription=An error occurred while running scripts from the package “Apache NetBeans 00.1.pkg”.}
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Removing client PKInstallDaemonClient pid=86206, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
2020-09-01 21:38:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Done with sandbox removals
2020-09-01 21:38:23+01 Johns-MacBook-Pro Installer[86206]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
2020-09-01 21:38:23+01 Johns-MacBook-Pro Installer[86206]: IFDInstallController 2360E80 state = 8
2020-09-01 21:38:23+01 Johns-MacBook-Pro Installer[86206]: Displaying 'Install Failed' UI.
2020-09-01 21:38:23+01 Johns-MacBook-Pro Installer[86206]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

I've never looked into this area at all really, @oyarzun or @arusinha does this ring a bell, could I have done something wrong?  I will try to take a closer look later on in the week if I can.

**Comment by mcdonnell-john** [comment]
Doing a diff of the 2 installation logs, 1, with an installer built using JDK8 and the other with the installer built with JDK11.
Here is where things start to differ:

JDK8:
```
2020-09-01 22:38:28+01 Johns-MacBook-Pro installd[620]: PackageKit: Set reponsibility for install to 86977
2020-09-01 22:38:28+01 Johns-MacBook-Pro installd[620]: PackageKit: Will do receipt-based obsoleting for package identifier org.netbeans.ide.javase.00.0 (prefix path=/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans)
2020-09-01 22:38:28+01 Johns-MacBook-Pro installd[620]: PackageKit: Will do receipt-based obsoleting for package identifier org.netbeans.ide.javaee.00.0 (prefix path=/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans)
2020-09-01 22:38:28+01 Johns-MacBook-Pro installd[620]: PackageKit: Will do receipt-based obsoleting for package identifier org.netbeans.ide.webcommon.00.0 (prefix path=/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans)
2020-09-01 22:38:28+01 Johns-MacBook-Pro installd[620]: PackageKit: Will do receipt-based obsoleting for package identifier org.netbeans.ide.php.00.0 (prefix path=/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans)
2020-09-01 22:38:29+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.0/Apache%20NetBeans%2000.0.pkg#nbide-00.0.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A34129E6-E88C-41BE-82C0-832EF0C7CE54.activeSandbox/Root/Applications/NetBeans, uid=0)
2020-09-01 22:38:30+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.0/Apache%20NetBeans%2000.0.pkg#javase-00.0.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A34129E6-E88C-41BE-82C0-832EF0C7CE54.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:38:31+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.0/Apache%20NetBeans%2000.0.pkg#javaee-00.0.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A34129E6-E88C-41BE-82C0-832EF0C7CE54.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:38:32+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.0/Apache%20NetBeans%2000.0.pkg#webcommon-00.0.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A34129E6-E88C-41BE-82C0-832EF0C7CE54.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:38:32+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.0/Apache%20NetBeans%2000.0.pkg#php-00.0.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/A34129E6-E88C-41BE-82C0-832EF0C7CE54.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.0.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:38:32+01 Johns-MacBook-Pro installd[620]: PackageKit: prevent user idle system sleep
2020-09-01 22:38:32+01 Johns-MacBook-Pro installd[620]: PackageKit: suspending backupd
2020-09-01 22:38:32+01 Johns-MacBook-Pro installd[620]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/A34129E6-E88C-41BE-82C0-832EF0C7CE54.sandboxTrash for sandbox /Library/InstallerSandboxes/.PKInstallSandboxManager/A34129E6-E88C-41BE-82C0-832EF0C7CE54.activeSandbox
2020-09-01 22:38:32+01 Johns-MacBook-Pro install_monitor[86990]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2020-09-01 22:38:32+01 Johns-MacBook-Pro installd[620]: PackageKit: Shoving /Library/InstallerSandboxes/.PKInstallSandboxManager/A34129E6-E88C-41BE-82C0-832EF0C7CE54.activeSandbox/Root (1 items) to /
2020-09-01 22:38:32+01 Johns-MacBook-Pro installd[620]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.Trjm7p/Scripts/org.netbeans.ide.nbide.00.0.NZ8q5m
2020-09-01 22:38:32+01 Johns-MacBook-Pro package_script_service[8331]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.Trjm7p/Scripts/org.netbeans.ide.nbide.00.0.NZ8q5m
2020-09-01 22:38:32+01 Johns-MacBook-Pro package_script_service[8331]: Set responsibility to pid: 86977, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
2020-09-01 22:38:33+01 Johns-MacBook-Pro package_script_service[8331]: Responsibility set back to self.
```

JDK11:
```
2020-09-01 22:39:17+01 Johns-MacBook-Pro installd[620]: PackageKit: Set reponsibility for install to 87072
2020-09-01 22:39:19+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#nbide-00.1.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/1F18B801-A715-45CE-8AFD-10E00066C545.activeSandbox/Root/Applications/NetBeans, uid=0)
2020-09-01 22:39:21+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#javase-00.1.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/1F18B801-A715-45CE-8AFD-10E00066C545.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.1.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:39:22+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#javaee-00.1.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/1F18B801-A715-45CE-8AFD-10E00066C545.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.1.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:39:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#webcommon-00.1.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/1F18B801-A715-45CE-8AFD-10E00066C545.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.1.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:39:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Extracting file://localhost/Volumes/Apache%20NetBeans%2000.1/Apache%20NetBeans%2000.1.pkg#php-00.1.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/1F18B801-A715-45CE-8AFD-10E00066C545.activeSandbox/Root/Applications/NetBeans/Apache NetBeans 00.1.app/Contents/Resources/NetBeans, uid=0)
2020-09-01 22:39:23+01 Johns-MacBook-Pro installd[620]: PackageKit: prevent user idle system sleep
2020-09-01 22:39:23+01 Johns-MacBook-Pro installd[620]: PackageKit: suspending backupd
2020-09-01 22:39:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Applications/NetBeans/Apache NetBeans 00.1.app relocated to Users/john/Apache/WIP/distpreparation/netbeans/12.1/vc1/installer/nbbuild/installer/mac/newbuild/netBeans/nbide/build/app/Apache NetBeans 00.1.app
2020-09-01 22:39:23+01 Johns-MacBook-Pro installd[620]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/1F18B801-A715-45CE-8AFD-10E00066C545.sandboxTrash for sandbox /Library/InstallerSandboxes/.PKInstallSandboxManager/1F18B801-A715-45CE-8AFD-10E00066C545.activeSandbox
2020-09-01 22:39:23+01 Johns-MacBook-Pro install_monitor[87080]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2020-09-01 22:39:24+01 Johns-MacBook-Pro installd[620]: PackageKit: Shoving /Library/InstallerSandboxes/.PKInstallSandboxManager/1F18B801-A715-45CE-8AFD-10E00066C545.activeSandbox/Root (2 items) to /
2020-09-01 22:39:24+01 Johns-MacBook-Pro installd[620]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.lBZEpU/Scripts/org.netbeans.ide.nbide.00.1.Sk3UTM
2020-09-01 22:39:24+01 Johns-MacBook-Pro package_script_service[8331]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.lBZEpU/Scripts/org.netbeans.ide.nbide.00.1.Sk3UTM
2020-09-01 22:39:24+01 Johns-MacBook-Pro package_script_service[8331]: Set responsibility to pid: 87072, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
2020-09-01 22:39:25+01 Johns-MacBook-Pro package_script_service[8331]: ./postinstall: /tmp/PKInstallSandbox.lBZEpU/Scripts/org.netbeans.ide.nbide.00.1.Sk3UTM/addproduct_id.sh: line 27: cd: /Applications/NetBeans/Apache NetBeans 00.1.app: No such file or directory
2020-09-01 22:39:25+01 Johns-MacBook-Pro package_script_service[8331]: ./postinstall: /tmp/PKInstallSandbox.lBZEpU/Scripts/org.netbeans.ide.nbide.00.1.Sk3UTM/addproduct_id.sh: line 28: cd: Contents/Resources/NetBeans*/netbeans/nb/config: No such file or directory
2020-09-01 22:39:25+01 Johns-MacBook-Pro package_script_service[8331]: Responsibility set back to self.
```

The key part seems to be that on the JDK 11 version, the app is relocated:
`PackageKit: Applications/NetBeans/Apache NetBeans 00.1.app relocated to Users/john/Apache/WIP/distpreparation/netbeans/12.1/vc1/installer/nbbuild/installer/mac/newbuild/netBeans/nbide/build/app/Apache NetBeans 00.1.app`
So the rest of the process, i.e. running the postinstall scripts fail, as there is no Apache NetBeans 00.1.app in the Applications/NetBeans folder.

I've no idea why that occurs at the moment.

**Comment by mcdonnell-john** [comment]
Actually this was a local issue... I needed to remove a file which is generated with the installer is built.  When I removed it the installation went fine.

Before approving this I just want to see about the changes to the distpreparation folder creation, but at the moment it this PR seems to work fine.

**Comment by oyarzun** [comment]
@mcdonnell-john thanks for reviewing the PR.

> Before approving this I just want to see about the changes to the distpreparation folder creation, but at the moment it this PR seems to work fine.

I'm not sure I know what you mean by the `distpreparation folder`.  I followed https://cwiki.apache.org/confluence/display/NETBEANS/Installer+Build+Steps to build the NB installer which makes no mention of such folder.

```
git clone https://github.com/apache/netbeans.git

cd netbeans

Run ant build

Copy release artifact zip(eg netbeans-11.3-bin.zip) to current folder.
```
So I run the build installer script from the top level dir from the cloned source.

**Comment by mcdonnell-john** [comment]
Hi @oyarzun 

Yep you've done nothing wrong here, what you did makes sense to me :)

The comment I'm making is when Jenkins runs, it executes a pipeline and as part of that pipeline it copies some files and folders into a specific folder as part of the build, that can be found in Jenkins called distpreparation:
https://ci-builds.apache.org/job/Netbeans/job/netbeans-TLP/job/netbeans/job/release121/13/artifact/distpreparation/

The job to do this is in the apache/netbeans-jenkins-lib project, I've created a PR for this here:
https://github.com/apache/netbeans-jenkins-lib/pull/20

As soon as thats approved I'll be happy to merge this in as well.  Just want to make sure that no possible step is missed that might impede the installer generation for the next Apache NetBeans release (12.2 for this change)

**Comment by lkishalmi** [comment]
@mcdonnell-john What do you think of this one. Would it be worth to backport this to NetBeans 12.0-u2?

**Comment by mcdonnell-john** [comment]
Hi @lkishalmi, That probably depends...

Do we plan to redo the installers for 12.0-u2, or is this update just for internal components for Apache NetBeans?  I'm happy for it to go into 12.3 and then subsequently into 13.0 afterwards...

**Comment by lkishalmi** [comment]
If we would release an installer, that would be for MacOS only, I'd 
leave out any unnecessary dances I can during this update release.

**Comment by mcdonnell-john** [comment]
Yeah, I probably wouldn't back merge this, I think...

**Pull request merged**
