### PR TITLE
Issue 4243: delete java/lang/Module and use dynamic proxy to implement Instrumentation across JDK versions…

### PR DESCRIPTION
**Pull request by nbauma109**
After JDK8, the Instrumentation interface introduced 2 methods isModifiableModule and redefineModule  having Module class in their signature. NbInstrumentation implemented the newer version of Instrumentation interface using Module, which was incompatible with JDK8. The compatibility was  ensured by an empty class Module which causes package conflict with the JDK. I propose to remove that and have a dynamic proxy that will handle all versions of Instrumentation interface thanks to an invocation handler.

### CODE REVIEW

**Comment by nbauma109** [comment]
Just noticed I forgot to throw UnsupportedOperationException. Just pushed the change.

**Comment by mbien** [comment]
can't get one of the commit validation jobs green (see #4211) and the build artifact is going to expire soon. I believe we can ignore that one.

**Comment by matthiasblaesing** [comment]
Ignore it - I restarted the Travis tests, as they more or less all failed.

**Comment by matthiasblaesing** [comment]
Travis is happy. I had a quick look at this and it looks sane to me.

**Comment by matthiasblaesing** [comment]
The code looks sane, there are unittests, that hit the modified codepaths and still work, lets get this in.

For the record @nbauma109 I assume you read the license header and you are aware, that your contribution is under the assumption that you donate the code to the ASF. Thank you for your work.

**Comment by JaroslavTulach** [comment]
Nice rewrite. Thank you.

**Pull request merged**
