### PR TITLE
Update FlatLaf from 1.0 to 1.1.1 and added "FlatLaf" options

### PR DESCRIPTION
**Pull request by DevCharly**
This PR updates FlatLaf from 1.0 to 1.1.1 and adds a "FlatLaf" options panel under "Appearance" category.

FlatLaf 1.1 release notes:
https://github.com/JFormDesigner/FlatLaf/releases/tag/1.1

FlatLaf 1.1 comes with fantastic news for Windows 10 users/developers: native window decorations.
This enables dark frame/dialog title bar and embedded menu bar with all JREs while still having:
- native Window 10 border drop shadows
- native Window 10 resize functionality
- [Windows 10 snapping](https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241) functionality
- native Windows 10 system window menu when right-clicking on title bar or left-clicking on application icon

## Light

The menu bar and the search field are now embedded into the window title, which saves vertical space for code editing. 😉 
image

Yes, I know that the search field needs some improvements, but this is not part of this PR.

With option "Unified title bar background" enabled:
image

With option "Embedded menu bar" disabled and "Unified title bar background" enabled:
image

## Dark

Finally dark window title bars:
image

With option "Unified title bar background" enabled:
image

With option "Embedded menu bar" disabled and "Unified title bar background" enabled:
image

## New FlatLaf options panel

image

First 3 check boxes are only enabled on Windows 10.

Menu with option "Use underline menu selection" enabled:
image

## Disable

It is possible to disable FlatLaf window decorations or embedded menu bar on command line with following VM options:
~~~
-J-Dflatlaf.useWindowDecorations=false
-J-Dflatlaf.menuBarEmbedded=false
~~~

### CODE REVIEW

**Comment by geertjanw** [comment]
So cool.

**Comment by eirikbakke** [comment]
Whoa! Sorcery! :-)

Digging down into the related FlatLAF code, I find the following comment:
"Support for custom window decorations provided by JetBrains Runtime (based on OpenJDK).
Requires that the application runs on Windows 10 in a JetBrains Runtime 11 or later."

https://github.com/JFormDesigner/FlatLaf/blob/477c3b6b1ec6cb00fea260fcb0a5c022a8d43994/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/JBRCustomDecorations.java

Does this only work when NetBeans is run using the JetBrains Runtime?

**Comment by eirikbakke** [comment]
I love this, by the way... another way to save some precious vertical space on incresingly wide (but seldom taller) screens.

**Comment by geertjanw** [comment]
This is an isolated piece of code by someone expert in this area of NetBeans, providing a feature that naturally follows previous commits in this area, and everyone automatically likes these developments. Hence, merging.

**Comment by lkishalmi** [comment]
@geertjanw Too quick with the fingers! The FlatLafOptionsPanel.form file does not have the License Header. RAT is broken!

**Comment by JaroslavTulach** [comment]
Yes, now the [RAT validation is failing](https://travis-ci.com/github/apache/netbeans/jobs/495012933) for everyone.

**Comment by neilcsmith-net** [comment]
Thanks @DevCharly On Travis, @geertjanw make sure to check which specific tests are failing before merging - some tests can be unstable and need retriggering (hints usually, although seem better now?).  Others are usually an accurate sign that something is wrong - eg. https://travis-ci.com/github/apache/netbeans/builds/221541407

**Comment by eirikbakke** [comment]
To answer my own question, the unified title bar seems to work even on plain OpenJDK distros, not just the JetBrains JDK. Very well done!

**Pull request merged**
