### PR TITLE
VSCode keyword fix

### PR DESCRIPTION
**Pull request by tbw777**

### CODE REVIEW

**Comment by tbw777** [comment]
inconsistent, corrected

**Comment by vieiro** [comment]
Hi, please focus in https://github.com/apache/netbeans/pull/5598 before posting new PRs. 
Once that one is ready for review you can then reopen this one.
Thanks.

**Comment by tbw777** [comment]
@vieiro I dont have restore button for this PR. Can you restore it?

**Comment by vieiro** [comment]
Hi @jlahoda I think this is indeed a bug, isn't it? Maybe you want to take a look?

**Comment by vieiro** [comment]
> @jlahoda what do i need to do?

Nothing! You have to wait now.

**Comment by mbien** [comment]
regarding contributing it to upstream as advised in:
https://github.com/apache/netbeans/blob/b3cf9b988542578e8d2c55c4d090e5fb5797fa1e/java/java.lsp.server/vscode/syntaxes/java.tmLanguage.json#L3-L5

its still broken there:
https://github.com/atom/language-java/blob/047fd33bd12f4926bc5dbc0c930cd9d5fa280602/grammars/java.cson#L42
but the atom editor project has shut down by now and is archived, see:
https://github.blog/2022-06-08-sunsetting-atom/

@sdedic would you like to take a last look before merge?

**Review by sdedic — APPROVED** [review]

**Comment by mbien** [comment]
@sdedic thanks!

**Pull request merged**
