### PR TITLE
[NETBEANS-5187] - cleanup Vector raw type warnings..

### PR DESCRIPTION
**Pull request by BradWalker**
Cleanup a bunch of the follow raw type warnings related to the use of Vector..

   [repeat] /home/bwalker/src/netbeans/enterprise/payara.eecommon/build/classes-generated/org/netbeans/modules/payara/eecommon/dd/impl/web/model_4/SessionConfig.java:22: warning: [rawtypes] found raw type: Vector
   [repeat] 	static Vector comparators = new Vector();
   [repeat] 	                                ^
   [repeat]   missing type arguments for generic class Vector<E>
   [repeat]   where E is a type-variable:
   [repeat]     E extends Object declared in class Vector

This check-in cleans up a lot of these..

### CODE REVIEW

**Review by mklaehn — APPROVED** [review]
thanks for your work

**Comment by matthiasblaesing** [comment]
Travis is (rightly) not happy: https://travis-ci.org/github/apache/netbeans/jobs/751753285#L9870-L9873

**Comment by BradWalker** [comment]
> Travis is (rightly) not happy: https://travis-ci.org/github/apache/netbeans/jobs/751753285#L9870-L9873

Hey @matthiasblaesing, I know this might sound dumb. But, this failure is not related to my changes, correct? I've look at it and doesn't seem related. Especially considering everything else did pass..

**Comment by BradWalker** [comment]
> Travis is (rightly) not happy: https://travis-ci.org/github/apache/netbeans/jobs/751753285#L9870-L9873

Hey @matthiasblaesing and @mklaehn , it's fixed now.. I only ever test with JDK 8. Since it's my bare minimum.. Good thing we have testing done upon checkins..

**Comment by matthiasblaesing** [comment]
Looks sane to me and Travis is indeed happy :-) Thank you.

**Comment by BradWalker** [comment]
> Looks sane to me and Travis is indeed happy :-) Thank you.

As usual, this stuff might be dull & boring. So, thanks to @matthiasblaesing  and @mklaehn for the help with the code review!

**Pull request merged**
