### PR TITLE
[NETBEANS-4861] nb-javac Upgrade to JDK-15

### PR DESCRIPTION
**Pull request by Akshay-Gupta-Oracle**
Upgraded nb-javac to merge with jdk15 so the new nb-javac will support jdk-15 features as well. All changes in nb-javac-15 are complete.

### CODE REVIEW

**Comment by lkishalmi** [comment]
@Akshay-Gupta-Oracle Please check why the signature check is failing.

**Comment by Akshay-Gupta-Oracle** [comment]
> @Akshay-Gupta-Oracle Please check why the signature check is failing.

Some api change did not get registered, trying to add in libs.javacapi.

**Comment by matthiasblaesing** [comment]
I asked on the mailing list, but did not get a reply: Oracle is still using apache controlled infrastructure (netbeans.osuosl.org), how far are plans to find a different distribution channel? Maven central would be the obvious place as we already require plugin developers to use it and it is the established way to distribute libraries for java applications.

**Comment by neilcsmith-net** [comment]
+1 to what @matthiasblaesing said, and as per mailing list conversation, if we can move to Maven Central we should consider publishing as NBMs via plugin portal (and remove from third-party UC) so that IDE updates aren't needed to update nb-javac.

**Comment by arvindaprameya** [comment]
> +1 to what @matthiasblaesing said, and as per mailing list conversation, if we can move to Maven Central we should consider publishing as NBMs via plugin portal (and remove from third-party UC) so that IDE updates aren't needed to update nb-javac.

Let me get back to you all with if and how we can do this .

**Comment by arvindaprameya** [comment]
Approved, thanks for getting this done Akshay

**Comment by arvindaprameya** [comment]
This is the latest nb-javac to support JDK 15 features along for NB 12.2

**Comment by Akshay-Gupta-Oracle** [comment]
@lkishalmi can you please add the milestone as 12.2 please?

**Comment by lahodaj** [comment]
The change looks fine to me.

Regarding publishing on Plugin Portal - not sure if that's desirable (at least unless we can have a separate plugin for every NetBeans release). As happened during the 11 timeframe (with .1 and .2 or .2 and .3, I don't recall), a newer version of NetBeans may require nb-javac that is incompatible with the newer version of NetBeans. So having a single AUC with a single version of nb-javac for both such versions may not be possible.

**Comment by ebarboni** [comment]
I'm not sure for plugin portal bug having nb-javac on maven central instead of netbeans.osuosl.org make easier to use for Mavenized NetBeans. 

By the way, you can't use org.netbeans groupId as it's locked by Apache NetBeans. 
But lots of groupId at com.oracle exists should be possible to add one specific like com.oracle.nbtooling and also maybe there is a global Oracle way to publish. Oracle jdbc are since a year or two in maven central

**Comment by neilcsmith-net** [comment]
@lahodaj yes, that's true, but we do now have unique plugin URLs for each release, which was half the problem. Unfortunately, 12.1 still ends up forwarded to the plugin catalog for 12.0 on the portal itself.  So we would need to fix that for this to happen - a good step forward, but probably not a viable idea for 12.2 at this time.

**Comment by lkishalmi** [comment]
I hope merged early enough to get some Java 15 feedback in the 12.2 cycle.

**Comment by jglick** [comment]
> if we can move to Maven Central we should consider publishing as NBMs

Would this allow nb-javac to be downloaded from Central? See the problem I have in https://github.com/stapler/netbeans-stapler-plugin/pull/7.

**Comment by netbeansuser2019** [comment]
This seems badly broken in Apache Netbeans 12.2 as every field, parameter,... that it is named as "permits" are presented a error even source level is 11 and JDK is 11.

**Comment by netbeansuser2019** [comment]
See also NETBEANS-5055

**Pull request merged**
