### PR TITLE
Global JS functions from classpath/platform are reported as undeclared global variable

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The JS hint, that detects undeclared global variables only queried the JS index for properties of the "window" object. This causes the variables and functions provided by the core- and dom-stubs to be mostly ignored.

This PR drops most of the hardcoded values in favor of querying the index.

The additional commits fix and reenable JS tests for CI/CD.

Closes: #4246

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
A test build is available here: https://doppel-helix.eu/NetBeans-dev-dev-305874798a712c97027ae7418159a185159c91e0-release.zip

**Comment by matthiasblaesing** [comment]
I intent to merge this some time next week. If anyone wants to object, please do so.

**Comment by matthiasblaesing** [comment]
What is your problem? 

image

Hell, NetBeans does not only "know" that the objects are in the global scope, it even can do code completion on them.

**Comment by qmegas** [comment]
My problem is that since NB 15 it looks like that:



Both `window` and `document` marked as not declared global variable.

**Comment by neilcsmith-net** [comment]
@qmegas please open an issue rather than discussing on a merged pull request, and by the looks of it, share a minimal reproducible example so that you're discussing the same thing.

**Pull request merged**
