### PR TITLE
bump CI matrix from 20-ea to 21-ea.

### PR DESCRIPTION
**Pull request by mbien**
preparations for the next LTS release of the JDK!

Java 20 is going to be released soon, this prepares the next round.

(not necessarily intended to be merged right away)

### CODE REVIEW

**Comment by ebarboni** [comment]
will this be the version were the "security manager" are removed ?

**Comment by mbien** [comment]
> will this be the version were the "security manager" are removed ?

@ebarboni I am not sure actually. The class is still there: https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/SecurityManager.html

I would expect them to announce such changes really early in the release cycle, so my guess would be that it will be still there in 21.

no yep here:
https://openjdk.org/projects/jdk/21/

or even here yet:
https://openjdk.org/jeps/0

**Comment by mbien** [comment]
oh interesting, build is failing now. Lets take a look.

**Comment by matthiasblaesing** [comment]
Locally I run directly against "improved" warnings:

```
-do-compile:
 [nb-javac] Compiling 122 source files to /home/matthias/src/netbeans/platform/api.search/build/classes
 [nb-javac] Ignoring source, target and bootclasspath as release has been set
   [repeat] /home/matthias/src/netbeans/platform/api.search/src/org/netbeans/spi/search/provider/SearchProvider.java:146: Warnung: [this-escape] possible 'this' escape before subclass is fully initialized
   [repeat]         private final ChangeSupport changeSupport = new ChangeSupport(this);
   [repeat]                                                                       ^
   [repeat] Fehler: Warnungen gefunden und -Werror angegeben
   [repeat] 1 Fehler
   [repeat] 1 Warnung
  [nbmerge] Failed to build target: all-api.search

```

I suspect, that we'll hit hit this often.

**Comment by mbien** [comment]
@matthiasblaesing yep. on it. Will fix this.

**Comment by matthiasblaesing** [comment]
In addition to the environment I need this to build:

```patch
diff --git a/groovy/libs.groovy/nbproject/project.xml b/groovy/libs.groovy/nbproject/project.xml
index ee6e1a6dc89b..a85eed42d526 100644
--- a/groovy/libs.groovy/nbproject/project.xml
+++ b/groovy/libs.groovy/nbproject/project.xml
@@ -30,7 +30,6 @@
                 <friend>org.netbeans.modules.groovy.editor</friend>
                 <friend>org.netbeans.modules.groovy.refactoring</friend>
                 <friend>org.netbeans.modules.groovy.support</friend>
-                <package>groovy</package>
                 <package>groovy.beans</package>
                 <package>groovy.cli</package>
                 <package>groovy.grape</package>
@@ -49,6 +48,7 @@
                 <package>groovy.util.logging</package>
                 <package>groovy.xml</package>
                 <package>groovyjarjarantlr</package>
+                <package>groovyjarjarantlr.collections.impl</package>
                 <package>groovyjarjarasm.asm</package>
                 <package>org.codehaus.groovy</package>
                 <package>org.codehaus.groovy.ant</package>
@@ -72,8 +72,8 @@
                 <package>org.codehaus.groovy.tools</package>
                 <package>org.codehaus.groovy.transform</package>
                 <package>org.codehaus.groovy.transform.sc</package>
-                <package>org.codehaus.groovy.transform.trait</package>
                 <package>org.codehaus.groovy.transform.stc</package>
+                <package>org.codehaus.groovy.transform.trait</package>
             </friend-packages>
             <class-path-extension>
                 <runtime-relative-path>ext/groovy-3.0.8.jar</runtime-relative-path>
diff --git a/php/websvc.saas.codegen.php/nbproject/project.xml b/php/websvc.saas.codegen.php/nbproject/project.xml
index 00bae6ea3295..8b0b4a6feeff 100644
--- a/php/websvc.saas.codegen.php/nbproject/project.xml
+++ b/php/websvc.saas.codegen.php/nbproject/project.xml
@@ -43,6 +43,15 @@
                         <specification-version>1.18</specification-version>
                     </run-dependency>
                 </dependency>
+                <dependency>
+                    <code-name-base>org.netbeans.modules.websvc.jaxwsmodelapi</code-name-base>
+                    <build-prerequisite/>
+                    <compile-dependency/>
+                    <run-dependency>
+                        <release-version>1</release-version>
+                        <specification-version>1.47</specification-version>
+                    </run-dependency>
+                </dependency>
                 <dependency>
                     <code-name-base>org.netbeans.modules.websvc.saas.api</code-name-base>
                     <build-prerequisite/>
@@ -93,7 +102,7 @@
                     </run-dependency>
                 </dependency>
                 <dependency>
-                    <code-name-base>org.openide.util.ui</code-name-base>
+                    <code-name-base>org.openide.util</code-name-base>
                     <build-prerequisite/>
                     <compile-dependency/>
                     <run-dependency>
@@ -101,19 +110,19 @@
                     </run-dependency>
                 </dependency>
                 <dependency>
-                    <code-name-base>org.openide.util</code-name-base>
+                    <code-name-base>org.openide.util.lookup</code-name-base>
                     <build-prerequisite/>
                     <compile-dependency/>
                     <run-dependency>
-                        <specification-version>9.3</specification-version>
+                        <specification-version>8.0</specification-version>
                     </run-dependency>
                 </dependency>
                 <dependency>
-                    <code-name-base>org.openide.util.lookup</code-name-base>
+                    <code-name-base>org.openide.util.ui</code-name-base>
                     <build-prerequisite/>
                     <compile-dependency/>
                     <run-dependency>
-                        <specification-version>8.0</specification-version>
+                        <specification-version>9.3</specification-version>
                     </run-dependency>
                 </dependency>
             </module-dependencies>
diff --git a/websvccommon/websvc.jaxwsmodelapi/nbproject/project.xml b/websvccommon/websvc.jaxwsmodelapi/nbproject/project.xml
index fc1d27a74167..ea090d5c10ad 100644
--- a/websvccommon/websvc.jaxwsmodelapi/nbproject/project.xml
+++ b/websvccommon/websvc.jaxwsmodelapi/nbproject/project.xml
@@ -63,6 +63,7 @@
                 <friend>org.netbeans.modules.websvc.saas.codegen</friend>
                 <friend>org.netbeans.modules.websvc.saas.codegen.j2ee</friend>
                 <friend>org.netbeans.modules.websvc.saas.codegen.java</friend>
+                <friend>org.netbeans.modules.websvc.saas.codegen.php</friend>
                 <friend>org.netbeans.modules.websvc.saas.ui</friend>
                 <friend>org.netbeans.modules.websvc.wsitconf</friend>
                 <package>org.netbeans.modules.websvc.jaxwsmodelapi</package>

```

**Comment by mbien** [comment]
gonna have to remove `-Werror` in the two affected modules. Since `-Xlint:-this-escape` is causing an error on older JDKs. 

```
jdk-20.0.0.36.1-corretto/bin/javac -Xlint:all -Xlint:-this-escape
error: invalid flag: -Xlint:-this-escape
Usage: javac <options> <source files>
use --help for a list of possible options

// https://github.com/openjdk/jdk/pull/11874
jdk-21-ea+18/bin/javac -Xlint:all -Xlint:-this-escape
error: no source files
```

It is probably the better to try to fix/ignore the warning anyway instead of suppressing it in javac.

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me, thank you.

The hint about the environment variable was primary intended to be able to build at all, so I agree, the warnings should be fixed/suppressed in the code.

**Pull request merged**
