### PR TITLE
[TRAVIS] Remove timeouts for platform/api.htmlui tests

### PR DESCRIPTION
**Pull request by blackleg**

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
I also had a look at this and with increased verbosity of the TestNG tests, I saw timeouts in the test preparation methods. Maybe we should just bump the timeouts from 9s to 30s?

**Comment by blackleg** [comment]
It can be a good fix, but can we remove the timeouts directly instead change these?

**Comment by matthiasblaesing** [comment]
Valid question - I admit, that I'm neither to deep in TestNG nor in the htmlui. But considering that stable unittest should not run into timeouts, that would also be a valid approach (IMHO).

**Comment by blackleg** [comment]
I'm going to edit this pull request to remove timeouts and test if tests are stable before merge.

**Comment by blackleg** [comment]
@matthiasblaesing  I removed all timeouts and Través passes the build.

**Pull request merged**
