### PR TITLE
Correct the breakpoint functionality in cpplite debugger.

### PR DESCRIPTION
**Pull request by entlicher**
Buggy behavior of C/C++ breakpoints is fixed. Breakpoints are properly added/removed in GDB. Enabled state is reflected correctly. A test is included.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
I cannot provide qualified review of the code changes, but I see `BreakpointTest`, so I assume we are moving in the right direction.

**Comment by neilcsmith-net** [comment]
At the moment, we don't have another beta scheduled, although discussions elsewhere might lead to one.  If not, I don't feel in a position to assess this one against the [bug priority guidelines](https://cwiki.apache.org/confluence/display/NETBEANS/Bug+Priority+Guidelines). Can we get assessment of the necessity to get this in to 12.3? Thanks!

**Comment by entlicher** [comment]
Although this PR improves significantly the behavior of C/C++ breakpoints, I don't feel it's really critical for 12.3.
I expect to do further improvements in 12.4 timeframe, thus this can move there as well.

**Comment by entlicher** [comment]
Changed the base to master and updated milestone to 12.4.

**Comment by neilcsmith-net** [comment]
@entlicher was actually going to say leave open against 12.3.  It was more about _whether_ we need another beta at all (which we initially weren't), but that's looking more likely.

**Comment by entlicher** [comment]
@neilcsmith-net O.K. I'm sorry. If it could go into 12.3, it'd be good as it makes the cpplite debugger complete enough for ordinary debugging. And then it can bring us feedback for changes/fixes in 12.4.

**Comment by neilcsmith-net** [comment]
@entlicher no problem, I didn't explain why I asked very well! :smile: If you put this back against delivery and 12.3 it will get merged assuming we have beta3.

**Pull request merged**
