### PR TITLE
Revert SpecificationVersion generics update

### PR DESCRIPTION
**Pull request by mbien**
followup on #4678 reverts the changes discussed here: https://github.com/apache/netbeans/pull/4678#pullrequestreview-1127588052

targets delivery

### CODE REVIEW

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me. Thank you for the quick revert.

**Comment by matthiasblaesing** [comment]
Please wait before merging. I was wrong with my reasoning.

**Comment by mbien** [comment]
tbh I don't think this actually needs to be reverted because the only safe way to stay backwards compatible in java is to build against the minimum version of the library you target. 

And since I can't come up with a scenario where code which was written against NB 15 wouldn't run on this, I still think this is safe.
(but i am also OK with a revert)

**Comment by neilcsmith-net** [comment]
I'm inclined to keep the generics update as is too.

**Comment by mbien** [comment]
closing for now - feel free to reopen if there are any new insights

**Pull request closed without merging**
