### PR TITLE
Move GraalVM job to JDK 11.

### PR DESCRIPTION
**Pull request by mbien**
[GraalVM 8 and 11 are EOL](https://github.com/oracle/graal/issues/5063) + PRs are blocked by the graal test job atm which runs on JDK 8 still.

lets try to upgrade to GraalVM 11 as intermediate step

meta issue #4904

### CODE REVIEW

**Comment by mbien** [comment]
'20.3.2' and  '22.3.3' don't have the python component and '21.1.0' gets a SIGSEGV

**Comment by mbien** [comment]
`DebugAllBaseTest`: `JPDADebugger#getCurrentThread()` is null when `python` is tested while `js`, `r` and `ruby` do seem to work.

**Review by lkishalmi — APPROVED** [review]
Looks good to me!

**Comment by mbien** [comment]
would be great if any of the graal gurus could take a look at this too @sdedic @entlicher @dbalek

**Review by sdedic — APPROVED** [review]
LGTM

**Comment by mbien** [comment]
thanks! squashing and merging.

**Pull request merged**
