### PR TITLE
[NETBEANS-3552] - Upgrade GraalVM from 19.0.0 to 19.3.0

### PR DESCRIPTION
**Pull request by pepness**
Notes:
- Added support for date, time, timezone and duration values in polyglot
- Better sub-process control
- Improved FileSystem management
- Updated Node.js to version 12.10.0
- Added support for reading environment variables
- Improved debugger
- Added support for temporary files and directories

Notes for ICU4J:
- Java 7 as minimum runtime
- Support Unicode 12.1
- Support CLDR 36 (Unicode Common Locale Data Repository)

[GraalVM Web Page](https://www.graalvm.org/)
[GraalVM SDK Release Notes](https://github.com/oracle/graal/blob/master/sdk/CHANGELOG.md)
[GraalJS Release Notes](https://github.com/graalvm/graaljs/blob/master/CHANGELOG.md)
[GraalVM Truffle Release Notes](https://github.com/oracle/graal/blob/master/truffle/CHANGELOG.md)
[ICU4J Release Notes](https://github.com/unicode-org/icu/releases/)

### CODE REVIEW

**Comment by blackleg** [comment]
@pepness See this pull request: https://github.com/apache/netbeans/pull/1748 to fix the problems with Travis.

**Comment by pepness** [comment]
> @pepness See this pull request: #1748 to fix the problems with Travis.

Thank you!, I will check it out

**Comment by JaroslavTulach** [comment]
GraalVM 19.3.x is the LTS version of GraalVM. Now, when the release has been shifted, it might make sense to update to it once the Travis jobs are stable.

**Comment by JaroslavTulach** [comment]
@ebarboni, unless it is too late from the perspective of release co-ordinator I'd like to get this into 11.3. If you agree, please merge. Otherwise remove the 11.3 label & milestone. Thank you. And also: Thank you, @pepness for starting this effort.

**Pull request merged**
