### PR TITLE
Update Maven archetype version for Jakarta EE 9.1

### PR DESCRIPTION
**Pull request by pepness**
Full build done
Verify successful creation of the project
Deploy and  run successfully

### CODE REVIEW

**Review by juneau001 — APPROVED** [review]

**Comment by ebarboni** [comment]
Hi @pepness does this PR contribute to fix some issue on javaee ?

**Comment by ebarboni** [comment]
I was looking for this issue too, #3723 . 
It seems that we can only create webapp using @juneau001 archetype , if you create ejb, ea or eac type you end creating a webapp.

**Comment by pepness** [comment]
Hi @ebarboni, you are correct, this will fix issue #4605 and these archetypes just work with webapps.

**Comment by HamiltonNCI** [comment]
Guys, I would appreciate some help on how exactly to implement these changes/updates. I'm kind of lost here. Thanks.

**Pull request merged**
