### PR TITLE
[cnd] merge master into cnd for JDK21-ga builds

### PR DESCRIPTION
**Pull request by vieiro**
In PR https://github.com/apache/netbeans/pull/6440 we talked about bringing PR https://github.com/apache/netbeans/pull/6469 so that CND can be build with JDK21-ga.

This PR brings master to cnd again (including the #6469) so that we can build this JDK version.

I'd appreciate a second look, as I'm doing this in a hurry _and_ tired. Thanks!

### CODE REVIEW

**Review by matthiasblaesing — APPROVED** [review]
The merge commit has exactly two parents, where one is the current head CND and the other was the head of master yesterday. There are no changes in the commit itself, so to me this looks like a straight merge. Thanks.

**Comment by bitrunner** [comment]
Should we consider, as @vieiro has suggested a few times, doing this in the other direction?  Would it be better to merge CND into master with CND in the full cluster but not the release cluster until it is ready for release similar to how rust module development is being handled?

**Comment by mbien** [comment]
well. this here is mostly done so that the build works again. I suggested to cherrypick a single commit, but merging everything has the same effect. Merging CND into master is ultimately the goal but since it conflicts with existing C/C++ support there probably have to be some issues resolved first. See [thread](https://lists.apache.org/thread/q85sp5oxqb8yo6yxxjt9xgo8d50x88bc). We could explore to merge it to master and build it completely separate as first step.

**Comment by vieiro** [comment]
@mbien @bitrunner Yeah, let's see if we can keep some compatibility with cpplite, as it's used somewhere.

**Comment by jlahoda** [comment]
FWIW, a few weeks ago, I was experimenting with "merging" CND and cpplite. I'll need to adjust that to this merge and finish, but it is unlikely I'd have time for that in the next ~2 weeks.

**Comment by jlahoda** [comment]
Sure, feel free to do anything in CND. I was deleting stuff from cpplite, and attempting to rebase cpplite debugger on top of the CND debugger common.

**Pull request merged**
