### PR TITLE
Sync delivery to master after 24-rc5 (merge conflict resolved)

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Sync delivery to master handling the merge conflicts while keeping all commits from delivery intact (just in case we need further changes)

Fix for #8003 Alternative to #8006 using the process used other times this has been necessary, eg. #6656 

@mbien please verify contents.

### CODE REVIEW

**Comment by mbien** [comment]
I originally wanted to do something like that but it didn't feel right, since this essentially lets the spec version go backwards in master and adds another commit which lets it jump forward again. (and if someone would look through the merge commits on master it will look like the same merge was applied three times)

essentially like this:
https://github.com/mbien/netbeans/commits/delivery-sync-rc5_resolvedv2/
instead of adding another branch merge commit, i added a commit to visualize what is happening here.

https://github.com/mbien/netbeans/commits/delicery-sync-rc5_resolved/ but this made more sense to me.

But ultimately I don't really care, whatever works is good.

FWIW: Followup RCs would have to keep doing the same trick to sync back. But this is a bit hypothetical given how late we are in the RC phase.

**Comment by neilcsmith-net** [comment]
@mbien I assumed from your comment elsewhere that you were going to amend the merge commit on delivery and force push it. That would be fine. The important thing is that all commits on delivery end up in master and release240.

I don't have an issue with the different merge commits here as they tell different stories, and other times we've done this it's been fixing merge conflicts from multiple PRs. The spec version decrement increment thing isn't ideal, but then this shouldn't have been touched in the original PR or the revert PR either.

**Comment by mbien** [comment]
> I assumed from your comment elsewhere that you were going to amend the merge commit on delivery and force push it.

I experienced [a momentary lapse of reason](https://en.wikipedia.org/wiki/A_Momentary_Lapse_of_Reason) and forgot that sync PRs don't have a branch (thats why I asked eric on slack if i should force push into his sync PR which makes no sense), they _are_ delivery. What I did instead was to use a copy of delivery as vehicle to move commits back to master.

**Comment by neilcsmith-net** [comment]
Sure, the PR branch is delivery. It's a transient integration branch. We can force push and fix things on there when necessary, and I have multiple times. You could check with Eric and [Meddle](https://en.m.wikipedia.org/wiki/Meddle) 😄 with that if you prefer.

Until the release is out, it's important to make sure the commits align or it can lead to knock on problems.

**Comment by ebarboni** [comment]
rc5 is ready, no branding issue. Merging. Thanks a lot.

**Pull request merged**
