### PR TITLE
FlatLaf Light editor color profile

### PR DESCRIPTION
**Pull request by AlexFalappa**
Initial attempt at an editor color profile that goes well with FlatLaf Light look and feel.

Still contains no syntax specific token colorings

Annotation colorings are those of default NetBeans color profile.

### CODE REVIEW

**Comment by AlexFalappa** [comment]
This may be too coarse for NetBeans 11.3.

I leave the choice of whether to include it to the reviewers and release manager.

**Comment by lkishalmi** [comment]
Could you attach a teaser screenshot?

**Comment by AlexFalappa** [comment]
@lkishalmi sure, forgot I had even prepared some 😅 .

Language (e.g. Java) tokens with some highlights (e.g. mark occurrences, guarded sections, folded regions), cursor was on `var` local variable (not captured by screenshot tool):
token-highlights

Markup (e.g. XML) tokens, cursor was on `parent` opening tag:
token-highlights-markup

**Comment by AlexFalappa** [comment]
Some syntax highlighting colors were derived from [Nord Theme](https://www.nordtheme.com/) "Aurora" scheme (darkened to better fit a light theme while Nord is a dark theme).

Things to improve:
* warning yellow underline is barely visible, may be make it a shade of light orange?
* not convinced of right margin line, maybe desaturate the blue a bit?
* light blue for keywords and markup elements could be saturated more to make it stand better against white backgorund

**Comment by ebarboni** [comment]
if you want to adjust you're welcome.

**Comment by AlexFalappa** [comment]
Just tweaked some colors a bit.

Language:
language

Markup:
markup

**Comment by ebarboni** [comment]
merging.

**Pull request merged**
