### PR TITLE
Make JDK URL calculation JDK 8 compatible

### PR DESCRIPTION
**Pull request by matthiasblaesing**

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@mbien please review. The build with nbjavac revealed, that method was used, that is not compatible with JDK 8 (`datesUntil` was introduced with 9). I think the replacement code is similar compact, equally readable and compatible with JDK8.

The reason this was not caught earlier, that modules with `requires.nb.javac` set normally don't set `--release`, while the nbjavac build seems to be ok with that and caught it.

**Review by mbien — APPROVED** [review]
@matthiasblaesing thanks for fixing this, looks good.

> The reason this was not caught earlier, that modules with requires.nb.javac set normally don't set --release, while the nbjavac build seems to be ok with that and caught it.

yeah as soon modules set `requires.nb.javac=true` they are all prone to link against the "wrong" JDK version ATM, since they can't actually use the `release` option. Interesting that this doesn't  cause issues more often since this is actually fairly dangerous, but might indicate that nobody is trying to run anything on JDK 8.

The build would need a JDK 8 installation somewhere which it could use as boot cp for all modules which set `requires.nb.javac=true` (and should probably fail otherwise for release builds).

**Comment by mbien** [comment]
gonna have to take a look at the html lexer test, it failed three times in a row at:
```
junit.framework.AssertionFailedError
    at org.netbeans.api.html.lexer.HtmlLexerPluginTest$TestPlugin.createAttributeEmbedding(HtmlLexerPluginTest.java:177)
```
might be wrapped into retry script as quick fix

**Review by jtulach — APPROVED** [review]
Nice. Better than  my [8018019](https://github.com/apache/netbeans/pull/5609/commits/8018019cf35825610c1e8ca9e59f96abe1aa3f04)

**Comment by jtulach** [comment]
> The build with nbjavac revealed, that method was used, that is not compatible with JDK 8

With a bit of satisfying feeling I'd say: `nb-javac` build (#5609) helped us make NetBeans better.

**Comment by mbien** [comment]
> With a bit of satisfying feeling I'd say: nb-javac build (https://github.com/apache/netbeans/pull/5609) helped us make NetBeans better.

its very unlikely the issue would have made it into the release, I merged that PR a few days ago and didn't update my dev build yet. One day nb-javac dependent modules will hopefully link against the right JDK which would fix this issue which we knew about for a while, its somewhere down on my todo-fix list even though I rather want to work on features/bug fixes instead of nb-javac issues.

**Comment by mbien** [comment]
> 
> ```
> u >z//<=>=>
> = 
> >>>/>>//w>
>  yl>be<<=k<uA>  F > Y <<<
>  >Jj/>k >>  ==a <z<=z  ><=r>>> =N///>>>/><< 
> EN>/>r> >p<<<L = > =<g=<C /=/   
>  q=R>  >B >=>z= />> J o  </>/>zn/><<>   z/>/>G=>nm< 
> ```
> 
> I'll look into this later, as this is not a fallout of this change.

oh boy, haha! The lexer made up its own language.

**Pull request merged**
