### PR TITLE
[TRAVIS] Test enterprise modules

### PR DESCRIPTION
**Pull request by blackleg**
Change Travis config to test enterprise modules

### CODE REVIEW

**Comment by mklaehn** [comment]
Build seems to have failed (https://travis-ci.org/apache/netbeans/jobs/618973448#L1046)
`platform/api.htmlui test` hadn't emitted any output for 10 minutes.
@matthiasblaesing maybe this is caused by your change of #1700 ?

**Comment by matthiasblaesing** [comment]
@mklaehn it is not my change, I'm just the committer (not the author). And no the change is not the problem, the problem is either the travis infrastructure or the htmlui unittests. Given that this is a heisenbug, it is difficult to diagnose.

**Comment by blackleg** [comment]
@mklaehn @matthiasblaesing I created this pull request to revert the changes in api.htmlui tests: https://github.com/apache/netbeans/pull/1710
Seems that the problem are with api.htmlui tests that fails randomly.

**Comment by mklaehn** [comment]
> @mklaehn it is not my change, I'm just the committer (not the author). And no the change is not the problem, the problem is either the travis infrastructure or the htmlui unittests. Given that this is a heisenbug, it is difficult to diagnose.

I saw your name at the top of the page wnd without reading further I made a bad assumption. Sorry for that.

**Comment by matthiasblaesing** [comment]
@blackleg is this intentional, that only a single module is tested?

**Comment by blackleg** [comment]
It's intentional, I didn't time to test more modules when prepared the pull request. It's the base to add more enterprise modules in Travis config.

**Comment by matthiasblaesing** [comment]
Thank you.

**Pull request merged**
