### PR TITLE
[NETBEANS-5784] Fixed defect: removal of deprecated constructor(Log.java) in JDK-17

### PR DESCRIPTION
**Pull request by singh-akhilesh**
https://issues.apache.org/jira/browse/NETBEANS-5784

### CODE REVIEW

**Comment by ebarboni** [comment]
looks like #2993 but seems you edit test too :D

**Comment by singh-akhilesh** [comment]
> looks like #2993 but seems you edit test too :D

Sorry, Not seen the PR is already present. It would be good if #2993 modify test case too.

**Comment by ebarboni** [comment]
can we close this and focus on #2993 ?

**Comment by singh-akhilesh** [comment]
> can we close this and focus on #2993 ?

Yes, Please do close. TIA

**Pull request closed without merging**
