### PR TITLE
[NETBEANS-4443] PHP 8.0 Support

### PR DESCRIPTION
**Pull request by junichi11**

### CODE REVIEW

**Comment by junichi11** [comment]
@lkishalmi I've not implemented all features for PHP 8.0 yet. (Some syntaxes are not supported yet.) But feature freeze is tomorrow, right? Should we merge these into the master once at the moment?

**Comment by lkishalmi** [comment]
We can merge this one, once Travis would agree. If the major infrastructure changes has happened here and there is a need for some polish, that can be introduced as PR-s on the upcoming delivery branch.

**Comment by junichi11** [comment]
@lkishalmi I see. Thanks!

@tmysik I haven't finished PHP 8.0 support (we have to implement new some syntaxes yet), but let's merge this into the master branch once. I'm going to fix the spec version after this is merged.

**Comment by lkishalmi** [comment]
please fix the spec versions in this PR. Master will receive a spec version bump after branching for the release. It would be really appreciated if I do not have to merge spec version changes.

**Comment by junichi11** [comment]
@lkishalmi This branch was created before 12.1 was released. So, maybe conflict would occur in this PR, I suppose. I didn't fix it to avoid that. Can I rebase this branch(it is in not forked repository but the apach/netbeans) with the master branch then fix the spec version then force-push it?

**Comment by junichi11** [comment]
@lkishalmi I'll close this then recreate a PR from my repository.

**Comment by junichi11** [comment]
Created the new PR: https://github.com/apache/netbeans/pull/2457

**Pull request closed without merging**
