### PR TITLE
[NETBEANS-84] - Add Support for JSF 2.3

### PR DESCRIPTION
**Pull request by juneau001**
- Added JSF 2.3 tag library
- Modified core to include new types
- Adjusted code to include references to JSF 2.3
- Added new external library reference and license for org.glassfish:javax.faces:2.3.9:jar

### CODE REVIEW

**Comment by junichi11** [comment]
Let's use the milestone instead of the version labels :) because version labels continue to increase and they are never used after specific versions are released.

**Comment by juneau001** [comment]
Prior to my commit, I synced my fork.  However, I did not cherry pick the commit for JSF 2.3, so it included a number of my previous commits as well.  Should I close this PR and clean up by cherry picking only the latest commit?  Thanks

**Comment by junichi11** [comment]
@juneau001 We can squash and merge your commits via GitHub "Squash and merge" button. i.e. Your commits will be just one commit if the person who merges this does that. So, if it is OK with you, you can leave it as it is. Of course, if you would like to squash them properly yourself in your local environment, you can do that then can push (force) it the same branch(NETBEANS-84). So, I don't think you need to close this :)

**Comment by matthiasblaesing** [comment]
@juneau001 I have better experience with using rebasing patches, instead of merging the base  branch into the feature branch as done here. For me the rebasing leads to a history, that can be much easier be refactored/cleaned up.

**Comment by juneau001** [comment]
I am closing this pull request because I have made additional changes.  I will also rebase my fork again before opening new pull request.

**Pull request closed without merging**
