### PR TITLE
Bugfixes for VSCode and Gradle

### PR DESCRIPTION
**Pull request by JaroslavTulach**
Invoking the "Java: Compile Workspace" on a Maven project prints empty lines. Removing `"\n"` lines altogether. The EOL character is implicitly present in the previous line.

Avoiding usage of `invokeLater` when in headless mode in Gradle: edc2ff9

Branding API (like the [one in Maven](https://github.com/apache/netbeans/pull/2427)) to disable output reuse: e29dfe1

### CODE REVIEW

**Review by dbalek — APPROVED** [review]
Looks fine.

**Comment by JaroslavTulach** [comment]
Laszlo, I have a question about `JavaActionProvider`. Why does it not run/debug single file?
```
   case COMMAND_DEBUG_SINGLE:
                            case COMMAND_RUN_SINGLE:
                                if (RunUtils.isAugmentedBuildEnabled(project)) {
```
unless the project is augmented? Btw. what does it mean "augmented"?

**Comment by lkishalmi** [comment]
Well run and debug single requires a runSingle taskwhich would take runClassName and runArgs. That task is injected by the NetBeans Gradle Tooling if build augmentation is enabled.
Well the situation can be improved to enable those actions if we have a runSingle task defined in the project. I'm going to create a PR for that one.

**Comment by JaroslavTulach** [comment]
I see. Gradle tooling does augmentation! I was wandering why I cannot find `runSingle` when launching gradle on the command line. The augmentation approach defeats the idea of NetBeans always doing internally the same thing as from command line and it beats the purpose of printing the command line at the beginning of output. It makes no sense to copy it to terminal.

> we have a runSingle task defined in the project

If we have this, then I have to modify the [testing project](https://micronaut.io/launch/) to have `runSingle` action.

Or I need to find a way to open a project and make it augmented.

**Comment by lkishalmi** [comment]
Well, I thought that the truth in the augmented command line would freak out an average user. Though it provides NetBeans binding for runSingle and deploy for web projects. 

I'm almost ready with the PR that accepts runSingle task if that's registered.

**Pull request merged**
