### PR TITLE
Snapshot of APIs as of NetBeans 15

### PR DESCRIPTION
**Pull request by neilcsmith-net**
Snapshot of APIs as of NetBeans 15.  For review (sorry, bit late again due to some issues, but we can run another RC if there's a real need to fix anything).  Not to be merged as / until release vote completes.

Constant changes introduced in #4025 in Utilities might be a problem?

Built in the usual way -

```
# checkout branch (or release tag)
git checkout release150
ant clean
ant build
ant gen-sigtests-release
git add -A
git stash
git checkout master
git checkout -b apis-nb150
git stash pop
git add -A
git commit -m "Snapshot of APIs as of NetBeans 15"
# remove getPeer() calls
find . -name "*.sig" -exec sed -i '/java.awt.peer.ComponentPeer/{N;d;}' {} \;
# check git diff
git add -A
git commit --amend
```

### CODE REVIEW

**Comment by ebarboni** [comment]
lots of modification on maven indexer also  (intended)
and openide constant change for OS identification

Would be nice to get a diff without the ' #version change ' line :D

**Comment by neilcsmith-net** [comment]
> and openide constant change for OS identification

Thanks @ebarboni This is #4025 - it might be a release blocker?

**Comment by neilcsmith-net** [comment]
@ebarboni using @jtulach trick from https://github.com/apache/netbeans/pull/3792#issuecomment-1071121107 gives the following file which might be easier to review -
[nb15sigs.diff.txt](https://github.com/apache/netbeans/files/9307357/nb15sigs.diff.txt)

**Comment by neilcsmith-net** [comment]
Regenerated from 15-rc4.  cc/ @mbien @lkishalmi

**Review by lkishalmi — APPROVED** [review]
Scrolled through. The ugly stuff seems to be gone.

**Pull request merged**
