### PR TITLE
Use RequestProcessor to fix SecurityException:setContextClassLoader.

### PR DESCRIPTION
**Pull request by entlicher**
Backporting https://github.com/apache/netbeans/pull/3082 to 12.5, if it's not too late...
The fix is quite simple and safe.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Delivery gets merged into master anyway - backporting things causes problems!

**Comment by matthiasblaesing** [comment]
I tested what happens when PRs #3095, #3096 and #3097 are merged to `delivery`. My setup is a clone from the github repository, with additonal fetches `fetch = +refs/pull/*/head:refs/remotes/github/pr/*`:

```bash
# Ensure github data is current
git fetch github
# Ensure repository state is clean
git reset --hard
git clean -f -d
# Ensure test branches don't exist yet
git branch -D delivery-test
git branch -D master-test
# Checkout github delivery into local branch delivery-test
git checkout -b delivery-test github/delivery
# Simulate merging of backport PRs
git merge github/pr/3097
git merge github/pr/3095
# Simulate merging of PR, that touches the same work area
git merge github/pr/3096
# At this point deliver-test has the state of delivery with PRS 3095, 3096 and 3097 merged
# Now check, if that can be merged back into master or if merge conflicts arise
git checkout -b master-test github/master
git merge delivery-test
```

The result is:

> Auto-merging java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
> CONFLICT (content): Merge conflict in java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
> Auto-merging java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
> CONFLICT (content): Merge conflict in java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
> Auto-merging java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/layer.xml
> Auto-merging java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
> CONFLICT (content): Merge conflict in java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources /desktop_build.gradle.fmk
> Automatic merge failed; fix conflicts and then commit the result.

My gut feeling is, that the problem is caused by the additional modifications in the backport:

```diff
diff --cc java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
index c4c275553848,71b86b0a8c2b..000000000000
--- a/java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
+++ b/java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
@@@ -52,7 -52,7 +52,11 @@@ if (!jdk8) 
  dependencies {
      implementation commonProject
      implementation "org.netbeans.html:net.java.html.boot:1.7.2"
++<<<<<<< HEAD
 +    implementation "com.dukescript.api:javafx.beaninfo:0.5"
++=======
+     implementation "com.dukescript.api:javafx.beaninfo:0.6"
++>>>>>>> delivery-test
      runtimeOnly "com.dukescript.api:javafx.base:8.60.11"
      runtimeOnly "org.netbeans.html:net.java.html.boot.fx:1.7.2"
  }
diff --cc java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
index dea1aaf122ce,2ba3db02c108..000000000000
--- a/java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
+++ b/java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
@@@ -39,7 -39,8 +39,12 @@@ sourceCompatibility = '1.8
  dependencies {
      implementation "org.netbeans.html:net.java.html.json:1.7.2"
      implementation "com.dukescript.api:javafx.base:8.60.11"
++<<<<<<< HEAD
 +    implementation "com.dukescript.api:javafx.beaninfo:0.5"
++=======
+     implementation "com.dukescript.api:javafx.beaninfo:0.6"
+     annotationProcessor "com.dukescript.api:javafx.beaninfo:0.6"
++>>>>>>> delivery-test
      runtimeOnly "org.netbeans.html:ko4j:1.7.2"
  }
  </#noparse>
diff --cc java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
index bbbc5ba900ed,43ee3ab223db..000000000000
--- a/java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
+++ b/java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
@@@ -23,7 -23,7 +23,11 @@@ buildscript 
          mavenCentral()
      }
      dependencies {
++<<<<<<< HEAD
 +        classpath "org.apidesign.bck2brwsr:bck2brwsr-maven-plugin:0.50"
++=======
+         classpath "org.apidesign.bck2brwsr:bck2brwsr-maven-plugin:0.51"
++>>>>>>> delivery-test
      }
  }

```

**Comment by JaroslavTulach** [comment]
To resolve the `delivery` -> `master` conflicts I have just integrated 60957e3 into the master. Now the merge seems be without any conflicts.

**Comment by matthiasblaesing** [comment]
@JaroslavTulach good idea :-) Seems to work.

**Pull request merged**
