### PR TITLE
Fix No such property: getFreeCompilerArgs kotlin plugin

### PR DESCRIPTION
**Pull request by moacirrf**
### Problem
When using kotlin plugin for gradle
```
plugins {  id 'org.jetbrains.kotlin.jvm' version '1.6.20-RC2' }
```
I receive a notification every time i execute any task.

netbeansGradleKotlinProblem2

> org.codehaus.groovy.runtime.metaclass.MissingPropertyExceptionNoStack: No such property: getFreeCompilerArgs for class: org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptionsImpl
> 

### Solution

**Project:** netbeans/extide/gradle/netbeans-gradle-tooling
**Class:** org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.java, line 292

Replace
` compilerArgs = (List<String>) getProperty(compileTask, "kotlinOptions", "getFreeCompilerArgs");`
 By 
`  compilerArgs = (List<String>) getProperty(compileTask, "kotlinOptions", "freeCompilerArgs");`

I'm open to any sugestion or other solution.
Thanks

### CODE REVIEW

**Comment by moacirrf** [comment]
I created my branch from release130, maybe is better open a new one from a branch originated from master, what do you think?

**Comment by matthiasblaesing** [comment]
Could you please check if this is already covered by: https://github.com/apache/netbeans/pull/3829?

**Comment by moacirrf** [comment]
Its covered by https://github.com/apache/netbeans/pull/3829
i will close this pull request.
Thanks.

**Comment by moacirrf** [comment]
> Could you please check if this is already covered by: #3829?

Its covered by https://github.com/apache/netbeans/pull/3829
i will close this pull request.
Thanks.

**Pull request closed without merging**
