### PR TITLE
make sure metabuild.jsonurl is set everywhere

### PR DESCRIPTION
**Pull request by mbien**
the default value 
https://github.com/apache/netbeans/blob/613087a5e020e52021d6b45ea7813a08af5aa33e/nbbuild/build.xml#L153
 is currently 404ing and causing the build to fail. This gives us the opportunity to check if the $OPTS are set everywhere (spoiler: they weren't :)).

### CODE REVIEW

**Comment by mbien** [comment]
looks like it might take a while longer till gitbox is restored (see https://status.apache.org/)

```
Identified - We have identified some issues with our repository browsing features for gitbox.apache.org that are currently rendering them unavailable. We do not have a precise ETA for when this will be addressed, and are expecting up to a couple of days of unavailability for these features. read/write access to the repositories is not affected by this.
Apr 29, 2023 - 19:03 UTC

```
I rebased to delivery for now

**Comment by jlahoda** [comment]
Well, this fixes the build on the CI, but it will still block anyone from doing the build, right? Maybe the default should be the GitHub URL temporarily, but longer-term, maybe we want to either (or both):
a) using a redirect we have under our control, instead of a hard link to some repository (the redirect could easily be changed from gitbox to github, or to hard-coded value, to fix all the builds at once)
b) make the build not fail when the URL is not available (would make a "dev" build, but since the official bundles include(?) the json, this shouldn't be a problem??)

**Comment by mbien** [comment]
@jlahoda I just sent a mail to dev how to build locally. You can pass the json link param just like CI does.

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me, thank you.

**Comment by neilcsmith-net** [comment]
> a) using a redirect we have under our control, instead of a hard link to some repository (the redirect could easily be changed from gitbox to github, or to hard-coded value, to fix all the builds at once)

This would probably be a good idea.  We can add a redirect similar to the update centres, etc. in https://github.com/apache/netbeans-website/blob/master/netbeans.apache.org/src/content/.htaccess  If someone wants to add this, please don't put under `/nb/` path.

> b) make the build not fail when the URL is not available (would make a "dev" build, but since the official bundles include(?) the json, this shouldn't be a problem??)

As added on list, as well as using a local file url for the setting, you can copy `netbeansrelease.json` into `nbbuild/`.  This will stop the download requirement (feature used for source releases and offline use).  Then up to you to keep it up to date though.

**Review by neilcsmith-net — APPROVED** [review]
Well, this is an annoying situation!

Thanks for this.  Looks good.  Just re-running a failed test, then will merge.  As we have nothing else in delivery yet, I'll do a separate sync to master and release180 to get them fixed ASAP.

cc/ @ebarboni

**Comment by ebarboni** [comment]
sorry for being late but altering the apache website is dependent on gitbox. As we "pull from github" but we push on gitbox.

cc/ @neilcsmith-net

**Comment by neilcsmith-net** [comment]
@ebarboni I'm currently setting up redirects and will put in a PR for the build shortly.  Have already added https://github.com/apache/netbeans-website/commit/4dfa17d594740c1ad38a5e579bc19e870bf9370d

Push on gitbox should be working OK, and gitbox is already redirecting to GitHub anyway.  Still be better to have under our control.

**Pull request merged**
