### PR TITLE
[NETBEANS-1157] Changed NBI Native Launcher compiler options

### PR DESCRIPTION
**Pull request by AndiMb**
Removed Compiler and Linkeroption -mno-cygwin since the x86_64-w64-mingw32-gcc needs to be used
a Cygwin64 Tool collection has to be configured in Netbeans before compiling (with the compilers $CYGWIN64_PATH$\bin\x86_64-w64-mingw32-gcc.exe and $CYGWIN64_PATH$ \bin\x86_64-w64-mingw32-g++.exe)

Steps to compile:
1. Download and install Cygwin on a Windows machine (with the latest version of gcc-core, gcc-g++, mingw64-x86_64-gcc-core, mingw64-x86_64-gcc-g++, gdb, make)
2. Download and run Netbeans with C/C++ support
3. Open the Netbeans C/C++ project (.../nbi/engine/native/launcher/windows)
4. Create a new Netbeans C/C++ configuration "Cygwin64" (Tools -> Options -> C/C++)
   Add $CYGWIN64_PATH$\bin\x86_64-w64-mingw32-gcc.exe as C compiler and $CYGWIN64_PATH$\bin\x86_64-w64-mingw32-g++.exe as C++ compiler
5. Clean and Build the project
6. The nlw.exe is in the folder ...\nbi\engine\native\launcher\windows\dist\nlw.exe

Hint: Do compile with the with configuration "Debug". The options are only added here, especially the needed libraries. In my opinion there are no real debug compiler options set in the "Debug" configuration. The Release configuration is not set up.

### CODE REVIEW

**Comment by geertjanw** [comment]
Great, thanks for this. So, what is the purpose of this enhancement, i.e., what does it do, how would we describe this in the release notes? Thanks.

**Comment by eirikbakke** [comment]
What kind of build process is used for the NBI launcher?

For other Windows binaries (e.g. netbeans64.exe) we have migrated away from IDE-based compilation, and away from Cygwin, instead using a plain Makefile using mingw. Search the codebase for "Makefile.mingw" for examples. This allows the binaries to be built as part of the regular build process; see https://issues.apache.org/jira/browse/NETBEANS-1145 . In fact, the old C/C++ IDE projects don't even load anymore on NetBeans 10 (though it seems the nbi project is actually Ant-based?)

Might it be better to migrate the NBI launcher compilation to mingw as well?

**Comment by AndiMb** [comment]
Hi, sorry for the late reply. Right now I am totally out of time. You both are completely right. I have to change the build process to enable a automatic build. This commit was just a quick fix to get somehow an executable.

**Comment by eirikbakke** [comment]
Making a mingw makefile might be a good start--automatic build could always be postponed until a later commit.

(Another realization: reading http://www.delorie.com/howto/cygwin/mno-cygwin-howto.html , it seems that building an EXE on Cygwin without the -mno-cygwin option will create an EXE that does not work without cygwin1.dll . It would also force the EXE to fall under the GPL license, apparently.)

**Comment by ebarboni** [comment]
we did others changes and split repository for netbeans launcher; Build improvement should be handled in this repository https://github.com/apache/netbeans-native-launchers

**Pull request closed without merging**
