### PR TITLE
Fixed issues in history view

### PR DESCRIPTION
**Pull request by troizet**
Hello! This PR fixes issues #4367 and #4394.

### CODE REVIEW

**Review by mbien — APPROVED** [review]
looks good to me. Seems to work too.

If you want to get this into NetBeans 15, you would have to put the commit on top of the delivery branch and then force push to this PR again. Master is for 16 already.

btw: I found another small issue while testing: if you select "Load All" it should probably remove the "Load next 30 days" item, since there shouldn't be anything more to load.

**Comment by neilcsmith-net** [comment]
To help release tracking, have marked with NB15 and do-not-merge as and until the change in branch is made as suggested by @mbien

**Comment by troizet** [comment]
Implemented the suggested changes to the branch. @mbien, @neilcsmith-net please check if I did it right.

**Comment by troizet** [comment]
@mbien, fixing the "Load All" issue, I think, is better done in another PR.

**Comment by mbien** [comment]
> Implemented the suggested changes to the branch. @mbien, @neilcsmith-net please check if I did it right.

looks good, thanks for rebasing on delivery.

**Pull request merged**
