### PR TITLE
Update netbeans bundled JNA library to 5.4.0

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The JNA release cycles not only added featured, but also improved stability
and deadlock resilience. This PR updates the JNA version bundled with JNA
and updates it to the current version.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
@neilcsmith-net with Praxis LIVE you are directly affected by this change. Could you please have a look at this?

- I updated in-tree users where they were either incompatible or used deprecated calls.
- Usage as a dependency is present in the `External Execution Process` and `JSch Agent Proxy library`. For the jsch agent proxy I checked out the original source code and updated the dependency to jna 5.4.0 (it compiled cleanly). For the `External Execution Process` JNA is only used from the `ProcessTreeKiller`. Missing the source code for the latter I decompiled it tried building it with a recent version of JNA. I feel confident, that this works.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing thanks for the offer to review.  This won't affect PraxisLIVE, as [for a long time](https://praxisintermedia.wordpress.com/2012/01/04/jna-3-4-0-on-the-netbeans-platform/) it has shipped with its own choice of version.

I can't test this until next week, but +1 in principle to this change.  It would also be good to remove the friend API restriction here?  JNA is top of my annoying use of friend API with third-party dependencies!  If you read the blog post link above, you'll notice me moaning about this in 2012. :smile:

**Comment by matthiasblaesing** [comment]
@neilcsmith-net I removed the friend-only restriction. I think JNA is mature enough to indicate, when it breaks compatibility and then netbeans has a mechanism to indicate the break as I utilized in this PR.

**Comment by matthiasblaesing** [comment]
I rereviewed my changes and think they are safe. If really problems creep in, I'm around to fix.

**Pull request merged**
