### PR TITLE
Sync delivery to master after 18-rc3

### PR DESCRIPTION
**Pull request by neilcsmith-net**

### CODE REVIEW

**Comment by mbien** [comment]
interesting, I had to restart CV twice here: https://github.com/apache/netbeans/actions/runs/4934810357 this rarely happens

**Comment by neilcsmith-net** [comment]
I had to restart a different test (assume you mean commit validation?) twice in https://github.com/apache/netbeans/actions/runs/4927433084

Which, is, incidentally, the reason this isn't merged yet!  Will merge now though.

**Comment by mbien** [comment]
yes I mean commit validation. Had to restart the job on JDK 8 twice. which can be a coincidence but is a bit unusual.

**Comment by neilcsmith-net** [comment]
Let's keep an eye on it!  That was one of the tests that was unstable after the first set of Graal classloader changes was merged.

**Comment by mbien** [comment]
github is also starting to have issues again today: https://www.githubstatus.com/
some jobs are failing because of that too

**Comment by neilcsmith-net** [comment]
Yes, build on this merge already failed https://github.com/apache/netbeans/actions/runs/4937441610  Been a bad week for GH services! :smile:

**Pull request merged**
