### PR TITLE
finalize() proposal

### PR DESCRIPTION
**Pull request by BradWalker**
Commit with prototype changes. Please see the conversation on the [discussion page](https://github.com/apache/netbeans/discussions/5436)

DO NOT INTEGRATE!

### CODE REVIEW

**Comment by BradWalker** [comment]
It was unclear how I should propose a "prototype" for discussion. So I recreated a discussion about it and submitted this pull request to help. It's not my intention to have this integrated.

If I didn't follow protocol, then just let me know. Also, if there is a better way, then also, please, let me know.

**Comment by matthiasblaesing** [comment]
If this affects NetBeans development I think it belongs onto ` dev@`. I don't read discussions and I'm pretty sure I'm not the only developer.

**Comment by neilcsmith-net** [comment]
I have no doubt we need to address the end of finalization, but I'm not sure we need to be changing the base release version of modules just to add the extended variety of the deprecated annotation?!

**Comment by BradWalker** [comment]
> I have no doubt we need to address the end of finalization, but I'm not sure we need to be changing the base release version of modules just to add the extended variety of the deprecated annotation?!

Hey @neilcsmith-net , I mostly agree with your comments.

Here's the problem.

We are going to need to change the base release if and when we resolve the finalization issue. That much we all agree on. I'm simply proposing that we start the process to make the work easier later on.

The first step in that process, to me, would be to mark the `finalize()` methods as deprecated like I propose.

**Comment by neilcsmith-net** [comment]
> We are going to need to change the base release if and when we resolve the finalization issue.

You can replace `finalize()` using JDK 8 if need be.  Admittedly not if we decide to use JDK Cleaner API, but that's not the only option.

We haven't yet agree to move the platform beyond JDK 8.  Some of these should upgrade to JDK 11 when we're ready to move the platform as a whole.  At least `o.n.bootstrap` will need to wait for that.

**Comment by mbien** [comment]
we should track this as issue.
we have one for ThreadDeath: #4952
and one umbrella issue for all JDK 11 incompatible tests: #4904

added #5440 for the finalization mechaninsm

**Pull request closed without merging**
