### PR TITLE
Update used groovy to 2.5.14

### PR DESCRIPTION
**Pull request by svenreimers**

### CODE REVIEW

**Review by mklaehn — APPROVED** [review]
Thanks for the update

**Comment by mklaehn** [comment]
There appear to be some test failures though...

**Comment by svenreimers** [comment]
Not sure why this fails.. Looking at the log all seems ok...

**Comment by svenreimers** [comment]
Ok. Figured it out.. Seems there is a problem with class generation for a script being different with Java 11, investigating now

**Review by mklaehn — APPROVED** [review]
Looks good to me

**Review by lkishalmi — APPROVED** [review]
Looks good to me!

**Pull request merged**
