### PR TITLE
Adding org.eclipse.lsp4j.debug and org.eclipse.lsp4j.jsonrpc.debug dependencies to LSP Client

### PR DESCRIPTION
**Pull request by albilu**
Fix for #5950
Allowing LSP Client to use not only the LSP Client but also the DAP Client

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
In general this change makes sense to me, though there might be alternatives. I assume, that you get two different gson versions in your classpath and that is what blows.

For the change:
- please increment the second component of the spec version (can be updated in place)
- please update the commit with your real name and valid e-mail address (currently your nickname and the github noreply address is listed)

**Comment by albilu** [comment]
> In general this change makes sense to me, though there might be alternatives. I assume, that you get two different gson versions in your classpath and that is what blows.

Yes right. But seems more complicated as the packages in LSP client are not public so i tried to exclude the gson from LSP client and many different solution but didn't work.

Spec Version updated!
Commit Amended with valid user name/email.

**Comment by albilu** [comment]
Updated lsp4j-0.13.0-license.txt and ignored-overlaps files as 1 check (Check Paperwork on Linux/JDK 11) previously failed

**Review by matthiasblaesing — APPROVED** [review]

**Comment by matthiasblaesing** [comment]
If noone objects, I'll merge next weekend. Thank you for the work.

**Pull request merged**
