### PR TITLE
apisupport dir: removed unessesary old forms of Integer type

### PR DESCRIPTION
**Pull request by tbw777**
Changed boxing/autoboxing with Integer()/valueOf()/intValue() to raw int values or parseInt(some string)

### CODE REVIEW

**Comment by vieiro** [comment]
Hi @tbw777 ,

Please add this as a single commit to PR https://github.com/apache/netbeans/pull/5229

Thanks!

**Comment by tbw777** [comment]
@vieiro origin/bumInteger/apisupport updated but not visible here. Its because reopen required?

origin/bumInteger/apisupport:

> rebased to master
> amended commit of above PRs

**Comment by vieiro** [comment]
Hi @tbw777 ,

 #5238 is already reviewed, no need to mess things there.

You can merge those different branches of yours (the branches for your PRs) into this branch (https://github.com/tbw777/netbeans/tree/bumInteger/apisupport ) and then push, the different commits will appear in this PR, so we can review it all at once.

**Comment by tbw777** [comment]
I did merge PRs already. but here is no timeline events. I think it because current PR was closed.

[1 hour ago](https://github.com/tbw777/netbeans/commit/1a6593dc18ce2fae8d44d4939e7f0e1a330e07fa)

**Pull request closed without merging**
