### PR TITLE
[NETBEANS-5533] Remove the URL of the old wiki

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-5533

- The old wiki is available no longer (http://wiki.netbeans.org/HowToConfigureXDebug)

### CODE REVIEW

**Review by tmysik — APPROVED** [review]
@junichi11 Was the information in that page useful even today? I mean, should we create a similar page?

**Comment by tmysik** [comment]
@ebarboni @junichi11 

The patch is OK, feel free to merge. Thanks.

**Comment by junichi11** [comment]
@tmysik Thank you for your review :)

> Was the information in that page useful even today? I mean, should we create a similar page?

Maybe, the information was so old... So, I added the following URL before: https://xdebug.org/docs

https://github.com/apache/netbeans/blob/6456f473f48f5d6daea9bc247198bccaa9017aa9/php/php.dbgp/src/org/netbeans/modules/php/dbgp/ConnectionErrMessage.java#L242

Instead of the old wiki, I suppose the following page is helpful for users: https://xdebug.org/docs/install
Thanks.

**Comment by ebarboni** [comment]
ok mergin

**Pull request merged**
