### PR TITLE
Fix npe from gradle build actions dialog

### PR DESCRIPTION
**Pull request by errael**
This fixes the NPE from #4702

### CODE REVIEW

**Review by lkishalmi — APPROVED** [review]
Looks sane.

**Comment by mbien** [comment]
want to squash the merge commit before integration or should we leave it as is?

**Comment by errael** [comment]
> squash the merge commit

Oops, not sure how that got there, I think github contributed that when I wasn't looking (or maybe wasn't paying attention). Look OK now.

I use hg-git, sometime things don't mesh quite right.

**Comment by mbien** [comment]
all green && approved -> merging

@errael thanks for fixing this

**Pull request merged**
