### PR TITLE
[NETBEANS-3521] - Upgrade Xerces2-J from 2.8.0 to 2.12.0

### PR DESCRIPTION
**Pull request by pepness**
Notes:
- Fixed several bugs 
- Many enhancements and performance improvements
- Xerces and Xalan now share a common serialization codebase
- Xerces' native serializer was deprecated
- Support for OASIS XML Catalogs v1.1
- Implementation of the parser related portions of JAXP 1.4
- Experimental support for XML Schema 1.1 by providing a fully compliant XML Schema 1.1 implementation

[Apache Xerces2-J Web Page](https://xerces.apache.org/xerces2-j/)
[Apache Xerces2-J Release Notes](https://xerces.apache.org/xerces2-j/releases.html)

### CODE REVIEW

**Comment by sdedic** [comment]
Please be careful about this update. Xerces 2.11.0 started to implement `ElementTraversal` on its `ElementImpl`s, but that class is not present in JDK 8's rt.jar - it is shipped from JDK9 onwards (java.xml module).

I've encountered this situation in other project; if the JDK8 runtime attempts Xerces' DOM implementation (`ElementImpl`), it will fail with `ClassDefNotFoundError` -- 

> public class org.apache.xerces.dom.ElementImpl extends org.apache.xerces.dom.ParentNode implements org.w3c.dom.Element,org.w3c.dom.**ElementTraversal**,org.w3c.dom.TypeInfo 

JDK9+ is fine.

**Comment by sdedic** [comment]
I looked into this a little more. It seems that there are only a very few references to the library in _the code_:
```
enterprise/tomcat5/src/org/netbeans/modules/tomcat5/deploy/TomcatManagerImpl.java:import com.sun.org.apache.xerces.internal.impl.dv.util.Base64;
enterprise/web.core/src/org/netbeans/modules/web/wizards/TagInfoPanel.java:        return org.apache.xerces.util.XMLChar.isValidNCName(name);
enterprise/web.core/src/org/netbeans/modules/web/wizards/targetpanel/providers/TagTargetPanelProvider.java:        return org.apache.xerces.util.XMLChar.isValidNCName(name);

......

ide/xml.tax/lib/src/org/netbeans/tax/io/XNIBuilder.java:import org.apache.xerces.xni.*;
ide/xml.tax/lib/src/org/netbeans/tax/io/XNIBuilder.java:import org.apache.xerces.xni.parser.XMLDTDSource;
ide/xml.tax/lib/src/org/netbeans/tax/io/XNIBuilder.java:import org.apache.xerces.xni.parser.XMLDTDContentModelSource;
ide/xml.tax/lib/src/org/netbeans/tax/io/XNIBuilder.java:import org.apache.xerces.xni.parser.XMLDocumentSource;
ide/xml.tax/lib/src/org/netbeans/tax/io/XNIBuilder.java:import org.apache.xerces.parsers.*;
ide/xml.tax/src/org/netbeans/modules/xml/tax/parser/ParserLoader.java:    private static final String PARSER_PACKAGE = "org.apache.xerces";  // NOI18N
ide/xml.tax/src/org/netbeans/modules/xml/tax/parser/ParserLoader.java:    private static final String XERCES_ARCHIVE = "modules/autoload/ext/xerces2.jar"; // NOI18N
ide/xml.tax/src/org/netbeans/modules/xml/tax/parser/ParserLoader.java:        Class apache = me.loadClass("org.apache.xerces.util.QName"); // NOI18N
ide/html.validation/src/org/netbeans/modules/html/validation/NbValidationTransaction.java:    //xerces's default locator returns slightly shifted positions for character content
```

and from testing, it would seem that **we do not need Xerces at all** except perhaps those few XNI utilities and the TAX implementation. The utilities can be easily changed, TAX ... who knows what purpose does the TAX library serve these days - couldn't it be replaced by plain DOM in the codebase ?

@jtulach how to handle this compatibly ? Application developers may rely on having *working* Xerces distributed as a module; at the same time, NetBeans IDE does not really need (most of) it.

**Comment by ebarboni** [comment]
I will wait @jtulach feedback on code rewrite that @sdedic mention

**Comment by neilcsmith-net** [comment]
Should this be moved to 12.1 milestone or beyond now?

**Comment by ebarboni** [comment]
> 
> 
> Should this be moved to 12.1 milestone or beyond now?

Yep this is not only update it's more rewrite or removal

**Comment by kz282** [comment]
Please consider upgrading to Xerces2-J 2.12.1.

**Comment by lkishalmi** [comment]
Well, I'd recommend think over this one, maybe close it, Get NetBeans independent from Xerces and offer updated Xerces through plugin portal/maven central.

**Comment by pepness** [comment]
Will try to get NetBeans independent from Xerces.

**Pull request closed without merging**
