### PR TITLE
Per-cluster repository layout

### PR DESCRIPTION
**Pull request by JaroslavTulach**
Up until now the repository structure of NetBeans source code has been flat - module next to a module. That comes with advantages, but also drawbacks. Recently two new cons appeared:

* github isn't willing to show the [whole repository](https://github.com/jtulach/netbeans-releases) - it limits the list to just a thousand files
* new modules are (hopefully) going to be granted by Oracle and not all of them are of the same importance

Luckily [NetBeans Runtime Container](http://wiki.apidesign.org/wiki/NetBeans_Platform) already supports grouping modules into bigger chunks - e.g. **clusters**. Thus it is natural that from time to time people would like to group the sources into **clusters** as well. This PR is another attempt to do so.

The `platform` modules are being moved into `platform` subdirectory. Other clusters shall follow, which would leave us with five to twenty top level directories in the repository (once more of the original NetBeans code is donated). There already is support for nesting modules into subdirs (used by [contrib](http://hg.netbeans.org/main/contrib/) repository) - e.g. this is about extending it to work with all the clusters.

The list of clusters and modules is specified in `nbbuild/cluster.properties` and `nbbuild/build.properties`. In general there seem to be two approaches:
* change these files to use full path to modules - e.g. `openide.util` would become `platform/openide.util`
* change the `nbbuild/antsrc` tasks to search for the modules in cluster subdirs, but keep their names.

I started with the latter approach, but currently the patch looks more like former one. I am not sure it is the greatest idea, as that means all references to properties like `${libs.osgi}` need to be replaced by `${platform/libs.osgi}` and it would be better to avoid it. 

In addition to this change, we also need to extend the the `apisupport` modules to recognize this new layout. Such tooling change shall be integrated soon,  as otherwise the IDE will not be able to work with own sources (btw. a drawback is that NetBeans 8.2 doesn't recognize this new layout).

Anyway this is a work in progress. I am creating this PR to get an early feedback on the overall direction. CC @jglick, @tzezula, @sdedic, @thurka, @jlahoda

### CODE REVIEW

**Comment by jlahoda** [comment]
FWIW, do you know about:
https://cwiki.apache.org/confluence/display/NETBEANS/Experiment%3A+split+the+main+NetBeans+repository
?

**Comment by JaroslavTulach** [comment]
Thanks @jlahoda, yes, I used to have some memories of your work. Looks like it changes the content of `cluster.properties` - e.g. the former approach. If it is working, then sure, we can integrate your change. I am however more and more inclined towards keeping `cluster.properties` untouched - should I continue with my patch, I probably focus on that direction. 

But as I said: feel free to proceed with your work, if the system can be compiled without problems (my current patch cannot yet).

**Comment by jlahoda** [comment]
I doubt I'll myself have time to work on this (the page is 1.5 years old). I was mentioning it mostly if something there would be helpful. But please feel free to continue!

**Comment by JaroslavTulach** [comment]
Heuréka, after 9089711 we have a working build with `platform` cluster being its own subdirectory and without changes to the `nbbuild/*.properties` files:
```bash
$ git diff -r origin/master -- cluster.properties
$ git diff -r origin/master -- build.properties
$ git log | head -n 4
commit 90897110b29aa242a5610babce7f59cae71579cf
```
next step is to fix `apisupport.*` modules to work with this new layout. Then I probably try to prepare  the infrastructure changes (without shuffling files around) into own PR and integrate those first. Once the IDE with the enhanced support is widely used, we can perform the shuffling.

**Comment by jtulach** [comment]
I've just updated the PR to reflect current changes in master. If the tests pass, I'd be glad if this could be integrated.

I know this change only moves `platform` and `harness` modules, but it is very painful to keep track with bigger master changes and merge files in different locations properly. If we just agree with the goal to lower the number of directories in the root of repository (so GitHub UI can display them all without scary messages), the let's integrate this as soon as possible and let migrate (with help of the community) other clusters later.

Apache NetBeans IDE 9.0 seems to work find with the moved sources.

**Comment by geertjanw** [comment]
Really cool. Will merge when checks succeed.

**Comment by geertjanw** [comment]
OK, everything looks good. Can I merge (checking one more time just to make sure)?

**Pull request merged**
