### PR TITLE
Update external batik lib from 1.14 to 1.16.

### PR DESCRIPTION
**Pull request by Chris2011**
As official mentioned 1.15 and 1.16 are just bugfixes. I just updated the version of it and will test whether everything is still fine or not.

### CODE REVIEW

**Review by sdedic — APPROVED** [review]
Seems OK, thanks.

**Comment by ebarboni** [comment]
@Chris2011 I think xmlgraphics-common should be 2.7 for 1.16 batik bump this version from 1.15

**Review by eirikbakke — APPROVED** [review]
If it compiles and there are no visible defects introduced in the SVG icons above the code editor, then all is good. Thanks for the PR!

**Comment by Chris2011** [comment]
Updated the requested xmlgraphics lib. I built it, ran it and it seems that it is working as before. If anyone else have smth to say, please do it. I will wait until next week and if there are no other concerns, I will merge it.

**Comment by ebarboni** [comment]
The sig test build is issuing warning. (was the case for 1.14 also)
https://ci-builds.apache.org/job/Netbeans/job/netbeans-apisigcheck/
for the batik module:
https://ci-builds.apache.org/job/Netbeans/job/netbeans-apisigcheck/lastCompletedBuild/testReport/org.netbeans.libs.batik.read/generate_Version_1_16_0/generate/

What would be a good way to clear this ?

**Comment by mbien** [comment]
@ebarboni what is the difference between the sig tests which run in github acitons and the sig tests which run on jenkins?

https://github.com/apache/netbeans/actions/runs/5125679254/jobs/9222051634
ran:

```
ant $OPTS verify-libs-and-licenses
+
ant $OPTS -quiet check-sigtests-release -Dfail.on.error=true
+
ant $OPTS -quiet gen-sigtests-release
```

**Comment by ebarboni** [comment]
I'm not 100% sure but it generate file over there **/sigtest/results/*.xml that are "junit" result. 
On github action we maybe don't pay attention to the result.

**Pull request merged**
