### PR TITLE
[NETBEANS-4338] Code Sniffer - updated link to homepage

### PR DESCRIPTION
**Pull request by KacerCZ**
GitHub page contains more installation options and issue tracker.
https://issues.apache.org/jira/browse/NETBEANS-4338

### CODE REVIEW

**Comment by KacerCZ** [comment]
@tmysik Please review.

**Comment by tmysik** [comment]
@junichi11 Can we merge PRs now, right? Thanks.

**Comment by junichi11** [comment]
@tmysik We can't merge PRs yet. I'll let you know when we can do that :)

**Comment by junichi11** [comment]
@KacerCZ I've updated the link for this issue because the issue number was not correct.

**Comment by tmysik** [comment]
@junichi11

Sorry for being an ignorant :)

**Comment by junichi11** [comment]
@tmysik No problem at all. I appreciate your review :)

**Comment by tmysik** [comment]
@junichi11

I maybe wrote line or two of the PHP support but that would be nothing without your work you do now and the last couple of years!

**Pull request merged**
