### PR TITLE
[NETBEANS-4606] Regenerate signature files for PHP 8.0

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-4606

nb-php80-regenerate-sigfiles

### CODE REVIEW

**Comment by junichi11** [comment]
@tmysik Of course, thanks to you we can update this :) Thanks a lot!

**Comment by KacerCZ** [comment]
@junichi11 How are the stubs generated?
I noticed that stubs contain old parameter names.

PHP 8.0 changed names of parameters because they become part of the API by implementing named parameters RFC.
In PHP 7.4 `ini_set()` had parameters `$varname` and `$newvalue`, in PHP 8.0 parameters were renamed to `$option` and `$value`.
* PHP documentation: https://www.php.net/manual/en/function.ini-set.php
* PHP tasks: https://github.com/php/php-tasks/issues/16 and https://github.com/php/php-tasks/issues/23

**Comment by junichi11** [comment]
I'll just regenerate it with the latest manual again. Thanks.

**Comment by tmysik** [comment]
@junichi11 

Nothing to thank for. However, it was MUCH bigger project than I expected :sweat_smile: 

@KacerCZ 

It used to be from the documentation sources, for years. But the original code was really messy and difficult to maintain, moreover it was not easy to follow all the _magic_ which is done when PHP manual is generated. Therefore I decided to generate the PHP sigfiles from the HTML manual. I have it as a private repo on Bitbucket, let me know if you would like to have access there.

**Comment by tmysik** [comment]
@junichi11 @KacerCZ 

Let's resolve the comments and merge this PR, thanks.

**Review by tmysik — APPROVED** [review]

**Comment by KacerCZ** [comment]
@tmysik Is there any reason why the tool can't be part of https://github.com/apache/netbeans-tools repository?

**Comment by tmysik** [comment]
@KacerCZ 

Simple - because I don't want to. Details offline, if you are interested.

**Comment by junichi11** [comment]
Regenerated.

**Review by KacerCZ — APPROVED** [review]
Tested and it looks OK.
Parameters for `ini_set()` are now coorect.
Thank you.

**Comment by tmysik** [comment]
@KacerCZ Thank you for your verification!

@junichi11 Thank you for your work!

**Pull request merged**
