### PR TITLE
[NETBEANS-132] Docker support: add inspect & process list actions

### PR DESCRIPTION
**Pull request by Ihsahn**

### CODE REVIEW

**Comment by geertjanw** [comment]
Thanks, this looks interesting, can you provide some screenshots of what the UI for this looks like, i.e., what the user will see?

**Comment by Ihsahn** [comment]
@geertjanw 
inspect output:
obraz

process list output:
obraz

**Comment by geertjanw** [comment]
Seems OK and is isolated to a specific functionality area. Not sure if everyone providing a PR needs to provide an Apache iCLA? Anyway, merging.

**Comment by Ihsahn** [comment]
> Yes I'm too late to the game, but I would have liked to have seen more benefit of a gui here. The other docker functions present the information in GUI windows - this is what I would have expected here.

I can always reiterate over this (and will check the json formatter) - my primary aim was to fill missing functionality (quickly).

**Comment by Ihsahn** [comment]
> Seems OK and is isolated to a specific functionality area. Not sure if everyone providing a PR needs to provide an Apache iCLA? Anyway, merging.

let me contact you by email ;)

**Comment by matthiasblaesing** [comment]
I just noticed, that the changelog also contains (IMHO) invalid data. @geertjanw please don't squash changesets of persons, that don't expose a full name and email on github. @Ihsahn please fix your github settings to expose your full name and email, both informations are distributed from the git history anyway.

**Comment by geertjanw** [comment]
Apologies.

**Comment by Ihsahn** [comment]
> Seems OK and is isolated to a specific functionality area. Not sure if everyone providing a PR needs to provide an Apache iCLA? Anyway, merging.

as discussed by email: I do confirm that I have signed iCLA (details provided to @geertjanw)

**Comment by matthiasblaesing** [comment]
@Ihsahn thank you
@geertjanw I think there might be different opinions about this around. From the Apache License 2:

> [...] 5. Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions.[...]

The license is fixed to ALv2 by this. We expect all normal contributions to carry the ASF attribution clause as well ("Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.") so I think we are save merging work of persons not having an ICLA on file.

**Pull request merged**
