### PR TITLE
Removed unused static data

### PR DESCRIPTION
**Pull request by tbw777**
Removed unused static data

### CODE REVIEW

**Comment by vieiro** [comment]
This is wrong. Next time please comment on the  mailing list before submitting PRs. Thanks.

**Comment by matthiasblaesing** [comment]
@vieiro my first impression was, that this looks right. Can you explain why you think, that this is wrong?

**Comment by vieiro** [comment]
@matthiasblaesing Because the removed part is still being used **in commented source code** in that the file. Removing it would make that commented code useless.

**Comment by matthiasblaesing** [comment]
@vieiro thank you. I missed that.

**Comment by vieiro** [comment]
@matthiasblaesing You're welcome!

**Pull request closed without merging**
