### PR TITLE
[NETBEANS-4443] PHP 8.0 Support: Union Types 2.0

### PR DESCRIPTION
**Pull request by junichi11**
https://issues.apache.org/jira/browse/NETBEANS-4443

#### Part 1

- https://wiki.php.net/rfc/union_types_v2
- Fix `ASTPHP5Parser.cup`
- Fix `InitializeFieldSuggestion` hint
- Fix `PHP80UnhandledError` and `UnusableTypesUnhandledError`
- Add the flag for union types to index signatures
- Fix code generation features (generate getter, setter, constructor, override/implement methods)
- Add unit tests for the parser, code generator, indexer, and hints

##### PHP 8.0 (Project Properties)

nb-php80-union-types

##### PHP 7.4 (Project Properties)

nb-php80-union-types-php74

##### Unusable Types Errors

nb-php80-union-types-unusable-types

##### Demo: Initialize fields

nb-php80-union-types-initialize-fields

##### Demo: Code Generator

nb-php80-union-types-code-gen

#### Part 2

- Fix Code Completion feature
- Add `false`, `null`, `self`, and `parent` as code completion items for parameter/return type
- Fix the `GSFPHPParser` for sanitizing a union type part

##### Demo CC

nb-php80-union-types-cc 

#### Part 3

- Fix the `PhpCommentGenerator`
- Fix the formatter
- Add unit tests for the comment generator, goto declaration, mark occurrences, and formatting features
- Fix the `DocRenderer`: use actual parameter/return types if there is no PHPDoc

##### Demo: Comment Generator

nb-php80-union-types-comment-gen

##### Demo: Formatter

nb-php80-union-types-formatting

#### Formatting Options

Unchecked by default

nb-php80-uni-types-formattiong-options2

##### Documentation of CC

nb-php80-union-types-cc-doc

### CODE REVIEW

**Comment by junichi11** [comment]
@tmysik I've created three commits, but the changes may be too many, sorry... Could you please review these when you can make time? Thanks!

**Review by tmysik — APPROVED** [review]
Well, it is not possible to review it carefully. But I see tests, I did not find any "suspicious" code so OK for me.

**Comment by tmysik** [comment]
@junichi11 

Perfectly done, as always. Thanks!

**Comment by junichi11** [comment]
@tmysik There are many changes and they are complicated. So, of course, that's more than enough :) Thank you for your review and your time!

**Comment by tmysik** [comment]
@junichi11 Nothing to thank for, really!

**Pull request merged**
