### PR TITLE
PHP Debugger - show NULL values by default

### PR DESCRIPTION
**Pull request by KacerCZ**
Changes default setting of filter for NULL values in PHP debugger.

Based on personal experience when I need to turn display of NULL values for almost every debugging session.

### CODE REVIEW

**Comment by junichi11** [comment]
@KacerCZ Could you attach screenshots(before and after)?

**Comment by KacerCZ** [comment]
Dialog "Local Variable Filters", after this patch "NULL type" is checked by default and variables with NULL value are shown in Variables pane.

Before:
filter-dialog-before

After:
filter-dialog-after

**Review by junichi11 — APPROVED** [review]
Thanks!

**Comment by KacerCZ** [comment]
Thanks for the review.

**Pull request merged**
