### PR TITLE
JUnit Report for github CI

### PR DESCRIPTION
**Pull request by mbien**
attempt to add the [junit-report](https://github.com/mikepenz/action-junit-report) action to display junit results on failure.

lets see if this works

### CODE REVIEW

**Comment by mbien** [comment]
can't upload the results
```
🚀 Publish results
  ℹ️ Creating check
  Error: ❌ Failed to create checks using the provided token. (HttpError: Resource not accessible by integration)
  Warning: ⚠️ This usually indicates insufficient permissions. More details: https://github.com/mikepenz/action-junit-report/issues/23
```

**Comment by mbien** [comment]
@neilcsmith-net do you know if it is possible to configure the permission token (`GITHUB_TOKEN`) of this repository? I believe all what is needed here is to switch "Checks" from read to write. Not sure if we can modify the project settings.

**Comment by ebarboni** [comment]
@mbien you should ask infra for this action maybe

**Comment by mbien** [comment]
@ebarboni yeah I probably will. If i take a look at the [apache actions doc](https://infra.apache.org/github-actions-secrets.html), it mentions tokens and also personal access tokens several times. So I thought there must be a way to configure those for the repo. 

Its no problem for regular github projects, since you can simply open the settings. I don't know how it works for centrally managed apache projects since the doc doesn't mention that :)

**Comment by mbien** [comment]
asked apache infra:
https://issues.apache.org/jira/browse/INFRA-23381

**Comment by mbien** [comment]
possible alternative:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

**Comment by mbien** [comment]
closing in favor of #4328

**Pull request closed without merging**
