### PR TITLE
[NETBEANS-3609] - Upgrade javaee6.api binaries

### PR DESCRIPTION
**Pull request by pepness**
Notes:
- javax.xml.bind:jaxb-api-osgi from 2.2 to 2.2.7
- javax.xml:webservices-api-osgi from 2.0 to 2.0.1

[JAVA EE 6 Specification](https://jcp.org/aboutJava/communityprocess/final/jsr316/index.html)
See page 152 for the technologies with their required versions

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
On which basis are the correct version for the modules determined? I see increments in minor version which would indicate feature releases.

**Comment by pepness** [comment]
Sorry I realize that the description does not match this PR and after reading the JAVA EE 6 Specification I realize that there are mistakes with the required versions that are bundled in NetBeans and in my PR (like Commons Annotations). I will fix it. 

Thanks for the observations @matthiasblaesing

**Comment by matthiasblaesing** [comment]
Thank you, looks sane to me.

**Comment by matthiasblaesing** [comment]
@pepness could you please squash the three commits into one? Thank you.

**Comment by matthiasblaesing** [comment]
Forget it - merged via c05d42e2420fc77f57d80cf6e26399cc8667468c

**Pull request closed without merging**
