### PR TITLE
[NETBEANS-4604] PHP - instant rename of private constant

### PR DESCRIPTION
**Pull request by KacerCZ**
https://issues.apache.org/jira/browse/NETBEANS-4604

Adds ability to rename private constant without displaying Rename dialog.

### CODE REVIEW

**Comment by junichi11** [comment]
@tmysik We need not hurry because we can't merge PRs into the master branch now :)

**Comment by KacerCZ** [comment]
@junichi11 Any chance to squeeze this change to 12.1?

**Comment by neilcsmith-net** [comment]
@junichi11 looks sufficiently minor, so if you're happy for it to be merged, before next week for next 12.1 beta, please go ahead.

**Comment by junichi11** [comment]
OK, I'll look at it tomorrow.

@tmysik Never mind about the review. I'll merge this if there is no problem after I verify this tomorrow. Thanks!

**Comment by KacerCZ** [comment]
@junichi11 @neilcsmith-net Thank you.

**Comment by tmysik** [comment]
@junichi11 Thanks for merging it! And sorry, quite busy these days...

**Comment by junichi11** [comment]
@tmysik No problem. I know you are busy :)

**Pull request merged**
