### PR TITLE
Add support for GlassFish 7.0.6

### PR DESCRIPTION
**Pull request by pepness**
Library Notes:

- Add support of the MicroProfile REST Client
- Add a new way to start GlassFish
- Add support for using @Inject to inject REST artifacts
- Bug fixes and updates of various components
- Bump the GlassFish version in some tests

NetBeans Testing:

- Verify successful execution of libraries and licenses Ant test
- Verify successful execution of Verify Sigtests
- Verify successful execution of `ant -Dcluster.config=release commit-validation`
- Verify successful execution of unit tests for modules `glassfish.common`, `glassfish.javaee`, `glassfish.tooling` and `glassfish.eecommon`
- Started NetBeans and ensure the log didn't have any ERROR or new WARNINGS
- Successfully register GlassFish 7.0.6, create a web app and verify that it works.

[Release Notes](https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.6)

### CODE REVIEW

**Comment by pepness** [comment]
Sorry for been late, I think it is important that a new NetBeans release support the latest version of GlassFish and Tomcat/TomEE.

**Comment by mbien** [comment]
just as general comment: we should try to find ways how to reduce the changes needed for simple updates like this one here. It can't be that we have to edit 8 files because a new glassfish point release dropped.

ideally the UI would check for updates e.g by looking at https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/maven-metadata.xml and offer downloads on a best effort basis until something breaks.

**Review by mbien — APPROVED** [review]
i diffed:
https://patch-diff.githubusercontent.com/raw/apache/netbeans/pull/6221.diff
with
https://patch-diff.githubusercontent.com/raw/apache/netbeans/pull/6002.diff
and the changes look good to me.

going to add do-not-merge so that nobody outside of the release team merges this by accident. I think its probably OK to merge since the change is fairly isolated from everything and has no real risk of causing regressions.

**Comment by neilcsmith-net** [comment]
No need for the label - we use that already for things we really don't want merged so it's going to get confusing! :wink:  If someone isn't paying attention we can always force push delivery back to the right state.

**Comment by neilcsmith-net** [comment]
Will merge for rc2.

@mbien am I missing it, or are the tests updated here not run on GH?

**Comment by mbien** [comment]
@neilcsmith-net correct, they don't run on CI yet. A lot of tests need to be hooked into the enterprise job still. @asbachb was helping with that in his PRs.

**Comment by neilcsmith-net** [comment]
@mbien that's fine - got in the habit of checking before merging when I see test changes in a PR.

**Pull request merged**
